Content.Client/Lobby/LobbyState.cs
Content.Client/Lobby/UI/LobbyGui.xaml

quick band aid fix we are just going to not display server player count and stuff for the time being, i need to look further to see where the blob is built to really fix this

lobby_ui_bandaid

---

Content.Client/Guidebook/Controls/GuidebookWindow.xaml.cs
Resources/Prototypes/Guidebook/ss14.yml
Resources/Prototypes/_NF/Guidebook/guidebook.yml

- Shows the top guidebook page by default when guidebook is opened.
- Reorganize hierarchy so that NF guidebook pages show at the top.
**Media**

Show NF guidebook pages by default, float to top

---

Resources/Prototypes/Entities/Objects/Power/powercells.yml
Resources/Prototypes/Entities/Objects/Specific/Medical/healthanalyzer.yml
Resources/Prototypes/_NF/Entities/Objects/Specific/Borgs/borgs_tools.yml
Resources/Prototypes/_NF/Entities/Objects/Specific/Power/powercells.yml
Resources/Prototypes/_Nyano/Entities/Mobs/Player/borgs.yml

Turns out borgs also have crew monitors that need power, also I got the dev build to work so it's even tested.
**Media**
**Changelog**
:cl: crazybrain
- fix: Medical cyborgs now have self-recharching crew monitors.

Borg crew monitor + slight refactor

---

Content.Server/Salvage/SalvageSystem.Expeditions.cs
Content.Server/Salvage/SpawnSalvageMissionJob.cs
Content.Server/_NF/GameRule/NfAdventureRuleSystem.cs
Content.Shared/CCVar/CCVars.cs
Resources/Maps/Shuttles/courserx.yml

expeditions back in, in the courser-x. this will probably be the absolute cheapest ship to do expeditions with since it doesnt actually have all that for amenities and its a meme and its big. Like a starter expedition why not.

reenable_expeditions

---

Resources/Locale/en-US/prototypes/catalog/cargo/cargo-vending.ftl
Resources/Locale/en-US/prototypes/catalog/fills/crates/vending-crates.ftl
Resources/Prototypes/Catalog/Fills/Crates/chemistry.yml

Chem Crates now have all the chems that the dispenser does. Took some liberties with Ethanol and Sugar since they aren't on the periodic table but oh well who cares
Also fixed the ChemVend not having a description or name so it's clearer that people can restock it if/when it's used
**Media**
**Changelog**
:cl: Lank
- add: Chemical Crates now contain every necessary precursor.

Various Chemistry Jug Fixes

---

Resources/Prototypes/Entities/Structures/Storage/Crates/base_structurecrates.yml

Per #bulletin-board "lower capacity of crates", cherry-picked from mining-station-14

Nerf crates to carry the default entity limit of 30 entities

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/ammo.yml

freedom? you mean knives?
if you dont get prospector its hard to get a knife which is extremely important for surviving, since you can stab a fish thats floating ontop of your canisters, but you can't shoot it.
dunno how this will play with restock pr since arbitrage might not be a thing but idk
**Media**
**Changelog**
:cl:
- add: The Liberation Station now sells knives to reduce the number of freak carp accidents.

add knives to ammo vendor

---

Resources/Locale/en-US/_NF/research/technologies.ftl
Resources/Locale/en-US/research/technologies.ftl
Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/Recipes/Lathes/devices.yml
Resources/Prototypes/Research/civilianservices.yml

Cargo teleporter stupid! It no work! This replaces it with void jetpack, a useful technology that does useful things

Replace cargo teleporter tech with void jetpack

---

Content.Shared/CCVar/CCVars.cs
Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
Resources/Prototypes/Roles/Jobs/Civilian/bartender.yml
Resources/Prototypes/Roles/Jobs/Civilian/chef.yml
Resources/Prototypes/Roles/Jobs/Command/captain.yml
Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
Resources/Prototypes/Roles/Jobs/Medical/chemist.yml
Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
Resources/Prototypes/Roles/Jobs/Science/research_director.yml
Resources/Prototypes/Roles/Jobs/Science/scientist.yml
Resources/Prototypes/Roles/Jobs/Security/detective.yml
Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
Resources/Prototypes/Roles/Jobs/Security/warden.yml

Role timers turned on after 2 weeks to give everyone some time in game and to learn the format better.  These will likely be raised again in a few weeks, I just didnt want these roles to go empty and unused/untested and not get feedback.  Hopefully this can cut a lot of the issues theres been with chaotic stations and mismanaged power.
**Media**
**Changelog**
:cl:
checkraze
- add: added the role timers

Initial Role Timers

---

Content.Server/Shuttles/Components/ShuttleComponent.cs
Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs
Content.Server/Shuttles/Systems/ShuttleSystem.cs
Resources/Maps/cargodepot.yml
Resources/Maps/frontier.yml

Make anchors better by making it harder for people to *rotate* Frontier Station and its cargo depots.

Add rotational anchors

---

Resources/ConfigPresets/Build/development.toml

Enable shipyard and set the default map and game mode so that new developers contributing to Frontier Station don't get confused why shipyards don't work and on how to set the map and game mode.

Update default development cvars

---

Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml
Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml.cs
Content.Server/Shuttles/Components/DockingComponent.cs
Content.Server/Shuttles/Systems/ShuttleConsoleSystem.cs
Content.Shared/Shuttles/BUIStates/RadarConsoleBoundInterfaceState.cs
Resources/Locale/en-US/headset/headset-component.ftl
Resources/Locale/en-US/shuttles/console.ftl
Resources/Prototypes/Entities/Objects/Devices/encryption_keys.yml
Resources/Prototypes/_NF/Catalog/Fills/AstroVend.yml

This adds some nice changes in preparations for having Space Traffic Control.
- Rename "Command" channel to "Traffic Control", put traffic control encryption key in AstroVend
- Allow docking ports to be named. If they are named, they appear in the shuttle console. Otherwise, they use the old dock numbers
- Add a scroll bar to the docking port list so that all the docks are visible on Frontier Station

Space Traffic Control Part 1

---

Content.Server/Salvage/SalvageSystem.Expeditions.cs
Content.Server/Salvage/SpawnSalvageMissionJob.cs

Salvage expeditions will now spawn rewards onto cargo pallets of their respective ships.

Salvage Rewards

---

Content.Client/Shuttles/UI/RadarControl.cs
Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml.cs
Content.Shared/Shuttles/BUIStates/RadarConsoleBoundInterfaceState.cs
Resources/Maps/frontier.yml

This is Part 2 of Space Traffic Control. This plots the dock names (from the last part) on the radar console. Then, update Frontier Station's docks to have dock names.

Space Traffic Control Part 2

---

Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
Resources/Prototypes/Entities/Clothing/Head/welding.yml

On my little economy balance journey, I've decided to fix multiple prices that make zero sense, same as in #64 here I'm trying to fix some questionable values that lead to empty stock when shift starts.
So, welding mask and engineering googles provide the same function, they protect eyes during welding, googles also protect from some other? Influence that may hurt your eyes.
A welding mask has many disadvantages: it is bulky, takes up a slot that won't let you wear your helmet, can't be used in space, etc. but its default price is $250.
On the other hand, engineering googles: take up a less important slot, provide additional protection, allow you to work welder in space, but for some reason they are basically free, just $75, even while being a more professional equipment.
My suggestion is …

Re-balanced engineering goggles and welding mask price

---

Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
Resources/Prototypes/Entities/Objects/Specific/chemical-containers.yml

still no infinitechem, but now jugs only cost 100. This means the chemistry crates are more reasonably priced. Also made the chemvend restock cheaper since it was pretty absurdly priced (especially since you have to pay for the jugs still)

Rebalanced ChemVend prices

---

Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks.yml
Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_cans.yml
Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_cups.yml
Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_flasks.yml
Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/donut.yml
Resources/Prototypes/Entities/Objects/Consumable/Food/Containers/condiments.yml
Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml

Food and drink prices never made much sense, why would a can of soda cost more than a hard suit or some engineering tool?
I think they should be more accessible, so players run through them faster and start seeking Kitchen ships, or buy more Vending refills instead
In this update:
Can drinks are $55
Cup drinks are $45
Snacks are $75
Donuts are $60
Condiments are $45
MRE snacks are $70
Booze-o-Mat fix:
Alcohol drinks are $80
Juices are $65
Water cans are $27
(Non-drink wares of Booze-o-Mat are going to be re-priced in different pull request)
Prices are a little different for variation, hopefully they make more sense
As a bonus consequence, now you can sell some of the trash left after Vending food and drinks for a very small price, which would definitely help keep the station cleaner …

Re-balanced vending food and drinks prices

---

Content.Server/VendingMachines/VendingMachineSystem.cs
Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml

The action to eject machine items is disabled,
Multitool, EMP, Player controlled or damage to vend machines will not drop any items.
Machines worth is now static of 1000 and will ignore any content in it.

Vend change

---

Content.Shared/Nutrition/AnimalHusbandry/InfantComponent.cs
Resources/Prototypes/Entities/Mobs/NPCs/animals.yml

slows down the ridiculous rate of animal breeding from animal husbandry.

balance animal husbandry

---

Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs

raises the mass requirements on a ftl destination auto-generating so 'large' category ships dont get them on accident but outposts like the main station stil will

raise minimum ftl destination size

---

Resources/Maps/Shuttles/cleric.yml
Resources/Maps/Shuttles/rogue.yml
Resources/Prototypes/_NF/Shipyard/cleric.yml
Resources/Prototypes/_NF/Shipyard/rogue.yml

Adds the other 2 small security ships for use in the carrier, Cleric and Rogue
**Media**
>Cleric
>Rogue Light/Dark mode
**Changelog**
:cl:
- add: 2 new security small ships, Cleric and Rogue.

2 new small security vessels

---

Resources/Prototypes/XenoArch/Effects/normal_effects.yml

After playing a round as research and getting a big hole in the ship twice, well, I made this PR. That's pretty much it :P
My idea was to make it rarer, but I underestimated how obvious that would be so just no removing plating and a slightly weaker explosion will make it more manageable hopefully

Reduces boom xeno artifact effect, no spacing

---

Resources/Prototypes/Entities/Objects/Fun/puppet.yml

Fixes issue where puppets would not let you sell the ship because they had the MobState component as Alive, now with it removed they aren't automatically ghost role, they now need to be manually added the ghost role by the admins.
**Changelog**
:cl:
- fix: You can sell ships with puppets inside of them.

Puppets are not longer "alive"

---

Content.Shared/CCVar/CCVars.cs
Content.Shared/Preferences/HumanoidCharacterProfile.cs

New frontiers is also popular in non-English speaking countries, so why not make more diversity of languages? For rp situations it is useful when a player plays a Spaniard, Italian, Russian. For forks it will make less problems in translation, they will not need to customize support for names in other languages.
**Media**
:cl:
- tweak: Names on any languages!

Any languages names

---

Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml

Nerfs Heavy Armor, ideally the solution would be to change the rewards given in the expeditions, but for now this will help to mitigate the fact that you can freely get an armor better then the deathsquad one without any significant speed slowdown, it will still be a good armor and reward but wont have use in space because its not insulated to the cold or pressure it.
***The old stats***
>80% Blunt
>80% Slash
>80% Piercing
>50% Heat
>100% Radiation lmao
>15% Caustic
***New stats***
>40% Blunt
>40% Slash
>50% Piercing
>30% Heat
>Removed radiation resistance.
>15% Caustic
>30% Explotion Resistance Added
**Changelog**
:cl:
- tweak: Nerfs Heavy armor

nerf heavy armor

---

Resources/Prototypes/Entities/Objects/Devices/pinpointer.yml
Resources/Prototypes/_NF/Catalog/Fills/AstroVend.yml
Resources/Prototypes/_NF/Entities/Structures/machines.yml

adds the bounty hunter vending machine. Contains some useful, non-lethal tools for both sec and civilian bounty hunters.  Should only be mapped inside Sec and only in certain capital Sec ships (carrier for one).

Bounty Vend

---

Resources/Maps/Shuttles/esquire.yml

**Media**
**Changelog**
:cl:
- fix: Fixed airlocks
- add: Added two more braking thrusters, because this thing handled like ass

esquire hotfix 2

---

Resources/Prototypes/Catalog/Cargo/cargo_engineering.yml
Resources/Prototypes/Catalog/Cargo/cargo_food.yml
Resources/Prototypes/Catalog/Cargo/cargo_medical.yml
Resources/Prototypes/Catalog/Cargo/cargo_science.yml
Resources/Prototypes/GameRules/cargo_gifts.yml

trims some stuff that was available in the catalog that dont make sense like some of the food crates that are actually just rewards for rng events, or artifacts. In theory, we are the ones on the frontier selling the artifacts to the stations etc.

cargo_catalog_trim

---

Resources/Prototypes/Catalog/Fills/Crates/salvage.yml
Resources/Prototypes/Entities/World/Debris/wrecks.yml

changes the lgbtq+ pins to be a wide range of various drip now. value shouldnt change overall but the variety should, including items probably not obtainable yet etc.  The salvage crate loot list in general, and in fact all procgen/rng loot tables in general could really use a pass for more interesting loot tables.
This adds strictly vanilla items and hasnt added any outside codebase drip yet.  Also pretty generic, mostly maints-loot level drip type stuff with maybe a few fun odds and ends.

salvage crate buff

---

Resources/Maps/Shuttles/empress.yml
Resources/Prototypes/_NF/Shipyard/empress.yml

Renamed carrier into Empress, monarch of the space, expanded the kitchen a little, added ID Computer to its bridge, some extra drip added, added 1 extra EMP-RPG with its ammo and 2 EMP guns to the armory, now perma has a toilet too (very important) and removed the crew-monitor server since it will use the frontier station central crew monitor server. 
:cl:
- tweak: Renamed the carrier into the empress plus fixed more of its functionality.

Update carrier into empress

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/engivend.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/youtool.yml

Removed the Network Configurator from the EngiVend and added 2 more multi and gloves
Removed the Budget Gloves since not a single soul ever got them, added empty utility belts.
Updated the rest of the items to match the same tool amounts to allow people to "buy" a full kit.
**Media**

tools vends change

---

Resources/Maps/Shuttles/marauder.yml
Resources/Maps/Shuttles/prowler.yml
Resources/Prototypes/_NF/Shipyard/default_shipyard_catalog.yml
Resources/Prototypes/_NF/Shipyard/marauder.yml
Resources/Prototypes/_NF/Shipyard/prowler.yml

Introduces the Prowler. A medium-sized patrol craft, the prowler class is a dedicated deep space reconnaissance and enforcement vessel outfitted with ECM technology to avoid detection.
The Marauder's stealth coating, upon further investigation by the Office of the Admiralty, was initially highly effective but has unfortunately lost its capabilities after long term exposure to the high UV rays found in the Frontier sector. As a result, only the shape of the vessel assists with providing stealth through a reduced radar cross section, and so IFF returns are able to be mitigated for longer-range stealth to be much the same as it was before.
**Media**
**Changelog**
:cl: Kesiath
- add: Added the Prowler! A new Stealth capable Medium ship for Security.
- remove: Removed the Stealth IFF Console …

Security Ship Line-up Alterations, Prowler Intro, Trident Retirement, and more!

---

Content.Server/Station/Components/StationRenameWarpsComponent.cs
Content.Server/Station/Systems/StationRenameWarpsSystems.cs
Content.Server/Warps/WarpPointComponent.cs
Resources/Prototypes/_NF/Entities/warp.yml
Resources/Prototypes/_NF/Shipyard/default_shipyard_catalog.yml

Same as faxes, but for ships warp points. Code is almost copy-paste from faxes. All ships will need to be updated and use `WarpPointShip`, but this should be just easy copy-paste.
**Media**
**Changelog**
:cl:
- tweak: Ghost warp point placed on a ship now synced with ship name.

Warp points with ships names

---

Content.Server/GameTicking/GameTicker.RoundFlow.cs
Content.Server/Nyanotrasen/GameTicking/RoundEndedEvent.cs
Content.Server/Nyanotrasen/RoundNotifications/RoundNotificationsSystem.cs
Content.Server/_NF/GameRule/NfAdventureRuleSystem.cs
Content.Shared/CCVar/CCVars.cs
Content.Shared/GameTicking/RoundRestartedEvent.cs
Resources/Locale/en-US/round-notifications/notifications.ftl

Notifications about the start of a round have been added, this is useful as the rounds in the frontier are very long, also notifications from the galactic bank have been made in the form of embed messages.
Also if i start talk about discord, here mine - Gados#1923
**Media**
Better use separeted channels for round notifications and bank leaderboard.
Reminder: NEVER PUT WEBHOOK URL IN GIT REPOSITORY!
**Changelog**
:cl:
- add: Round notification!
- tweak: Make bank notifications embed!

Better discord notifications

---

Content.Server/VendingMachines/VendingMachineSystem.cs
Content.Shared/VendingMachines/VendingMachineComponent.cs

Max amount of items you can get for free from vending machines is now 3.
EMP / Hiting it / Multitool, all add up to max 3 in total (Either by a mix of them or one of them, wont pass the 3 in total)
You can get less then 3 items if you spam the vend wire with a multi tool instead of waiting because of the way the eject code is (It will not eject before the animation didn't end but it will still count the random eject event and add +1)
Please consider merging the EMP update before to make it harder for sec to EMP all the vend machines on frontier at the same time.

Vending max output 3 items for free

---

Content.Server/Salvage/SalvageSystem.Expeditions.cs

They were getting parented to the pallet and not the map/grid like they should have been, should fix all the weird expedition crate hullaballoo

Fix Expedition Reward Crates

---

Resources/Maps/Shuttles/Kestrel.yml

Replaces the crew monitor with a station records computer (whoopsie) as well as adding a fax machine to the cockpit.
**Changelog**
:cl:
- add: Station Records Computer for requesting crew members
- add: Fax machine to cockpit.

Kestrel Cockpit Fixes

---

Resources/Locale/en-US/_NF/ghost/roles/ghost-role-component.ftl
Resources/Locale/en-US/_NF/prototypes/catalog/cargo/cargo-livestock.ftl
Resources/Locale/en-US/_NF/prototypes/catalog/fills/crates/livestock-crates.ftl
Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Resources/Prototypes/_NF/Catalog/Cargo/cargo_livestock.yml
Resources/Prototypes/_NF/Catalog/Fills/Crates/npc.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/emotionalsupportanimals.yml
Resources/Prototypes/_NF/Markers/Spawners/Random/emotionalsupportanimals.yml
Resources/Prototypes/_NF/Voice/speech_emote_sounds.yml

Added a crate and spawner for emotional support animals.
It will spawn one of:
Cat
Cat Calico
Cat Caracal
Corgi
Rare:
Cat Bingus
Cat Space
Corgi Puppy
Chicken
They all have ghost role.
They all have animal speech (Cats or dogs), cog wont work on them (Code issue from upstream)
They all have combat disabled, and cannot suicide.
They all can open doors (Unless no rights to open a door. AKA they have door bump)
They all can use emote (The sound they make on pet) as a "scream"
The crate could be bought in cargo for 10k, might be removed from cargo later if it will be an issue, as this is still useful for admins and ship makers to add a ship pet.
This PR also make the space cat space suit act like a space suit.
**Media**
https://discord.com/channels/1123826877245694004/1127687656084611214/11395 …

Emotional Support Animals

---

Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
Resources/Prototypes/Entities/Mobs/Player/dragon.yml
Resources/Prototypes/Procedural/salvage_factions.yml
Resources/Prototypes/Procedural/salvage_rewards.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/xeno.yml

Xeno queen and dragon will get removed if they try to leave the planet they live on.
Tested this isn't breaking the rewards.
If it died before the end it will complete as normal
If it was left on the planet the expo will not be completed
If it was left on the planet and you called to leave before timer ended the expo will not be completed
If it was left on your ship alive expo will not be completed
This PR also fix 2 missing crate rewards that where no longer in the game.
I will try to add some rare dragon egg later to allow spawn of a mini dragon.

Dungeon Fix

---

Resources/Prototypes/_NF/Entities/Structures/Windows/window.yml

The mime wall for mime ship now keeps the air inside the ship

WallInvisibleShip-Fix

---

Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml

was asked for in an ideas thread in discord, changes one line in yaml 👍 
It has the small mob mask now, the same one crates have, surely the machine mask it had previously wasnt important =)
did basic tests and they still do all their normal atmos things, if this change ends up causing a problem one day i give permission to kill me, but it shouldnt have done anything at all.
**Media**
**Changelog**
:cl: terezi4real
- tweak: Air canisters can go under plastic flaps

air cannisters can go under flaps

---

Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers.yml
Resources/Prototypes/_NF/Entities/Structures/Machines/cryo_sleep_pod.yml
Resources/Prototypes/_NF/Entities/Structures/atms.yml

Frontier critical machines are now damage protected
Except ATM's, they just drop nothing.
:cl: dvir01
- tweak: Critical machines in frontier wont break anymore.

Computers Update 2

---

.github/workflows/changelog.yml

Prevent multiple changelog actions from running at once via [job concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency). This means they get queued instead of all ran at once. If there are ever any future actions that will commit directly to the repository, they should also run under the `commit_action` group.
**Changelog**
No CL no fun

Prevent multiple changelog commits at once

---

Resources/Maps/Dungeon/cave_factory.yml
Resources/Maps/Dungeon/lava_brig.yml
Resources/Maps/Dungeon/ruined_shops.yml
Resources/Maps/Shuttles/pirate.yml
Resources/Maps/Shuttles/trident.yml

Removes High Velocity Ammo from a few places it was still in.

Remove High Velocity Ammo

---

Resources/Locale/en-US/station-laws/laws.ftl
Resources/Prototypes/Maps/frontier.yml
Resources/Prototypes/_NF/Shipyard/default_shipyard_catalog.yml

Station Laws ended up being per-station, and since we use custom stations is why the borgs couldnt state their laws.
Now every ship and the stations have laws, and all Silicons should still operate on their most recent set of laws when it comes to EVA activities etc.
:cl:
- add: Added Laws for the borgs

Implements Frontier Silicon Laws

---

Resources/Prototypes/Procedural/biome_templates.yml

chasms are neat code and make a funny sound but gameplay wise are really *really* punishing so we are going to just disable these insane things until they have some better gameplay behind them.
:cl:
- tweak: Disables chasms spawning on expeditions

Disable Chasms

---

Content.Client/Entry/EntryPoint.cs
Content.Server/Atmos/EntitySystems/AirtightSystem.cs
Content.Server/Worldgen/Components/GC/GCAbleObjectComponent.cs
Content.Server/Worldgen/Prototypes/GCQueuePrototype.cs
Content.Server/Worldgen/Systems/Debris/DebrisFeaturePlacerSystem.cs
Content.Server/Worldgen/Systems/GC/GCQueueSystem.cs
Resources/Prototypes/Entities/World/Debris/asteroids.yml
Resources/Prototypes/Entities/World/Debris/wrecks.yml
Resources/Prototypes/GC/world.yml

too many people too may asteroids

Restore GCQue

---

Resources/Prototypes/Entities/Objects/Devices/pda.yml
Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml

You can no longer sell PDA or ID cards by mistake.
:cl: dvir01
- tweak: Nanotrasen wont pay you anymore for your used PDA and ID cards.

ID&PDA-CargoSellBlacklist

---

Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml

This PR changes the ammo and size of some of the laserguns.
Most notably the retro lasergun has been nerfed to be inferior compared to the rest of other laserguns, the stats would end as:
- retro 12 shots 14 damage inv. size 15
- rifle 18 shots 17 damage inv. size 30
- advanced laser now recharges faster 17 damage inv. size 30 
- x-ray now has 20 shots 50 inv. size
- laser cannon now has 16 shots 50 inv. size
- makeshift laser gun deals less damage
:cl:
- tweak: Leander Co has improved the fabrication of most of its laser gun arsenal.

Rebalance laser guns

---

Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml

why 100% reflect
:cl:
- fix: Reflective vests now have 20% chance to reflect, down from 100%

Nerf Reflective Vests

---

Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/cart.yml
Resources/Prototypes/Entities/Objects/Devices/encryption_keys.yml
Resources/Prototypes/Entities/Objects/Devices/pda.yml
Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
Resources/Prototypes/Entities/Objects/Misc/paper.yml

Station Representative related update
After playing as SR for sometime I noted few small issues with his locker content and the vend machine content, this PR meant to fix the issues.
**Changelog**
:cl: dvir01
- add: Station Representative had their lockers content balanced, now with added items!
- tweak: Station Representative had their vend machine items updated.
- tweak: Captains lockers items should be more organized.

Station-Representative

---

Content.Server/Salvage/SalvageSystem.ExpeditionConsole.cs
Resources/Locale/en-US/_NF/adventure/adventure.ftl

Checks for objects nearby > 50 units of mass, whichever units the game uses idk.  Check is for around 300 meters. To prevent the pirate cheese.
**Media**
**Changelog**
:cl:
checkraze
- tweak: Added a mass proximity check to initiate FTL travel. Anything bigger than a PTS outside of around 300 meters will prevent FTL travel.

FTL Proximity Check for Expeditions

---

Resources/Prototypes/Catalog/Fills/Crates/botany.yml

Why was this missing?
**Changelog**
:cl: dvir01
- add: Added clippers in hydroponic tools crates.

Clippers in hydroponic tools crate

---

Content.Server/StationEvents/Components/BluespaceSyndicateCargoRuleComponent.cs
Content.Server/StationEvents/Events/BluespaceSyndicateCargoRule.cs
Content.Shared/CCVar/CCVars.cs
Resources/Locale/en-US/_NF/events/bluespace-syndicate-crate.ftl
Resources/Locale/en-US/_NF/prototypes/catalog/fills/crates/syndicate-crates.ftl
Resources/Prototypes/_NF/Catalog/Fills/Crates/syndicate.yml
Resources/Prototypes/_NF/Events/events.yml
Resources/Prototypes/_NF/Store/presets.yml

A bit of a late round event that can happen when a light (Mostly safe frontier items) syndicate crate show up on someone ship
**Media**
**Changelog**
:cl: dvir01
- add: The syndicates might try and send you a crate with equipment in an attempt to mess with the balance of frontier, please let security know if you found a syndicate crate on your ship!

Event - Syndicate Crate

---

Content.Server/Paper/PaperSystem.cs
Content.Shared/Paper/StampComponent.cs
Resources/Locale/en-US/_NF/paper/stamp-component.ftl
Resources/Prototypes/Entities/Objects/Misc/paper.yml

The captain stamp is now used to stamp the using player name instead of the word "captain".
Its working by using the equipped card, so a syndicate ID can be used to fake a paper stamp.
Captain stamp was useless, now it has an actual use.
Added a new component to stamps, when used it will replace the stamp name with your card name when you pick it up and use it to stamp.
Nothing
**Changelog**
:cl: dvir01
- tweak: Captain stamp will use your card name for the stamp.

Captain Stamp

---

Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Resources/Prototypes/Entities/Structures/cargo_telepad.yml
Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers.yml
Resources/Prototypes/_NF/Entities/Structures/atms.yml
Resources/Prototypes/_Nyano/Entities/Structures/Machines/mailTeleporter.yml

Cargo request computer cannot be broken, or have the board removed, can still be moved around as before.
Cargo Telepad cannot be broken, or have the board removed, can still be moved around as before.
Black Market Shipyard computer can be destroyed, allowing sec to take it down.
Frontiers deposit and withdraw ATM's are protected from damage now, the rest are not.
Mail Teleporter cannot be broken, can still be moved around as before.
Oversights with some of the computers and machines.
.yml changes
None
**Changelog**
:cl: dvir01
- tweak: As per the SR and Security request, Frontier machines are made from a stronger metal now.
- tweak: The pirates Black Market shipyard computer has lost its immortality.

Computers Fix

---

Resources/Locale/en-US/_NF/prototypes/catalog/cargo/cargo-fun.ftl
Resources/Locale/en-US/_NF/prototypes/catalog/fills/crates/fun-crates.ftl
Resources/Prototypes/_NF/Catalog/Cargo/cargo_fun.yml
Resources/Prototypes/_NF/Catalog/Fills/Crates/fun.yml

Added the fun floor tiles crate, cost 500 and has 30 tiles from the "fun" type
Fun
.yml changes
None
**Changelog**
:cl: dvir01
- add: Added the floor tiles crate for the price of 500, get some fun tiles for your ship!

Fun floor tiles crate

---

Resources/Prototypes/Catalog/Fills/Crates/botany.yml
Resources/Prototypes/Catalog/Fills/Crates/chemistry.yml
Resources/Prototypes/Catalog/Fills/Crates/circuitboards.yml
Resources/Prototypes/Catalog/Fills/Crates/emergency.yml
Resources/Prototypes/Catalog/Fills/Crates/engineering.yml
Resources/Prototypes/Catalog/Fills/Crates/engines.yml
Resources/Prototypes/Catalog/Fills/Crates/medical.yml
Resources/Prototypes/Catalog/Fills/Crates/science.yml
Resources/Prototypes/Entities/Structures/Storage/Crates/crates.yml

Restored many of the crates to be the "Secured" version, but now the crates just have the "AccessReader" removed.
After the changes with the new plasma crate this is for the best as it will allow faster changes to crates later.
About the same, more easy to make changes.
yml edits
None
**Changelog**
:cl: dvir01
- tweak: NT Has updated the locks on the cargo crates again, the crates should open again as expected,

Crates-Fix

---

Content.Server/Explosion/EntitySystems/TriggerSystem.cs
Resources/Locale/en-US/_NF/paper/book-medical-insurance.ftl
Resources/Locale/en-US/_NF/prototypes/catalog/cargo/cargo-medical.ftl
Resources/Locale/en-US/_NF/prototypes/catalog/fills/crates/medical-crates.ftl
Resources/Locale/en-US/implant/implant.ftl
Resources/Prototypes/Catalog/VendingMachines/Inventories/medical.yml
Resources/Prototypes/Entities/Objects/Misc/subdermal_implants.yml
Resources/Prototypes/_NF/Catalog/Cargo/cargo_medical.yml
Resources/Prototypes/_NF/Catalog/Fills/Boxes/general.yml
Resources/Prototypes/_NF/Catalog/Fills/Crates/medical.yml
Resources/Prototypes/_NF/Entities/Objects/Misc/implanters.yml
Resources/Prototypes/_NF/Entities/Objects/Misc/paper.yml
Resources/Prototypes/_NF/Entities/Objects/Misc/subdermal_implants.yml

Added a new implant to help new and coming medical insurance providers, or private medical teams find and save people who are using the implants.
There isn't any hard "terms of use" as of now, I did add a template for an agreement a player can have with a medical team to make sure he will be saved for a fixed rate.
I also made the implants report grid names with cords, or just cords if missing a grid (Space)
Giving medical teams a lot more to do, making sure people have an RP way to be saved from dying in deep space.
yml mostly, c# for added function to tracking implants to also report grid names.
None
**Changelog**
:cl: dvir01
- add: Medical implants added to cargo, sign a contract with an insurance providers, or hope for a private medical team to come ans save you, you can now buy a kit …

Medical insurance tracking implant

---

Resources/Prototypes/GameRules/events.yml

Event fix after the last Rat King killing people on spawn in cryo area
Rat king on frontier is an issue.
.yml
None
**Changelog**
:cl: dvir01
- tweak: NT Started to use new rat poison in the vents, large rats should not be a thing anymore.

Events flip

---

Content.Server/Cargo/Components/MobPriceComponent.cs
Content.Server/Cargo/Systems/PricingSystem.cs
Resources/Prototypes/Body/Organs/Animal/animal.yml
Resources/Prototypes/Body/Parts/animal.yml
Resources/Prototypes/Catalog/Cargo/cargo_livestock.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/chefvend.yml
Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Resources/Prototypes/Entities/Objects/Misc/monkeycube.yml
Resources/Prototypes/Entities/Objects/Specific/rehydrateable.yml
Resources/Prototypes/_NF/tags.yml
Resources/Prototypes/tags.yml

Monkey mob worth less, so monkey cubes price adjusted.
Animal organs worth less, needed to be to fix monkey price. 
ChefVend more full of stock.
Allows the monkey cubes to have a normal price.
.yml changes, added a new tag (LabGrown) and a new double (LabGrownPenalty) with added code to allow it to lower the worth of the monkey mob more.
Overall all mobs will sell for a lower price since the animal organs are worth 10 times less 50<5
**Changelog**
:cl: dvir01
- tweak: Lab grown monkey cubes now cost less.

Monkey Fun

---

Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml

Lowered world generator to 600 and rounded the radar to 1600, you will still be able to use the very long range radar without hurting server performance. will look a lil jank but its in the name of server performance.
Too many asteroids hurt server performance also cleaner radar console.
:cl: Leander
- tweak: Empress no longer hurts the server as much

Lower empress asteroid spawn range

---

Resources/Prototypes/Entities/Structures/Machines/crew_monitor_server.yml

Up the crew monitor range 500<10000
500 isnt usefull for frontier
.yml change
None
**Changelog**
:cl: dvir01
- tweak: Crew monitor range 500<10000

crew_monitor_server.yml

---

Content.Client/Bank/BUI/StationBankATMMenuBoundUserInterface.cs
Content.Client/Bank/UI/StationBankATMMenu.xaml
Content.Client/Bank/UI/StationBankATMMenu.xaml.cs
Content.Server/Cargo/Systems/CargoSystem.Orders.cs
Content.Server/_NF/Bank/ATMSystem.cs
Content.Server/_NF/Bank/BankSystem.cs
Content.Server/_NF/Bank/StationATMSystem.cs
Content.Shared/_NF/Bank/BUI/StationBankATMMenuInterfaceState.cs
Content.Shared/_NF/Bank/Components/StationBankATMComponent.cs
Content.Shared/_NF/Bank/Events/StationBankDepositMessage.cs
Content.Shared/_NF/Bank/SharedBankSystem.cs
Resources/Locale/en-US/_NF/bank/bank-ATM-component.ftl
Resources/Prototypes/_NF/Entities/Structures/atms.yml

Allow the SE to deposit money back into the bank, needed for SR mistakes, fines and recovered assets from sells related to contraband found by security.
Much needed and requested.
Added a new deposit function to the station bank computer, this one isn't the same as the normal ATM since it require you to provide logic for logs when you insert money into it, and also allow multi deposits to be done to the inserted money.
On the discord
https://discord.com/channels/1123826877245694004/1127687656084611214/1156642734174634034
None, testes it to make sure it wont have exploits or issues.
**Changelog**
:cl: dvir01
- tweak: NT Now allows the SR to deposit money into the station bank.

Station Bank Deposits

---

Content.Server/Maps/TileSystem.cs
Content.Shared/RCD/Systems/RCDSystem.cs
Content.Shared/Tiles/FloorTileSystem.cs

Floors can be replaced on frontier
RCD Remove floor and add floor is blocked
Axe / axe like tools cannot remove plating from the floor
Safe zoom tiles actually not bad now.
C#
Used the code from the original "FloorTileSystem" with added changes to make it work for frontier.
Frontier Demo:
https://discord.com/channels/1123826877245694004/1127687656084611214/1158156380604219593
Ship Demo (Nothing changed):
https://discord.com/channels/1123826877245694004/1127687656084611214/1158157307427950622
None, only effect places with "ProtectedGridComponent"
**Changelog**
:cl: dvir01
- tweak: NT Fixed the floor tiles auto bolt function on frontier so now you can replace the floors.

ProtectedGridComponent

---

Content.Server/StationEvents/Components/StationEventComponent.cs
Content.Server/StationEvents/EventManagerSystem.cs

To allow us to add events for lower pop shifts
SR Do be poor
C#, Added a new flag called MaximumPlayers with a default of 999 to StationEventComponent
The 999 means the it will never false the event (Cancel it) unless you require a lower number to be the max.
None
**Changelog**
No need

Event Flag - MaximumPlayers

---

Resources/Prototypes/Catalog/Fills/Lockers/engineer.yml

Remove from lockers like the other remotes, used for trolling
Remove from lockers like the other remotes, used for trolling
.yml changes
None
**Changelog**
N/A

DoorRemoteFirefight Remove From Lockers

---

Resources/Maps/Bluespace/asteroidvault.yml
Resources/Prototypes/Entities/Markers/Spawners/Random/magicbooks.yml

Replace the ForceWall Magic book with a Random Magic Book Spawner (safe).
This PR change the BluespaceAsteroidVault map to replace it with a spawner.
Its also adds 2 Spawners (Magic Book Spawner) / (Magic Book Spawner Safe).
Giving some randomness in the magic book would be nice and make peoples return to see what is.
Add 2 Spawners.
- Added Random Magic Book Spawner.
- Added Random Magic book Spawner (Safe).
**Changelog**
:cl: FoxxoTrystan
- tweak: Added some randomness in the Asteroid Vault.

Asteroid Vault Random Magic Book

---

Content.Server/Explosion/EntitySystems/TriggerSystem.cs
Resources/Locale/en-US/implant/implant.ftl

Add the specie name to the tracking implants report
With the added names to pets, its getting harder to know what specie is the dead report on (Player? pet?)
Adding a test to grab the specie name, if not existing leave empty or mob number.
None
**Changelog**
:cl: dvir01
- add: Tracking implant (Security and medical) will now list your specie!

Medical implant list specie

---

Resources/Prototypes/Entities/Objects/Specific/Xenoarchaeology/artifact_equipment.yml
Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Resources/Prototypes/Entities/Structures/Machines/anomaly_equipment.yml
Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
Resources/Prototypes/Entities/Structures/Power/apc.yml
Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml
Resources/Prototypes/Entities/Structures/Storage/Closets/wall_lockers.yml
Resources/Prototypes/Entities/Structures/Storage/Crates/crates.yml
Resources/Prototypes/Entities/Structures/Wallmounts/fireaxe_cabinet.yml
Resources/Prototypes/_NF/Entities/Structures/Storage/Crates/base_structurecrates.yml

Fixed Access Configurators not working on certain objects that should definitely have access configuration.
Ended up being forced to unload a shotgun round as SR into some guy who was (successfully) managing to loose a sentient artifact while I was trying to work out the logistics of letting it stay aboard in a crate, after said sentient artifact fried both my translator and disabler. He had to be dragged to medbay, revived, and the artifact chucked into space, which was not a good outcome for anyone involved.
Station Representative is the only one with access to an access configurator, so all should be well still.
Separately, I found out that Cargo Trade Crates just straight-up couldn't be unlocked or opened, even with AA. Fixed that.
Re-enables the blank `AccessReader` component in …

Access config fix

---

Resources/Prototypes/Entities/Clothing/Uniforms/base_clothinguniforms.yml
Resources/Prototypes/Entities/Objects/Devices/pda.yml
Resources/Prototypes/Entities/Objects/Misc/subdermal_implants.yml
Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Resources/Prototypes/Entities/Structures/Machines/crew_monitor_server.yml
Resources/Prototypes/Entities/Structures/Machines/surveillance_camera_routers.yml
Resources/Prototypes/Entities/Structures/Machines/wireless_surveillance_camera.yml
Resources/Prototypes/Entities/Structures/Wallmounts/monitors_televisions.yml
Resources/Prototypes/Entities/Structures/cargo_telepad.yml
Resources/Prototypes/_NF/Entities/Objects/Misc/subdermal_implants.yml

Remove range tests from some basic tracking to try and avoid lags.
Test to see if its helping with lags.
Range tests removed.
N/A
**Changelog**
N/A

Tracking changes

---

Resources/Maps/Shuttles/bison.yml

Bison isn't spawning, quick hotfix.
**Changelog**
:cl:
- fix: Fixed deprecated prototype inside Bison, it can now be purchased again.

Bison Hotfix

---

Resources/Maps/Shuttles/hospitaller.yml
Resources/Maps/Shuttles/templar.yml
Resources/Prototypes/_NF/Shipyard/hospitaller.yml
Resources/Prototypes/_NF/Shipyard/templar.yml

Introduces two Crusader class assault vessels, the Hospitaller and Templar, both Small class Security Ships produced by KesCo for the New Frontier Sheriff Department. These ships are both designed around the same hull, and each have their own set mission. The Hospitaller's primary mission is to provide medical aid and security to the site while doing so, while the Templar is an assault craft meant to quickly get weapons and deputies on a crime scene. These ships are designed to work independently or alongside an Empress Class carrier, taking up two of the docking bays.
The current tiny security ships available to the NFSD, while proficient in their intended role, lack the flexibility to handle the evolving threats present in the Frontier sector. The Crusader class assault ship retains the …

Hospitaller and Templar, the Sheriff's Crusaders

---

Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
Resources/Prototypes/Roles/Jobs/Security/brigmedic.yml
Resources/Prototypes/Roles/Jobs/Security/detective.yml
Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
Resources/Prototypes/Roles/Jobs/Security/senior_officer.yml
Resources/Prototypes/Roles/Jobs/Security/warden.yml
Resources/Prototypes/_Nyano/Roles/Jobs/Security/prisonguard.yml

Auto inject all the security team and SR with the security implants to make sure they can be found if dead.
Might as well.
.yml changes
N/A
**Changelog**
:cl: dvir01
- add: NT is getting mad about SR and the NFSD dying in action without tracking implants, so now they come pre injected.

Tracking Implants for security and SR on spawn.

---

Resources/Prototypes/Entities/Markers/Spawners/Random/salvage.yml
Resources/Prototypes/_NF/Catalog/Cargo/cargo_materials.yml

A crate of wood for wood work, 7k
Removed wood crate from salvage, also removed MRE at the same time.
7K, not cheap
.yml
N / A
**Changelog**
:cl: dvir01
- add: You can now buy wood crates for 7K

Wood Crate

---

Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml
Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml

Balanced the security hardsuits stats to match space combat.
Fixed the captain armor and hardsuit to not be stronger then the sheriff suit.
Laser goes pew pew, security goes dead dead.
.yml changes
N/A
**Changelog**
:cl: dvir01
- tweak: NT Added more plates to the NFSD hardsuits to allow for laser combat.

Balance changes to hardsuits

---

Resources/Maps/Dungeon/lava_brig.yml
Resources/Maps/Shuttles/dart.yml
Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
Resources/Prototypes/Catalog/Fills/Lockers/security.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/detdrobe.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/secdrobe.yml
Resources/Prototypes/Entities/Clothing/Ears/headsets_alt.yml
Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
Resources/Prototypes/_NF/Entities/Clothing/Ears/headsets.yml

Gave the sheriff his headset back but replaced the key to command so it match with his look, but he wont loss anything.
Added the "ClothingHeadsetSecuritySafe", the security headset but without the security key, new security hires will need to ask SR or Sheriff for keys, meaning they will have to be registered and accounted for.
Since getting a security key was simple as going on a single expo and getting a key from a hacked vend machine, using the security channel was useless.
.yml changes
N/A
**Changelog**
:cl: dvir01
- tweak: The security radio channel is a bit more secured now.

Secure Security Headset

---

Content.Client/Nyanotrasen/Players/PlayTimeTracking/JobRequirementsManager.Whitelist.cs
Content.Server/GameTicking/GameTicker.Player.cs
Content.Server/Nyanotrasen/Players/PlayTimeTracking/PlayTimeTrackingManager.Whitelist.cs
Content.Server/Players/PlayTimeTracking/PlayTimeTrackingManager.cs
Content.Server/Players/PlayTimeTracking/PlayTimeTrackingSystem.cs
Content.Server/Whitelist/WhitelistCommands.cs

I made an oopsie and forgot the bit of code that sends clients their whitelist status, meaning they'd only be aware of their whitelist while connected, for the duration of that connection.
Closes #465
**Changelog**
:cl:
- fix: Whitelists should now work properly again.

Fix whitelist not being sent to client

---

Resources/Maps/Shuttles/helix.yml
Resources/Maps/Shuttles/rosebudmki.yml
Resources/Maps/Shuttles/rosebudmkii.yml
Resources/Prototypes/Catalog/Fills/Lockers/suit_storage.yml
Resources/Prototypes/_NF/Shipyard/rosebudmki.yml
Resources/Prototypes/_NF/Shipyard/svnugget.yml
Resources/Prototypes/_NF/Shipyard/svorange.yml
Resources/Prototypes/_NF/Shipyard/svtide.yml

Small changes resolving:
- #364: Fixed improperly-oriented defib cabinets
- #473: Added a Station Records console to the Rosebud MKI
- Raised the price of Rosebud MKI (80000 -> 85000) as appraisal was higher than old sell price (even without the console, how was this overlooked?)
- Minor internal (non-breaking) changes where the Rosebud MKI was referred to as the MKII, and vice versa
- SV ship names are no longer hyphenated on shipyard consoles, in line with all other ship names
- SV vessels now show with the SV14 prefix on IFF.
- Removed access on suit storage units (excluding Security)
Minor tweaks resolving issues, as well as parity.
Suit storage units were previously locked unless you spawned as the requisite role or begged SR for clearance; e.g. a Helix captain previously could not …

Various ship minifixes

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/cart.yml

Added more PDA to the Ptech at the SR office.
People keep asking for this.
.yml changes
Might need to create new entity for PDA without cards, nothing that will be an issue at the moment.
**Changelog**
:cl: dvir01
- add: SR has received a crate full of all kind of PDA, now available from the Ptech vend machine.

PDA's in Ptech

---

Resources/Prototypes/Entities/Objects/Consumable/Food/Containers/tin.yml
Resources/Prototypes/Entities/Objects/Devices/encryption_keys.yml

Lower tin can size 2>3
Lower encryption key size 2>5
Allow the items to fit into the card-box
.yml changes
N/A
**Changelog**
N/A

Balance For Servivel Box size

---

Resources/Prototypes/_NF/Shipyard/anchor.yml
Resources/Prototypes/_NF/Shipyard/cleric.yml
Resources/Prototypes/_NF/Shipyard/crescent.yml
Resources/Prototypes/_NF/Shipyard/empress.yml
Resources/Prototypes/_NF/Shipyard/fighter.yml
Resources/Prototypes/_NF/Shipyard/hospitaller.yml
Resources/Prototypes/_NF/Shipyard/interceptor.yml
Resources/Prototypes/_NF/Shipyard/marauder.yml
Resources/Prototypes/_NF/Shipyard/pathfinder.yml
Resources/Prototypes/_NF/Shipyard/prowler.yml
Resources/Prototypes/_NF/Shipyard/rogue.yml
Resources/Prototypes/_NF/Shipyard/sprinter.yml
Resources/Prototypes/_NF/Shipyard/templar.yml

Changes the KesCo civilian ships to use KC14 as the prefix code, denoting their manufacturer. Additionally, changes the NFSD ships to use the NSF14 prefix code.
moar lore moar better
**Changelog**
:cl:
- tweak: Changed KesCo ships to use a manufacturer prefix.
- tweak: Changed NFSD ships to use the NSF prefix.

Lore-based Manufacturer Prefix Codes

---

Content.Client/Research/UI/DiskConsoleBoundUserInterface.cs
Content.Client/Research/UI/DiskConsoleMenu.xaml
Content.Client/Research/UI/DiskConsoleMenu.xaml.cs
Content.Server/Research/TechnologyDisk/Components/DiskConsoleComponent.cs
Content.Server/Research/TechnologyDisk/Components/TechnologyDiskComponent.cs
Content.Server/Research/TechnologyDisk/Systems/DiskConsoleSystem.cs
Content.Server/Research/TechnologyDisk/Systems/TechnologyDiskSystem.cs
Content.Shared/Research/SharedDiskConsole.cs
Resources/Locale/en-US/research/components/technology-disk.ftl
Resources/Prototypes/Entities/Objects/Specific/Research/disk.yml

Changed how the tech disk printer working a tiny bit
It will print tier 1 disks for the price of 10k (worth 5k per disk)
And tier 2-3 disks for the price of 13k (worth 5k per disk)
Research disks worth more to much closer to tech disks
Allow printing for more points with a balance worth, to remove entity spam
Allow people to unlock tier 2/3 with less issues with a small extra price to points.
C#
Added new sub component to split the 2 disks pools to common and rare.
Added new button on the printer to allow printing rare disks
Updated the .yml for disks and .ftl for points amounts.
Not as far as im aware
**Changelog**
:cl: dvir01
- tweak: The R&D disk printer can now print the disks for 10k for tier 1, and 13k for tier 2/3.
- tweak: Tech disks are worth 5000
- tweak: Research disks worth …

TechBalance

---

Content.Server/Nyanotrasen/Carrying/CarryingSystem.cs
Content.Server/Resist/EscapeInventorySystem.cs
Content.Shared/Nyanotrasen/Carrying/CarryingDoAfterEvent.cs
Content.Shared/Nyanotrasen/Carrying/CarryingSlowdownComponent.cs
Resources/Locale/en-US/nyanotrasen/carrying/carry.ftl
Resources/Prototypes/DeltaV/Entities/Mobs/Species/vulpkanin.yml
Resources/Prototypes/Entities/Mobs/Species/arachnid.yml
Resources/Prototypes/Entities/Mobs/Species/base.yml
Resources/Prototypes/Entities/Mobs/Species/diona.yml
Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
Resources/Prototypes/Entities/Mobs/Species/human.yml
Resources/Prototypes/Entities/Mobs/Species/moth.yml
Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
Resources/Prototypes/Entities/Mobs/Species/skeleton.yml
Resources/Prototypes/Entities/Mobs/Species/slime.yml

Adds the carrying system and gives the component to all available species. Carry the dead, carry the wounded, carry the people you want to throw, carry the prisoners, carry the felinids and launch them at mach 5 to the void of space where they belong when they spam meows.
Can be used by pirates to throw mates for boarding, sec for carrying prisoners, medics for carrying the wounded or just to throw away some people to space.
Most of the carrying code is already in this repository, this just takes the changes done on delta with some little changes so it could build, "it works on my machine" right now.
https://github.com/new-frontiers-14/frontier-station-14/assets/80334192/20c8f86e-5eac-48df-91f7-01a24eb376b4
**Changelog**
:cl: Leander
- add: All species have learned how to carry people and …

Port carrying from Delta-v

---

Resources/Prototypes/Catalog/Fills/Crates/salvage.yml
Resources/Prototypes/Entities/Markers/Spawners/Random/salvage.yml

Using orGroup istead of spawners, since spawner always showup on top of the crates instead of inside
Working parts crates for ones.
.yml changes
:cl: dvir01
- fix: Parts crates contain parts now, no more lies!

Parts Crates Fix

---

Resources/Maps/Shuttles/inquisitor.yml
Resources/Prototypes/_NF/Shipyard/inquisitor.yml

The NSF Inquisitor is my first attempt at building a ship, using GitHub, and a whole bunch of other things, so if I mess something up please tell me.
A small, detective-oriented ship that fits a crew of three and can hold two prisoners.
Features:
- A detective room filled with all sorts of crime-solving gadgets
- Two prisoner cells with a prisoner transfer airlock
- Three suit storages and three lockers for each crewmember
- Cat ears
I noticed that there was only one detective-based ship, and I don't think it even works properly. I also wanted to try making a ship of my own to help contribute to Frontier.
https://www.youtube.com/watch?v=EFGI7QmwByc
**Changelog**
:cl:
- add: Due to a lack of Detective-based ships, the NSF Inquisitor has been added to Security's shipyard!

NSF Inquisitor

---

Resources/Locale/en-US/_NF/prototypes/catalog/cargo/cargo-engineering.ftl
Resources/Prototypes/_NF/Catalog/Cargo/cargo_engines.yml

Sells the 3 generators in cargo
JrPacman - 1500
Pacman - 2500
SuperPacman - 3500
Allow people to buy extra generators instead of having to scrap them off ships. 
.yml
N/A
**Changelog**
:cl: dvir01
- add: NT managed to strike a deal with PACMAN Corp and will now sell generators in cargo.

Cargo Generators For Sell

---

Content.Server/VendingMachines/VendingMachineSystem.cs
Content.Shared/VendingMachines/VendingMachineComponent.cs
Resources/Locale/en-US/_NF/vending-machines/vending-machine-component.ftl

Fixed vending force eject to work again
Changed it to work based on charges.
Machines gets 1 free eject every 60 minutes by default, for max of 2 charges saved (3 if you consider the timer refresh)
Giving sentient vending machines a bit more gameplay, no longer limited by 3 items, giving them few more free items in total they can vend over the shift.
C# changes.
N/A
Might need to change the numbers on "rare" vends like the ContraVend to give it only 3 vends for free over the full shift, or dont, its not a big issue.
**Changelog**
N/A
Im not even sure what can be told to players about this.

Vending Random Eject Rework

---

Resources/Prototypes/Entities/Mobs/Player/dragon.yml
Resources/Prototypes/Procedural/salvage_factions.yml

Fixing the salvage xeno queen to die on FTL again.
No need to have it running on frontier.
.yml
N/A
**Changelog**
N/A

Salvage Mobs, fix again

---

Resources/Maps/Shuttles/decadedove.yml

-Removes stray cargo pallets underneath some walls.
**Changelog**
:cl:
- fix: Stray cargo pallets on the Decade Dove have been removed.

Decade Dove Cargo Pallet Fix

---

Resources/Locale/en-US/_NF/prototypes/catalog/cargo/cargo-fun.ftl
Resources/Prototypes/_NF/Catalog/Cargo/cargo_fun.yml

Added 4 "piano" like instruments to cargo.
Piano
Upright Piano
Church Organ
Minimoog
No way to get them unless you buy ships that has them.
.yml
N/A
**Changelog**
:cl: dvir01
- add: NT listened to people needs, and now selling 4 piano like instruments in cargo

Cargo Piano Orders

---

Resources/Maps/Shuttles/rigger.yml
Resources/Prototypes/_NF/Shipyard/rigger.yml

A medium-sized (531 tile) ship that is designed to serve as a mobile platform for construction projects in space. Features a functional atmos setup completed with a mixing chamber.
While most ships are self-sufficient as far as the engineering part goes (or can be easily modified to be), I haven't seen a design that has a fully functioning gas mixing chamber that allows the creation of tritium and frezon.
**Changelog**
:cl:
- add: NT Rigger - a medium-sized dedicated engineering/atmospherics ship suitable for daring deep space construction projects.

NT Rigger: A Dedicated Engi/Atmos Ship

---

Content.Client/Nyanotrasen/Mail/MailSystem.cs
Content.Server/Nyanotrasen/Mail/MailSystem.cs
Resources/Locale/en-US/_Nyano/mail.ftl
Resources/Prototypes/DeltaV/Entities/Mobs/Player/vulpkanin.yml
Resources/Prototypes/Entities/Mobs/Player/arachnid.yml
Resources/Prototypes/Entities/Mobs/Player/diona.yml
Resources/Prototypes/Entities/Mobs/Player/dwarf.yml
Resources/Prototypes/Entities/Mobs/Player/human.yml
Resources/Prototypes/Entities/Mobs/Player/moth.yml
Resources/Prototypes/Entities/Mobs/Player/reptilian.yml
Resources/Prototypes/Entities/Mobs/Player/slime.yml
Resources/Prototypes/Entities/Mobs/Player/vox.yml
Resources/Prototypes/_Nyano/Entities/Mobs/Player/felinid.yml
Resources/Prototypes/_Nyano/Entities/Mobs/Player/oni.yml
Resources/Prototypes/_Nyano/Entities/Objects/Specific/Mail/base_mail.yml

Match closer to DeltaV code to rebase the mail system.
Changes include:
Mail need some love, this is part one of a bigger rework I want to do, have to start with something.
.yml
C#
Didn't find any new issues. 
**Changelog**
:cl: dvir01
- tweak: Mail bags can fit more open mail.
- tweak: Mail is now made from normal paper that isn't infused with steel, paper cuts wont hurt as much.
- tweak: Closed mail is a bit less bulky as it used to be and will fit into reclaimers.

Mail Rework Part 1

---

Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactSystem.cs

Block artifact activating on protected grid simple as that.
Killing people on frontier from people who keep getting artifacts with deadly effects to pulse on frontier.
c# added a scan for arti to test the grid for ``ProtectedGridComponent``
N/A
**Changelog**
N/A

Block artifact activating on protected grid

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/medidrobe.yml

Added the medical beret that is used by brigmedic to the medidrobe, its so generic it can be used by all medical.
Nice looking
.yml
N/A
**Changelog**
N/A

Beret to medidrobe

---

Content.Server/VendingMachines/VendingMachineSystem.cs

When a vending machine gets broken it can now be fixed to working state with full health.
Why not.
C#
When the machine move into broken visuals we add the ``WeldableComponent`` to it.
Then we add the ``WeldableChangedEvent`` event and make the machine go back to full health and working state.
Finally we remove the ``WeldableComponent`` so the machine can only be fixed when its broken.
N/A
**Changelog**
:cl: dvir01
- tweak: Using welding tools on broken vending machines will restore them to working order.

Allow vending machines to be repaired

---

Resources/Prototypes/Entities/Structures/Shuttles/thrusters.yml

Fix from #588 
Removed the gyro name by mistake
.yml
N/A
**Changelog**
N/A

Fix gyro name

---

Resources/Prototypes/Entities/Mobs/Player/observer.yml
Resources/Prototypes/GameRules/events.yml
Resources/Prototypes/_NF/Events/events.yml

Fix to allow ghosts to hear traffic channel
Also add it to solar flare event
Was missing
.yml
N/A
**Changelog**
N/A

 let ghosts hear traffic radio

---

Resources/Locale/en-US/_NF/prototypes/catalog/fills/crates/vending-crates.ftl
Resources/Prototypes/_NF/Catalog/Fills/Crates/vending.yml
Resources/Prototypes/_NF/Entities/Objects/Specific/Service/vending_machine_restock.yml

Fix the crate to match the rest
fix
.yml
N/A
**Changelog**
N/A

LessLethalVend Fix missing FTL

---

Content.Server/StationEvents/Components/GasLeakRuleComponent.cs
Content.Server/StationEvents/Events/VentClogRule.cs
Resources/Prototypes/GameRules/events.yml

Restore some of the events
Grid power: seems to be working fine, lowered max time of power off from 120 to 60 to not piss people off too much over it.
Foam: Made the event use the safe chem options only
Gas Leak: Using only WaterVapor leaks, not major health risks
.yml
Few line of c# to fix the pools
N/A
**Changelog**
N/A

Restore Events

---

Resources/Prototypes/Entities/Objects/Specific/Janitorial/trashbag.yml

Allow a trashbag in belt to use the magnet option
Just running around and sucking in trash.
.yml
N/A
**Changelog**
:cl: dvir01
- tweak: Trash bags in belts has a vacuum function now, TECHNOLOGY.

Trashbag Magnet Pickup 

---

Content.Server/Chat/Systems/ChatSystem.cs

After a while playing without emotes on frontier-pt I noticed some emotes in English would still work.
Having a period at the end of emote messages prevented a lot of emotes from triggering a sound effect, because they have to match the message exactly for it to work.
Instead of making sure each and every emote has a . and ! replicate, I removed the auto punctuation for emotes.
Emotes are usually not full sentences so the period on them probably won't be missed a lot. They don't express what people are saying, so it's less likely the lack of a period impacts on meaning, attitude, tone or rhythm.
Cheers

Disables auto-punctuation for emotes

---

Resources/Prototypes/Catalog/Cargo/cargo_atmospherics.yml
Resources/Prototypes/Entities/World/Debris/wrecks.yml
Resources/Prototypes/_NF/Entities/Markers/Spawners/Random/salvage.yml

Removed O2 and N2 liquid canisters from cargo.
Balance issues
.yml
N/A
N/A
**Changelog**
:cl: dvir01
- remove: Removed liquid O2 and N2 from cargo, moved them to salvage wrecks as rare finds.

Liquidated

---

Resources/Prototypes/_NF/Entities/Clothing/Uniforms/jumpskirts.yml
Resources/Prototypes/_NF/Entities/Clothing/Uniforms/jumpsuits.yml
Resources/Prototypes/_Nyano/Catalog/Fills/Vending/Inventories/maildrobe.yml
Resources/Prototypes/_Nyano/Roles/Jobs/Civilian/valet.yml

Added the valet gear to the MailDrob
Added new uniforms for valet (Still using bartender sprite till someone replace it)
Allow new hires to gear up.
.yml
N/A
**Changelog**
:cl: dvir01
- add: Added the valet gear to the MailDrob

Valet Gear In Vending

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/cargodrobe.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/engidrobe.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/medidrobe.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/secdrobe.yml
Resources/Prototypes/Entities/Clothing/Masks/masks.yml

* Added Salvage boots to cargodrob.
* Added missing gas maskes to cloth venders.
* Nerfed the explorer gas mask to match security.
* Nerfed the atmost/captain gas mask from 20% to 10% heat protection.
Missing items
The gas masks needed a nerf since they can be obtained without an issue.
.yml
N/A
N/A
**Changelog**
N/A

Adding missing items to vends

---

Resources/Prototypes/Entities/Structures/Storage/Tanks/base_structuretanks.yml

Lowers the density of the base Liquid Storage Tank entity (Welding Fuel, Water, Water Cool) to a lower amount.
These entities are primarily depicted as a cart with wheels on them, presumably for ease of moving them around. On Frontier they are moved around a lot more frequently than other servers, so rarely are we ever pulling them from a maintenance hallway but rather stocking up on these things for ship supplies. At the current density (155) they are almost three times the density of a Thruster (60).
- [ x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
**Changelog**
tweak: CentCom has finally fixed the wheels on the Liquid Storage Tanks sent out to the Frontier. They are now easily to pull around.

Lower Storage Tank density

---

Resources/Prototypes/Maps/frontier.yml
Resources/Prototypes/Roles/Jobs/Security/brigmedic.yml

Changes the order of jobs to put Passenger: at the top of frontier job lists.
Added brigmedic to the list so its no longer ship only based.
Removed medical requirement play time from brigmedic since its not simple to get playtime as medical unless a medical job open on ship, or psychologist.
Passenger was a bit hidden as the last one in the list
Brigmedic was a ship only starting job.
.yml
N/A
N/A
**Changelog**
N/A

Frontier jobs order update + Brigmedic

---

Content.Client/Shuttles/UI/RadarControl.cs
Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml
Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml.cs
Content.Server/Shipyard/Systems/ShipyardSystem.Consoles.cs
Content.Shared/Shuttles/Components/IFFComponent.cs
Resources/Locale/en-US/shuttles/console.ftl

Add button to hide player shuttle labels from shuttle console radar
Radar can get very clogged with player shuttle labels, makes it hard to read the station / POI labels
Add button to hide player shuttle labels from shuttle console radar, using IsPlayerShuttle IFFFlag
Add IsPlayerShuttle IFFFlag to shuttles bought at shipyard console
**Changelog**
:cl:
- add: The shuttle console radar now has an option to hide shuttle labels

Shuttle Console option to hide player shuttle labels

---

Resources/Maps/anomalouslab.yml

The anomalous lab has been reinforced with plastitanium walls and windows, and the liquid canisters have been replaced with standard ones. I also edited the eastern dock to be a little less "straight into the lab"
Seeing people space the lab to kill the slimes every time makes me big sad.
mapping
**Changelog**
:cl:
- tweak: The Anomalous lab has been heavily reinforced due to ongoing reports of destructive looters.

Anomalous Lab Reinforcement

---

Resources/Prototypes/Entities/Structures/Wallmounts/air_alarm.yml

Allows Captains to access Air Alarms.
Inability of ship owners to access air alarms on their ships is inconvenient. And dangerous during "gas leak event".
.yml changes
**Changelog**
- tweak: Air Alarm parameters are now can be altered by Captains.

Allows Captains to access Air Alarms

---

Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml

Change the layer of the condiment station.
Allow the shutters in the Skipper and McCargo to close over it.
.yml
https://github.com/new-frontiers-14/frontier-station-14/assets/39403717/888e1b13-98d1-4d1e-8698-95933c0c58f2
You can walk over the condiment station, but this is a plus if anything.
**Changelog**
N/A

Condiment Station Layer Update

---

Content.Server/_NF/CryoSleep/CryoSleepSystem.cs
Content.Shared/_NF/CryoSleep/SharedCryoSleepSystem.cs

Fixed auto-cryo (happens when a person keeps lying in the cryopod without deciding to decline or accept cryosleep). I messed up so the system was trying to cryo-store the cryopod instead of the body, which obviously didn't work... 
Me stupid
CryoStoreDoAfter.User --> CryoStoreDoAfter.Used
None
**Changelog**
:cl:
- fix: Cryopods should now correctly accept SSD people.

Better cryo 2 electric boogalo

---

Resources/Maps/Shuttles/skipper.yml

Hydrotrays eating so much power to a point skipper forced to run generator as 30
This change adding another generator to allow a normal 15+15 split. 
The skipper was not usable for new people with it having this big power issue.
Map editor.
N/A
**Changelog**
N/A

Skipper Power Fix

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/chapel.yml
Resources/Prototypes/Entities/Objects/Specific/Service/vending_machine_restock.yml

- Increased stock of PietyVend: increased quantity of items available for purchase items from 1 to 3.
- Changed Wardrobe Restock Crate so it could be used for restocking PietyVend.
- Increased the quantity of purchasable items to bring it closer to other cloth vendomats.
- PietyVend wasn't restockable.
.yml changes in base game files.
**Changelog**
- tweak: PietyVend holds a bigger stock and can be restocked like other cloth vendomats.

PietyVend Tweaks: increased stock, can be restocked with wardrobe restock crates

---

Content.Server/Radio/EntitySystems/RadioSystem.cs
Content.Server/VoiceMask/VoiceMaskComponent.cs
Content.Server/VoiceMask/VoiceMaskSystem.Equip.cs
Content.Server/VoiceMask/VoiceMaskerComponent.cs
Resources/Prototypes/Entities/Clothing/Masks/specific.yml
Resources/Prototypes/_NF/Entities/Clothing/Masks/specific.yml

Normal voice mask no longer fully work in radio, it shows name as unknown
Added 2 new masks for admins
One that fake the name on radio and one that only shows real name on radio
Its near impossible to locate someone who is pretending to be someone else on the radio in frontier.
A bit of a revert of https://github.com/space-wizards/space-station-14/pull/13858
N/A
N/A
**Changelog**
:cl: dvir01
- tweak: Voice masks over radio shows you as "Unknown".

Make voice mask not working in radio

---

Resources/Maps/grifty.yml

* Docks got tiny fans so the POI wont be spaced every single time someone dock.
* Moved 2 carps spawners next to docks so people will be a bit more ready for the incoming carps.
* Fixed the atmost piping having unintended broken layout, added missing pumps, added missing pipes colors.
* Made the back area airlocks sync with smart "or" gates so they wont need tiny fans and wont space the station by mistake (If someone fixed the missing wall)
* Made some of the trash on floor random based spawner and not manual mapped.
* Removed the cybersun pen
* Added empty fire cabinet
* Added firedoors to internal airlocks
It can be now fixed and used without un-fixable isuees.
Mapping editor
N/A
**Changelog**
N/A

Grifty changes

---

Resources/Maps/frontier.yml

Doing few more changes
Added 2 implanters on table in sec, removed the unused charger from there.
Replaced the 2 racks with secured storage to keep people off the "loot"
Sec doors smart cycle, logic gate inside to keep it away from peoples messing with them:
Fireaxe is back at SR area after it was missing.
Making sec area a bit more secured
Maaping.
N/A
**Changelog**
N/A

Yet more frontier map changes

---

.github/labeler.yml
.github/workflows/pr-labeler.yml

Uses this GH action: https://github.com/actions/labeler
Existing contents in `.github/labeler.yml` were unused, so they were removed entirely and replaced with the new target contents. Currently this would only auto-assign the following labels: Map, Shuttle
Labels should exist on the repo already. ( @dvir001 )
This is the currently configured behavior:
- If any mapping change is detected, the Map label is added.
- If additionally the mapping change in question is a shuttle, the Shuttle label is added as well.
Better behavior can be made if POI prototypes are moved to a separate folder, and not in `Resources/Prototypes/_NF/Shipyard`.
**Changelog**
No CL.

Add PR workflow for automatically labeling mapping changes.

---

Content.Server/Body/Systems/BodySystem.cs
Content.Server/Cloning/CloningSystem.cs
Content.Server/Morgue/CrematoriumSystem.cs
Content.Server/Nyanotrasen/Item/PseudoItem/PseudoItemComponent.cs
Content.Server/_NF/SizeAttribute/SizeAttributeComponent.cs
Content.Shared/_NF/Cloning/ITransferredByCloning.cs

- Crematories will no longer accept connected players or alive mobs, similarly to biomass reclaimers.
- Fixed a bug where if and only if you clicked the "return to body" button while being a ghost, ghostrespawn would require waiting hours before respawning, depending on how long the shift was going on for and how slow the server was running.
- Added support for components that are carried over upon cloning. Currently this is used to carry over the "small" and "tall" traits, but later it can be used to add support for lasting genetic changes.
The first one is because MY BODY WAS CREMATED ALIVE THAT ONE SHIFT GOD DAMN IT!!! And not only mine, those raiders cremate half the station!!! 
The rest are because why not.
C# changes
Added an ITransferredByCloning interface and applied it to …

QOL changes on the matter of life and death

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/engivend.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/vendomat.yml

This PR adds the holofan projector and geiger counter to the EngiVend and glass beakers to the Vendomat.
The holofan and geiger counter should really be accessible alongside the other tools.
The glass beakers are required for some of the machines in the CircuitVend, and setting up an autolathe just to print 2 beakers seems a bit inconvenient.
YML
**Changelog**
:cl:
- tweak: The EngiVend now sells geiger counters and holofan projectors.
- tweak: The Vendomat now sells glass beakers.

Additions to EngiVend and Vendomat inventory

---

Resources/Prototypes/_NF/Roles/Jobs/Fun/misc_startinggear.yml

Ask SR for cards, no need for free ID cards with every pet.
Card not needed, sorry pets.
.yml
N/A
**Changelog**
N/A

Remove ID from emotional pets

---

Resources/Prototypes/Catalog/Fills/Lockers/service.yml
Resources/Prototypes/Catalog/Fills/Lockers/suit_storage.yml

Removed duplicated HandheldGPSBasic from one of the pirate lockers.
Removed shotgun from bar locker.
The bartender can go buy one
This is an upstream meme.
.yml
N/A
**Changelog**
N/A

Lockers Changes

---

Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml
Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml.cs
Resources/Locale/en-US/_NF/shuttles/console.ftl
Resources/Locale/en-US/shuttles/console.ftl

Add ship designation to shuttle console UI
This solves the problem of ship designations being annoying to remember/track when you need them.
Replaces the text "Display" above the ReadonlyDisplay with the name of the ship. (If the ship is a POI or something without a 6-character designation, it uses the whole ship name. Otherwise, it uses everything except the designation)
Also adds two Labels to the ShuttleConsoleWindow's ReadonlyDisplay:
- Text "Designation:"
- ShuttleDesignation, the 6-character designation of the current ship, or "Unknown" if it does not have a designation
N/A
**Changelog**
:cl:
- add: Shuttle console display UI now shows ship name and designation

Add ship designation to shuttle console UI

---

Content.Client/Shuttles/UI/RadarControl.cs
Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml
Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml.cs
Resources/Locale/en-US/shuttles/console.ftl

Added a search bar to the shuttle console, which allows to filter IFFs by name
Mailmen will be happy
Client-side changes only
Added a new field to RadarControl - a reference to a filter function that accepts an EntityUID, a MapGridComponent, and an IFFComponent and return a boolean. The current code only uses the first argument (the uid), but other ones can be used to implement more advanced filtering later on. Made RadarControl's draw code call that filter function if it's not null.
I have genuinely spent more time trying to make dotnet recompile the client than writing the code.
https://github.com/new-frontiers-14/frontier-station-14/assets/69920617/89a11127-e4e5-44ac-9017-8e4c4b223072
N/A
**Changelog**
:cl:
- add: Added an IFF filtering feature to the shuttle console UI, allowing to …

Implemented IFF search

---

Content.Client/Shipyard/BUI/ShipyardConsoleBoundUserInterface.cs
Content.Client/Shipyard/UI/ShipyardConsoleMenu.xaml.cs
Content.Server/Shipyard/Systems/ShipyardSystem.Consoles.cs
Content.Shared/Shipyard/BUI/ShipyardConsoleInterfaceState.cs
Content.Shared/Shipyard/Components/ShipyardListingComponent.cs
Content.Shared/Shipyard/SharedShipyardSystem.cs
Resources/Maps/Shuttles/empress.yml
Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers.yml
Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/mothership-computers.yml
Resources/Prototypes/_NF/Shipyard/cleric.yml
Resources/Prototypes/_NF/Shipyard/fighter.yml
Resources/Prototypes/_NF/Shipyard/rogue.yml
Resources/Prototypes/_NF/Shipyard/spectre.yml

This PR adds support for custom, per-console shipyard lists. This is achieved using the ShipyardListingComponent. 
Additionally:
- It changes the empress' shipyard console to only sell small security ships.
- It removes the Cleric and the Fighter from the standard security shipyard, making them only available from the empress' console (as that's what was written in the TODOs of those ships)
- It fixes Spectre's shipyard name (as Dvir has requested)
Sec too greedy
Also I want to use this to add a small shipyard console to the caduceus in the future, as its specifics suggest that it should act as a mothership for a medical fleet rather than a standalone ship
Added a new shipyard ui key - custom (used only for custom consoles, inapplicable to shuttles)
Moved the shipyard listing logic from …

Custom shipyard listings

---

Resources/Maps/Shuttles/praeda.yml
Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
Resources/Prototypes/Entities/Clothing/Eyes/specific.yml
Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
Resources/Prototypes/Entities/Structures/Decoration/banners.yml

Removes "Shitcurity" and "Cargonia" from entity descriptions.
"Shitcurity", and similarly "Cargonia", are harmful references in an MRP server.
N/A
**Changelog**
N/A

Remove shitcurity and cargonia references

---

Content.Client/Shuttles/UI/RadarConsoleWindow.xaml
Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml

Increases the default height of the Shuttle Console and Mass Scanner UI's, so the top and bottom edges aren't hidden and need re-adjustment.
Slight inconvenience fixed.
Changed 2 numbers.
**Changelog**
Minor fix, changelog not needed.

Changes default Shuttle Console and Mass Scanner UI height.

---

Resources/Prototypes/Roles/Jobs/Security/brigmedic.yml
Resources/Prototypes/Roles/Jobs/Security/detective.yml
Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
Resources/Prototypes/Roles/Jobs/Security/warden.yml
Resources/Prototypes/_Nyano/Roles/Jobs/Security/prisonguard.yml

Its time to up security play time requirement, might help balance the security team.
Less security issues.
up playtime.
N/A
**Changelog**
N/A

Security time requirement

---

Content.Server/Anomaly/Components/AnomalyGeneratorComponent.cs
Resources/Locale/en-US/anomaly/anomaly.ftl
Resources/Prototypes/Entities/Structures/Machines/anomaly_equipment.yml
Resources/ServerInfo/Guidebook/Science/AnomalousResearch.xml

Making the anomaly generator require a material that either need you to go mine for, or buy from miners.
Plasma is too cheap and simple for a money machine.
yml
C#
N/A
**Changelog**
:cl: dvir01
- tweak: Anomaly generator now require bananium processed ore.

Bananium Anomaly Generator

---

Content.Server/Nyanotrasen/Item/PseudoItem/AllowsSleepInsideComponent.cs
Content.Server/Nyanotrasen/Item/PseudoItem/PseudoItemSystem.cs
Content.Shared/Nyanotrasen/Item/Components/PseudoItemComponent.cs
Resources/Locale/en-US/_NF/actions/sleep.ftl
Resources/Prototypes/Entities/Clothing/Back/backpacks.yml

Allows pseudo-item creatures (small cats and vulps) to sleep while being placed inside a bag.
37 added lines, 0 removed
Amimir
I need it. Seriously.
Created a new component, AllowsSleepingInside, and added it to the base backpack item. Modified PseudoItemSystem to add/remove the sleep action when a pseudo-item entity gets into/out of a container with that component, and show a popup when it falls asleep.
https://github.com/new-frontiers-14/frontier-station-14/assets/69920617/2845d58c-bd9a-4821-a99a-55754fa79914
(Note: in the video the popup can show even when the entity is already asleep, I changed the code to prevent that)
None
**Changelog**
:cl:
- add: Scientists have discovered that small creatures can sleep inside bags.

Sleeping inside bags

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/ammo.yml

Adds .45 cal magnum to the Liberation vending machine
Deckard is in the T2 gun safe, like all weapons you have a chance of it being nonlethal instead of lethal.  However, unlike all the other weapons in the Gunsafe pool,  You aren't able to buy lethal ammo for the Deckard (The T2 magnum weapon). Since the majority of the time you can obtain T2 weapon safes via expedition ships at the Lodge. Not having a way to buy .45, you can be stuck without your t2 weapon on expeditions which leaves you at a huge disadvantage instead. 
**Changelog**
add: .45 Magnum is added to the Liberation Station for $222

add 45cal to the Liberation machine

---

Resources/Maps/_NF/Shuttles/chisel.yml
Resources/Prototypes/_NF/Shipyard/chisel.yml

Updating ICR Chisel to current mapping standards:
- Wiring rework.
- Atmos rework (initial atmos setup was introduced in this PR: https://github.com/new-frontiers-14/frontier-station-14/pull/708).
- Added blastdoors and linked control button to the southern conveyor line.
- Replaced custom filled captain's locker with QM's Locker and QM's Suit Wallstorage Unit.
- Replaced consoles with tabletop variants.
- Enabled Pilot Job.
New mapping standards.
**Changelog**
- tweak: Updated ICR Chisel to current mapping standards.

ICR Chisel Update

---

Resources/Maps/_NF/Shuttles/prospector.yml
Resources/Prototypes/_NF/Shipyard/prospector.yml

Updating NC Prospector to current mapping standards:
- Wiring rework.
- Atmos rework (initial atmos setup was introduced in this PR: https://github.com/new-frontiers-14/frontier-station-14/pull/708).
- Replaced custom filled captain's locker with QM's Locker.
- Replaced consoles with tabletop variants.
New mapping standards.
**Changelog**
- tweak: Updated NC Prospector to current mapping standards.

Prospector (Update)

---

Resources/Prototypes/_NF/Entities/Structures/Storage/Closets/suit_storage_wall.yml

- **The issue:** weird interaction angles for Suit Wallstorage Units.
- **Proposed solution:** explicitly declared the arc for interaction with wallstorage unit as 360.
- **Discussion:** Maybe the problem arises from wall mounts are somewhat broken in general (might be upstream issue) - wall mounted nanomed angles are not consistent. So I explicitly declared the arc for interaction with wallstorage unit as 360. Seems to work: bought about 10 ships with that kind of storage to test the solution and had no problems with accessing the storage from expected angles.
360 might be a bit of overkill, but 180 isn't as reliable as I'd like it to be and you still from time to time can access the storage unit from outside of 180 arc.
Bugfix
.yml edits
**Changelog**
- fix: Fixed …

Suit Wallstorage Unit Fix (Maybe)

---

Resources/Prototypes/Catalog/Cargo/cargo_armory.yml
Resources/Prototypes/Catalog/Cargo/cargo_fun.yml
Resources/Prototypes/Catalog/Cargo/cargo_medical.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/medical.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/sec.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/theater.yml
Resources/Prototypes/Entities/Objects/Vehicles/buckleable.yml
Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/watergun.yml
Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/cuddlycritter.yml
Resources/Prototypes/_NF/Entities/Structures/Machines/vending_machines.yml

Removing crates from cargo for cleanup.
All implants moved to vending
Most "Fun" crates items moved to vending
Removed TrainingBomb from cargo
Removed MindShield from cargo
Cargo depo cleanup
.yml
N/A
**Changelog**
:cl: dvir01
- tweak: Cargo has moved some of the crates items to vending machines, Implant to medical, cloth to theater, toys to cuddly critter.

Cargo Cleanup

---

.github/mapchecker/whitelist.yml
Resources/Maps/_NF/Shuttles/esquire.yml
Resources/Prototypes/_NF/Shipyard/esquire.yml

Updating NC Skipper to current mapping standards:
- Wiring rework.
- Atmos rework.
- Removed Food Vendomat.
- Removed some loose items.
- Replaced consoles with tabletop variants.
- Replaced security room with mercenary room.
- Enabled Mercenary Job.
- Enabled Pilot Job.
- Removed Station Engineer Job.
New mapping standards.
**Changelog**
- tweak: Updated NC Esquire to current mapping standards.

Esquire (Update)

---

Content.Server/_NF/SizeAttribute/SizeAttributeSystem.cs
Resources/Prototypes/Entities/Mobs/Species/reptilian.yml

Fixes tall lizards, tall cats and small vulps being twice as heavy as others of the same size, and thus incomparably stronger
Also makes tall lizards slightly less heavy compared to oni (reduces their density by roughly 10%)
*SCREAMS*
Every mob has two fixtures: the main one used for collisions, and an auxillary one used for flammability. The second one normally has a density of 1, and thus contributes little to nothing to the mass. SizeAttribute, however, used to change the density of ALL fixtures, thus making the flammable fixture have mass AND DOUBLING THE FINAL MASS OF THE MOB.
https://cdn.discordapp.com/attachments/1127687656084611214/1201800015753007134/weeee-2024-01-30_10.55.29.mp4?ex=65cb227c&is=65b8ad7c&hm=730dbbe0f2217b6d376ccbec0f4c64543ae268f1f76cc95e8c7c59ffa93befe0&
N/A …

Fix improper SizeAttribute scaling

---

Content.Shared/CCVar/CCVars.cs
Resources/Maps/_NF/Outpost/frontier.yml

Prevent this insanity from happening:
Also:
- Add rechargers to SR office (wall variant), engineering (wall variant) and the security office.
- Removes a cuddlycrittervend (Count 2 -> 1) in the stage area, replace it with a maints access hatch.
- Rotates all wallmount ATM's to be the correct way around.
**Changelog**
:cl:
- tweak: NFSD Outpost should now be practicing proper social distancing towards Frontier Outpost.

Fix Frontier outpost's station offset to (0, 0), also rechargers

---

Resources/Maps/_NF/Shuttles/helix.yml
Resources/Prototypes/_NF/Shipyard/helix.yml

Updating NM Helix to current mapping standards:
- Atmos rework.
- Removed some loot.
- Replaced some consoles with tabletop variants.
- Added firelocks.
- Added blast doors to cover conveyor lines output.
New mapping standards.
**Changelog**
- tweak: Updated NM Helix to current mapping standards.

Helix (Update)

---

Resources/Maps/_NF/Shuttles/sparrow.yml
Resources/Prototypes/_NF/Shipyard/sparrow.yml

Updating NR Sparrow to current mapping standards:
- Wiring rework.
- Atmos rework.
- Replaced some consoles with tabletop variants.
- Scrapped the atmosia, replaced it with engineering room.
- Updated mapchecker whitelist.
New mapping standards, never ever seen atmosia used on this ship (might be wrong, don't have any statistics to support this claim).
**Changelog**
- tweak: Updated (and slightly reworked) NR Sparrow to current mapping standards.

Sparrow (Update)

---

Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
Resources/Prototypes/Entities/Structures/cargo_telepad.yml
Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers.yml
Resources/Prototypes/_NF/Entities/Structures/Machines/cryo_sleep_pod.yml
Resources/Prototypes/_NF/Entities/Structures/Machines/m_emp.yml
Resources/Prototypes/_NF/Entities/Structures/Machines/vending_machines.yml
Resources/Prototypes/_NF/Entities/Structures/Shuttles/thrusters.yml
Resources/Prototypes/_NF/Entities/Structures/atms.yml
Resources/Prototypes/_NF/Entities/Structures/base_structure.yml

Cleanup for all yml we edited.
Removed the no ROT from wall-mount ATM.
Made ATM & Shipyards single user to block people from stealing your money.
Used multi perents so we dont need to add lines into comps anymore.
Needed cleanup and bug fix.
.yml
N/A
ATM That were placed sideways will now be sideways. we will need to fix it later to make cash not glitch into walls.
Keep in mind this isnt a new bug, its just that only now we can tell its an issue.
**Changelog**
N/A

YML Cleanup

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/sec.yml
Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/bountyvend.yml

Added ForensicScanner and BoxForensicPad to SecTech and BountyVend inventory to allow the use of scanners for all security and private mercs.
Was missing.
.yml
N/A
**Changelog**
:cl: dvir01
- add: Added ForensicScanner & BoxForensicPad to SecTech & BountyVend

Forensic In Vends

---

Content.Server/_NF/SizeAttribute/SizeAttributeSystem.cs
Content.Server/_NF/SizeAttribute/SizeAttributeWhitelistComponent.cs
Resources/Prototypes/DeltaV/Entities/Mobs/Species/vulpkanin.yml
Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
Resources/Prototypes/_Nyano/Entities/Mobs/Species/felinid.yml

Makes the tall trait cosmetic-only for lizards and cats
And adds the ability to mark the tall/small traits as cosmetic-only in SizeAttributeWhitelistComponent
@dvir001 
*Screams*
12 changed lines
N/A
**Changelog**
:cl: 
- tweak: The tall trait no longer makes cats and lizards heavier.

Tall trait tweak

---

Resources/Prototypes/Entities/Objects/Misc/spider_web.yml

The web has no actual build node, removing it to remove the errors when you spawn it.
Edit web to wood to match upstream having it burn from fire.
bug fix.
bug fix.
N/A
N/A
**Changelog**
N/A

Spider web node broken

---

Content.Client/Shuttles/UI/RadarControl.cs

`RadarControl.DrawDocks` now scales the dock label position by the user's UI scale. Previously, using a different UI scale would result in the dock labels "drifting" and being very misaligned. Image attached.
Fixes a visual error. Issue discussed on Discord bugs-feedback channel.
Divides the the label's scaled `uiPosition` by `UIScale`. The error appears to be a typo/oversight that was not caught due to use of 100% UI scale. 
See the correct scaling done here (ignore the vector offset, which is used only for grid labels): https://github.com/new-frontiers-14/frontier-station-14/blob/f1d81417323294b204bcf0a1e2a2982d58cab7fb/Content.Client/Shuttles/UI/RadarControl.cs#L277-L279
This screenshot demonstrates the erroneous scaling. *Users with `100%` UI scale do not experience this effect.* This …

fix(ui): Fix dock labels misbehave with UI scaling

---

Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml

Chief engineer's suit no longer has 100% protection
Balance, no one should have 100% protection
.yml
N/A
N/A
**Changelog**
:cl: dvir01
- tweak: CE suit 100<95% rad protection.

Chief engineer's hardsuit 95% radiation protection

---

Resources/Maps/_NF/Shuttles/caduceus.yml

Removes a syndicate turret toolbox from the Caduceus.
Duh.
**Changelog**
:cl: MagnusCrowe
- remove: Removed syndicate turret box from Caduceus.

Removes syndicate turret box from Caduceus

---

Resources/Prototypes/_NF/Entities/Structures/Doors/secret_door.yml
Resources/Prototypes/_NF/Recipes/Construction/Graphs/structures/secretdoor.yml
Resources/Prototypes/_NF/Recipes/Construction/structures.yml

Added construction recipe for shuttle secret door that I forgot to add.
Fixes.
**Changelog**
- tweak: Shuttle Secret doors are actually constructible now.

Shuttle Secret Door Recipe

---

Resources/Prototypes/_NF/Shipyard/sparrow.yml

Re-adds sparrow.yml from #955, which was reworked to be in line with updated mapping guidelines by ErhardSteinhauer. Solves #1012 issue. I'm not sure why after the upstream merge this file vanished and I couldn't find any info why. I would like it back. Also easy pr for first pr.
I like this ship a lot.
A separate sparrow.yml already exists in Maps/_NF/Shuttles, that is the grid. This sparrow.yml is for Prototypes/_NF/shipyard which gives the shuttle a price and ID so it can be listed and purchased by players in-game.
**Changelog**
:cl:
- add: Added sparrow.yml, which re-lists the vessel in the shipyard again.

Re-add sparrow.yml

---

Resources/Prototypes/Entities/Markers/Spawners/Random/salvage.yml
Resources/Prototypes/Entities/Mobs/NPCs/carp.yml

Makes sharkminnow and carp hit boxes slightly larger to combat wall clipping at high speeds, and slightly reduces their damage because it was a bit high for a lower tier mob
sharks be killin people
**Changelog**
:cl:
- tweak: Changed sharkminnows to be less frequent, less deadly, and less teleporty

Sharkminnow Adjustments

---

Content.Shared/Storage/Components/MagnetPickupComponent.cs
Content.Shared/Storage/EntitySystems/MagnetPickupSystem.cs

Fixes the bugged pickup animation & sound that would play on all clients for disabled magnets.
*screams incomprehensibly*
Added the NetworkedComponent and AutoGenerateComponentState to MagnetPickupComponent, and AutoNetworkedField to the MagnetEnabled field; Called Dirty(...) in the magnet toggle method.
See the #development channel on discord
None
**Changelog**
:cl:
- fix: Fixed the buggy client-side magnet belt pickup animation

Fix visual bug on disabled magnets

---

Resources/Maps/_NF/Shuttles/menace.yml

Removes the perfect IFF console.
It should never have had it in the first place.
**Changelog**
:cl: MagnusCrowe
- remove: Removed the perfect IFF from the Menace.

Removes OP IFF from the Menace

---

Resources/Prototypes/Recipes/Cooking/meal_recipes.yml

currently super big bite burger is not craftable, merging it from upstream directly since its a small fix
original pr 
https://github.com/new-frontiers-14/frontier-station-14/pull/1041
**Changelog**
tweak: super big bite burger easier to craft

Make super bite burger easier to craft (#24231)

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml

Allows to print Advanced Magboots after they were researched.
The "Localized Magnetism" research in Experimental tree says that it'll unlock Advanced Magboots, but it doesn't, so here is the fix.
**Changelog**
- fix: Advanced Magboots can be printed after they were researched.

[Fix] Printable Advanced Magboots

---

Resources/Prototypes/_NF/Entities/Clothing/Masks/masks.yml
Resources/Prototypes/_NF/Roles/Jobs/Wildcards/pilot.yml

- Now it's possible to pull down pilot breathing mask.
- Players who join round as Pilots now start with filled extended capacity gas tank in their pocket instead of empty one.
Bug fixes.
**Changelog**
- tweak: Now you can pull down pilot mask.
- tweak: Players who join round as Pilots now start with filled extended capacity gas tank in their pocket.

Pilot Job Gear Fixes

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml

Fixed microreactor power cells not being printable with the portable fission research at lathes
Bug fix, the research tech was already present but functionally useless since it did not add the recipe to lathes.
None
None
**Changelog**
:cl:
- fix: Fixed Microreactor cells not being printable at protolathes.

Fixed microreactor cell not being printable

---

Resources/Maps/_NF/Shuttles/gourd.yml
Resources/Maps/_NF/Shuttles/rosebudmkii.yml
Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/salvage.yml

Restore the drill to sci, removed from lockers and venders.
The mining drill is crazy fast now and is an an upgrade to the pickaxe.
.yml
N/A
N.A
**Changelog**
:cl: dvir01
- tweak: Mining drill has been moved back to sci tech, ask someone to print you some.

Mining drill back to sci tech

---

Resources/Prototypes/Entities/Objects/Specific/chemistry-vials.yml
Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/contravend.yml

Adds a vial of vestine (30u) to the contravend at the cost of 15k spesos per vial.
Vestine is a crucial component of syndicate chemicals, and is unobtainable on frontier (unless you raid a syndicate vault, which is nearly impossible most shifts). Adding it to the contravend should open up new opportunities for pirates and other criminals.
Currently the contravend offers 6 vials, the price and count can be a subject for discussion.
3 added yml lines
N/A
**Changelog**
:cl:
- add: The contravend now sells vials of vestine, a precursor to a few powerful chemicals.

Add a vestine vial to the contravend

---

Content.Client/Shuttles/UI/RadarControl.cs

This fixes two things
- Frontier Station doesnt show label when outside radar distance
- Shuttle labels don't show when outside radar distance
it fixes the above issues
client side changes only
**Changelog**
fix: frontier not showing from distant
fix: player shuttle names not showing from distant

Fix distant ship labels and frontier label

---

Content.Server/Pinpointer/PinpointerSystem.cs
Content.Shared/Pinpointer/PinpointerComponent.cs
Content.Shared/Pinpointer/SharedPinpointerSystem.cs
Resources/Prototypes/Entities/Objects/Devices/pinpointer.yml
Resources/Prototypes/_NF/Entities/Objects/Devices/pinpointer.yml

#description is outdated - see the comments
Adds a maximum range to pinpointers, which for normal pinpointers is 128m. When the target entity is more than 128m away, you can observe the same effect as when the tracked entity disappears - the arrow gets "stuck", and if you toggle the pinpointer off and on, it will show a question mark. It will retain this state until the target is in the range again, or until you reconfigure it.
The maximum distance is configurable, and there's also a new [unlimited] variant meant for admemes.
Powergamers such as prosmasher use pinpointers to permamently track people and ships. Security can pinpoint *potential* criminals even before they commit anything bad, and criminals can pinpoint security to know if they're being chased. In both cases there's NO …

Nerf pinpointers

---

Resources/Maps/_NF/Shuttles/eagle.yml

Removes RCD and Ammo from the Eagle.
Unbalanced 
**Changelog**
:cl:
- remove: RCD and Ammo have been removed from the Eagle.

Remove RCD and Ammo from Eagle

---

Resources/Locale/en-US/_NF/chemicals/chemicals.ftl
Resources/Prototypes/Entities/Objects/Specific/Xenoarchaeology/item_artifacts.yml
Resources/Prototypes/_NF/Reagents/chemicals.yml
Resources/Prototypes/_NF/Recipes/Reactions/chemicals.yml

Changed the reagent within Artifact fragments to a raw version that is 'less potent'.
ie simply gives drastically less amount, still works the same as regular artifixium otherwise.
Adds in five new recipes total.
3 of them "refine" the raw artifixium with another ingredient, producing the regular artifixum as we know it in reasonable quantities. 
One from a rare source, one from an uncommon source, and one from a more common source that might be painful.
The amount ratios are no way set in stone, just put together from my best judgement from when I've done science
-Why: A solution has been asked for regarding Artifexium for a while, this is an attempt to bring that to the table.
-Balance:  Doing this sort of change will add engagement with other systems within science and hopefully other …

Refinement process for Artifexium

---

Resources/Prototypes/_NF/Shipyard/hauler.yml

Adjusts the price of the NC Hauler to cost what it should
The initial addition of the ship did not push with the correct value of the ship and it sells for a few thousand more than it buys for. This adjusts the buy price up to 60,000
Just a YML change
**Changelog**
:cl:
- fix: Adjusts the price of the NC Hauler from 49,500 to 60,000 to cost what it should.

Adjusts the price of the NC Hauler to cost what it should

---

Content.Shared/Access/Systems/AccessReaderSystem.cs
Content.Shared/Doors/Systems/SharedDoorSystem.cs
Content.Shared/Lock/LockSystem.cs

UnEmagged is back to normal, working on locks and doors.
Got broken after https://github.com/space-wizards/space-station-14/pull/25419
Edited C# to fix the issues.
N/A
N/A
**Changelog**
N/A

UnEmagged Fixed

---

Content.Server/Paper/PaperSystem.cs
Content.Shared/Paper/PenComponent.cs
Content.Shared/Paper/StampComponent.cs
Resources/Locale/en-US/_NF/paper/stamp-component.ftl
Resources/Locale/en-US/paper/paper-component.ftl
Resources/Prototypes/Entities/Objects/Misc/paper.yml

Pen sign is back
And now also using the player name and not your ID name.
The code was broken after upstream yml update with pen parent change,
And the player name from ID name is for QOL.
Cleaned my old shit code.
N/A
N/A
**Changelog**
:cl: dvir01
- tweak: Pen sign is back, signing is now based on your name and not your ID name.

Fix Pen Sign

---

Resources/Prototypes/Entities/Objects/Consumable/Food/soup.yml

Make bowl-based foods not spill when eating them.
I don't wanna spill the soups and stews and stuff I put lots of ingredients into!
Several of the bowl-based foods in the game have a `maxVol` that is smaller than the sum of the reagents in the food. This problem is partly inherited from upstream, partly caused by the 'flavorol' reagent unique to Frontier. This really ought to be fixed on upstream too, however due to the presence of flavorol, Frontier would need different volumes anyway.
As with other foods, there is some headroom for condiments and such. I've tried to round the volume up to the nearest multiple of 5, leaving 5u unused in most cases, but some foods have less than that. There seems to be little consistency across foods anyway, with some having room for 1u of condiments, …

Increase soup maxVol to prevent spillage

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/ammo.yml

Adds boxes of slug rounds to Liberation Station.
Slugs got changed from the upstream merge, they do 28 piercing damage now which makes them useful.
**Changelog**
:cl:
- add: Liberation Station now offers slug rounds.

Adds BoxShotgunSlug to ammo.yml

---

Content.Server/Species/Systems/NymphSystem.cs
Content.Server/_NF/Species/Systems/ReformSystem.cs
Content.Shared/Species/Systems/ReformSystem.cs

this fixes the issues adressed in https://discord.com/channels/1123826877245694004/1220441283894448278
> if you die as diona and decided to gib yourself then reform as a nymph , you will lose access to your account as if you were borged. this is because the new diona is a different reference from the original player , 
Steps to reproduce
> 1.die as a diona
> 2.gib yourself so you split into nymphs
> 3.reform as a new diona
> 4.try to acess your acount , you are locked out
Also, newly formed dionas can be sold at cargo so basically you can sell yourself
-
This PR transfers bank from dead corpse to nymph and then further to the newly formed diona.
-
**Changelog**
fix: Diona reform missing bank component

Fix diona reform banking

---

Resources/Prototypes/XenoArch/Effects/normal_effects.yml

Bye bye artifact portals.
There are many unintended and uncontrollable player deaths, such as when a portal opens up on someone teleporting them to someone else's 50-reacting artifact pit and instantly dies.
no cl

Comments out Artifact Portals from list of Artifact effects

---

Resources/Maps/_NF/Shuttles/anchor.yml
Resources/Prototypes/Entities/Objects/Devices/Circuitboards/computer.yml
Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers_tabletop.yml

All mass scanners have been nerfed to be the same range as the shuttle console radar range and also added a new radar computer with 768 range that will be only available for mapping. 
People where taking the mass scanner from POIs to have much better range trying to find places like the listening post or the pirate cove, this also evens out the play field for everyone when it comes to ship combat and chases.
This console will be only available for very select ships and on the frontier outpost for the STC.
Added the console with included board also removed unintended expanded range from the anchor, (such an old ship and until now that i found about this issue lol) 
Comparison side by side
**Changelog**
:cl: Leander
- add: Nanotrasen just its newest radar microchip NSR-882 now available on …

Nerf mass scaner and add radar console

---

Content.Server/Procedural/DungeonJob.Generator.cs

Space platform dungeon generation is broken, this pr fixes it
When you start the server you get some errors as well about some `DebugTools.Assert(result);` line in DungeonJob.Generator.cs.
Before:
After: 
https://github.com/new-frontiers-14/frontier-station-14/assets/1354802/ad318457-45bc-4ee5-ba59-ae7170b6e923
In the current situation, generation stops whenever decal placement system finds a hole in the `spaceplatform.yml`, in theory this should spawn one or two rooms but it's really weird its just a huge platform with a single room or two, thats it.
The space platform has holes all over the place, so generation stops only because decal system before generating anything that makes remotely sense.
Simply commenting out the debug assertion fixes the dungeon generation and wont hurt …

Fix space platform dungeon generation

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/ammo.yml

Tranquilizers are removed from Liberation Station. Can only be obtained by crafting with an exotic recipe at Ammofab (expedition reward) or SecurityFab.
Two-shot, 20-second stuns sucks fun out of PvP and makes PvE horrifically easy.
**Changelog**
:cl:
- remove: Removed Tranquilizer rounds from LibertyVend.

Removes BoxShellTranquilizer from Liberation Station

---

Content.Server/Explosion/Components/OnTrigger/GibOnTriggerComponent.cs
Content.Server/Explosion/EntitySystems/TriggerSystem.cs
Content.Shared/Bed/Sleep/AutoWakeUpComponent.cs
Content.Shared/Bed/Sleep/SharedSleepingSystem.cs
Content.Shared/Buckle/Components/BuckleComponent.cs
Content.Shared/Buckle/SharedBuckleSystem.Buckle.cs
Resources/Prototypes/_NF/Entities/Mobs/NPCs/syndicatemob.yml
Resources/Prototypes/_NF/Entities/Objects/Misc/implanters.yml
Resources/Prototypes/_NF/Entities/Objects/Misc/subdermal_implants.yml

Added a new comp called ``AutoWakeUp`` to allow mobs who went into sleep to wake up alone after 5 secs.
Added a new Disable option to buckling to make it possible to remove buckling from a nested mob (Ignore parent control)
Added a new death acidifier that also remove organs, and working from crit state, this is done to remove entity spam of organs on floors and nothing else to be honest.
Added the comps to the syndicate faction to fix abuse of them.
C#
N/A
N/A
**Changelog**
:cl: dvir01
- tweak: Syndicate agents are now more agitated, refusing to sit, and having issues with sleeping for long duration.

Dungeons Mobs Fixup

---

Resources/Locale/en-US/_NF/chat/managers/chat_manager.ftl
Resources/Locale/en-US/deltav/chat/managers/chat_manager.ftl

Apparently on the last go-around, I missed that Frontier's version of Wizden code doesn't have folder-agnostic .ftl files, and thus it straight up didn't actually read the localizations I put there. This was an easy fix, I just take all the harpy verb localizations and put them in the frontier localizations. 
:cl: VMSolidus
- fix: Harpies now correctly trill, tweet, chirp, and caw instead of miraculously screeching about missing localizations.

Harpy speech localization 2: Electric Boogaloo

---

Content.Shared/Atmos/Rotting/PerishableComponent.cs
Content.Shared/_NF/CCVars/CCVars.cs

Adds 5 more minutes to the times it takes to rot away and respawn.
Making dying a little more meaningful and giving more chance for people to rescue recently dead people.
:cl: Leander
- tweak: Respawn times take longer but your body takes longer until it starts rotting away.

Increased respawn/rotting times again

---

Resources/Prototypes/_NF/Entities/Clothing/OuterClothing/hardsuits.yml

New stats on experimental mining hardsuit are a combination of best stats from spationaut, mining and luxury hardsuits, additionally increased caustic resistance.
Experimental Mining Hardsuit stats were underwhelming for a T3 research.
**Changelog**
- tweak: Buffed stats on Experimental Mining Hardsuit.

Experimental Mining Hardsuit Buff

---

Content.Server/GameTicking/GameTicker.Spawning.cs
Content.Server/Spawners/EntitySystems/ContainerSpawnPointSystem.cs
Content.Server/Spawners/EntitySystems/SpawnPointSystem.cs
Content.Server/Station/Systems/StationSpawningSystem.cs
Content.Shared/Roles/JobPrototype.cs
Resources/Prototypes/Nyanotrasen/Roles/Jobs/Cargo/mail_carrier.yml
Resources/Prototypes/Nyanotrasen/Roles/Jobs/Civilian/valet.yml
Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/prisoner.yml
Resources/Prototypes/Roles/Jobs/Civilian/janitor.yml
Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
Resources/Prototypes/_NF/Roles/Jobs/Command/stc.yml
Resources/Prototypes/_NF/Roles/Jobs/Security/security_guard.yml

Based on multi PR's from DeltaV
https://github.com/DeltaV-Station/Delta-v/pull/511
https://github.com/DeltaV-Station/Delta-v/pull/743
Making frontier jobs forced to spawn on the job spawns for them and not next to cryo.
Its a bit weird the spawn points for critical jobs don't get used and you just spawn next to cryo pods unless you ready on round start.
Frontier workers get sent to spawn points, that is all.
N/A
N/A
**Changelog**
N/A

Some Late Join Fixing

---

Resources/Maps/_NF/Shuttles/ceres.yml

Move the dining area defib to a reachable location.
After adding the dispensers, I forgot about the defib, and now it's _very_ hard to reach. :)
Single line of .yml
no
**Changelog**
Feels unnecessary for such a tiny change

Ceres (update): defib location hotfix

---

Resources/Prototypes/DeltaV/Entities/Mobs/Species/harpy.yml

Harpies were too fast and too furious. They now walk the same speed as everyone else.
Speed is too much of a bonus for species, this speed boost was also removed from Vulpkanin when they were ported over to Frontier.
**Changelog**
:cl: MagnusCrowe
- tweak: Harpies are no longer fast and furious.

Fix Harpy speed

---

.github/mapchecker/config.py

Adds "Admeme" to the mapchecker's list of illegal matches.
The suffixes `Admeme` and `DO NOT MAP` are currently mutually exclusive, but admeme entities should under no circumstances be mapped. Since it's easy to detect them, let's do so!
One line of Python!
Not unless someone's committed a severe mapping sin. :)

Add 'Admeme' to mapchecker as an illegal match

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml

Adjusted yml to allow ammo techfabs to accept gold and silver, since thanq shots require silver to craft.
https://discord.com/channels/1123826877245694004/1224031887245443237

[Fix] Ammotech not taking silver for use in recipes

---

Resources/Prototypes/Nyanotrasen/Roles/Jobs/Security/prisonguard.yml
Resources/Prototypes/_NF/Roles/Jobs/NFSD/brigmedic.yml
Resources/Prototypes/_NF/Roles/Jobs/NFSD/detective.yml
Resources/Prototypes/_NF/Roles/Jobs/NFSD/head_of_security.yml
Resources/Prototypes/_NF/Roles/Jobs/NFSD/security_officer.yml
Resources/Prototypes/_NF/Roles/Jobs/NFSD/senior_officer.yml
Resources/Prototypes/_NF/Roles/Jobs/NFSD/warden.yml

Updates and changes NFSD hours so it ends up as:
- Sheriff 12 hours in sec department + 30 in general
- Sergeant 9 hours in sec department + 3 hours as Deputy + 30 in general
- Warden 6 hours in sec department + 3 hours as Deputy + 15 in general
- Brigmedic, Prison guard, Detective 3 hours in sec department + 10 in general
- Deputy 6 hours in general
- Cadet 3 hours in general 
This hours take into account that sometimes people get directly hired to the NFSD so they don't do their times regularly.
**Changelog**
:cl: Leander
- tweak: NFSD hour requirements have been updated.

Change NFSD playtime requirements

---

Resources/Prototypes/_NF/Entities/Objects/Consumable/Food/Baked/misc.yml

Adds a new admin item, the _divine cookie_.
Suggested by Jester: https://discord.com/channels/1123826877245694004/1224110014877139087/1224110014877139087
It can serve as a small reward for players who do something good, like submit an ahelp about a rule violation, or whatever else admins feel like. :) It glows with a soft, magical aura. It also tastes _so_ good it even heals your injuries!
This entity is marked "DO NOT MAP" for obvious reasons.
.yml
no
**Changelog**
Not for an admin-only thing.

Divine cookie, an admin reward

---

Resources/Maps/_NF/Shuttles/lyrae.yml
Resources/Prototypes/_NF/Shipyard/lyrae.yml

Adds a new shuttle, the SBB Lyrae, a medium size science vessel with a compact interior, two laboratories configured for xenoarchaeology and anomalous science respectively, and a workshop. 
The shuttle is named after the genitive case of the constellation [Lyra](https://en.wikipedia.org/wiki/Lyra), which has been a subject to a lot of scientific study over the years. It also contains the star [Vega](https://en.wikipedia.org/wiki/Vega); a star which has been significant in science, and heavily studied by astronomers, along with the Ring Nebula, the best known planetary nebula.
As part of the name, the abbreviation 'SBB' stands for Shipyard: BlueBird, a new fictional shipbuilder.
Huge thanks to @arimah and @Gotimanga who both assisted me with mapping and many other things.
Big thanks also …

SBB Lyrae (New) - Medium Research Vessel

---

Resources/Maps/_NF/Shuttles/bookworm.yml
Resources/Prototypes/_NF/Shipyard/bookworm.yml

Adds a new shuttle, the SBB Bookworm, a library ship with a large open reading room, a games room, and a private study for the librarian. This is the second vessel to come out of Shipyard BlueBird (the first being Lyrae, #1110).
You've mined every rock in sight, stripped every wreck, gone to planets and killed four dozen dragons and xenos, and your account balance is overflowing with more spesos than you could spend in a lifetime. It's time to _relax_. Why not visit the local library to read a book or play a board game? Maybe the librarian will write epic tales of your heroic conquests, or _you_ can write about your exciting smuggling adventures.
More RP-focused ships have been requested for a long time now, and I've been enjoying playing librarian on upstream. :)
Design considerations:
* …

Bookworm (New): Library

---

Resources/Prototypes/Research/experimental.yml

No more gravity guns, i have come with complains about them for long time but always forget to make the PR for it, until now.
Bad for RP, exploited for bugs and physics issues, don't bring anything of value besides being annoying.
**Changelog**
:cl: Leander
- remove: Gravity guns have disappeared from the public research database forever.

Remove gravity guns

---

Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
Resources/Prototypes/Entities/Clothing/Uniforms/ship_vs_ship.yml
Resources/Prototypes/_NF/Entities/Clothing/Uniforms/jumpsuits.yml
Resources/Prototypes/_NF/Roles/Jobs/Hostile/syndicate_naval_forces.yml

Turns jumpsuit sensors off on syndicate agents jumpsuits to keep secrecy. Also reverts some of the changes made to base game files, so a little bit les maint work. Yay!
Turns out some of the syndicate jumpsuits had their sensors on, which spoils the location of Listening Post Bravo. This PR fixes it.

Syndie Jumpsuit Sensors Fix

---

Content.Server/Cargo/Systems/CargoSystem.Orders.cs
Content.Server/Cargo/Systems/CargoSystem.Shuttle.cs
Content.Server/Cargo/Systems/CargoSystem.Telepad.cs
Content.Shared/Cargo/CargoOrderData.cs

- Only orders made on the same computer will be shown now.
- Only linked telepads will spawn goods
This allows for mappers to map more cargo request consoles on the same grid without consoles showing orders from other people, possibly mis-approving orders that arent theirs. Also, goods only spawn on linked telepads, so it wont end up elsewhere on station anymore.
Added net entity to the cargo order data, so any client can filter the orders accordingly
**Changelog**
add: only show cargo orders from same console

Split cargo request console

---

Resources/Prototypes/Entities/Clothing/Back/backpacks.yml
Resources/Prototypes/Entities/Clothing/Back/duffel.yml
Resources/Prototypes/Entities/Clothing/Back/satchel.yml

This PR reduces the size of the the bags of holding, duffel, and satchel to be 4 more columns then a duffel bag, adding the ability to carry more items then normal while not quite the same as before this PR.
The size of items before was a grid of 19x9 which was far too many slots for people to be carrying, it took up a majority of the screen and broke gameplay.
**Changelog**
:cl:
- tweak: Nerfed bluespace bags to only 4 additional bag columns.

Bluespace Bag Rebalance

---

Resources/Maps/_NF/Shuttles/Security/prowler.yml

As per #1230, the Prowler needed to be updated with the new sprites for NFSD hardsuits, thrusters etc. On top of that, I have made a few changes to bring the Prowler up to date with the changes to security ship design, along with some general improvements to wiring, atmos and some other things to bring it in line with current submission guidelines. 
With the new rules about loose weapons, the armoury demanded a rework, and with current mapping guidelines I made some corrections to wiring and the atmos system, which I also streamlined to try and reduce the number of pipes going under walls.
New NFSD colour scheme was applied through some redecoration.
List of changes:
- Floor decals repainted in the new NFSD colour scheme.
- NFSD sprites for airlocks, lockers, thrusters, vendors etc have …

NSF Prowler: Sprite update, redecoration, tweaks

---

Resources/Prototypes/Entities/Objects/Devices/pda.yml
Resources/Prototypes/Nyanotrasen/Entities/Objects/Books/hyperlinks.yml

Currently the hyperlink system, Nyanocode, is still functional. Losing the spacelaw book has been a real pain for teaching cadets in NFSD so this would be a temp fix to be reverted once a guidebook is implemented for spacelaw.
**Changelog**
:cl:
- tweak: Temporarily restored Spacelaw books.

Hyperlink Book Restore

---

Resources/Prototypes/Datasets/ion_storm.yml
Resources/Prototypes/Species/species_weights.yml
Resources/Prototypes/_NF/ai_factions.yml

- ERT squad members have a chance to spawn as a goblin now.
- Borgs can have laws that force them to become goblin slayers due to ion storms. Same for harpies.
- Wizard Federation and Blood Cult have zero tolerance for goblins. Wonder why.
Missing features
Spawn ERT troopers
none afaik
**Changelog**
- tweak: Borgs can have laws that will force them to become goblin slayers due to ion storms. Same for harpies.

ERT goblins, borg laws regarding goblins

---

Resources/Prototypes/_NF/Recipes/Lathes/eva.yml
Resources/Prototypes/_NF/Recipes/Lathes/materials.yml

Fixes the plasteel recipe to be lore accurate: Plasteel = Plasma + Steel
Bug fix
Spawn autolathe, put stack of steel and plasma, print plasteel
none afaik
**Changelog**
- fix: Fixes the plasteel recipe to be lore accurate: Plasteel = Plasma + Steel

Plasteel Recipe Fix

---

Resources/Prototypes/_NF/Catalog/Fills/Backpacks/StarterGear/backpack.yml
Resources/Prototypes/_NF/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml
Resources/Prototypes/_NF/Catalog/Fills/Backpacks/StarterGear/satchel.yml
Resources/Prototypes/_NF/Catalog/security_uplink_catalog.yml
Resources/Prototypes/_NF/Entities/Objects/Specific/security.yml

Updated Uplink values to be more balanced.
Updated NFSD backpacks spawns to now have 10 coins on spawn, Sergeant/Bailiff uplink starts with 15 coins, and Sheriff 20. Also tuned down Hoverbike costs to now be 10 fucs instead of 35.
This change is intended to be merged along side the removal of ship armories, to prevent the buying and selling of ships specifically for the guns.
**Changelog**

Uplink FUC Balance pass

---

Resources/Prototypes/Entities/Clothing/Uniforms/base_clothinguniforms.yml
Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml

Jumpskirts were not being consistently parented to UniformJumpskirtBase, and so all of the colored jumpskirts in the game were not listed as skirts, resulting in Harpies being unable to wear them. I reparented them to the correct base, so now this works as intended.
Digitigrade Entities are fun. Tajaran are going to have the same annoyances to deal with when I port them.
**Changelog**
:cl: VMSolidus
- fix: All Jumpskirts in the game have been correctly listed as skirts, now Harpies can wear them again.

Fixes Harpy Skirt Bugs

---

Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/expeditionaryflatpackvend.yml
Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/flatpackvend.yml

Lower IFF board in vend since they can be found and resold from planets, left only 1.
Added R&D Servers back, so people wont have to buy a full kit just for an extra server.
Remove the EMAG hover since they are also sold on the contravend itself now.
Cleanup
N/A
N/A
**Changelog**
:cl: dvir01
- tweak: Lower IFF amounts in Expeditionary Flatpackvend, you can now find many IFF boards on planets.
- tweak: Added R&D Server Flatpack to Flatpackvend, removed the hidden HoverBike, they can also be found on planets now.

Flatpack Vend Edits

---

Resources/Maps/_NF/Shuttles/mailpod.yml
Resources/Prototypes/_NF/Shipyard/mailpod.yml

Cable fix
**Changelog**
:cl: dvir01
- fix: Fixed mailpod power issue

Mail Pod (Update)

---

Resources/Prototypes/_NF/Damage/modifier_sets.yml

Goblins receive 10% more damage now making them have 20% less resistance to piercing, brute and slash, also increased poison resistance by 5% and added caustic resistance by 10%.
They are even smaller than felinids and have smaller hitbox, felnids have 15% less resistance to everything so this balances out with their size.
**Changelog**
:cl: Leander
- tweak: New goblins send by the nanotrasen recycling plant are more fragile but somehow resist poison and acid much better.

Increase goblin damage

---

.gitmodules

You will need to reset the RT origin location in the local repository and force a tag reset, otherwise it will just keep using the base engine.
The client isn't aware anything is wrong and this is fully launcher compatible, as it will just keep using the original signed v218.1.0 client version.

Backport Lidgren logging cvars to RT V218.1.0

---

.gitmodules

This temporary fix isn't needed anymore, so you shouldn't keep targeting this repo.
Make sure the local watchdog origin is updated too

Retarget space-wizards/RobustToolbox

---

Resources/Prototypes/_NF/Catalog/Fills/Items/belt.yml
Resources/Prototypes/_NF/Catalog/Fills/Items/misc.yml
Resources/Prototypes/_NF/Entities/Clothing/Belt/belts.yml
Resources/Prototypes/_NF/Entities/Clothing/Neck/misc.yml
Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/belt.yml
Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/jumpsuit.yml
Resources/Prototypes/_NF/Loadouts/contractor_loadout_groups.yml
Resources/Prototypes/_NF/Loadouts/mercenary_loadout_groups.yml
Resources/Prototypes/_NF/Loadouts/pilot_loadout_groups.yml

- Filled Pilot Webbing is actually filled now.
- Fixed filled variant of salvager rig (it was empty and functioned as utility belt and not like webbing).
- Fixed price tag on filled salvager rig.
- Fixed dark green jumpsuit for contractor/pilot/mercenary loadouts.
- Made pilot drip available for mercenaries.
- Changed contents of filled chaplain sash to contain: Crucifix, Censer, Bible, Lantern, Flask with Holy Water, Mortuary Urn (Frontier specific one).
Fixes.
Choose loadout options and spawn with them.
none afaik
**Changelog**
:cl: erhardsteinhauer (discord)
- tweak: Changed contents of filled chaplain sash to contain: Crucifix, Censer, Bible, Lantern, Flask with Holy Water, Mortuary Urn.
- tweak: Gave mercenaries access to pilot clothes in loadouts.
- fix: Fixed filled Pilot webbing …

Loadout Hotfix

---

Content.Server/Worldgen/Prototypes/GCQueuePrototype.cs
Content.Server/Worldgen/Systems/LocalityLoaderSystem.cs
Content.Shared/_NF/Worldgen/Components/Debris/SpaceDebrisComponent.cs
Resources/Prototypes/Entities/World/Debris/base_debris.yml
Resources/Prototypes/GC/world.yml

its just deleting people now, needs a revert

Revert "Optimize Debris Code"

---

Content.Server/MassMedia/Systems/NewsSystem.cs
Content.Shared/_NF/MassMedia/Component/SectorNewsComponent.cs
Resources/Prototypes/_NF/Shipyard/base.yml

News consoles should work now, anyone with a valid ID with a station record can publish messages on a console.  Also, you should be able to read all published news messages from your PDA wherever you are.
The following changes were made to the code:
1. **NewsSystem no longer has an onMapInit handler.**  For shuttles being purchased, this was being run before there was a station entry, and the shuttle would never receive a StationNewsComponent.  This prevented the publish/delete actions.
2. **Added a SectorNewsComponent, with a statically defined article list.**  This mimics old behaviour, but the data is accessible through a Component instead of a System.  This makes all news stories readable from anywhere.
3. **Added a SectorNewsComponent to Frontier Outpost.**  Since Frontier Outpost …

Fix news manager consoles

---

Resources/Prototypes/_NF/Entities/Clothing/OuterClothing/armor.yml
Resources/Prototypes/_NF/Loadouts/Jobs/Mercenary/outer.yml
Resources/Prototypes/_NF/Loadouts/mercenary_loadout_groups.yml

Adds new web vest for mercs loadout with reasonable stats for $600.
Fixing my mistake
Go to merc loadouts, choose black merc vest, compare it with regular merc web vest after spawn
none I think
**Changelog**
- tweak: Starting black web vest no longer come with additional armor inserts.

Fix for loadout black web vest

---

Resources/Locale/en-US/_NF/reagents/meta/chemicals.ftl
Resources/Locale/en-US/_NF/reagents/meta/medicine.ftl
Resources/Prototypes/_NF/Reagents/chemicals.yml
Resources/Prototypes/_NF/Reagents/medicine.yml
Resources/Prototypes/_NF/Recipes/Reactions/chemicals.yml
Resources/Prototypes/_NF/Recipes/Reactions/medicine.yml

Adds 1 new chem to create a new cryo chem called Tramoxadone which restores brute damage even if dead
This helps balance the changes from med where there are no longer re-stocks and encourage advance med rather than treating everything with brute packs.  This is the Brute version of Aloxodone
take a urist,  whap it with a throngler 8 times tossed it into a cryo system and once cooled added the tramoxadone to ensure the brute was cured
**Changelog**
:cl:
- add: new Cryo Chem

adding tramoxadone and supporting chems for post mortem brute restoration

---

Content.Shared/_NF/CCVars/CCVars.cs

Makes cryobed delete people after 3 hours instead of 1.
Most people come back to the server after 1 or 2 hours when they SSD cryo, this will make sure they dont need to ask or wait for respawn as often.
No need for CL

Increase cryo delete time

---

Content.Server/MassMedia/Systems/NewsSystem.cs

This PR adds an event handler for round restart cleanup in NewsSystem.  This handler cleans up the current article set.  This is a return to behaviour that existed before the March upstream pull (compare vs [6ac021f4](https://github.com/new-frontiers-14/frontier-station-14/blob/6ac021f43cb6c6b39e8edf053062500b96954285/Content.Server/MassMedia/Systems/NewsSystem.cs#L58)).
Articles published in previous rounds showed up in later ones.  The article set is static, and has no lifecycle separate from the program's.  It must be cleared at some point, but that wasn't being done.  I should have included this in the initial feature.
1. Start a round.
2. Spawn a MassMediaConsole.
3. Publish an article.
4. Run `/golobby`.
5. Start a new round.
6. Spawn a MassMediaConsole.
7. Open it, the article …

Fix: Clear news articles on round restart

---

Resources/Prototypes/_NF/Shipyard/helix.yml

Removes the Helix from the Shipyard
With the influx of new Medical oriented vessels, the Helix has grown to show its wrinkles. Paling in comparison to other medical vessels and leaving it in an awkward position lacking modern chemistry amenities and structural artifacts reflecting the time it was designed. Also Cloning Bad 
Spawn in
Check that shipyard is missing the Helix
**Changelog**
:cl:
- remove: NT has decided to rescind its License for the Helix Blueprint from the Frontier.

Removes the Helix

---

Resources/Locale/en-US/_NF/guidebook/guides.ftl
Resources/Maps/_NF/Shuttles/ceres.yml
Resources/Prototypes/Nyanotrasen/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/_NF/Guidebook/shipyard.yml
Resources/Prototypes/_NF/Shipyard/ceres.yml
Resources/ServerInfo/_NF/Guidebook/Shipyard/Ceres.xml

Main changes:
* Expanded the freezer by one tile so I could fit a rack with restock boxes for the ChefVend, Plasteel Chef, Booze-O-Mat and condiment station.
* Also expanded the dock/entry area for symmetry. Put down a sofa in the absence of any better ideas.
* Rebranded the ship from NC Ceres to SBB Ceres. It's now made by Shipyard BlueBird, alongside the Lyrae and the Bookworm.
* Added a pre-flight checklist as is standard on all BlueBird ships. :)
Tweaks:
* Add frames around all buttons, for better visibility. Also moved the bar shutter button for increased reachability.
* Renamed a few things to make their purpose clearer.
* Correct lateral lights, in accordance with BlueBird safety requirements. :)
Restock boxes were requested by @dvir001 as these are no longer available from cargo …

Ceres (Update): Restock boxes + various tweaks

---

Content.Client/PDA/PdaMenu.xaml
Content.Client/PDA/PdaMenu.xaml.cs
Content.Server/PDA/PdaSystem.cs
Content.Shared/PDA/PdaUpdateState.cs
Resources/Locale/en-US/_NF/pda/pda-component.ftl

https://github.com/Corvax-Frontier/corvax-frontier-14/pull/208
Code taken from Corvax Frontier
Let you see your bank balance on the PDA
More info on PDA
Run the game, spawn in
Look in PDA
N/A
**Changelog**
:cl:
- tweak: Bank balance added in PDA.

PDA Bank Data

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/Research/arsenal.yml
Resources/Prototypes/_NF/Recipes/Lathes/security.yml

Restores rubber ammunition recipes to NFSD techfab.  Adds recipes to non-lethal ammunition tech.
Rubber rounds were brought back, but were left commented out of the NFSD techfab.
For the lathe recipe amounts, from [previous amounts here](https://github.com/new-frontiers-14/frontier-station-14/blob/3f1c55ea8554317085a4b05f168e8a4bd0525598/Resources/Prototypes/Recipes/Lathes/security.yml), there were ratios of 1:1 and 2:1 plastic:steel, I settled on 2:1 and applied that onto the total materials required for lethal rounds of each type.  Since plastic is considerably more expensive/difficult to obtain than steel, I think this might disincentivize its use.
1. Spawn research server, R&D computer, NFSD techfab, and research point disks
2. Research non-lethal rounds on the R&D computer (should …

Make rubber rounds printable in NFSD Techfab

---

Content.Server/Mech/Systems/MechSystem.cs
Content.Shared/Mech/EntitySystems/SharedMechSystem.cs
Content.Shared/NPC/Components/NpcFactionMemberComponent.cs
Resources/Prototypes/Entities/Objects/Weapons/Guns/turrets.yml

Mechs now copy the user mob state and factions when you enter them, making AI no longer ignore mechs
Remove the faction and mob state when you exit the mech so AI ignore it ones again.
Fixed it so mechs now eject dead users.
Abuse in mech code allow it to be used to ignore AI and attack it without ever getting hit back.
Spawn in,
Spawn a mech
Enter the mech
Spawn any hostile AI
Die.
N/A
N/A
**Changelog**
N/A

Fix mech codes to stop AI abuse

---

Content.Client/Preferences/UI/LoadoutContainer.xaml.cs
Content.Client/Preferences/UI/LoadoutGroupContainer.xaml.cs
Content.Shared/Preferences/Loadouts/LoadoutPrototype.cs
Resources/Prototypes/_NF/Catalog/Fills/Boxes/emergency.yml
Resources/Prototypes/_NF/Catalog/Fills/Crates/npc.yml
Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/belt.yml
Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/fun.yml
Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/survival.yml
Resources/Prototypes/_NF/Loadouts/Jobs/Nfsd/belt.yml
Resources/Prototypes/_NF/Loadouts/Jobs/Nfsd/survival.yml

Adds override fields for the name, description, and the entity used to get the preview sprite, to loadouts.
The loadout window under Character Setup uses these fields now to populate loadout entries.
Being stuck with the name and description of an item led to some redundancy (particularly in filled vs. unfilled belts).  Any loadout entry with more than one item shows up without a sprite, name, or description - this allows a way to get a normal-looking entry.  More control is better.
**Note:** the steps below do not test all fields (Description, PreviewEntity) on the branch under PR.  To test these, use [whatston3/branch 2024-06-07_bibleuser-implanter-tools-loadout](https://github.com/whatston3/frontier-station-14/tree/2024-06-07_bibleuser-implanter-tools-loadout), which adds a new …

Loadouts: add overrides for name, description, and preview entity

---

Content.Server/Materials/MaterialReclaimerSystem.cs
Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml
Resources/Prototypes/Entities/Objects/Specific/chemical-containers.yml
Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
Resources/Prototypes/Entities/Objects/Tools/bucket.yml
Resources/Prototypes/Entities/Structures/Machines/material_reclaimer.yml

Allow reclaimer to convert logs.
Increase storage to 1000 from 100
Remove beakers and buckets from recycle
Improvements
Use the reclaimer
N/A
**Changelog**
:cl:
- tweak: Reclaimers can now process logs and empty beakers, jugs, and buckets.
- tweak: Reclaimers liquid storage increased to 1000u.

Reclaimer update

---

Content.Server/Nyanotrasen/Abilities/Oni/HeldByOniComponent.cs
Content.Server/Nyanotrasen/Abilities/Oni/OniSystem.cs

Wielded weapons will now generally* fire in front of you as an Oni.  You are not accurate, you are an Oni.
One-handed weapons will now generally* fire about as well as wielded weapons in front of you as an Oni.
OniSystem now tracks if a weapon has a wielded malus before increasing its spread, and stores how much penalty was added in HeldByOniComponent.  It should also now prevent consistency issues with race conditions from picking up/dropping entities.
This also reduces overall spread for Oni weapons by 10% (20x normal spread to 18x normal spread).
\*See Balance.
Previous behaviour had all wielded weapons shooting in all possible directions (see media for previous behaviour) when they should be marginally accurate.  Previous behaviour also had Oni shooting pistols as reliably as any …

Fix Oni accuracy with wielded weapons, and apply Oni accuracy to handguns.

---

Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml

This was changed by mistake when restoring the old names of suits.
Should be 95% radiation protection.
https://github.com/new-frontiers-14/frontier-station-14/pull/996

CE Suit rads fixup

---

Resources/clientCommandPerms.yml

Removes the ability for clients to record replays, most people already use stuff like OBS or better options to record their game.
Lead to abuse and exploits.
No need for CL

Disable client replays

---

Content.Server/Paper/PaperSystem.cs
Content.Shared/Paper/StampComponent.cs
Resources/Prototypes/Entities/Objects/Misc/paper.yml

Fixes a bug where the server would erroneously let people think they are, and I quote, `A very important person`. This was caused by pens still having the stamp component from the old signing system, component has now been removed and signing works as normal.
Fixing bugs.
Spawn paper.
Spawn any stamp.
Stamp paper.
Click paper without alt, observe. You are not `A very important person`.
**Changelog**
:cl:
- fix: Left clicking a signed/stamped paper won't add a bogus signature onto it anymore.

Pen signing fix

---

Resources/Prototypes/_NF/Entities/Markers/Spawners/Random/dungeon_items_mercenary.yml
Resources/Prototypes/_NF/Entities/Markers/Spawners/Random/dungeon_items_weapons.yml

- Lowered the chance for spawning explosives: 30% for tier 1 (fire bombs), 40% for tier 2 (pipe bombs), 50% for tier 3 (seismic charges), 40% for tier 4 (hiex grenades) and 30% for tier 5 (C4).
- Removed empty weapon cases from weapon spawners.
- Lowered the chance for spawning weapon cases overall: "loose" weapon cases - 50%, vault - 70% for unprotected and 90% for protected.
Cutting down explosives spam, changing somewhat frustrating for players mechanics with empty cases.
Use `random weapon [Dungeon, ...]` spawners, observe the results.
none
**Changelog**
not needed I think

Dungeon Weapon Spawner Rebalance

---

Resources/Prototypes/_NF/Entities/Structures/Doors/Airlocks/access.yml

I am not in a form filling mood today.
Adds three missing suffixes, the entire file actually has suffixes now. To my knowledge none of these doors were erroneously placed anywhere in the existing maps/shuttles.

Add missing suffixes to Frontier Command Engineering/Atmos doors

---

Resources/Prototypes/_NF/Catalog/Fills/Backpacks/StarterGear/messenger.yml
Resources/Prototypes/_NF/Loadouts/Jobs/StationRep/bags.yml
Resources/Prototypes/_NF/Loadouts/stationrep_loadout_groups.yml

Changes the station rep's messenger bag in loadouts.  Uses a filled version, and uses the green and tan version that @ErhardSteinhauer created.
Not giving the SR a filled bag was an oversight.
Giving the SR a green bag makes sense, since we have a role-specific version.
Build and run local server.
1. Open loadout, check SR backpack options.  Green messenger bag should appear.
2. Select messenger bag, spawn in-game.  Check backpack contents, should include a flash, stamp, access configurator and red phone.
**Changelog**
- fix: The station representative's messenger bag loadout option is now correctly filled.

Loadouts: fix empty SR messenger bag

---

Content.Server/Body/Components/MetabolizerComponent.cs
Content.Server/Body/Systems/MetabolizerSystem.cs
Content.Server/Medical/CryoPodSystem.cs
Content.Shared/Chemistry/Components/Solution.cs
Content.Shared/Chemistry/EntitySystems/SharedSolutionContainerSystem.cs
Content.Shared/Medical/Cryogenics/CryoPodComponent.cs
Resources/Locale/en-US/_NF/metabolism/metabolism-groups.ftl
Resources/Locale/en-US/reagents/meta/medicine.ftl
Resources/Prototypes/Body/Organs/Animal/animal.yml
Resources/Prototypes/Body/Organs/Animal/slimes.yml
Resources/Prototypes/Body/Organs/arachnid.yml
Resources/Prototypes/Body/Organs/diona.yml
Resources/Prototypes/Body/Organs/human.yml
Resources/Prototypes/Body/Organs/moth.yml
Resources/Prototypes/Body/Organs/slime.yml
Resources/Prototypes/Entities/Mobs/NPCs/behonker.yml
Resources/Prototypes/Entities/Mobs/Player/dragon.yml
Resources/Prototypes/Reagents/medicine.yml
Resources/Prototypes/_NF/Body/Organs/goblin_organs.yml
Resources/Prototypes/_NF/Body/Organs/synthetic_organs.yml
Resources/Prototypes/_NF/Chemistry/metabolism_groups.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/baby_dragon.yml
Resources/Prototypes/_NF/Entities/Mobs/Player/jerma.yml
Resources/Prototypes/_NF/Reagents/medicine.yml
Resources/ServerInfo/Guidebook/Medical/Cryogenics.xml

This PR addresses side effects of the Cryo Overhaul PR, and reverts most changes in behaviour to metabolism.
1. Metabolism is once again limited (see point 4) to a fixed number of reagents per metabolizer (hereafter, organ).
2. A new metabolism group was added, "Cryogenic", that contains all current cryogenic medicine.
3. All existing organs that could metabolize Medicine have had Cryogenics metabolism added.
4. Any organ that can metabolize cryogenic medicine can metabolize an unlimited number of them at once without counting against the number of processed reagents.
5. Cryo pods now only administer cryogenics medicines, but maintain all efficiency and injection rate changes (2x as efficient, 0.25u/s draw per reagent in solution)
I have added versions of per-reagent SplitSolution …

Cryogenics: restrict cryo pods to cryo meds, restore limited metabolism

---

Content.Shared/Movement/Systems/SharedMoverController.cs

Outer clothing (hardsuits, etc.) that has a footstep modifier will apply its status to the player when they walk.  This takes precedence over the shoes (your shoes should be inside your armoured hardsuit).  Since outer clothing usually has sprites that cover the character's feet, this seems sensible to me.
Brought up in #1551.  No real balance, just fun - opens the possibility for more immersive, beefier hardsuits (could make the clown hardsuit squeak, for instance).  If this is desirable vs. pilotable mech suits, I do not know.
Check out [whatston3:maid-time](https://github.com/whatston3/frontier-station-14/tree/maid-time) - visually check that the commit history includes this PR's exact commits - all of them.  Run the following tests:
0. Walk around, you make barefoot/shoe noises.
1. …

Check outer clothing for footstep noise

---

Resources/Prototypes/_NF/Entities/Objects/Specific/pirate.yml
Resources/Prototypes/_NF/Roles/Jobs/Pirates/pirate.yml
Resources/Prototypes/_NF/Roles/Jobs/Pirates/pirate_captain.yml
Resources/Prototypes/_NF/Roles/Jobs/Pirates/pirate_first_mate.yml

Fixed pirates actually having access to their uplinks on spawn
**Changelog**
:cl:
- fix: Pirate roles now spawn with their proper uplink.

Added uplinks to pirate spawn loadout

---

Resources/Prototypes/_NF/Mail/Items/paper.yml
Resources/Prototypes/_NF/Mail/mail.yml
Resources/Prototypes/_NF/Mail/mailDeliveries.yml

Cleans up mail papers (noSpawn set to true), adds more mail for the SR.  Skub, SecurityDonuts, and SecurityNFSpaceLaw mail entries fixed.
noSpawn was only commented out for testing - should've been removed when the PR went out of draft.  Skub, Donuts, and SpaceLaw entries were broken.  My fault, sloppy.  SR could also use some more mail.
Spawn in, check spawn menu for "MailPaperNF".  Nothing should show up.
None.
**Changelog**
:cl:
- tweak: Skub and a few security mail types have been fixed.  Added a new SR and common mail type.

Mail: Cleanup, Fixes, More SR Mail

---

Resources/Prototypes/_NF/Events/events_bluespace.yml

It increses its duration from 15-20 minutes to 35-40 minutes to give players more time to loot it.
15-20 minutes is defently not enough to kill all enemies and loot it, even with the sheer of 20-30 creates. I mostly see NFSD starting to loot it and then just disappearing when they directly responded to it.
Run fork
add the game rule BluespaceDataCarrier via addgamerule
go and wait the timer out and see it disappear
**Changelog**
:cl:
- tweak: The Data Carrier is now lasting longer before it disappears.

Buffing Data Carrier Duration

---

Content.Server/Shipyard/Systems/ShipyardSystem.Consoles.cs
Content.Shared/Shipyard/Components/SharedShipyardConsoleComponent.cs
Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers_shipyard.yml
Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers_shipyard_mothership.yml

Move a bunch of stuff from ShipyardSystem to the ShipyardConsoleComponent, to reduce hardcoded nonsense. Chiefly this reduces logic based on the UI key (very smelly code).
* `ShipyardChannel` is now *always* used for the primary purchase and sale announcement, instead of picking the channel based on the UI key.
* `SecurityShipyardChannel` is gone, and in its place we get `SecretShipyardChannel`, a secondary channel that announces redacted information. Used by black market and syndicate shipyards to alert the NFSD.
* New field: `NewJobTitle`, which updates the ID card's job title if present. Allows us to *not* update job titles for NFSD and the SR. Additional logic will be introduced **in a future PR** such that we *always* leave certain jobs alone.
* New field: `NewAccessLevels`. Pretty …

Unhardcode a bunch of shipyard console stuff

---

Resources/Prototypes/Entities/Structures/Shuttles/cannons.yml

Added `MobState` and `NpcFactionMember` to shuttle cannon parent, all cannons (bar pirate one) are NT-aligned.
Mobs (and turrets) should recognize cannons as dangerous object and treat it like a valid target
Spawn shuttle guns
```
ShuttleGunSvalinnMachineGun
ShuttleGunPerforator
ShuttleGunFriendship
ShuttleGunDuster
ShuttleGunPirateCannon
ShuttleGunKinetic
```
Spawn any mob/turret, that's hostile to NT
edits to base game file
**Changelog**
:cl: erhardsteinhauer (discord)
- tweak: Shuttle cannons can now be targeted by mobs and turrets.

Shuttle cannons can now be targeted by mobs and turrets

---

Content.Server/Administration/Systems/AdminVerbSystem.Antags.cs
Resources/Prototypes/Shuttles/shuttle_incoming_event.yml
Resources/Prototypes/_NF/Events/events.yml

Removes the LoneOpsSpawn along with the admin verb that creates them.
Unwanted, preloaded shuttle grids have also been commented out.
Regression - event was concrete, could spawn in normal gameplay.  Preloaded shuttles clutter the objects menu, and are not spawned through events.
1. Build and run local server.
2. Try to run `addgamerule LoneOpsSpawn` in the debug menu (`)
3. It should fail, autocomplete should not populate "LoneOpsSpawn" in the suggestions.
4. Right-click your character, open the "Antag Ctrl"
5. Open the admin bar (F7), check the objects menu.
6. You should not see "SLV Salami-Salami" or other preloaded shuttle names - only POIs and a few asteroids/wrecks should be visible.
No nukie verb:
Clean objects list:
**Changelog**
:cl:
- fix: Lone operative ghost roles should no …

Remove LoneOpsSpawn rule, nukie admin verb, and unused preloaded shuttles.

---

Resources/Prototypes/Recipes/Construction/Graphs/structures/railing.yml

Commented out `southRotation: true` in railing construction graph so it is possible to build railing facing any direction.
bug fix
use construction menu to build railings facing different directions
base game file changes
**Changelog**
- fix: Fixed railings always facing south upon construction.

Fix railing

---

Content.Client/UserInterface/Systems/Ghost/Controls/Roles/GhostRolesEui.cs

Ghost roles are now permissive if they don't have a prototype.
Non-whitelisted ghost roles (e.g. mr. dips, pet rock, emotional support pets, hydroponics trays) don't have a prototype listed - this is by design.  In the case where there is no prototype, the ghost role should be non-whitelisted.
1. Build and run local server.
2. Make sure you aren't whitelisted at all (nuke & backup your build's DB if needed)
3. Spawn mr. dips
4. Put mr. dips in your hand, insert the hand.  Run /aghost.
5. Open Ghost Roles.
6. Only mr. dips should be accessible.
7. Run `ghostroleadd <your_account_name> CatClarpy`
8. Close and open Ghost Roles.
9. mr. dips and Clarpy should be selectable.
10. Run `whitelistadd <your_account_name>`
11. Close and open Ghost Roles.
12. All ghost roles should be selectable.
Not …

Fix Ghost Role Whitelist Conditions

---

Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
Resources/Prototypes/Entities/Clothing/OuterClothing/vests.yml

- Adds `AllowSuitStorageClothing` as a second parent to `ClothingOuterBase`
imo if the item has `SuitStorage` it should be able to store items with `suitStorage` there
1. equip any outer clothing article
2. put gas tank in your suit storage slot
changes to `base_clothingouter.yml`
**Changelog**
:cl: erhardesteinhauer
- fix: Restored suit storage slot functionality in outer clothing articles.

Suit storage slot for outer clothing

---

Content.Client/Lobby/LobbyUIController.cs
Content.Client/Lobby/UI/CharacterPickerButton.xaml.cs
Content.Client/Lobby/UI/Loadouts/LoadoutWindow.xaml
Content.Client/Lobby/UI/Loadouts/LoadoutWindow.xaml.cs
Content.Client/Lobby/UI/LobbyCharacterPreviewPanel.xaml
Content.Client/Lobby/UI/LobbyCharacterPreviewPanel.xaml.cs
Content.Shared/Preferences/HumanoidCharacterProfile.cs
Resources/Locale/en-US/_NF/loadouts/loadouts.ftl
Resources/Locale/en-US/_NF/preferences/humanoid-character-profile.ftl

Added per-character bank balance to lobby screen and character setup GUI, commented Frontier-modified lines.
Value should always be visible, whether or not a job is selected.
Partial regression vs. master before upstream merge, quality of life - should have some idea of how much money your character has before entering the game, especially when selecting loadouts.
Build and run server.
1. Create a new character.
2. Lobby should display the bank balance of your current character.
3. Open character setup screen.
4. All displayed characters should have their bank balances stated.
5. Create a new character.
6. Your new character should have its bank balance stated.
7. Start the round with a particular character.
8. Insert money into an ATM, deposit it.  Note the value of your bank account.
9. …

Add bank balance to lobby, character setup, and loadout screens.

---

Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/neck.yml
Resources/Prototypes/_NF/Loadouts/contractor_loadout_groups.yml

Added IFF strobes to loadout menu
QoL
Check `neck` section of loadouts menu.
**Changelog**
:cl: erhardesteinhauer
- add: Added IFF strobes to loadouts menu.

IFF strobes to loadouts

---

Resources/Prototypes/_NF/Guidebook/shuttle_maps.yml

Added `noSpawn: true` to all guidebook shuttle maps
Fixing oversight
Load the environment, try (and fail) to spawn shuttle maps through entity spawn menu
None 
**Changelog**
Not needed

NoSpawn for shuttle maps

---

Resources/Locale/en-US/_NF/guidebook/guides.ftl
Resources/Maps/_NF/Shuttles/bookworm.yml
Resources/Prototypes/_NF/Catalog/Fills/Paper/Shipyard/manuals.yml
Resources/Prototypes/_NF/Guidebook/shipyard.yml
Resources/ServerInfo/_NF/Guidebook/Shipyard/Bookworm.xml

This PR addresses some feedback I have received from players, mostly in game, on the SBB Bookworm shuttle. The biggest complaint is that the Bookworm on purchase simply uses _too much power_. The poor single PACMAN has to run at 18 kW to keep up, which eats through plasma like nobody's business. Summary of changes:
* Replace three thrusters with small thrusters (lateral + reverse). This reduces the power consumption by 3 kW and does not drastically alter the shuttle's flight characteristics. As a result, the PACMAN can now be turned _down_ to 14 kW instead of up to 18.
* Use the new on-by-default air pump for distro, and anchor the canister.
* Remove librarian and pilot spawn points, move latejoin spawn point up one tile.
* Move preflight checklist to a newly created guidebook entry, add …

Bookworm (Update): QoL stuff

---

Content.Shared/_NF/CCVars/CCVars.cs

Wait at a stop timer increased 150 -> 180
Time in FTL decreased 145 -> 50
QoL: harder to miss the buss
Get on the bus
none afaik
**Changelog**
- tweak: Changed bus schedule: 50 seconds in FTL, 3 mins at a stop.

Changes to the bus schedule

---

Resources/Textures/Structures/Machines/VendingMachines/pride.rsi/meta.json

updates the pride-o-mat json to have my current discord tag, i am the spriter for it
discord no longer has username#number, and this is outdated

Update meta.json for pride drobe

---

Content.Server/Nutrition/EntitySystems/FoodSystem.cs
Content.Server/Nutrition/EntitySystems/SliceableFoodSystem.cs

When food is bitten or sliced, this adjusts the capacity in the food - for instance, you shouldn't be able to replace the bite of chocolate cake you just ate with ketchup.
Separated out at the request of @dvir001 - this was added into the Goblin Food Rework PR (#1159) a long time ago, and has been stuck in limbo and needs more work.  Feature's simple enough and easy to verify that it should be done separately.
1. Spawn an apple.
2. Open the solution editor on the apple.
3. Take a bite.  Note that the solution capacity decreases.
4. Spawn an apple cake and a knife.
5. Cut the cake.  Note that the solution capacity decreases proportionally with the number of slices in the cake.
**Changelog**
- tweak: Food now loses capacity when bitten or sliced.

Adjust solution size on slicing/eating food

---

Resources/Prototypes/_NF/Entities/Markers/Spawners/Random/dungeon_items_mercenary.yml

Some how forgor to remove couple lines with empty cases in [Dungeon Weapon Spawner Rebalance PR](https://github.com/new-frontiers-14/frontier-station-14/pull/1543). This PR fixes that old overlook.
Removing somewhat frustrating for players mechanics with empty cases.
Use random weapon [Dungeon, ...] spawners, observe the results: should not spawn empty cases at all.
**Changelog**
- fix: Removed empty weapon cases from expeditions fr this time.

Actually removing empty weapon cases from weapon spawners

---

Resources/Prototypes/_NF/Entities/Objects/Devices/pda.yml
Resources/Prototypes/_NF/Entities/Objects/Misc/mail_capsule.yml
Resources/Prototypes/_NF/Roles/Jobs/Fun/emergencyresponseteam.yml
Resources/Prototypes/_NF/Roles/Jobs/Nfsd/sheriff.yml

This PR changes the starting gear for ERT mail carriers and the sheriff to free up the suit storage slot for Vox.
The ERT mail carrier now has a CentCom pen in their PDA, and their mailbag starts equipped with ten mail cartridges.
The Sheriff's multiphase laser gun now starts in their bag, and their starting gear, as ordered, will fill a satchel, backpack, and messenger bag without any items spawning on the floor.
The Vox include a suitstorage-bound item on spawn, which would collide with the job loadouts.
These were the only Frontier-specific jobs with suitstorage items.
1. Build and run server.
2. Spawn as sheriff with a satchel.  Note your gear, none of it should be missing.  None of it should be on the floor.
3. Run `golobby`.
4. Spawn as sheriff with a backpack.  Note your gear, none …

Sheriff, ERT Mail Carrier Starting Gear: vacate suitstorage

---

Content.Server/Connection/ConnectionManager.cs

With this PR, if a new player joins during a round before panic bunker is enabled, then disconnects (e.g. due to network issues), this allows them to rejoin later in the round.
Letting somebody in to play only to kick them out on a reconnect shortly after is pretty awful.
1. Run a server.  Do not skip the timer, let the lobby timer go.
2. Open the client (Client 1).  Connect to the server with a unique username.
3. Open the client (Client 2).  Connect to the server with a unique username.
4. Run `deadmin` on Client 2.
5. Disconnect from Client 2.
6. On Client 1, run `panicbunker`.
7. Reconnect on Client 2.  You should be let in.
8. Open the client (Client 3).  Connect to the server with a unique username.  You should be rejected.
9. Disconnect from Client 2.
10. On Client 1, run …

ConnectionManager: respect existing sessions

---

.vscode/launch.json
.vscode/tasks.json

This PR adds a new build target specifically to the VSCode config: "Server/Client (Release)".
Over the past many months of mapping for Frontier and helping others map for Frontier, I've noticed one recurring problem: people map in debug mode, and get annoyed or discouraged when the game keeps crashing. Unlike Visual Studio, the very popular and generally easier-to-use VSCode does _not_ have any easy way of forcing a release build. Visual Studio has a Debug/Release dropdown, VSCode has nothing. "Run Without Debugging" still creates a debug build and just doesn't attach a debugger to it. To run a server in release mode, additional hoops must be jumped through, making mapping needlessly complicated for non-coders.
To help people have a better time whilst mapping, this is my solution: just …

Add 'Server/Client (Release)' build for VSCode

---

Resources/ServerInfo/_NF/Guidebook/Rules/12_PVP.xml

Remove clause for players needing to ahelp to become pirate since it is no longer relevant with the new system of latejoins.
**Changelog**
:cl:
- fix: The rule stating that pirates must ahelp has been removed.

Fix pirates rule

---

Resources/Maps/_NF/Shuttles/BlackMarket/schooner.yml
Resources/Maps/_NF/Shuttles/bazaar.yml
Resources/Maps/_NF/Shuttles/liquidator.yml

Updated radiation safety equipment on Liquidator (shutters start in closed position), Schooner (added radiation protection shutters and suits), fixed small issue with Bazaar (radiation shutter wasn't linked to button).
Safety!
Buy Liquidator, Schooner, Bazaar.
**Changelog**
- tweak: Updated radiation safety measures on Liquidator and Schooner.

Update to radiation safety gear on Liquidator and Schooner

---

Resources/Locale/en-US/_NF/navmap-beacons/station-beacons.ftl
Resources/Maps/_NF/POI/grifty.yml
Resources/Maps/_NF/POI/lodge.yml
Resources/Prototypes/_NF/Entities/Objects/Devices/station_beacon.yml

- Added FuelVend to The Lodge and Grifty's.
- Fixed station beacons at the Lodge.
QoL
1. Spawn at the Lodge, use station map, use fuel vend.
2. Warp to the Grifty's.
none
**Changelog**
- add: Added FuelVend to the Lodge and Grifty's.
- fix: Fixed map beacons at the Lodge.

Added FuelVend to The Lodge and Grifty's

---

Resources/Maps/_NF/Outpost/frontier.yml
Resources/Prototypes/_NF/Catalog/Fills/Paper/forms_sr.yml

- Added 8 paper templates for SR with forms for: employment contract, employee's pay history, fund requisition form, authorization contract, shuttle title change form, derelict ship form, contraband turnover form, contraband permit form (in case no sheriff on duty).
- Mapped SR folder with said templates to SR's office.
QoL
1. Spawn as SR, look for green folder in the office, inspect papers inside that folder.
**Changelog**
- add: Added a folder with paperwork templates to SR's office.

SR paperwork templates

---

Resources/Prototypes/Catalog/Fills/Crates/salvage.yml
Resources/Prototypes/Entities/Mobs/Corpses/corpses.yml
Resources/Prototypes/_NF/Entities/Markers/Spawners/Random/dungeon_items_corpses.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/corpses.yml

- Random corpses spawned at expeditions and in salvage crates now drop rotten meat if butchered.
Immersion? Plus less free human meat.
1. Use `SpawnDungeonRandomHumanCorpse` to spawn a random corpse, butcher it, get rotten meat.
2. Spawn `CrateSalvageAssortedGoodies` until you get a body inside one, butcher it, get rotten meat.
**Changelog**
- tweak: Random corpses spawned at expeditions and in salvage crates now drop rotten meat if butchered.

Spawned random human corpses drop rotten meat if butchered

---

Resources/Maps/_NF/Shuttles/Expedition/praeda.yml
Resources/Maps/_NF/Shuttles/caduceus.yml
Resources/Prototypes/_NF/Entities/Structures/atm.yml

Reverted noRot to standing ATMs (this was a mistake, sorry).
Kept noRot to false on wallmount ATMs (looks good, maps with the accessible sides)
Validated that all ATMs are placed in reasonable locations between all POIs and ships (why are there so many ships)
Sideways standing ATM consoles look wrong.
1. Purchase a Caduceus, look at the ATM placement, should make sense, should be accessible from the white floor to the south.
2. Purchase a Praeda, look at the ATM placement, should make sense (jutting outside of one end of the wall).
3. Spawn a withdraw-only ATM, a bank ATM, a wallmount ATM, a black market ATM and a black market wallmount ATM.
4. Rotate the screen.  Standing ATMs should not rotate, wallmount versions should.
Caduceus ATM placement
Praeda ATM placement (locker moved during …

ATM rotation fixes

---

Resources/Maps/_NF/Shuttles/hauler.yml

Hauler had a black wall closet that would _instantly trap_ anyone who tried to open it, and then you would be crushed to death. In a recent round on Maunder, 4 or 5 people died, some permanently, to this one closet.
This was caused by a custom fill that referenced invalid entity IDs. For some reason, that causes the locker to close instantly. I first tested with the invalid entities removed, and that resolved the instant closing. Then, because the locker just contained some useless clothing and a lantern, I deleted the whole thing and replaced it with an empty locker.
Death trap bad. Custom fill bad. Change approved by Safety Moth.
1. Buy a Hauler.
2. Open the closet in the screenshot below.
3. Don't suffocate inside a wall with no hope of escape.
If anything, this will *stop* breaking …

Hauler (Hotfix): Death trap closet is no longer an instant killer

---

Content.Shared/Fluids/SharedPuddleSystem.Evaporation.cs
Resources/Prototypes/Reagents/Consumable/Food/condiments.yml
Resources/Prototypes/Reagents/biological.yml

Your blood isn't food, stop farming your own blood for food.
Slimes and diona should not be farmed for food.
Be slime, remove blood, drink blood, get nothing.
N/A
N/A
**Changelog**
:cl: dvir01
- tweak: Slimes and Diona blood no longer satiate hunger.

Blood isn't Food

---

Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_bloodcultist.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_syndicate.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_wizardfederation.yml

Added new gibbing system to syndicate, wizard federation and blood cultist humanoid mobs.
BaLaNcE.
1. Spawn any human mob, like syndicate naval captain for example.
2. Kill and gib it. There shouldn't be any equipment left.
gaemer loot :(
**Changelog**
- fix: Removed equipment spawn on gib event from mobs.

Fix gib for syndicate, wizfed and cultist mobs

---

Resources/Prototypes/_NF/Shipyard/Expedition/ambition.yml
Resources/Prototypes/_NF/Shipyard/Expedition/brigand.yml
Resources/Prototypes/_NF/Shipyard/Expedition/dartx.yml
Resources/Prototypes/_NF/Shipyard/Expedition/decadedove.yml
Resources/Prototypes/_NF/Shipyard/Expedition/dragonfly.yml
Resources/Prototypes/_NF/Shipyard/Expedition/gasbender.yml
Resources/Prototypes/_NF/Shipyard/Expedition/gourd.yml
Resources/Prototypes/_NF/Shipyard/Expedition/praeda.yml
Resources/Prototypes/_NF/Shipyard/Expedition/sprinter.yml

Went through available for purchase expedition shuttles and increased final price markup to 30% (from 15%). Added some missing notes about shuttle creators/maintainers.
Hidden guidelines.
1. Look through shuttle listing on expedition shipyard.
Mah wallet
**Changelog**
- tweak: Adjusted expedition shipyard prices according to guidelines.

30% markup for expedition shuttles

---

Resources/Prototypes/_NF/Shipyard/cleithro.yml

Makes DC Cleithro unavailable. Keeps the map file for Darin to do whatever he wants to with it.
Requested by Darin. The joke was never that funny and the ship isn't great.
- Ensure Cleithro is no longer buyable.
No.
**Changelog**
:cl:
- remove: The DC Cleithro is no longer available.

Remove DC Cleithro

---

Resources/Prototypes/_NF/Entities/Clothing/OuterClothing/hardsuits.yml

Experimental NFSD hardsuit inherited `ContrabandClothing` from its parent and because of that anyone who used that hardsuit was targeted by contraband denying turrets. This PR fixes this issue.
Bug fix
1. Spawn Experimental NFSD hardsuit
2. Spawn CDET
3. Wear Experimental NFSD hardsuit
**Changelog**
- fix: Experimental NFSD hardsuit is no longer targeted by CDET.

Fixed faction on experimental nfsd hardsuit

---

Resources/Maps/_NF/Shuttles/Scrap/orange.yml

Removes the microwave from SV Orange.
Missed in #1684. The SV Orange is not a food ship by any stretch of the imagination. :D
1. Buy an Orange
2. Try not to die when you enter it
3. Make sure there's no microwave
No. :)
**Changelog**
:cl:
- remove: The SV Orange no longer comes with a microwave.

Remove microwave from SV Orange

---

Content.Server/Chemistry/EntitySystems/InjectorSystem.cs
Content.Shared/Chemistry/Components/InjectorComponent.cs
Content.Shared/_NF/Chemistry/EntitySystems/ChangeReagentWhitelistSystem.cs

* Fix selective dropper server/client desync by adding an explicit call to `SolutionContainers.UpdateChemicals`. This is called indirectly by the non-whitelist code, in `SolutionContainers.Draw`, and is responsible for synchronising client and server.
* Use `SplitSolutionWithOnly` instead of `SplitSolutionWithout`, since the former does the same job as what we'd reimplemented for whitelisty stuff.
* Change the whitelist to an array instead of a list. Less overhead, easier to cast to `string[]`.
Selective dropper code was a bit ugly. Server/client desync bad.
1. Put some solutions in a beaker.
2. Set the dropper to draw one of the solutions in the beaker.
3. Draw.
4. Notice that the beaker updates its visuals correctly, and that the correct solution is present in the dropper.
5. Rejoice. …

Selective dropper fixes

---

Resources/Prototypes/Entities/Clothing/Belt/belts.yml
Resources/Prototypes/_NF/Catalog/Fills/Items/belt.yml
Resources/Prototypes/_NF/Entities/Clothing/Belt/belts.yml

- Commented out whitelists on every single belt.
- Belts now have uniform storage capacity.
- Renamed 'wand belt' -> 'wizard belt'.
- Swapped grappling gun with screwdriver in pilot webbing.
With webbings so widely available, belts become completely irrelevant, this PR fixes it.
Grab a belt, use it like you'd use a webbing
**Changelog**
- tweak: Belts now function like webbings.

Removed whitelists from belts

---

Resources/Maps/_NF/Outpost/frontier.yml
Resources/Prototypes/_NF/Shipyard/Sr/bottleneck.yml

Added the SR Shipyard Console from #1580 to Frontier Outpost station map.
Now the SR can actually purchase and use the NT Bottleneck.
Requisite addition for the SR to be able to purchase their exclusive shuttle.
I propose two options for this. (Screenshots of both options in media). _THIS PR IS USING OPTION ONE._
Option one:
The console is placed next to the gun safe in the office. I've therefore also moved the filing cabinet down a bit, and also moved the uniform printer and the table with materials over to where the mail teleporter is located so that corner doesn't feel too cramped. 
Option two:
The console is placed in the staff lounge next to the SR's bedroom. There's an unused space in the top right corner of that room.
Of course, it could be placed in other locations in different …

Adds SR Shipyard Console to Frontier Outpost

---

Resources/Maps/_NF/Outpost/frontier.yml
Resources/Prototypes/_NF/Shipyard/Sr/bottleneck.yml

Recreation of #1725. Unfortunately, since the original PR, the Frontier Outpost map had received additional updates and an entity ID was duplicated. This broke everything. I replicated Tych0's mapping changes:

Add SR shipyard console to Frontier Outpost

---

Resources/Maps/_NF/POI/tinnia.yml
Resources/Maps/_NF/POI/trade.yml
Resources/Prototypes/_NF/Entities/Structures/Machines/fax_machine.yml

1. Removes that silly extra pipe from Tinnia's.
2. Powers the new cargo market computer at cargo bay 3 in the Trade Outpost. The wires are moved north by one tile to better match (most of) the other cargo bays.
Good maps good.
1. Warp to Tinnia's. Don't see a random red pipe in hydroponics. Happy.
2. Warp to Trade Outpost, visit cargo bay 3. Notice that the new cargo market computer is powered. Happy.
Tinnia's:
Trade Outpost:
No.
**Changelog**
N/A

Fix two minor POI bugs (Tinnia's, Trade)

---

Content.Server/Kitchen/EntitySystems/MicrowaveSystem.cs
Content.Shared/Kitchen/MicrowaveMealRecipePrototype.cs
Resources/Locale/en-US/_NF/reagents/foods.ftl
Resources/Locale/en-US/_NF/reagents/meta/consumable/food/food.ftl
Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
Resources/Prototypes/_NF/Entities/Objects/Consumable/Food/ingredients.yml
Resources/Prototypes/_NF/Reagents/Consumables/food.yml
Resources/Prototypes/_NF/Recipes/Cooking/meal_recipes.yml

* Add a new reagent: Raisins.
* Update the raisin bag to come with 50u raisins instead of being a useless empty item.
* Add a new microwave recipe for a raisin bag: 5 grapes for 30 seconds. Dries out the grapes, you know? It's a little bit cursed to spawn a bag out of nowhere, but what can you do.
* Add a new `ResultCount` to MicrowaveMealRecipePrototype, allowing us to spawn multiple things when a recipe is completed. Defaults to 1.
* Update cookie recipes to yield more than one cookie per batch. Cook time is increased as well.
* Rename "chocolate chip bag" to "cocoa powder bag", to reflect what it actually contains.
* The raisin bag is in a weird place currently: it's useless! It doesn't contain anything, can't be used in any recipe, and is overall meaningless. The new Raisins reagent …

Raisins + some minor ingredient and microwave recipe changes

---

Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml
Resources/Prototypes/Entities/Mobs/Player/observer.yml

Title, adds an intrinsic radar action and UI for regular observer ghost so they can watch with more detail ships colliding or moving around and its location, set to the regular range of 256 like all other mass scanners, and the admin one has been set to 1024. 
why the regular observer one so low compared to the admin one? we dont want ghost guys trying to find secret POIs with a longer radar.
>start server
>become observer
>press hotkey 1
**Changelog**
:cl: Leander
- add: Observer ghost can now use their own mass scanner to watch ships around.

Observer radar update

---

Resources/Prototypes/_NF/Entities/Structures/Machines/telecomms.yml

Removes superfluous encryption keys from shuttle telecom server. The server gets to keep its common and medical keys.
This prototype exists only for expeditionary vessels. When you're on an expedition, realistically speaking, you don't need anything other than common and _maybe_ medical for implants. Once you're back from the expedition, you don't need your own server at all, so all the extra keys are extra useless.
1. Spawn a `TelecomServerFilledShuttle`.
2. Verify that it only contains Common and Medical.
No.
**Changelog**
N/A

Remove superfluous keys from shuttle telecom server

---

Resources/Maps/_NF/Outpost/frontier.yml

This is the most important PR. It changes the centre of that one medical cross that is a _very slightly_ different shade of blue for absolutely no justifiable reason.
It drives me personally insane every single time.
Load Frontier Outpost and behold. Tears of happiness may emerge.
Before (cleaned):
After (also cleaned):
No.
**Changelog**
N/A

Frontier Outpost: Fix the dang medical cross colour

---

Resources/Prototypes/_NF/Maps/Outpost/frontier.yml
Resources/Prototypes/_NF/PointsOfInterest/nfsd.yml

Two things:
* Sets Frontier Outpost to spawn at (0, 0) with no rotation, always.
* Slightly increases the distance between Frontier Outpost and NFSD Outpost.
Due to upstream changes, stations by default spawn at a random position with a random rotation. Combined with our recent POI rework, NFSD Outpost could end up inside Frontier, or mere metres from it. Not ideal.
Frontier Outpost should be at (0, 0) always. We can just say all "global" coordinates in the game are actually relative to Frontier, easy peasy. :)
NFSD Outpost is moved out a little bit to give the system more room to breathe. The previous minimum of 500 metres isn't _tiny_ by any means, but imo feels a little too close.
1. Start a round
2. `tp 0 0 1` and observe how you end up on Frontier Outpost
3. Look at a mass scanner …

Change Frontier and NFSD offset

---

Content.Server/Salvage/SpawnSalvageMissionJob.cs

For salvage expeditions, alignment now only considers the largest grid for bounding box alignment.
Buggy.  If bits of the ship fall off, the overall bounding box might be huge, because you flew kilometers away from it.  Your ship might then be at one of the corners of that km-wide box, and very far away from the actual dungeon when it spawns.
1. Spawn at the Expeditionary Lodge.
2. Purchase a ship.
3. Climb aboard, add a lattice extension out from the ship, only needs to be a few tiles.
4. Snip the lattice from the ship, creating a new grid.
5. Pilot the ship several hundred meters away from your new grid, making sure not to bring it along with you.
6. Warp out to expedition.
7. When you arrive, the dungeon should be close to one of the sides of your ship with this fix.  Without the fix, …

Expedition: Only use bounding box of largest grid for dungeon alignment

---

Content.Server/Salvage/SalvageSystem.ExpeditionConsole.cs
Content.Server/Salvage/SalvageSystem.Expeditions.cs
Content.Server/Salvage/SpawnSalvageMissionJob.cs
Content.Server/_NF/Salvage/ExpeditionSpawnCompleteEvent.cs
Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_expeditions_dinosaurs.yml
Resources/ServerInfo/_NF/Guidebook/MobsHostileExpedition/dinosaurs.xml

Adds a new event, ExpeditionSpawnCompleteEvent, that is fired when an expedition job either completes (hooray), or fails.  Handling this failure case allows us to unstick the expedition console on errors (e.g. ones occurring during dungeon generation, or FTL init failures, or if dungeons are generated).
Expedition consoles getting stuck is no fun.
1. On line 266 on Content.Server\Salvage\SpawnSalvageMissionJob.cs, add `throw new NullReferenceException();`.
2. Build and run the server and client.
3. Buy an expedition ship.
4. Fly out from the station, try to warp to a mission.
5. The dungeon will start to generate, and take a second or so, 
**Changelog**
:cl:
- fix: When expeditions fail to generate, for any reason, the expedition console should not get stuck.

Expeditions: unstick consoles on failure

---

Content.Server/_NF/Salvage/SalvageMobRestrictionsSystem.cs
Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_rogue_ai.yml

Fix an issue that made some mobs not use the SalvageMobRestrictionsNF
Needed to fix silicon bug
Spawn in debug
Get a ship
Take silicon expo
Take a silicon back with you to ship
See it explode when you early finish
N/A
N/A
**Changelog**
:cl:
- tweak: Silicon mobs now explode when leaving expeditions.  Make sure to keep them off your ship.

Cleanup SalvageMobRestrictionsNF

---

Resources/Changelog/Changelog.yml
Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml
Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml

Restore https://github.com/new-frontiers-14/frontier-station-14/pull/459
Removed by mistake since it was missing notes
:cl:
- tweak: The piercing, heat, radiation and caustic armor of the captain's armored spacesuit has been reduced to its old values.

Armor FIxup

---

Resources/Prototypes/Catalog/Fills/Crates/salvage.yml
Resources/Prototypes/Recipes/Reactions/fun.yml

* Adds plastic to `CrateSalvageAssortedGoodies`, removes one occurrence of plasma.
* Makes the plastic chem recipe produce 10 sheets instead of just 1.
This PR is aimed at making plastic more obtainable. It's currently a total crapshoot whether you find plastic on any given wreck, as the only source is a plastic sheet crate. The plastic chem recipe is basically just a meme. As a result, you see people doing shit like this:
Buying dozens of janitorial supplies crates just to deconstruct the box. LRP and lame as hell.
Re `CrateSalvageAssortedGoodies`: The spawn list contained `SheetPlasma` twice. I believe this is a mistake on the part of whoever originally wrote it; one of those is almost certainly meant to be `SheetPlastic`. By making this change, it's now possible to find single stacks …

Make plastic more findable and buff recipe

---

Content.Server/Paper/PaperSystem.cs
Resources/Prototypes/Entities/Objects/Misc/pen.yml

Uses TrySign when using a pen instead of TryStamp, removes duplicate signatures when reading the description for a piece of paper.
Fixes issues with writing "default-component-stamp".  Signature unduplication just for QOL.
1. Spawn three pieces of paper, a pen, an APPROVED stamp, and a few crayons.
2. Sign the first piece of paper with alt-click.
3. Stamp the second piece of paper first and then click it with the pen to sign it.
4. Sign the third piece of paper with all of the crayons and stamp it with the APPROVED stamp multiple times.
5. Use the first two pieces of paper, they should both be signed with your character's name.
6. Examine the third piece of paper.  It should be signed by your character (listed once), and stamped by the APPROVED stamp (listed once).
7. Open the third piece …

Fix signing, undupe signatures in description.

---

Resources/ServerInfo/_NF/Guidebook/Shipyard/Akupara.xml

Tiny guidebook information SMES addition and cabin overpressure handling procedure addition
-I added an SMES and did not reflect this change in the guidebook
-The in-built overpressure handling feature probably isn't recognizable without this guide change
Proofread the Akupara guidebook
- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
Should be okay
**Changelog**
-add: Helpful guidebook info to Akupara guidebook

Akupara guidebook touchup

---

Resources/Prototypes/_NF/Shipyard/stellaris.yml

Reclassify the Stellaris as Civilian, not Science.
Sir, this is a ~~Wendy's~~ theatre.
1. Filter the shipyard console by "Class: Civilian". There is a Stellaris.
2. Filter the shipyard console by "Class: Science". There is no Stellaris.
N/A
No.
**Changelog**
N/A

Stellaris (Update): Reclassify as Civilian

---

Resources/Prototypes/Recipes/Lathes/sheet.yml

Fixes an issue where the ore processor's reinforced glass recipe called for Steel and Glass instead of raw iron and raw quartz.
Bug fix.
- Build an ore processor or its industrial variant
- Load it with iron, quartz, and coal
- Produce reinforced glass
- Incredible
**Changelog**
:cl:
- fix: Fixed a bug where ore processors could not produce reinforced glass

Ore Processors can now produce Reinforced Glass

---

Content.Server/Corvax/Respawn/RespawnSystem.cs

Swaps RespawnData over from a struct to a class to avoid pass-by-value semantics.
I goofed.  Cryo spawning sets up values in a struct, but it's a local set of data and not a reference to the system's dictionary.  The regular MindRemoved event then overwrites values and sends a network event saying that you'll respawn in 20 minutes, but the dictionary still shouldn't be changed.
1. Spawn.  Cryo. 20 second respawn timer.
2. Wait it out.  Spawn.  Cryo.  ~1200 second respawn timer.
Small video showing the cryo sleep pod in use twice.  The first respawn takes 20 seconds, the second takes about 1200.
https://github.com/user-attachments/assets/34b5aedc-61e5-4162-a829-cd25c8bff2d5
**Changelog**
:cl:
- fix: When entering into cryo, your first respawn timer should now be 20 seconds by default.

Cryo respawn timer fix - swap RespawnSystem.RespawnData to class

---

Resources/Prototypes/Entities/Structures/Furniture/beds.yml

* Update the disgusting dirty mattress to use our own unique construction graph, `bedNF`, with the correct node.
* Update the `Destructible` component so the mattress breaks into 1–2 cloth, not 1–2 steel.
On upstream, mattresses can be neither constructed nor deconstructed. They're also not encountered often. Here on Frontier, we have our own construction graph for mattresses, which requires 2 cloth per mattress. If we don't override the mattress construction graph to `bedNF`, then it can be deconstructed into 2 cloth + 1 steel, same as a bed. The 2 cloth can be used to make another mattress, and now you have an infinite steel glitch.
Similarly, the destruction trigger is updated to match the actual material cost of the mattress.
With the arrival of the McHobo, with its 4 million …

No more free mattress steel

---

Content.Shared/Paper/PaperSystem.cs

Gets the pen to display "You sign the paper" once, and play the sound once, when signing a piece of paper.
Annoying, buggy, inconsistent with stamp.
1. Sign paper.  Message should appear once, sound should play once.
2. Bonus points: connect with another client.  Sign on first client.  On the second client, message should appear once, sound should play once.
https://github.com/user-attachments/assets/a6b21d59-4b27-4db8-94f2-668f8c2ca79b
**Changelog**
:cl:
- fix: Signing a piece of paper no longer duplicates audio and popup messages.

Pen signing: Undupe messages, sound

---

Resources/Prototypes/_NF/Shipyard/crown.yml

Remove the SBI Crown from the shipyard.
This ship has numerous problems, most egregious of which that you can't enter it without a hardsuit. At only 20k spesos with little ability to make money, it is a noob trap.
1. Look at a shipyard console. Fail to buy an SBI Crown.
N/A
No.
**Changelog**
:cl:
- remove: Removed the SBI Crown pending a complete rework.

Remove SBI Crown

---

Content.Server/Salvage/SalvageSystem.ExpeditionConsole.cs
Content.Server/StationEvents/Events/BluespaceErrorRule.cs
Content.Server/Worldgen/Systems/LocalityLoaderSystem.cs
Content.Server/_NF/Salvage/NFSalvageMobRestrictionsComponent.cs
Content.Server/_NF/Salvage/SalvageMobRestrictionsSystem.cs
Resources/Prototypes/Entities/Mobs/NPCs/carp.yml
Resources/Prototypes/Entities/Mobs/NPCs/flesh.yml
Resources/Prototypes/Entities/Mobs/NPCs/space.yml
Resources/Prototypes/Entities/Mobs/NPCs/spacetick.yml
Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
Resources/Prototypes/Entities/Mobs/Player/dragon.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/corpses.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/elemental.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_base.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_expeditions_xeno.yml

Edit to the grid-tied salvage spawns.
Allow us to keep some event mobs without deleting them if they moved off grid.
Spawn event with mobs
Give one of the mobs the "DespawnIfOffEventGrid" ``false``
Move it off grid, it will not despawn on event end
N/A
N/A
**Changelog**
N/A

Allow some mobs to not despawn with events

---

Resources/Maps/_NF/Shuttles/ceres.yml
Resources/ServerInfo/_NF/Guidebook/Shipyard/Ceres.xml

Slightly updated the Ceres to fit new guidelines:
* Directional fans instead of tiny fans
* Fancy new kitchen sign instead of the directional "food" sign
* Service worker EVA suit instead of wallstorage suit locker
* Replace the dumbwaiter disposal units with mailing units
* Materials locker by the service techfab instead of loose materials on the ground (ew)
Make good ship gooder. :)
1. Buy Ceres.
2. Enjoy.
No changes to the subfloor, so subfloor is hidden in all the screenies.
New entrance area with "KTCHN" signs:
Dumbwaiter mailing units + materials locker + EVA locker:
Whole ship, preinit:
None.
**Changelog**
:cl:
- tweak: The SBB Ceres has received some minor updates.

Ceres (Update): Directional fans + other goodies

---

Resources/Maps/_NF/Shuttles/bookworm.yml
Resources/Prototypes/_NF/Shipyard/bookworm.yml
Resources/ServerInfo/_NF/Guidebook/Shipyard/Bookworm.xml

A few updates to the Bookworm to keep it up to date and stuff:
* Replace tiny fans with directional fans
* Oxygen + nitrogen mix instead of air canister
* Completely redid engineering with a SMES + wallmount substation and a plasma fuel wall locker
* Redid piping and wiring around engineering, to reduce the "oh my god what is this"
* Service worker EVA locker
* Reduced price by 1,000 spesos to fit new appraisal price
Make Bookworm great again.
The redone engineering no longer has a power monitor, as the ship hasn't started at a power deficit for some time now. The SMES provides further resilience against power loss in case you forget to refuel or choose to install more machines or whatever.
1. Buy Boookworm.
2. Read a book. :)
Full ship with subfloor:
Reworked engineering:
Service worker …

Bookworm (Update): Directional fans + mixer + more

---

Resources/Maps/_NF/Shuttles/Expedition/pathfinder.yml

Replaced all tiny fans with directional fans
Also added coloured decals for the O2 and N2 connector ports and gave them names.
Each tiny fan has been replaced with a directional fan aligned to the outer edge of the shuttle.
The O2 and N2 connector ports have been named, and each has been given a colour-coded decal.
Tiny fans trap bad air inside their bounding box and are difficult or impossible to clean up. Directional fans merely create a single bounding box around the outside edge of the ship, allowing the entire ship to be one air box with a linked atmosphere (when all airlocks are opened), and allowing the scrubbers and vents to do their job.
Adding indicators for which connector port is intended for which gas brings it into line with other shuttles (see the Gasbender).
Purchase a …

Pathfinder directional fans update

---

Resources/Maps/_NF/Shuttles/Expedition/sprinter.yml

Replaced tiny fans with directional fans.
Named O2 and N2 ports and added decals.
Replaced medical doctor's locker with wallmount.
Added dirt where the locker used to be.
Replaced AME fuel rack with wall locker.
Tiny fans create an enclosed atmosphere box that will quickly become unbreathable. Directional fans fix this problem.
Connector port changes bring the shuttle in line with other shuttles such as the Gasbender.
Wall lockers are preferred, especially for AME fuel.
Load the Sprinter and walk around. Open all the airlocks while watching the atmosphere for any sudden drops or other changes. check that two AME fuel bottles are supplied in the wall locker.
**Changelog**
:cl:
- tweak: Retrofitted the Sprinter with directional fans and tweaked storage.

Sprinter shuttle update

---

Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml
Resources/Prototypes/Entities/Objects/Fun/toys.yml
Resources/Prototypes/_NF/Entities/Objects/Fun/toys.yml

Adds contraband status to fake cap guns.  Both found and grown fake cap guns do not display their contraband status on examine, but found fake cap guns will redeem for one FUC.
Grown fake cap guns have normal magnum rounds and sell for no FUCs.
Oversight.  Both should be contraband (if not immediately visible) and the grown ones shouldn't be a farmable source of armor-piercing rounds or FUCs.
1. Farm some fake capfruit, it should output a grown fake cap gun.
2. Eject the rounds from the cap gun, they should be regular magnum ammunition.
3. Redeem the gun at the contraband pallet, it should redeem for no FUCs.
4. Spawn a fake cap gun (two objects should show in the spawn menu - the found fake capgun and the real cap gun)
5. Eject the rounds from the fake cap gun, they should be AP magnum …

Capfruit: fake cap guns are contraband, grown ones have standard ammo.

---

Content.Shared/_EstacaoPirata/Cards/Stack/CardStackSystem.cs

It's currently possible to draw a card from the hand/deck you're holding INTO the hand/deck you're holding by pressing Z with cards in your active hand.
This should probably do something for a deck and flip a hand of cards, but at the very least this cuts down on spammy message passing.
Bug.
1. Spawn a deck of cards.
2. Make a hand of cards (right click->draw or press E a few times).
3. Press Z.
4. Nothing should happen.
5. Put the hand down, pick up the deck.
6. Press Z.
7. Nothing should happen, no sound should play.
**Changelog**
:cl:
- fix: Using a hand or deck of cards in-hand currently does nothing.

Cards: no drawing from objects in-hand into the same object.

---

Resources/Maps/_NF/POI/cove.yml
Resources/Prototypes/_NF/Entities/Structures/Storage/Crates/crates.yml

Makes contraband smuggling crates worth 2 doubloons, and adds a contraband turn-in computer to the Pirate Cove.
I forgot this bit in the smuggling rework.  Currently, you only get the notification that smuggling happens, and then you go and get crates, and then you can turn them in for cash.  Great.
1. Warp to the Pirate Cove.
2. Put a few contraband crates on the pallets with the red flashing X.
3. Sell them from the console with the blue screen.
4. Get two doubloons per crate.
**Changelog**
:cl:
- add: Contraband crates are now actually redeemable for doubloons at the Pirate's Cove on the plunder exchange console.

Pirate contraband crate turn-in

---

Resources/Prototypes/_NF/Shipyard/Expedition/dartx.yml

Retires the Dart-X pending a rework.
The Dart-X has a lot of problematic stuff, including, but not limited to:
* Custom filled lockers in many places, including a medal case.
* A random drain in the middle of the ship for no justifiable reason.
* Clown equipment?!
* THREE defibs, but no extinguisher.
* A bunch of seemingly random clothes vendors.
* Booze and soda dispensers (filled).
* Free medicine and a medical bed.
* Two AME cores on a ship that needs no more than one.
* ...
In attempting to fix these things quickly, it became clear that the ship would benefit from a more thorough rework. The Dart-X is an adaptation of the upstream admeme ship Dart, which has received several changes we could probably take inspiration from. Alternatively, we can leave it in the past and focus on giving …

Retire the Dart-X pending a rework

---

Content.Server/Ghost/GhostSystem.cs
Content.Server/Warps/WarpPointComponent.cs
Content.Shared/Ghost/SharedGhostSystem.cs
Resources/Prototypes/_NF/Entities/Markers/warp_point.yml

Makes LP Bravo and Pirate's Cove admin-only warp points.
Admin-only warp points shouldn't be displayed on users' ghost warp UI unless they're an admin.
`warp` command should be unaffected.
Limits player abuse of sensitive locations.  In combination with the reduced radar range and the removal of ghost radar coords (both in the upstream merge) this should help alleviate shittery.
1. Deadmin.
2. /ghost
3. Open the Ghost Warp UI.  Neither LP Bravo nor Pirate Cove should appear.
4. Readmin.
5. Open the Ghost Warp UI.  LP Bravo (if it exists) and Pirate Cove should appear.
6. Warp to Pirate Cove, it should work.
**Changelog**
:cl:
- tweak: Pirate's Cove and LP Bravo no longer appear in the list of player-accessible warp points.

Make LP Bravo and Pirate Cove admin-only warp points.

---

.github/labeler.yml

* Add a new entry to .github/labeler for database migrations
A botched database migration has the potential to completely wipe out our economy. Every single migration has to be vetted properly. By attaching a label to anything that touches migrations, it is my hope that we'll be able to catch them _early_ and perform the necessary testing.
1. You can't, easily. :) Make a PR based on this branch that adds a dummy migration? I'm not sure.
N/A
No.
**Changelog**
N/A

Add GitHub auto-label for database migrations

---

Resources/Prototypes/_NF/Entities/Markers/atmos_blocker.yml

Changed sauna atmos fix marker to use the `watervapour` sprite instead of `oxygen`.
Correctness. Fixing Darin's _laziness_.
1. Spawn an Atmos Fix Sauna Marker.
2. Enjoy the barely legible text. 
3. Get annoyed at how it looks more like "H²O" than the more reasonable "H₂O".
No.
**Changelog**
No.

Use correct sprite for sauna atmos fix marker

---

Resources/Prototypes/Entities/Structures/Walls/walls.yml

Lower the price of reinforced, exterior shuttle wall back to 150, as it was before upstream merge.
Upstream increased the price to 250 because the materials that the wall is made of are now more expensive.  With my change, theoretically someone could disassemble the shuttle wall and get ~20 spesos more value, but shuttle walls are a gargantuan pain to deconstruct, so this seems like an acceptable tradeoff.
1. Appraise a shuttle wall.
2. 150 spesos.
N/A
This is not a breaking change. This is a fixing change.
**Changelog**
No.

Lower the price of shuttle wall

---

Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Basic/sawn_pka.yml

Nerfed sawn-off PKA, gone are the days when one could turbo blast walls with 2 of those. Swapping hands resets cooldowns so it is faster to use one. Reduced fire rate from 8 to 0.9, decreased ammo regeneration from 0.75 to 1, added usedelay of 1.
Balance: double sawn-off PKA were significantly better than specialized wall busting equipment.
1. Get a sawn-off PKA, start blasting
2. Get two sawn-off PKAs, start blasting rapidly swapping hands, expect worse performance.
**Changelog**
- tweak: Nerfed sawn-off PKA dual wielding: firing more than 1 shot per second shouldn't be possible now.

Sawn-off PKA Nerf

---

Resources/Prototypes/_NF/Entities/Structures/Machines/vending_machines.yml

Hotfix to the Acradia machine bug
fix the error message
it's a no-no
splurge in monies fashion baby fashion
[x] I have added media to this PR or it does not require an in-game showcase.
**Changelog**
:cl:
- fix: The ArcadiaDrobe no longer shows an error when denying vending.

Hotfix to the Acradia machine bug

---

Resources/Prototypes/Recipes/Reactions/medicine.yml
Resources/Prototypes/_NF/Recipes/Reactions/medicine.yml

This adjusts the recipe for Opporozidone. It replaces Cognizine with Mannitol.
The recipe as given provides some challenges for manufacture to meet the needs of Frontier, with its specific context and shift lengths. Additionally this change is proposed in partial response to the proposals for future efforts to phase out carp. Which would, for all practical purposes, make carpotoxin something accessed behind botany mutation knowledge. Which is impractical and further removed from the specific needs of the server.
Mannitol is a drug that specifically treats brain damage. So there is a logical bridge.
Check that 'ol recipe.
Make that 'ol recipe.
Good time. Good time.
**Changelog**
🆑 
- tweak: Opporozidone recipe uses Mannitol instead of Cognizine.

Opporozidone recipe tweak.

---

Resources/Maps/_NF/Shuttles/pts.yml

The PTSDFCU updates the Personal Transport Shuttle to be compliant with directional fan guidelines. Is there a reason this title has to be comically long? Not really. Is it truly comical? I mean, I find it so.
Directional fan good. Also, since the PTS is shared by the Chauffeur, this rounds off every ship on the Frontier Staff Shipyard Console.
- Purchase a Personal Transport Shuttle or Chauffeur from the Shipyard Console or Frontier Staff Shipyard Console respectively.
- Open doors.
- Directional fans.

Personal Transport Shuttle Directional Fan Compliance Update

---

Resources/Maps/_NF/POI/bahama.yml

Bahama Mama's had a tiny HV wiring issue which meant the second SMES wasn't connected to the powernet. This has now been resolved so the POI doesn't power down within 5 mins of roundstart when the solars aren't aligned. 
Added decals to the gas ports for greater visibility there.
Added a toolbox so there are some available if you need to anchor the JRPACMAN.
Noticed these issues while observing during a round. 
Checkout the branch, load the POI.
Not required.
None.
**Changelog**
:cl:
- fix: Fixed power issues on Bahama Mama's.

Bahama Mama's: Fix power issues + some tiny changes

---

Resources/Maps/_NF/POI/lodge.yml
Resources/Maps/_NF/POI/nfsd.yml

Removes the pacified zone from the NFSD Outpost and the Exped Lodge.
These POIs are both outside the safe zone. The pacified zone also made it hard for new players to use the gun ranges in each POI, even with the provided practice rounds.
1. Warp to the NFSDO or Lodge with less than 10 hours of playtime.
2. Go ham. There's nothing there to stop you. Shoot and destroy. There are no admins to stop you in your private world.
N/A
No.
**Changelog**
N/A

Unpacify NFSD and Lodge

---

Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml

The regular shuttle console was hidden in the entity spawn menu. I unhid it.
Allows it to be spawned again. Don't just want to use tabletops.
Play hide and seek with the shuttle console by opening the entity spawn menu, look for it, find it. Congratulations, you win!
**Changelog**
- fix: Made the shuttle console spawnable again.

Unhide shuttle computer in entity spawn menu

---

Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/frame_tabletop.yml

Changes the construction step for the BaseStructureComputerTabletop prototype to be the last step.
Fixes #1521
Pre-mapped/built tabletop computers are currently bugged in that they do not return the board upon deconstruction
1. Spawn tabletop computer variant from spawn menu
2. Attempt to deconstruct
Before change:
Result of deconstruction:
---
After change:
Result of deconstruction:
**Changelog**
:cl:
- fix: prebuilt tabletop computers can now be properly deconstructed

fix prebuilt tabletop computer deconstruction

---

Resources/Prototypes/Catalog/Fills/Crates/service.yml

This fixes a integration test that tests if there is sufficient space for entities with StorageFillComponent.
I removed one item from it to make the test pass.

Fix CrateTrashCart contents exceeding maximum contents

---

Content.Server/Shipyard/Systems/ShipyardSystem.cs

If some computer with the shipyard component is spawned the system makes a new map automatically
with this pr the map is only created before spawning a shuttle.

Fix shipyard causing SpawnAndDeleteEntityCountTest to fail

---

Content.Client/Nyanotrasen/Mail/MailSystem.cs

```
Caught exception in "entsys" Exception: System.ArgumentNullException: Value cannot be null. (Parameter 'key')
```
in this if-statement the `job` is null, causing the TryIndex to become null
Happens during SpawnAndDeleteEntityCountTest

Fix TryIndex used with null param

---

Resources/Prototypes/_NF/Roles/Jobs/Hostile/blood_cultists.yml

https://github.com/new-frontiers-14/frontier-station-14/pull/2209
SpawnInhandMeleeWeaponBloodCultHigh
SpawnInhandMeleeWeaponBloodCultLow
They are just spawners and spawn the weapon on the floor
they dont equip it 
replace it all with EldritchBlade until someone else fixes it

Fix SpawnInHand not working for blood cultists

---

Resources/Prototypes/Catalog/Fills/Boxes/general.yml
Resources/Prototypes/Entities/Clothing/Back/backpacks.yml
Resources/Prototypes/Entities/Clothing/Back/duffel.yml
Resources/Prototypes/Entities/Clothing/Back/satchel.yml
Resources/Prototypes/Entities/Clothing/Belt/belts.yml
Resources/Prototypes/Entities/Objects/Specific/Medical/medkits.yml
Resources/Prototypes/Entities/Objects/Tools/toolbox.yml
Resources/Prototypes/_NF/Entities/Clothing/Back/base_clothing_backpack.yml
Resources/Prototypes/_NF/Entities/Clothing/Back/duffel.yml
Resources/Prototypes/_NF/Entities/Clothing/Back/messenger.yml
Resources/Prototypes/_NF/Entities/Clothing/Belt/base_clothing_belt.yml
Resources/Prototypes/_NF/Entities/Clothing/Belt/belts.yml
Resources/Prototypes/_NF/Entities/Clothing/Belt/belts_blood_cult.yml
Resources/Prototypes/_NF/Entities/Clothing/Belt/belts_crossbow_quiver.yml
Resources/Prototypes/_NF/Entities/Clothing/Belt/belts_punk.yml
Resources/Prototypes/_NF/Entities/Objects/Storage/weapon_cases.yml

Right now, for example, a utility belt has a 2x8 inventory space, but its current footprint is 6x6, and it can't be stored in duffels or backpacks. In this PR I'm adjusting its footprint to match its actual inventory size, such as 2x8 or 4x4, and removing the restriction on placing them in larger containers like backpacks. This could similarly apply to other belt slot storage accessories or containers like toolboxes. This change should not significantly impact game balance, but it could enhance the quality of life for players in certain edge cases.
Slightly more context [in this post](https://discord.com/channels/1123826877245694004/1294667861876277341/1294667861876277341). Here is the table of new values. 
<html>
<body>
Container | Container size | Max stored size | Grid | Footprint
-- | …

Сontainer grid sizes and footprints

---

Resources/Prototypes/_NF/Catalog/Fills/Items/weapon_cases_expedition.yml

Fix weapon crate sizes since well guns dont fit  Weh
https://github.com/new-frontiers-14/frontier-station-14/pull/2209

Change cases to heavy to fit weapons

---

Content.Server/_NF/Smuggling/DeadDropSystem.cs

When reassigning dead drops on compromise (i.e. unanchored), we need to check if the station is actually tearing down, and check if the entity we've selected is terminating before adding another reference.
#2209, and mistakes on my side.
Destroy a station with dead drops on it, no debug assertions or errors.
**Changelog**
None.

DeadDropSystem: check lifecycle and null refs on compromise.

---

Content.Server/Gateway/Systems/GatewayGeneratorSystem.cs
Content.Server/Procedural/DungeonJob/DungeonJob.cs
Content.Server/Procedural/DungeonSystem.Commands.cs
Content.Server/Procedural/DungeonSystem.cs
Content.Server/Salvage/SalvageSystem.Magnet.cs
Content.Server/Salvage/SpawnSalvageMissionJob.cs
Content.Server/Shuttles/Systems/ShuttleSystem.GridFill.cs
Content.Server/_NF/GameRule/NfAdventureRuleSystem.cs
Content.Shared/Procedural/DungeonConfig.cs
Resources/Prototypes/Procedural/dungeon_configs.yml
Resources/Prototypes/_NF/Procedural/dungeon_configs.yml

Adds a skipDungeonGeneration to DungeonConfigPrototype to skip dungeon generation in NfAdventureSystem for base types (i.e. BasePlanet, Everything).
Add an ID field to DungeonJob for debugging - this will print the name of the prototype being generated - should help with error tracking.
Run game, no dungeon generation errors.  Go on expedition, should be fine.
**Changelog**

Debuggable dungen output, wallmount typo

---

Content.Server/Corvax/Respawn/RespawnSystem.cs

When players reconnect, this fixes the timer shown on the respawn button.
Bug.  Players that have a respawn timer currently have the ghost button show that they can respawn without issue when they are on a cooldown.
1. Deadmin, spawn.
2. Ghost.
3. Disconnect, reconnect.
4. The button should show the amount of time you have left to wait.
None.
**Changelog**
:cl:
- fix: Respawn timers are now properly shown on reconnect.

Respawn timer fix: show correct time on reconnect

---

Resources/Prototypes/Entities/Structures/Walls/walls.yml
Resources/Prototypes/_NF/Entities/Structures/Walls/walls.yml

Changes ice and sandstone walls to no longer spawn a girder on their destruction
1. Spawn Ice Wall / Sandstone Wall
2. Destroy it
https://github.com/user-attachments/assets/a343877b-af1c-47b8-bb59-00946d6b81f9
**Changelog**
:cl:
- tweak: Ice and sandstone walls no longer spawn a girder upon their destruction

Ice and Sandstone walls dont spawn girders

---

Resources/Prototypes/Entities/Objects/Devices/Circuitboards/Machine/production.yml
Resources/Prototypes/Entities/Structures/Machines/lathe.yml

Adds the ammolathe blueprint receiver parent, hides secfab and secfab machine board
I goofed.
**Changelog**
Never again.

Ammolathe Blueprints (for real), Hide Secfab

---

Resources/Prototypes/_NF/Entities/Objects/Consumable/Smokables/Pipes/tobacco_pouch.yml
Resources/Prototypes/_NF/Entities/Objects/Specific/Hydroponics/leaves.yml

fixing integration test's bitchings from https://github.com/new-frontiers-14/frontier-station-14/pull/2263
**Changelog**

tobacco pouches error fixes

---

Resources/Maps/_NF/Shuttles/spectre.yml
Resources/Prototypes/_NF/Shipyard/spectre.yml

Spectre tweak.
Replaced the BasePenAdvanced in the bridge with the captain's pen.
Adjusted price to current price plus around 15%.
The BasePenAdvanced prototype should not be mapped. Quite aside from being T3 contraband, it should also probably be an abstract prototype, being a cybersun pen without the accompanying appearance, name, and description. A captain's pen is relatively normal for a bridge pen on a medium or large ship.
An 85-90% markup is entirely out of line with existing standards, and is likely the result of the ship's price falling significantly since its last evaluation. 15% appears to be a normal ship markup for non-expedition ships. I took the median of five price checks and rounded the result, then rounded the marked-up price.
Purchase the ship, compare the purchase …

Replaced Misplaced BasePenAdvanced in the Spectre's Bridge With a Captain's Pen.

---

Content.Server/Chat/Managers/ChatSanitizationManager.cs
Content.Server/Chat/Systems/ChatSystem.cs

Fixes Chatsan emote entries that end in letters by adding periods.
Brainrot.
Enter the following text in in-game chat.  Each one of them should result in an emote.  Note that the `>:i` entry requires an additional > because of local chat.
```
:D
:O
:S
xD
qwq
:u
:v
>:i
:i
:p
;p
:b
o-o
o.o
smh
lmao
lmfao
lol
lel
kek
rofl
idk
```
**Changelog**
:cl:
- fix: Chatsan emotes ending in letters now work again.

Chatsan fixes to emote entries ending with letters.

---

Resources/Prototypes/Entities/Clothing/Masks/masks.yml
Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_flasks.yml
Resources/Prototypes/Entities/Objects/Consumable/Food/Containers/bowl.yml
Resources/Prototypes/Entities/Objects/Consumable/Food/Containers/plate.yml
Resources/Prototypes/Entities/Objects/Misc/handcuffs.yml
Resources/Prototypes/Entities/Objects/Tools/gps.yml
Resources/Prototypes/_NF/Entities/Objects/Devices/production.yml
Resources/Prototypes/_NF/Entities/Objects/Weapons/Melee/brassknuckles.yml
Resources/Prototypes/_NF/Recipes/Lathes/clothes.yml
Resources/Prototypes/_NF/Recipes/Lathes/electronics.yml

#2263 
making the Great Material Arbitrator (blessed be their name) pleased
**Changelog**

more mat arbitrage fixes

---

Content.Server/_NF/GameRule/Components/AdventureRuleComponent.cs
Content.Server/_NF/GameRule/NfAdventureRuleSystem.cs
Content.Shared/Procedural/DungeonConfig.cs
Resources/Locale/en-US/_NF/adventure/adventure.ftl
Resources/Prototypes/Procedural/dungeon_configs.yml
Resources/Prototypes/_NF/GameRules/roundstart.yml
Resources/Prototypes/_NF/Procedural/dungeon_configs.yml

Dungeon generation is currently done by enumerating all dungeon configs and removing ones we don't care about.  This turns it into an explicitly whitelisted process, with the AdventureGameRule itself defining the set of space dungeons it generates.
All generated space dungeon grids will be given a name (e.g. "Space Dungeon: VirologyLab").
Haunted and Mineshaft, as they generate using rock walls, were removed from this whitelisted pool - they look odd having rock walls on a giant steel sheet in space.
Note: unsure if the dungeons generate well in Debug configs, but Release seems to work fine.  The space platform itself should probably be removed in favour of having a crappy lattice that the dungeon sits on in space.
Missed a dungeon config added upstream containing fultons.
1. Start a …

Space Dungeon generation: explicit list of prototypes, name dungeon grids.

---

Content.Server/_NF/Salvage/SalvageMobRestrictionsGridComponent.cs
Content.Server/_NF/Salvage/SalvageMobRestrictionsSystem.cs
Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_punkganger.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_syndicate.yml

Mobs Depsawn FIxups

---

Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactComponent.cs
Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactSystem.Nodes.cs
Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactSystem.cs
Content.Server/_NF/EntityEffects/Effects/NFActivateArtifact.cs
Resources/Prototypes/Guidebook/science.yml
Resources/Prototypes/Reagents/chemicals.yml
Resources/ServerInfo/_NF/Guidebook/Science/Xenoarchaeology.xml

Can we actually use the spray to what its intended?
Restore arti to what it used to be.
Spawn arti on a ship, spray it, scan.
N/A
N/A
**Changelog**
:cl:
- tweak: Using artifexium to trigger artifacts now results in gaining no points for any triggered nodes.
- add: The Xenoarchaeology guidebook now has a section on using artifexium.

Artifacts no longer gain points on spray, just skip nodes.

---

Resources/Locale/en-US/_NF/ghost/roles/ghost-role-component.ftl
Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_meme_goblinbane.yml
Resources/Prototypes/_NF/Roles/Ghostroles/whitelisted.yml
Resources/Prototypes/_NF/ai_factions.yml

Non-speciesist update! Wow!
- Made Goblinbane ghost role whitelisted.
- Altered ghost role rules and description so Goblinbane wouldn't have to target exclusively goblins/felinids or chaplains. Every one at risk now.
- The mob is now neutral to everyone by default, but still will retaliate if attacked.
**Changelog**
- tweak: Made Goblinbane ghost role whitelisted, altered ghost role rules and description so Goblinbane wouldn't have to target exclusively goblins/felinids or chaplains. Every one is at risk now. When not controlled by a ghost, Goblinbane is neutral towards players.

whitelisted equal opportunities goblinbane

---

Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_bloodcultist.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_expeditions_aberrant_flesh.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_expeditions_explorers.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_rogue_ai.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_syndicate.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_wizardfederation.yml

Laser reflect was initially added to limit player abuse of AI short comings during expeditions, however since then non-transparent windows and airlocks were added, so I guess there is no need to have both of those tweaks.
Small QoL for laser enjoyers
**Changelog**
<!--
- tweak: Removed laser reflect from mobs.

removed laser reflect on mobs

---

Resources/Prototypes/_NF/Events/events.yml
Resources/Prototypes/_NF/Events/nf_events_bluespace.yml

Allow more bluespace events for low pop
With sheriff change vaults should be around without the need for min players anymore
Allow more events for 20 players online.
N/A
N/A
N/A
**Changelog**
:cl:
- tweak: Bluespace events require less players overall to show up.

Events pass

---

Resources/Prototypes/_NF/Shipyard/tyne.yml

Increased the price of the SBB Tyne to 19000 spesos. This is still around 5-7% markup.
You could sell it for a profit. A whopping 19 spesos. 
(More importantly it was causing test failures).
Check the .yml, checkout the branch, load the game and buy it for 19k. 
No.
Nuh uh.
**Changelog**
:cl:
- fix: Corrected price of the SBB Tyne.

Fix SBB Tyne Shipyard Price

---

Resources/Prototypes/Entities/Mobs/NPCs/animals.yml

They said it cannot be done, I proved it can.
Funny
Spawn as goblin, spawn a cat
Not sure, I didnt manage to find any issues with the cats but this is very weird way to add it.
**Changelog**
:cl:
- add: Goblins can now ride cats, to some extent.

Allow Goblins to ride cats

---

Content.Server/Worldgen/Components/WorldLoaderComponent.cs
Content.Server/Worldgen/Systems/WorldControllerSystem.cs
Resources/Maps/_NF/Shuttles/Bus/publicts.yml
Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers.yml

Adds a disable flag to WorldLoaderComponent, disables the world loader attached to station traffic consoles on Frontier Outpost and Trade Outpost.  Disables world loader on the bus.
Unnecessary overhead.
Spawn on Frontier Outpost, check the remote feed around Trade Outpost.  There should be no asteroids loaded.
Wait until the bus jumps to Trade Outpost, there should be no asteroids loaded.
The Trade Outpost, as viewed through the remote console on Frontier Outpost.
**Changelog**
No real in-game impact, slight performance gain.

Remove world loader from outpost STC terminals, bus shuttle console.

---

Resources/Prototypes/_NF/Events/events.yml
Resources/Prototypes/_NF/GameRules/roundstart.yml

Title, Paracusia AKA MassHallucination event is removed, i have always hated the event and does not fit the frontier at all as an event.
Solar flare even has been getting way too annoying recently so i lowered its weight and made it last the double of time in average, doors opening and it breaking lights chances have also been reduced too.
**Changelog**
:cl: Leander
- remove: Paracusia event removed, now all things you hear will be real.
- tweak: Solar flares are more rare but will last longer but less light bulbs will break from it.

Remove paracusia and changes solar flare event

---

Content.Server/Cargo/Systems/CargoSystem.Shuttle.cs
Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/pets.yml

Changes the order of checks in CargoSystem.CanSell, removing the "return true" for dead mobs.  Critical mobs are now not sellable.
Pun Pun, Yip Yip, and the station cats are now blacklisted for sale at cargo (Cappy's bounty is still valid).
Abusable.
**Changelog**
:cl:
- tweak: Critical mobs can no longer be sold.

Cargo Sell - fix order of checks, no selling station pets.

---

Resources/Prototypes/_NF/Entities/Structures/Wallmounts/shelfs.yml

Added NFSD access-locked variants of the wood and metal sturdy shelves.
Useful for mapping. Some NFSD ships have shelves already but anybody can open them. 
Checkout the branch, spawn the shelves, try to open with and without an NFSD or guard ID.
No changed visuals.
None.
**Changelog**
:cl:
- add: Added access-locked shelves for the NFSD.

NFSD Access Shelves

---

Resources/Prototypes/_NF/Entities/Objects/Devices/flatpacks.yml

Add the `Damaged` suffix to the damaged RTG generator flatpack.
Makes it easier to distinguish them.
1. Search the entity spawn panel for "RTG".
2. Be able to distinguish the damaged RTG generator flatpack from the intact one.
3. :)
Negatory.
**Changelog**
N/A

Add suffix to damaged RTG generator flatpack

---

Resources/Prototypes/Entities/Structures/Walls/grille.yml

Changed WallLayer (Blocks laser shots) to GlassLayer (does not) for Diagonal Clockwork and Diagonal Grilles
Bug report on the discord mentioned it and I did not think there was really a reason for specifically corner windows to block shots.
Load up a server
Spawn a diagonal grille
Spawn a laser weapon
Fire at the grille, witness the laser pass through
Forgot to take a picture, of it, apologies.
Hopefully none?
**Changelog**
:cl:
-fix: Diagonal grilles and diagonal clockwork grilles no longer block lasers from passing through them.

Diagonal grille fix

---

Resources/Prototypes/Entities/Clothing/Masks/specific.yml
Resources/Prototypes/Entities/Markers/Spawners/Random/Salvage/tables_loot.yml

Title, removed cursed component from the golden mask, too much of a random RNG insta-ghost and dead over an item found in expeditions over 6+ hour rounds.
**Changelog**
:cl:
- tweak: The golden mask is no longer cursed.

Remove curse from the golden mask.

---

Content.Server/Administration/Systems/AdminVerbSystem.Smites.cs
Resources/Prototypes/Entities/Objects/Devices/pda.yml
Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
Resources/Prototypes/Roles/Jobs/Civilian/janitor.yml
Resources/Prototypes/_NF/Entities/Objects/Devices/Misc/identification_cards.yml
Resources/Prototypes/_NF/Entities/Objects/Devices/pda.yml
Resources/Prototypes/_NF/Roles/Jobs/Civilian/janitor.yml

Adds a new Frontier-specific janitor set up to receive Frontier janitor access.
Removes the maid smite as it spawns a new PDA with a janitorial ID with old janitorial permissions.  If we want to keep this, I can make a version with contractor permissions.
https://discord.com/channels/1123826877245694004/1305566159890026559
No access to the mail room or break room on roundstart.
1. Join as a roundstart Janitor, open the break room.  You should be able to, you have Frontier access.
2. Open the spawn menu, there should be one janitor ID card and janitor PDA, and they should be the frontier variant.
**Changelog**
:cl:
- fix: Fixed access for round start Janitors.

Fix roundstart janitor access, no maid smite

---

Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml

Editing the damage out of the PTK-800 projectiles
Did you know the PTK-800 is used for mining?
Almost didn't know that with how its getting used now.
Overall the damage nerf also means it wont self destroy itself when you mine + lifetime might make it more easy to avoid reflects.
Place one, place some ore in front, mine with it normally 
N/A
N/A If you used it for mining nothing changed.
**Changelog**
:cl:
- tweak: The PTK-800 Range and damage lowered, mining ability stay the same with the PTK-800 able to mine without self destructing itself on reflects.

PTK-800 But only for mining

---

Resources/Prototypes/_NF/Entities/Structures/Furniture/Armory/weapon_racks_filled.yml

Removes crusher glaives from the salvage weapon rack
Crusher glaives were recently buffed and removed from vendors, however one can still be found on the prospector via the filled salvage melee weapons rack.
1. Spawn filled salvage melee weapons rack
2. Check contents
N/A
**Changelog**
:cl:
- remove: The salvage weapons rack (Found on the prospector) no longer contains a crusher glaive.

remove glaive from salvage weapons rack

---

Content.Shared/Inventory/InventorySystem.Equip.cs

Raises a DroppedEvent on all items in dependent inventory slot when unequipping its parent.
When removing a piece of clothing in an outer slot, the dependent slots' contents (e.g. pockets, suit storage, belt) would not raise a DroppedEvent.  Some items (jetpacks, health scanners, etc.) rely on this event to cut down on bookkeeping or maintain state.
Fixes https://discord.com/channels/1123826877245694004/1305455935216549940.
This fix depends on some existing behaviour - all existing code that raises DroppedEvent removing items from slots through interaction or the like only interacts with the item being dropped directly, ignoring any children (which it doesn't know about from the call).  The contents of dependent slots are only removed and relocated without any event.
1. Wear an EVA suit …

Raise DroppedEvent on items in pockets/suit storage.

---

Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Rifles/rifles.yml

Mags on gestio and svt are once again visible.
Fixes
Get Frontier specific magfed rifles (Gestio and SVT), insert mags in the, rack the bolts.
**Changelog**
- fix: Fixed Gestio and SVT mags visial bug.

Frontier Weapon Mags Visual Fix

---

Resources/Prototypes/Entities/Objects/Decoration/flora.yml

Disables "insane" Christmas presents.
Insane presents can contain almost any conceivable entity. This includes a variety of hostile mobs, various consoles, chasms (hello, instant round removal!), tesla balls, singularities, and so much more. They are a little bit _too_ insane at times. In the interest of keeping Frontier just a little bit safe from _instant death_, insane gifts are disabled with this PR.
"Unsafe" gifts (any item) remain. I'm sure fun shenanigans will occur.
Unfortunately, yes, this means you can't get crates and lockers that fit in a pocket. :(
1. Spawn a number of gift-giving Christmas tree
2. Don't receive a PresentRandomInsane.
Yeah, this one is annoying to test. :D
N/A
No.
**Changelog**
:cl:
- remove: Christmas gifts are now limited to things that are normally items. …

Disable insane Christmas gifts

---

Resources/Locale/en-US/GPS/handheld-gps.ftl

Moves GPS coordinates to their own line, after the text "Coords:".
With the newish action bar, the previous single-line approach frequently resulted in hard-to-read coordinates. In particular, if the Y-coordinate is negative, the minus sign has a tendency to stay on the first line while the rest migrates to the second. It's much too easy to miss it and send people on a wild goose chase. Especially problematic considering Frontiersmen usually read their coordinates when they're lost and time is of the essence.
1. Hold GPS or PDA with the AstroNav app.
2. Behold coordinates.
**Before:**
**After:**
The label can easily support ridiculous, unrealistically large offsets even within the limited space afforded to it:
No.
**Changelog**
:cl:
- tweak: GPS coordinates are now more readable.

Display GPS coordinates on their own line

---

Resources/Prototypes/Entities/Mobs/NPCs/animals.yml

Fixing new-frontiers-14/frontier-station-14#2312
:cl:
- remove: Goblins can no longer ride cats.

Fix "Allow Goblins to ride cats"

---

Content.Server/NPC/HTN/HTNSystem.cs
Content.Shared/Tiles/ProtectedGridComponent.cs
Resources/Maps/_NF/Outpost/frontier.yml

2024 12 06 hostile ai on grid suggestions

---

Resources/Maps/_NF/Shuttles/piecrust.yml

Adds fryer to piecrust in addition to a button to feather the thrusters
This PR adds a fryer to the piecrust.
It moves a locker and a freezer to make room.
It adds a button that allows the pilot to turn the thrusters off during long duration docking to save juice.
Imagine not being able to make donuts on the piecrust. Imagine. 
Buy piecrust. Check stuff. Hit big red button to turn thrusters on and off.
**Changelog**
- add: Add fryer to Piecrust

Shuttle edit - Add fryer to Piecrust

---

Content.Server/Anomaly/AnomalySystem.Scanner.cs
Content.Server/Anomaly/AnomalySystem.Vessel.cs
Content.Server/Anomaly/Components/SecretDataAnomalyComponent.cs
Content.Server/Anomaly/Effects/AnomalyCoreSystem.cs
Content.Server/Anomaly/Effects/InnerBodyAnomalySystem.cs
Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactComponent.cs
Content.Shared/Anomaly/Components/AnomalyComponent.cs
Content.Shared/Anomaly/Components/AnomalyCoreComponent.cs
Content.Shared/Anomaly/SharedAnomalyCoreSystem.cs
Content.Shared/Anomaly/SharedAnomalySystem.cs
Resources/Locale/en-US/_NF/anomaly/anomaly.ftl
Resources/Locale/en-US/_NF/cargo/pirate-bounties.ftl
Resources/Maps/_NF/Dungeon/mineshaft.yml
Resources/Maps/_NF/POI/anomalousgeode.yml
Resources/Maps/_NF/Test/dev_map.yml
Resources/Prototypes/Entities/Markers/Spawners/Random/Salvage/tables_loot.yml
Resources/Prototypes/Entities/Markers/Spawners/Random/maintenance.yml
Resources/Prototypes/Entities/Objects/Devices/Circuitboards/Machine/production.yml
Resources/Prototypes/Entities/Objects/Specific/Research/disk.yml
Resources/Prototypes/Entities/Structures/Machines/Computers/techdiskterminal.yml
Resources/Prototypes/Entities/Structures/Machines/anomaly_sync.yml
Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/Entities/Structures/Specific/Anomaly/anomaly_injectors.yml
Resources/Prototypes/Recipes/Lathes/electronics.yml
Resources/Prototypes/Research/experimental.yml
Resources/Prototypes/XenoArch/Effects/utility_effects.yml
Resources/Prototypes/_NF/Catalog/Bounties/pirate_bounties.yml
Resources/Prototypes/_NF/Entities/Markers/Spawners/Random/dungeon_items_research.yml
Resources/Prototypes/_NF/Entities/Objects/Devices/flatpacks.yml

A proposal to rebalance science and incentivize researching technologies.
Anomaly cores (both inert and active) and artifacts receive value for the research points earned (0.4:1), with anomalies capping at a fixed value ($30k at time of writing).  This supplants technology disks as a source of income.  "PvE" income is to come from selling researched materials (anomaly cores and artifacts) for cash - the points themselves are yours, and can be spent on technology, which can be used to make fun things and/or sell to other players.
Recipes for the technology disk console and anomaly synchronizer circuitboards have been removed, and the anomaly synchronizer has been unmapped from the Anomalous Geode - science gameplay should be active and involve player input, and turning science into an idle …

Science Rebalance: The Point of Points

---

Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml

Based on https://github.com/DeltaV-Station/Delta-v/pull/2339
Allow all borgs basic flight in space
Spawn as borg, jump into space
N/A
N/A
**Changelog**
:cl: Emily9031
- add: Cyborgs are now able to slowly fly through space.

Make borgs able to fly in space (DeltaV #2339)

---

Content.Server/_NF/Salvage/SalvageMobRestrictionsSystem.cs

When a mob leaves its restricted grid, if the mob will not be destroyed when leaving (i.e. it's a safe mob that spawns in with a bluespace event), it will not be warned or leave an admin log if leaving the grid.
Oversight in #2449.
1. Run `addgamerule BluespaceCave`.
2. Become Clugg.
3. Leave the grid.  You shouldn't get a popup.
4. Return to the grid.
5. Spawn in and become a Xeno queen.
6. Leave the grid. You should get a popup and turn pacified.
7. Return to the grid.  No more pacifism.
8. Check the admin logs, you should have nothing from Clugg, and messages about the xeno queen leaving.
Step 6: the xeno queen leaves the grid it's attached to, and is prompted to return.
**Changelog**
:cl:
- fix: Clugg is no longer prompted to return to the cave if leaving.

SalvageMobRestrictions: no warning/logging for safe mobs (e.g. Clugg)

---

Content.Shared/EntityTable/EntitySelectors/EntSelector.cs
Content.Shared/EntityTable/EntitySelectors/EntityTableSelector.cs
Content.Shared/EntityTable/ValueSelector/RangeNumberSelector.cs
Resources/Prototypes/Entities/Markers/Spawners/Random/Salvage/tables_loot.yml
Resources/Prototypes/_NF/Catalog/Fills/Crates/salvage.yml
Resources/Prototypes/_NF/Catalog/Fills/Lockers/wardrobe_colors.yml
Resources/Prototypes/_NF/Entities/Markers/Spawners/Random/dungeon_items_general.yml
Resources/Prototypes/_NF/Entities/Markers/Spawners/Random/salvage.yml
Resources/Prototypes/_NF/Entities/World/Debris/base_debris.yml
Resources/Prototypes/_NF/Entities/World/Debris/wrecks.yml
Resources/Prototypes/_NF/Events/nf_bluespace_dungeons_events.yml

Edited some of the loot to be more consistent, less seed crates and crates that have single item in them.
Upped artifact spawner a tiny bit, and made a change that wont allow the arti to trigger on wreck anymore.
Arti trigger and wreck and send half the loot into deep space.
N/A
N/A
N/A
**Changelog**
:cl:
- tweak: Blue wrecks should now have more interesting loot.

More wreck edits

---

Resources/Maps/_NF/Shuttles/spectre.yml

The Spectre had a port lateral thruster which was turned off by default. I turned it back on. 
Fixes mapping error.
Checkout branch, buy the ship, verify all thrusters are working.
Nope.
No.
**Changelog**
:cl:
- fix: Fixed a disabled thruster on the Spectre.

Spectre: Fix Disabled Thruster

---

Resources/Prototypes/_NF/Recipes/Cooking/meal_recipes.yml

Removes duplicated recipeType `Assembler` from chocolate donut recipe.
It's causing errors in my cookbook, man. :(
1. Make a chocolate donut, I dunno. It has no outward effect.
N/A
This is not a breaking change. It is a fixing change.
**Changelog**
N/A, exactly no outwardly visible effect.

Remove duplicated recipe type from chocolate donut recipe

---

Content.Server/Corvax/Respawn/RespawnSystem.cs

Resets respawn timers at the end of a round.
New round, new me - the respawn timers from last round shouldn't apply to the next one.
1. Open two clients.
2. On client 1, deadmin yourself.
3. On client 2, start the round.  Summon a throngler, kill client 1.
4. Make sure client 1 goes to a ghost (just to verify that you see a respawn timer.)
5. On client 2, end the round, start a new one.
6. On client 1, observe.  You should not have a timer on this branch (which is good), but you should on master (which is bad).
The issue on master: a new round starts, I was dead, I choose to observe, and I get penalized for my untimely death.
**Changelog**
:cl:
- fix: Respawn timers are reset on a new round.

End of round respawn cleanup

---

Resources/Prototypes/_NF/Entities/Markers/Spawners/Conditional/mobs_hostile_argocyte.yml
Resources/Prototypes/_NF/Entities/Markers/Spawners/Conditional/mobs_hostile_explorers.yml
Resources/Prototypes/_NF/Entities/Markers/Spawners/Conditional/mobs_hostile_mercenaries.yml
Resources/Prototypes/_NF/Entities/Markers/Spawners/Conditional/mobs_hostile_rogue_ai.yml
Resources/Prototypes/_NF/Entities/Markers/Spawners/Random/mobs_hostile_silicons.yml
Resources/Prototypes/_NF/Procedural/basalt_vgroid.yml
Resources/Prototypes/_NF/Procedural/cave_vgroid.yml
Resources/Prototypes/_NF/Procedural/chromite_vgroid.yml
Resources/Prototypes/_NF/Procedural/scrap_vgroid.yml
Resources/Prototypes/_NF/Procedural/snow_vgroid.yml

Added the following bosses:
- Basalt VGroid: Mercenary Captain.
- Cave VGroid: Explorer Captain (ghost role). Added T3 spawns to the interior.
- Chromite VGroid: Ascended Cultist.
- Scrap VGroid: One Star Unit or Guardian Unit (random). Added drone spawns to the exterior.
- Snow VGroid: Xeno Queen (ghost role) and Leviathing.
Danger!
1. Use addgamerule command to spawn VGroid, eg: `addgamerule BluespaceDungeonCave `
2. Take control over a boss and leave the grid, mob should become pacified and despawned after ~15 sec off-grid.
**Changelog**
- tweak: Hostile faction bosses can now be encountered on VGroids.

Add Bosses to VGroids

---

Content.Server/AlertLevel/AlertLevelSystem.cs
Content.Server/Light/EntitySystems/EmergencyLightSystem.cs

Adds a MapInit function for emergency lights, reorders some checks in the AlertLevel system.
I goofed, previous PR wasn't quite ready.
Emergency lights start on, pulsing in Green level. (my fault)
Constructed lights didn't match current alarm status. (upstream issue though)
1. Start game, join Frontier.
2. Emergency lights should be green and off.
3. Set status to red.
4. All emergency lights should be red and on (rotating PointLight).
5. Purchase a Construct.
6. The emergency light on the construct should be red and on.
7. Spawn an emergency light on the construct, it should be red and on.
CODE RED.  Steps 5, 6, and 7 of the test are shown below.
**Changelog**
:cl:
- fix: Emergency lights start in their appropriate state when built.

Fix Emergency Lights

---

Content.Server/_NF/Chemistry/RandomPillSystem.cs
Content.Shared/Chemistry/Components/PillComponent.cs
Resources/Prototypes/Entities/Objects/Specific/Medical/randompill.yml

Adds a flag to PillComponent that randomly swaps pill state on init, and swaps strange pills to use these.
Dirty needed to propagate state to client.
Ever think it's boring that floor pills are always orange and purple?
Spawn strange pills.
The colours.
I have a hunch this might fail some of the init and save tests.
**Changelog**
Trivial, no changelog.

Random appearance for random pills

---

Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/donut.yml

Blue-Pumpkin jelly donuts, Bungo jelly donuts, Apple jelly donuts, and meat donuts were unable to fit inside a donut box due to being erroneously marked as non-donuts due to tags being overwritten. This PR fixes this by defining the Donut tag WITH the fruit/meat tag.
Because it makes no sense that a donut made of fruit or meat cannot fit inside a standard issue donut box.
1. Spawn a donut box.
2. Spawn a blue-pumpkin jelly-donut, bungo jelly-donut, apple jelly-donut, and meat donut.
3. Place each donut inside the donut box one-by-one.
4. mmm donuts.
**Changelog**
:cl:
- fix: Fixed certain jelly-filled donuts, and a particularly meaty one, being unable to fit inside a donut box.

Fix certain donuts being unable to fit inside a donut box

---

Resources/Prototypes/_NF/Entities/Structures/Machines/lathe.yml

This PR adds a crafting option for the black light to the service tech fab.
Some changes added to the color strobe PR removed the black light from salvage boxes. Which previously was, as far as I can tell, the only way of accessing them. This allows players with this specific lathe to access them again for decoration purposes.
This fix can be considered as temporary as we want. I recognize that there's a whole piece about adding black crystals. I think upstream has been comfortable sitting on that one for a while and I don't know if it's something we really want to do on our own down here just for one additional light.
Spin up a service lathe. Print out a light.
**Changelog**
🆑 
- add: Black light to service lathe.

Quick black light fix.

---

Content.Server/Worldgen/Systems/LocalityLoaderSystem.cs
Content.Server/_NF/StationEvents/EventSystems/LinkedLifecycleGridSystem.cs
Resources/Prototypes/_NF/Entities/World/Debris/base_debris.yml
Resources/Prototypes/_NF/Events/nf_bluespace_dungeons_events.yml
Resources/Prototypes/_NF/Events/nf_bluespace_grids_events.yml
Resources/Prototypes/_NF/Events/nf_bluespace_salvage_events.yml

- Fix players despawning on salvage and other things like wrecks derelicts
- Also they cannot pilot them anymore
if you knock them away with a ship the player also wont despawn but the salvage will still despawn.
Fixed the despawn
Spawn as a contractor
Aghost
Drag body through space and put the body on a salvage wreck
griddrag
toss the grid away and watch as your body wont despawn anymore.
**Changelog**
:cl:
fix: Fix player bodies despawning on debris
tweak: No longer possible to fly debris, wrecks, and salvage

Prevent player despawning on salvage and other debris

---

Resources/Maps/_NF/Shuttles/lyrae.yml

Fixes the Lyrae gas mixer setting.
The setting was incorrect, pumping in more oxygen than nitrogen.
Load Lyrae. Look at mixer.
BEFORE:
AFTER:
No.
**Changelog**
N/A, just a tiny fix

Fix Lyrae mixer setting

---

Content.Server/Materials/MaterialStorageSystem.cs

Made lathes automatically turn off their magnets if you try to eject materials from them.
QoL fix, saves 1 click or possibly more if you forgot to disable the magnet beforehand.
Turn on a magnet on a lathe
Insert materials
While the magnet is active, try to eject materials.
https://github.com/user-attachments/assets/9568d35d-981e-46e4-8adc-63a6129ed21a
None identified
**Changelog**
:cl:
- tweak: Lathes now automatically disable their magnets when ejecting materials.

Automatically turn off magnet when ejecting materials from lathes

---

Resources/Prototypes/_NF/Catalog/Fills/Crates/materials.yml
Resources/_NF/migration.yml

Some wanted a crate, we got a crate
Crate
Spawn entity, open, look inside
Its a steel crate
None
**Changelog**
None

Added a new materials CRATE

---

Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/tools.yml
Resources/Prototypes/_NF/Loadouts/contractor_loadout_groups.yml

Contractors, pilots, and mercs can choose a monkey or kobold cube in loadout.  
CaptainHonesty wanted it and it seemed harmless enough.
Choose a cube and spawn in.
Nah
**Changelog**
:cl:
- add: Added monkey and kobold cubes to loadout under tools.

Add monkey/kobold cube to loadout under tools (Merry Christmas Aka)

---

Content.Shared/Paper/PaperSystem.cs
Content.Shared/Paper/StampComponent.cs
Resources/Prototypes/Entities/Objects/Misc/pen.yml
Resources/Prototypes/Entities/Objects/Misc/rubber_stamp.yml
Resources/Prototypes/_NF/Entities/Objects/Misc/pen.yml
Resources/Prototypes/_NF/Entities/Objects/Misc/rubber_stamp.yml
Resources/Prototypes/_NF/tags.yml

Adds a Protected field to Sheriff, SR and Centcomm rubber stamps.  When a stamp with this field set to true is used to stamp a piece of paper, the paper receives a tag that notes it is protected.
The CyberPen can no longer edit papers stamped with these stamps.  The CentComm pen, however, can.
Should also fix any issue with the centcomm pen being labelled as class 3 contraband.
The biggest issue with Cyberpen availability is (apparently) game ruining through impersonation of command jobs.  With these changes, that should hopefully be less of an issue, so we can get more lower-level fraud to spur more cheeky interaction between players.
If we need additional levels of protection (traffic tickets?  signatures only?), this could be moved from a boolean & tag to integral fields.
With this, it …

Protected stamps, weaker cybersun pen

---

Resources/Maps/_NF/Shuttles/Nfsd/prowler.yml

Added a medicine locker and box of body bags to the Prowler to stop the voices who keep asking me to do so.
Why is the Prowler? Honestly could not tell you.
I added the medicine and body bag to the gym because I figured that's where the NFSD were suffering the most casualties on an average shift.
Basically same equipment that the Wendigo, the new gold standard, enjoys. Seemed like a reasonable request.
Go check out the new locker and box on the Prowler.
**Changelog**
🆑 
- tweak: Prowler now has medicine cabinet and body bags. Die on the treadmill in peace.

Adds a first aid locker and box of body bags to the prowler.

---

Resources/Locale/en-US/_NF/research/technologies.ftl
Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/Research/civilianservices.yml
Resources/Prototypes/_NF/Research/civilianservices.yml

Cleanup the lathe file
Restore the option to make chem machines in sci but require tech.
Clean out the shuttle guns that we missed and leave the mining one as added.
Get the tech, print some boards.
N/A
N/A
**Changelog**
:cl:
- tweak: ChemicalDispensary tech is added again, allow sci to print tier one medical machines again.

Fixed missing tech and boards

---

Content.Server/Chemistry/EntitySystems/ChemMasterSystem.cs
Content.Shared/Chemistry/SharedChemMaster.cs
Resources/Prototypes/Entities/Structures/Machines/chem_master.yml

Now the chemmaster shows a different sprite when it has a beaker!
unused sprite was languishing in the code, bring it in and warm it up
put beaker in chemmaster
**Changelog**
:cl:
- fix: Chemmaster now uses a new sprite when beaker inserted!

use unused filled chemmaster sprite

---

Resources/Prototypes/Entities/Objects/Materials/scrap.yml

Renames _scrap circuitry_ to _fried circuitry_.
On about a dozen occasions, I've watched people try to put scrap circuitry in the scrap processor. It's visually similar to scrap chunks, and people seem to think it's somehow compatible. It is my hope that changing it to "fried circuitry" might disabuse people of this notion and make it ever clearer that this is junk that goes in the material reclaimer, not scrap to be refined.
1. Spawn fried circuitry.
2. Behold the new name.
N/A
No.
**Changelog**
:cl:
- tweak: Scrap circuitry has been renamed to fried circuitry. Put it in the material reclaimer, not the scrap processor!

Rename scrap circuitry to fried circuitry

---

Content.Shared/Storage/EntitySystems/MagnetPickupSystem.cs
Content.Shared/Storage/EntitySystems/SharedStorageSystem.cs

This is a bandaid fix for high memory usage for bags that use the magnet component.
It still happens when u have total, spread out, enough free slots, but this at least reduces the amount of occurrences of it happening.
Performance fix
strap on your favorite magnet bag
put a giant load of items around you, fill up the bag, put even more items around you. (about 20+)
lets say you have 2 spaces left in your bag and theres a ton of items around you that each need 4 spaces.
Now, it wont cost you your computer's soul
None
**Changelog**
Changelog not needed

Fix 20gb memory usage for magnet code

---

Content.Server/_NF/StationEvents/EventSystems/LinkedLifecycleGridSystem.cs

Changes the LinkedLifecycleGridSystem to stop matching false positives with humanoid characters.
Bug report: https://discord.com/channels/1123826877245694004/1331093959648219186
Medical bounties currently have MindContainer, which was being matched against for grid despawn prevention.  This replaces it with BankAccountComponent - this is hacky, but will match player characters, which is the intent.  We could add an "NFPlayerComponent" or some tag after spawning to the same effect.  I believe admin-spawned characters won't match this, though I'm not sure.
1. Fly to a wreck.
2. Make sure there's a medical pod on the wreck.
3. Spawn a Urist on the wreck, give them BankAccountComponent.
4. Face north.
5. Fly forward for about 300 meters - check your Content.Server console, there should be a …

Fix LinkedLifecycleGridSystem player check

---

Resources/Prototypes/Research/arsenal.yml

Merges "Basic" and "Advanced" shuttle armaments into just basic shuttle armaments
Considering advanced shuttle tech has all of... an EMP grenade and a high capacity power cage, there's no need for two techs. Bumped the price of basic shuttle arma up to 17.5K to compensate.
Load server
check the guidebook
notice the tech
**Changelog**
:cl:
- tweak: Merged Advanced and Basic shuttle tech into one.

Reduce shuttle tech to one tech

---

Resources/Prototypes/_NF/Roles/Jobs/Nfsd/bailiff.yml

Gives bailiff med and chemistry access.
Bailiff is brig medic's direct superior so they need to mirror their access to chem and med.
#2740 related
Use bailiff to open a chemistry and medical locked door.
**Changelog**
:cl:
- add: Added medical and chemistry access to bailiff.

Give bailiff access to chemistry and medical (since they are brigmed's boss)

---

Resources/Maps/_NF/Shuttles/Nfsd/empress.yml
Resources/Maps/_NF/Shuttles/Nfsd/wasp.yml

Updates the chemistry rooms on the Empress and Wasp with chemistry-locked doors.
The brigmedic was given chemistry access in #2740 and the chem area on the NFSD Outpost was put behind chemistry access. To keep some sort of parity with the NFSDO, this PR gives the Empress and the Wasp the same treatment.
1. Buy an Empress.
2. Equip an NFSD ID card that is not that of Sheriff or Brigmedic. Fail to enter the chemistry room.
3. Equip a Sheriff or Brigmedic ID card. Success.
4. Repeat with the Wasp.
Empress:
Wasp:
No.
**Changelog**
:cl:
- tweak: The chemistry rooms on the Empress and the Wasp are now only accessible to people with chemistry access. (Sheriff and Brigmedic by default.)

Update Empress and Wasp with chemistry-locked doors

---

Content.Server/Ame/EntitySystems/AmeControllerSystem.cs

Bugfix to stop the AME from injecting on update if the fuel slot is empty.
Abusable, bugfix for https://discord.com/channels/1123826877245694004/1332130518816391249
1. Spawn on expeditionary lodge.
2. Purchase a Pathfinder.
3. Walk onto it.
4. alt-click the AME controller, the fuel jar should pop out.
5. Wait up to 10 seconds for the next injection cycle.  The AME controller should turn off.
6. Spawn a power monitoring console and confirm that the power supplied by the AME is 0 W.
**Changelog**
:cl:
- fix: The AME no longer provides power if the fuel slot is empty.

AME controller: stop injecting if fuel slot is empty

---

Resources/Prototypes/Entities/Objects/Specific/Mech/mechs.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/pets.yml

Added 2 clamp slots to the vim, to bring it in line with the hamtr, per whatstone's suggestion. 
added tags to base NFcat so they can pilot the vims as well 
the hamtr is cool, but only lets a hamster in. so its either make a full new mech, rename and rebrand the hamtr, or give the vim a couple slots so that our pet friends  have a little more function. 
load local host
spawn a vim
spawn some clamps and install them
spawn cappy or any other NF cat and shove them in. enjoy the ability to move small objects
alternativly spawn any already authorized ghost pet (or vermin) and shove them in, also to enjoy the new clamps
N/A
NA
**Changelog**
:cl:
- tweak: VIM can now take two small clamps so our little friends can carry around their favorite plushies.

Vim update

---

.vscode/launch.json

Adds a new vscode launch task that only starts the debugger.
Names could be changed, and "Server/Client" should probably be called "Server/Client (Debug)".
Sometimes I just want to run the debugger.
1. Run "Server/Client".  It'll build and launch the debugger.
2. Run "Server/Client (No Build)".  It should only launch the debugger using the existing executables.
**Changelog**
no in-game changes

VSCode Config: Server/Client launch task without build

---

Resources/Locale/en-US/_NF/guidebook/guides.ftl
Resources/Maps/_NF/Shuttles/bodkin.yml
Resources/Prototypes/_NF/Guidebook/shipyard.yml
Resources/Prototypes/_NF/Shipyard/bodkin.yml
Resources/ServerInfo/_NF/Guidebook/Shipyard/Bodkin.xml

Updated the SBB Bodkin, adding a couple of new things along with a guidebook entry. In fact, the first guidebook entry of anything I've mapped! Wow!
The Bodkin now gets a wallmount mass scanner in the cargo bay area, allowing the salvage crew to coordinate with the pilot and see what's around them. 
Shutters were added to the windows on the bridge and in the rest area. Not sure why I didn't include those to begin with.
Guidebook entry created. Omitted the preflight checklist as frankly the shuttle spawns with everything working, so a checklist isn't necessary. 
New features were added to the game, things that the Bodkin could make use of, so now it does. Also brings it in line with other standard features on shuttles.
Hopefully the arbitration script doesn't kill my wife and children this …

SBB Bodkin 1.1

---

Resources/Prototypes/_NF/Entities/World/Debris/asteroids.yml
Resources/Prototypes/_NF/Entities/World/Debris/base_debris.yml
Resources/Prototypes/_NF/Entities/World/Debris/wrecks.yml
Resources/Prototypes/_NF/World/Biomes/basic.yml

Creates abstract entities for base wrecks/asteroid sizes that do not inherit from instances of wrecks/asteroids.
All concrete wrecks/asteroids inherit from an abstract size and an abstract biome/template with layout.
Added a rare(r) extra large brass wreck since we're in the neighbourhood.
Previous implementation had scrap asteroids inheriting off of the orange rock asteroid template twice, leading to gas deposits on scrap asteroids.
1. Spawn a gas deposit locator.
2. Spawn a bunch of scrap asteroids (they can overlap)
3. The locator should not ping when near them.
4. Repeat step 2 for rock asteroids.
5. The locator should (likely) ping when near them.
6. Spawn some wrecks, they should spawn as normal.
Forks defining their own asteroid sets might need changes to deleted IDs.
**Changelog** …

Fix asteroid and wreck parenting.

---

Content.Client/Input/ContentContexts.cs
Content.Client/Options/UI/Tabs/KeyRebindTab.xaml.cs
Content.Shared/Hands/EntitySystems/SharedHandsSystem.Interactions.cs
Content.Shared/Input/ContentKeyFunctions.cs
Resources/Locale/en-US/escape-menu/ui/options-menu.ftl
Resources/keybinds.yml

Adds a keyboard shortcut to swap to the previous hand (Shift+X by default vs. X for swap to next).  Useful for cyborgs, harmless for everyone else.
Cyborgs have some modules with 6+ items.  Having to press swap 5 times to get to the previous item sucks.
1. Play a borg.
2. Press X, you'll select the next item.
3. Press shift+X, you'll select the previous item.
4. Keep pressing X to cycle through all the items, no issues.
5. Keep pressing Shift+X to cycle through all the items, no issues.
**Changelog**
:cl:
- add: A keybind is available to swap to the previous hand (default Shift+X).

Keyboard shortcut for "swap to previous hand"

---

Resources/Prototypes/_NF/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/_NF/Recipes/Lathes/service.yml

Adds a desk bell recipe to the service techfab.
Requested on the Discord. Not all service ships come with a desk bell premapped and some players would like to add them to their custom food ship builds.
Put two pieces of steel in a service techfab.
Create desk bell.
Ding the bell a few times just to make sure.
None.
**Changelog**
:cl:
- add: Added desk bell to the service techfab.

Add desk bell to the service techfab.

---

Content.Server/_NF/Worldgen/Systems/Debris/RandomEntityPopulatorSystem.cs

Fixes gas deposit duplication - a list is used to gather spawned entities, it needs to be cleared between calls.
Bug.
Generate large asteroids until you get one with two gas deposit sprites.
**Changelog**
:cl:
- fix: Gas deposits no longer duplicate on asteroid tiles.

Fix asteroid gas deposit entity duplication

---

Resources/Prototypes/_NF/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/_NF/Recipes/Lathes/service.yml

Adds a BRB sign recipe to the service techfab.
Allows service ships to alert customers they are currently not there and will be right back.
Put two pieces of cardboard in a service techfab (or work your way up to creating it from two pieces of wood).
Create BRB sign.
Hide in the back from customers.
None.
**Changelog**
:cl:
- add: Added BRB sign to the service techfab.

Add BRB sign to the service techfab.

---

Content.Server/Silicons/Borgs/BorgSystem.Modules.cs

When re-equipping items from a borg's provided item container:
1. If the item is an actual item, equip it as usual.
2. If the item is a placeholder, create a hand, equip it, make sure it's equipped, and if so, you're fine.
3. If the item equipped is not your item (e.g. an empty hand), delete the hand.  No free hands, ever.
I goofed.
1. Become service borg
2. Swap to your service module.
3. Drop your borg shaker and borg lighter.
4. Unequip the service module, re-equip the service module.
5. Your shaker and lighter placeholder items should _still exist_ in your hands.
The book bag and shaker here are unequipped, placeholder items.
**Changelog**
Not in-game yet.

BetterBorg Hotfix: Unremoveable after equip

---

Content.Server/Station/Components/StationJobsComponent.cs
Content.Server/StationRecords/Systems/GeneralStationRecordConsoleSystem.cs
Resources/Prototypes/_NF/Maps/Outpost/frontier.yml
Resources/Prototypes/_NF/PointsOfInterest/medical.yml
Resources/Prototypes/_NF/PointsOfInterest/nfsd.yml

Protects interactions with station records consoles.  The StationJobsComponent now gets optional access levels and tags - any of the given tags (or any within the listed groups) is required on the person changing the access for changes to go through.
Issue: there isn't currently a single API call to do this without having an AccessReaderComponent (which really makes no sense on the station - what are you protecting), so this is currently duplicating a routine that the shipyard console uses.
Any dingus dragging a station records computer onto a grid shouldn't be able to open station job slots.  Long open pain point.
Counterpoint: you can't open slots if the last guy nodded off without reopening their own position.
1. Spawn a Urist, become the Urist.  Purchase a ship, edit your job listings …

StationJobs: protect station jobs with access levels/groups

---

Content.Server/Chemistry/EntitySystems/ReagentDispenserSystem.cs

Calls ContainerSystem.Insert directly instead of ItemSlot.Insert when initializing a reagent dispenser.
Currently, the reagent dispenser plays the clicky insert sound when inserting things into the dispenser.  It does this _for each item in the dispenser_ on spawn.  If you warp to a chemistry ship, your ears currently bleed.
1. Spawn a chemical dispenser.
2. Enjoy the silence.
3. View the contents of the chemical dispenser.
4. They should match.
5. Insert more jugs, you should be able to fit five.  Each insertion is clicky.
6. Remove and reinsert jugs.  Removal/insertion is clicky.
The contents of a chemical dispenser after spawning.  Everything is accounted for.
**Changelog**
:cl:
- fix: Reagent dispensers no longer play a sound for inserting all jugs on initializing.

Silence reagent dispensers on spawn.

---

Content.Server/_NF/GameRule/NfAdventureRuleSystem.cs
Resources/Locale/en-US/_NF/adventure/adventure.ftl

Fix the webhooks to contain the server name and round number for admins use
Was missing
Trust me
N/A
N/A
**Changelog**
N/A

Update Frontier webhooks

---

Resources/Maps/_NF/POI/nfsd.yml
Resources/Prototypes/_NF/Catalog/Fills/Lockers/heads.yml
Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/cart.yml
Resources/Prototypes/_NF/Roles/Jobs/Frontier/sr.yml

Filled the Sheriff's Locker on the NFSD Outpost (ID Card, Cuff Box, Demag, Access Config, etc.)
Moved the SR's Access Config from their bag to their locker.
EDIT: Access config is in the PTechs now, not locker.
Firstly, currently if an SR is not ingame, no access configurator exists, which is a problem if needed by for example the DoC or the Sheriff.
Also, the sheriff used to get a few things in their locker, including the demag, but now they just don't. With this PR they get a demag, which is arguably more important for them then for the SR, alongside an access configurator for if they want to change NFSD Accesses (Add an armory lock to a bought armory crate, make certain areas on ships require higher access, etc.) Alongside some misc things such as a cuff box, comms console board, nfsd …

Fill Sheriff's Locker & Move SR Access config to their locker.

---

Content.Server/_NF/Cargo/Systems/CargoSystem.TradeCrates.cs

Fixes the time reference used for trading crate description text.
As a reminder, GameTiming.CurTime is effectively the total simulated uptime of the server.
I goofed.  Again.  The same goof as before.
1. Start a round.
2. Warp to the Trade Outpost.
3. Buy some crates.
4. Check the time on the crates, should be ~28:00 minutes.
5. Wait about a minute.
6. `golobby`, `startround`
7. Warp to the Trade Outpost.
8. Buy some crates.
9. Check the time on the crates, should _still_ be ~28:00 minutes.  On the head of master, this might be 30 - not shift time, but uptime.
Following the test procedure, this is what you should see at step 9 (and 4).
**Changelog**
:cl:
- fix: Trading crates should report their delivery time correctly.

Trade crates: fix time reference

---

Content.Client/Shuttles/UI/ShuttleNavControl.xaml.cs

Fixes #2775 
The occlusion bounds in the dock drawing code didn't take into account UI scale, so docks passed a certain point would disappear. This patch fixes the issue.
Not being able to see docks too far to the right/bottom of the view is annoying. So is playing at 100% UI scale on a high-DPI display.
1. Set your UI scale to >100% - the biggest you can reasonably use, the easier the issue will be to see.
2. Pilot and position a ship so that a docking port is near the bottom right of the NAV display, and observe that it no longer disappears.
Before:
After:
**Changelog**
:cl:
- fix: Fix docks disappearing on the NAV console at >100% UI scale

Fix docks disappearing in NAV when >100% UI scale

---

Content.Server/Access/Systems/IdCardConsoleSystem.cs
Content.Shared/Access/Components/IdCardConsoleComponent.cs

Bugfix for the ID Card Console, type mismatch.
There were a few uses of AccessLevelPrototype when they should really be using JobPrototype.
Should upstream this, then we can move to a lesser ring of comment hell.
Note: for Frontier specifically, we might want to add the JobPrototype to the ID card itself, because blank ID cards (fairly common, muh replacements) check station records to get a job prototype (they will never have a record, they are a blank ID).  As such, there are still some remaining issues where the dropdown won't stay on the item you'd expect, reverting to Contractor.  Leaving this as a separate issue for now.
1. Spawn on Frontier Outpost as a Contractor.
2. Drag yourself into the SR's office as an aghost.
3. Take your admin ID, put it into the ID card computer.
4. aghost …

Great job ID card console bugfix

---

.gitignore
Content.Server/NPC/HTN/HTNSystem.cs

Makes the HTN system skip npc's that are stuck in space or they keep trying to do their current plan for as long as possible
NPC's that are stuck in space will continue to plan till they disapear or in some cases Forever. this change stops it.
massive npc budget improvement 
spawn NPC in space ( examine HTN comp for plan accumulator tick not ticking) observe npc starting to plan the instant they can on a grid
- [ X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X ] I have added media to this PR or it does not require an ingame showcase.
**Changelog**
:cl:
fix: Fixed NPC hang in case of tons of NPC's being in space

Stop NPC's from trying to plan when they wont be able to plan anyways in space

---

Resources/Locale/en-US/_NF/prototypes/access/accesses.ftl
Resources/Maps/_NF/POI/cove.yml
Resources/Maps/_NF/Shuttles/BlackMarket/barnacle.yml
Resources/Maps/_NF/Shuttles/BlackMarket/bocakillo.yml
Resources/Maps/_NF/Shuttles/BlackMarket/falcon.yml
Resources/Maps/_NF/Shuttles/BlackMarket/menace.yml
Resources/Maps/_NF/Shuttles/BlackMarket/schooner.yml
Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml
Resources/Prototypes/Entities/Objects/Tools/access_configurator.yml
Resources/Prototypes/_NF/Access/pirate.yml
Resources/Prototypes/_NF/Entities/Objects/Devices/Electronics/door_access.yml
Resources/Prototypes/_NF/Entities/Structures/Doors/Airlocks/access.yml
Resources/Prototypes/_NF/Roles/Jobs/Pirates/pirate.yml
Resources/Prototypes/_NF/Roles/Jobs/Pirates/pirate_captain.yml
Resources/Prototypes/_NF/Roles/Jobs/Pirates/pirate_first_mate.yml

Introduces a new access for pirates.  Locks pirate shuttle doors behind pirate access.  All doors on the cove apart from the freezer and bathroom doors are Pirate access-locked.  Pirates, Pirate First Mates (this includes Clarpy), and Pirate Captains all receive the Pirate access.
Aghosts receive this access level, as well as the universal configurator having it.
**Note: the two NFSD ships that currently have unlocked docking airlocks are the Templar and the Hospitaller.**  Unsure of the best course, **I have left those as-is for the time being.**
The sheriff now has disposable access configurators.  This PR ensures that the NFSD cannot break into the Pirate Cove or pirate shuttles, or lock access _to_ them by simply opening or reconfiguring the doors.  Get an ID card off of a pirate.
Why …

Pirate Shuttles, Pirate Cove: pirate-locked doors

---

Content.Server/Silicons/Borgs/BorgSystem.Modules.cs

Fixes an issue where droppable items weren't being considered in equality checks for duplicated modules.  This led to some cases where modules were considered duplicates (e.g. fire extinguisher and jetpack) because their set of fixed items is empty.
Impromptu bug report from Discord.
1. Spawn a borg, inhabit it, pick the generic chassis, exit the borg.
2. Spawn two fire extinguisher modules and two jetpack modules.
3. Unlock and screwdriver the borg.
4. Try to insert both fire extinguisher modules.  The first should work, the second should fail (it's duplicated).
5. Try to insert both jetpack modules.  The first should work (the bug has been fixed), the second should fail (it's duplicated).
6. Repeat with the GPS module (only fixed items).
7. Inhabit the borg, drop your fire extinguisher, …

BorgSystem: check droppable items for duped mods

---

Resources/Prototypes/Entities/Clothing/Ears/headsets.yml
Resources/Prototypes/Entities/Clothing/Ears/headsets_alt.yml
Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/encryption_keys.yml
Resources/Prototypes/_NF/Loadouts/contractor_loadout_groups.yml

Remove the unneeded limit for frontier headset use, just allow using all the keys cuz why the fuck not.
This is an upstream limit that make sense there where john station should not be on 5 departments
Insert key to radio, insert 9 more
N/A
N/A
**Changelog**
:cl:
- tweak: You can now insert up to 10 headset keys into any headset.

Up the Headsets keys limits to 10

---

Content.Client/Materials/MaterialStorageSystem.cs
Content.Server/Materials/MaterialStorageSystem.cs
Content.Shared/Materials/SharedMaterialStorageSystem.cs

Largely reverts #2943.
Adds missing server- and client-side functions that override TryInsertMaxPossibleMaterialEntity - these functions handled the entity deletion or simulated client-side deletion and exist for the base TryInsertMaterialEntity function.  TryInsertMaxPossible now respects the bounds of the stack, and the material storage interaction now _only_ calls TryInsertMaxPossible rather than running two insertion checks.
A new output boolean (currently named `empty`) tells whether or not the item or stack was exhausted and needs to be deleted.
This PR aims to fix the root cause of the issue behind the hotfix PR.  The public API of a class should behave straightforwardly, and "insert all material that fits" shouldn't stop working because a material storage is unlimited, or you …

Server- and Client-side partial stack insert functions, hotfix reversion

---

Content.Shared/Atmos/Atmospherics.cs
Resources/Prototypes/Atmospherics/reactions.yml

Hoo boy.
This PR is an attempt to make tritium generation viable through straightforward burn chambers.
As-is upstream, both the plasma and tritium fire reactions start at the same temperature.  This results in a bunch of tritium burning off as water vapour.  Since our sources of oxygen are limited, and tritium production requires an oxygen-rich mix to begin with, and consumes oxygen from the fire, we try to conserve oxygen by:
1. Enabling low temperature burn chambers to run without starting a tritium fire.  Tritium fires release a ton of energy and consume a bunch of tritium.  By increasing the temperature that tritium fires start at, we can allow for steady tritium generation under proper conditions.  An efficient burn chamber requires ensuring that your mix does not generate …

Atmos tweaks to improve tritium generation

---

Resources/Prototypes/_NF/Entities/Structures/Wallmounts/switch.yml

Adds a lockable button with Pirate access for mapping purposes.
I thought this would be added in #2893 but it wasn't, want to use this for my own purposes.
This will be nice for pirate ships that want to use shutters, specifically in a brig.
Spawn in as a contractor, place lockable pirate button, can't open it, spawn in pirate ID card and open.

Lockable Pirate button

---

Content.Server/_DV/Mail/Components/MailTeleporterComponent.cs
Content.Server/_DV/Mail/EntitySystems/MailSystem.cs
Content.Server/_DV/Mail/MailCommands.cs
Content.Server/_NF/Mail/Components/SectorMailComponent.cs
Resources/Locale/en-US/_NF/mail/mail.ftl
Resources/Prototypes/_NF/Mail/mail.yml
Resources/Prototypes/_NF/SectorServices/services.yml

Makes mail a sector-wide occurrence.  Mail deliveries will now occur every 35 minutes regardless of the state of the mail teleporters.  No teleporters are powered on?  No mail.  Tough.
For the mail teleporters that are on, the delivery will be split randomly between these.  More mail teleporters should not mean more mail, merely more places where mail can spawn.  Don't want to run between the Trade Mall and Frontier Outpost?  Okay, pick one, and disable the other mail teleporter.
Parameters have been pushed largely from the mail teleporter into a new SectorMailComponent - this does mean that mail can no longer be controlled per-teleporter.
If you are capable of showing an SSD icon and you are considered as SSD by the game, you are ineligible to receive mail.
The isPriority and isFragile …

Sector-wide mail, no mail to SSD players

---

Content.Server/Botany/SeedPrototype.cs
Content.Server/Botany/Systems/BotanySwabSystem.cs
Content.Server/Botany/Systems/MutationSystem.cs
Content.Server/Botany/Systems/PlantHolderSystem.cs
Content.Server/Botany/Systems/SeedExtractorSystem.cs
Content.Server/EntityEffects/Effects/PlantMetabolism/PlantDestroySeeds.cs
Content.Server/EntityEffects/Effects/PlantMetabolism/PlantRestoreSeeds.cs
Content.Server/_NF/Botany/Systems/PlantAnalyzerSystem.cs
Resources/Locale/en-US/_NF/botany/components/plant-holder-component.ftl
Resources/Locale/en-US/_NF/botany/swab.ftl
Resources/Prototypes/Hydroponics/seeds.yml
Resources/Prototypes/_NF/Entities/Objects/Specific/Hydroponics/seeds.yml

Adds three fields to seed data: PermanentlySeedless, PreventClipping, and PreventSwabbing.
These are applied to capfruit and gatfruit to prevent mass python spam as a counterpart to #2992.  Bees are also made unswabbable (they're bees) - useful for #2964.  I've left the bee clipping for now, but it should ideally be swapped out for a net and used for bees and/or fish if added.
If it's reasonable, we could add an uplink item for a discount "do-it-yourself gatfruit farm" with 5-10 gatfruit seeds, but that isn't in the PR as-is.
Being able to get an infinite number of gatfruit out of a given seed is a nightmare.  This restricts you to anything you can harvest in one plant's lifetime.
Grow some gatfruit.
1. Try to get gatfruit seeds from an extractor, shouldn't work.
2. Try to get gatfruit …

Add permanently seedless, no clip/no swab attributes to gat/capfruit, prevent swabbing bees.

---

Resources/Prototypes/_NF/Entities/Clothing/Ears/headsets.yml
Resources/Prototypes/_NF/Entities/Clothing/Ears/headsets_alt.yml
Resources/Prototypes/_NF/Roles/Jobs/Frontier/sr.yml

Removes CC encryption key from the SR and Sheriff.
We've been a little bit sloppy in giving Central Command items to non-CC actors. Generally, "Central Command" refers to the game's administration; we shouldn't blur that line. Only CC gets CC stuff.
If admins for any reason want to give CC comms access to the SR and/or Sheriff for an admeme, the encryption key can easily be given as and when it's needed.
1. Spawn as SR. Don't have a CentComm encryption key in your bag.
2. Respawn as Sheriff. Don't have a CentComm channel in your headset. :)
N/A
No.
**Changelog**
:cl:
- remove: The SR and Sheriff no longer start with CentComm comms keys. Coordinate over command comms instead!

Remove CentCom encryption key from SR and Sheriff

---

Content.Server/Standing/StandingStateSystem.cs
Content.Shared/_NF/Interaction/Systems/SharedHandPlaceholderSystem.cs
Content.Shared/_NF/Standing/PreventDropOnDownedComponent.cs
Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml

A fix for cyborg inventory management.
Instead of hand/dropped events, a borg's placeholder item for droppable module slots is spawned on container events (always raised).  The placeholder is spawned and placed in the slot at the time of removal.
Additionally, borgs now do not drop their items when downed - their module items should be internal.
Bug.
1. Spawn a service cyborg.
2. Start another client, become the cyborg, equip the module with the lighter, shaker and book bag.
3. On the first client, throngle the borg until it drops. It shouldn't drop its items.
4. Revive the borg.  On the second client, drop your droppable items.
5. Try to pick up the borg's modules and drop them on the first client.  You shouldn't get borg placeholders.
6. Remove the "- type: PreventDropOnDown" line from …

Cyborgs: don't drop on down, spawn placeholders on container events

---

Content.Client/_NF/BountyContracts/UI/BountyContractUiFragmentCreate.xaml.cs

In the bounty console, use the original vessel index as the dropdown item ID, not the new index.
Just two lines above where the vessels are added, we sometimes skip items:
```csharp
if (string.IsNullOrWhiteSpace(_vessels[i]))
continue;
VesselSelector.AddItem(_vessels[i], listIndex);
listIndex++;
```
Unfortunately, later on in GetVessel, we use the item ID as an index into `_vessels`:
```csharp
var id = VesselSelector.SelectedId;
if (id < _vessels.Count)
vessel = _vessels[id];
```
If an item has indeed been skipped, the ID will point to the wrong index in `_vessels`! The simplest solution of all is to skip the `listIndex` dance and just use the original index, which allows us to get back to the right value in `_vessels` with no hassle of any kind. Easy peasy.
It appears index 1 is often …

Use original vessel index as ID in bounty console

---

Content.Server/Atmos/EntitySystems/AirFilterSystem.cs
Content.Server/Atmos/EntitySystems/AtmosphereSystem.API.cs
Content.Server/Atmos/EntitySystems/AtmosphereSystem.CVars.cs
Content.Server/Atmos/Piping/Unary/EntitySystems/GasPassiveVentSystem.cs
Content.Server/Atmos/Piping/Unary/EntitySystems/GasVentPumpSystem.cs
Content.Server/Atmos/Piping/Unary/EntitySystems/GasVentScrubberSystem.cs
Content.Server/Atmos/Portable/PortableScrubberSystem.cs
Content.Shared/_NF/CCVar/NFCCVars.cs

Prevents gas extraction from map atmospheres.
NOTE: Until we have a proper solution where planetary atmospheric collection is challenging, and an intentional design that makes it more engaging, this removal addresses the issue of infinite resource extraction.
Infinite sources of gas are undesirable.  Gas miners got axed for the same reason.
1. Purchase a Gasbender, spawn a debug console, go on expedition to a planet with an atmosphere.
2. Try to scrub the atmosphere.  Try on solid tiles that should be map-exposed.  Try on lattice that should be map exposed.
3. Try to purge the gas inside your shuttle through waste, it should work as normal.
4. Place a character outside, they should interact with the atmosphere as normal.
**Changelog**
:cl:
- remove: Scrubbers and other atmospheric intakes …

Prevent gas extraction from map mixes - see note, temporary until a better solution is proposed.

---

Resources/Prototypes/_NF/Recipes/Lathes/blueprints.yml

Lowers the material cost of a single blueprint from 5 sheets of paper to 3.
With a full stack of paper, the previous cost allowed you to make only 6 blueprints. Many of the more desirable blueprintable technologies are broken up into multiple blueprints – 3 blueprints for super parts, 3 for advanced tools, one per bluespace bag type, and so on. With the tweaked cost, you can print 10 blueprints. Since paper is still ever so slightly annoying to obtain, my hope is that lowering the material cost may incentivise players to use blueprints more.
Just a YAML change.
1. Set up an R&D server and computer, unlock stuff.
2. Print some blueprints: they should cost 3 sheets of paper each.
No.
**Changelog**
:cl:
- tweak: Blueprints now require only 3 sheets of paper. Go sell some cool tech!

Lower blueprint material cost

---

Resources/Maps/_NF/Shuttles/Nfsd/heimdall.yml

Adds a `BecomesStation` component to the newly merged Heimdall.
Breaks the map renderer. Missed in review.
.yml
1. Buy a Heimdall
2. VV the grid to make sure it has a BecomesStation component with the ID `Heimdall`
N/A
No.
**Changelog**
N/A, just a tiny, invisible hotfix on a ship that hasn't been rolled out yet.

Add BecomesStation component to Heimdall

---

Resources/Prototypes/Entities/Clothing/Back/backpacks.yml
Resources/Prototypes/Entities/Clothing/Back/duffel.yml
Resources/Prototypes/Entities/Clothing/Back/satchel.yml

Small edit to give 4 more blocks but allow storing of 4 4x4 items
Small QOL for the overall already nerfed (As it should) from upstream size
``0,0,7,7 # Frontier: Was 0,0,19,9``
Backup, open, add 4 guns.
AK47 FOR EVERYONE
N/A
**Changelog**
:cl:
- tweak: Slightly adjusted the backpacks of holdings to allow more storage

Change size for holding bags

---

Content.Shared/CCVar/CCVars.Interactions.cs

Since its not bugged anymore and were adding wallets its good to up the storage limit, right now set to 3 UI but can be upped to 5 also.
QOL the storage windows limits never effected the sweaty powergamers who quick swap like its a competitive sport to.
Edited ``control.storage_limit``
Start the game, put a backpack, put a belt, open them all with an extra survival box as well.
N/A
**Changelog**
:cl:
- tweak: Grid storage UI upped to 3 windows.

Update UI storage limits

---

Content.Server/Atmos/EntitySystems/AirFilterSystem.cs
Content.Server/Atmos/EntitySystems/AtmosphereSystem.API.cs
Content.Server/Atmos/EntitySystems/AtmosphereSystem.Utils.cs
Content.Server/Atmos/EntitySystems/AtmosphereSystem.cs
Content.Server/Atmos/Piping/Unary/EntitySystems/GasPassiveVentSystem.cs
Content.Server/Atmos/Piping/Unary/EntitySystems/GasVentPumpSystem.cs
Content.Server/Atmos/Piping/Unary/EntitySystems/GasVentScrubberSystem.cs
Content.Server/Atmos/Portable/PortableScrubberSystem.cs

Disables atmospheric devices entirely when not on the FTL or default map.
As an alternative, we could set the only gas mixture available on expeditions to none.
Fixes https://github.com/new-frontiers-14/frontier-station-14/issues/3110.
Adds a function to AtmosphereSystem.Utils to check that an atmos device can run on a particular map, replaces returning SpaceMixture when exposed to map atmos with failing to do anything on non-default maps.
1. Recreate procedure from #3110, shouldn't work.
2. Ride the bus, release ammonia while in FTL, it should siphon off even when in FTL.
Not this time.
**Changelog**
probably not

Disable atmospheric devices on expedition maps.

---

Content.Shared/_NF/Interaction/Systems/HandPlaceholderSystem.cs

changed order of enabling placeheld item so it doesnt try to swap into the aether or something
changed order of enabling the placeheld item to only after its held
no debug asserts threw depsite my best attempts so this will probably fix the random test fails too
standard interaction spamming and changing from e.g. bruise packs to sutures
also putting items in a container then clicking on them to take them out no longer triggers a debug assert
webedit ops :rocket: now from a branch because github didnt do it automatically for some reason
**Changelog**
i dont think treatment module on frontier has hands so no cl

fix borg hand exploit 2

---

Resources/Prototypes/_NF/Entities/Clothing/Belt/belts_crossbow_quiver.yml

Added missing tag in quiver whitelist, so shrapnel bolts now fit into bolt quivers.
Bolts go in bolt quiver.
1. Spawn `ClothingBeltQuiverCrossbow`
2. Spawn `CrossbowBoltShrapnel`
3. Put the bolt in the quiver
**Changelog**
:cl:
- fix: Shrapnel bolts now fit into bolt quivers.

Fix: Shrapnel bolts now fit into bolt quivers

---

Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Resources/Prototypes/Entities/Objects/Specific/rehydrateable.yml
Resources/Prototypes/_NF/Entities/Objects/Consumable/Food/egg.yml
Resources/Prototypes/_NF/Recipes/Cooking/meal_recipes.yml

Makes chickens and ducks eat on their own, turns any laid egg (fertilized or not) into bad food (so the chickens won't immediately turn around and eat it.
Replaces recipes with FoodEgg to use Egg reagent (6 per egg).
Ranch gaming.  Make sure to keep your chickens adequately contained.  Resolves #3079.
The RuminantCompound is the same as the MouseCompound, but I figured if they ever changed, it'd be safer to use the livestock version than the mouse one.
The egg change is needed because we're using new prototypes for laid eggs (and those wouldn't work with fertilized eggs either - breakfast balut bagel is real).
Note that chickens still don't get hungry very quickly, but if you feed them to the point they'll lay an egg, they'll lose 60 hunger and are likely to eat again.  There's a large …

Make chickens and ducks eat on their own.

---

Content.Shared/Lathe/SharedLatheSystem.cs

Changed *SharedLatheSystem.CanProduce* to use *FinalMaterialUseMultiplier* instead of *MaterialUseMultiplier*
So you can actually produce what you ought to, considering your discounts.
Changed *SharedLatheSystem.CanProduce* to use *FinalMaterialUseMultiplier* instead of *MaterialUseMultiplier*
- Upgrade a lathe
- Add materials to a lathe and open the UI
- Enter a quantity that you should be able to produce, including all discounts
- Check that you can in fact produce it.
**Changelog**
:cl:
- fix: Lathes, fabricators and ore processors should now allow you to make things respecting material discounts again.

made lathes respect final discount when calculating whether something can be produced

---

Resources/Prototypes/Entities/Structures/Windows/rplasma.yml

fixes diagonal reinforced plasma windows using normal diagonal plasma window sprites
ugly
**Changelog**
:cl:
- fix: Reinforced diagonal plasma windows use the correct sprite now.

Diagonal r-plasma window sprite fix

---

Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers_shipyard.yml

Disables the NFSD radio message regarding the purchase of pirate and syndicate ships
Actually has NFSD communicate with other players instead of just somehow knowing someone bought a pirate ship/syndie ship somehow
SecretShipyard tag is commented out
pop a syndie, NFSD, and freelancer key in your headset
buy a ship
notice only the syndie/freelancer radio gets notified of it
Rejoice that you can play the game easier?
🆑
- tweak: NFSD no longer get notified about the purchase of black market ships

No more hidden radio messages

---

Resources/Locale/en-US/_NF/materials/materials.ftl

Adds a small handful of missing material ftl defs.
N/A
N/A
Add mats to a Flatpacker. Check to see if the names appear.
N/A
N/A
**Changelog**
- add: Fixed localization on some materials (Brass included).

Missing material names.

---

Content.Server/Mech/Equipment/EntitySystems/MechGrabberSystem.cs
Content.Server/_NF/Mech/Equipment/EntitySystems.cs/MechForkSystem.cs

Removes people from crates when being picked up by mechs.  Should deposit them at the feet of the mech when they're picked up.
"Fixes" https://discord.com/channels/1123826877245694004/1360140435183505599.
The problem is caused by things escaping a box when the box is contained inside a container within the mech.  If we can stop that by preventing things from entering into the mech in the first place, that seems reasonable, so that's the approach taken here.
Applies a function (twice, once in the MechGrabberSystem, once in the MechForkSystem (yes, nasty), that checks all containers on the item being picked up, looks for entities with a present mind (present/non-ghosted[?] SSD players) or a ghost role (possible future players), and removes them from the container.
This still allows …

Remove player characters and ghost roles from containers picked up by mechs.

---

Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_base.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_expeditions_explorers.yml
Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_mercenaries.yml

Replaced `FoodMeatHuman` with `FoodMeatRotten` for human mobs on expeditions. Delish.
Never ending tax war to support food shuttles.
yml
1. Spawn exped PvE humanoid (punk/syndicate)
2. Kill, butcher on spike, collect your portion of rotten meat.
**Changelog**
:cl:
- tweak: Replaced FoodMeatHuman with FoodMeatRotten for human mobs on expeditions. Delish.

No edible meat from expedition human mobs

---

Resources/Prototypes/Entities/Structures/Furniture/chairs.yml

Allow pilot seat rotation while buckled, just like brass seat does.
Kind of makes sense to have increased mobility for the pilot's seat: should be able to rotate the seat to look through different cockpit windows while being buckled. RP, you see.
yml changes
1. Spawn pilot seat, buckle in, spin around.
**Changelog**
:cl:
- tweak: It is now possible to spin around while buckled in the pilot seat.

Allow pilot seat rotation while buckled

---

Content.Server/_NF/Power/Generator/FuelGradeAdapterComponent.cs
Content.Server/_NF/Power/Generator/FuelGradeAdapterSystem.cs
Resources/Prototypes/Entities/Structures/Power/Generation/portable_generator.yml
Resources/Prototypes/_NF/Entities/Structures/Power/Generation/portable_generator.yml

Allows generators to receive ore at a reduced efficiency compared to sheets (currently 0.5 fuel-grade material per ore).
Makes the Pioneer just a little bit friendlier for newbies.
The adapter now has a list of materials it will transform and a conversion rate.
1. Spawn PACMAN, SUPERPACMAN, DK, and DK JR generators.
2. Spawn plasma, fuel-grade plasma, and plasma ore.
3. Insert all three into the PACMAN.  Should insert without issue, check that the amount in the generator increased for each.
4. Repeat step 2-3 with uranium for the SUPERPACMAN, and bananium for the DK/DK JR generators.
Any forks with their own generators using the FuelGradeAdapterComponent will need to update to the new struct.
**Changelog**
:cl:
- add: Generators can now accept ore as fuel at reduced efficiency.

Allow generators to convert raw ore to fuel-grade material.

---

Resources/Prototypes/Entities/Structures/Power/Generation/Singularity/emitter.yml

Reparents the emitter, from `SmallConstructibleMachine` to `ConstructibleMachine`. This has the single effect of removing the `RequireProjectileTarget` component, which means projectiles, including the emitter bolt, can hit emitters without being explicitly targeted.
Unfortunately, people have discovered that they can make looooong rows of emitters, one behind the other, to fire off volleys of incredible destructive potential. This is distinctly uncool. It turns out it's the `RequireProjectileTarget` component that stops emitter bolts (and indeed other 'stray' projectiles) from hitting emitters. On upstream, this probably makes sense, as emitter sabotage is almost invariably round-ending and must be done deliberately. Here on Frontier, it leads to lame powergaming bullshit.
YAML change, …

Make bullets (including the emitter bolt) hit emitters

---

Resources/Maps/_NF/POI/trade.yml

Adds power to the Trade Outpost conference room.
⚡
Vent and scrubber not work. Power make work. Feel refresh.
Due to a hilarious bug around saving office chairs – that being that they _don't_ save at present – I had to manually edit the YAML. It should still work, I hope.
1. Go to the Trade Outpost
2. Behold the conference room
3. The vent does a thing. The scrubber does a thing. The fax machine does a thing.
These LV cables are new:
No.
**Changelog**
- fix: The Trade Outpost conference room has power cables under it now. The air vent and scrubber now work, hurrah!

Add power to Trade Outpost conference room

---

Resources/Prototypes/Entities/Objects/Tools/spray_painter.yml

Adds an "external" purple color for pipes to the Spray Painter. As seen with gaslocks.
As one of maybe 2 spray painter users in existence, non-replicable pipe colors irk me. This makes it so you can set up your own network in purple.
Single-line YML change
- Have pipe.
- Have spray painter.
- Paint pipe.
- ourple
**Changelog**
:cl:
- add: The spray painter can now color pipes purple.

ourple pipe

---

Content.Server/Cargo/Systems/PricingSystem.cs

Moved the logic from GetPriceConditional (a frontier specific function) into the main GetPrice logic.
So that ghosts and other calculations that terminate price calculations actually prevent their contents from also being appraised. In the previous implementation, it would still appraise the contents.
_GetPriceConditional_ removed
_GetPrice_ has had predicate logic added to it as an optional argument
- Spawn a pile of cash on a ship
- Check that the shipyard price doesn't include the pile of cash
- Check that the appraisegrid console command does include the pile of cash
- Aghost and pick up the pile of cash
- Check that the appraisegrid console command doesn't include you nor the value of the cash being held
It breaks things if upstream add an optional argument to getPrice that isn't …

Fixed a bug with GetPriceConditional not exiting early when a PriceCalculationEvent ends early due to being handled

---

Resources/Prototypes/_Goobstation/Entities/Objects/Vehicles/vehicles.yml

Comments out `PhysicalComposition` component for hover chair and wheel chair. A fix for [this issue](https://discord.com/channels/1123826877245694004/1366372491043405886/1366372491043405886).
Was funny. Was.
yml
1. Spawn hover and wheel chairs, spawn material reclaimer.
2. Seat in chairs, try to ram material reclaimer.
**Changelog**
:cl:
- tweak: Hover chair and wheel chair are no longer recyclable.

[Fix] Make chair-vehicles non-recyclable

---

Resources/Prototypes/_NF/Entities/Structures/Furniture/Armory/base_weapon_rack.yml
Resources/Prototypes/_NF/Entities/Structures/Furniture/Armory/weapon_racks.yml
Resources/Prototypes/_NF/Recipes/Construction/furniture_armory_construction.yml

This PR makes the following 2 changes:
1. The NFSD Weapon Racks (Pistol, Weapon, and Melee), are now locked to NFSD Access.
2. All wall-mount Weapon Rack variants now have a 175 degree wallmount access arc.
1. If the NFSD decides to store their weapons in the weapon racks that some ships have mapped, those should be secure.
2. If I put a weapon rack facing north on the bottom wall of my armory, I do not want somebody accessing it from outside that armory.
Just YAML changes, all within _NF directories.
Spawn them in and check the locks/arcs, spawn them on ships and rotate those ships, all works.
Not much to show, looks how you would expect it to.
**Changelog**
:cl: BramvanZijp
- add: Added a lock to NFSD Weapon, Pistol, and Melee racks.
- fix: Wallmount Weapon/Pistol/Melee racks are now …

Lock NFSD Weapon Racks, make Wallmount Weapon Racks Directional.

---

Content.Client/Input/ContentContexts.cs
Content.Client/Options/UI/Tabs/KeyRebindTab.xaml.cs
Content.Shared/Input/ContentKeyFunctions.cs
Content.Shared/Interaction/SmartEquipSystem.cs
Content.Shared/Storage/EntitySystems/SharedStorageSystem.cs
Resources/Locale/en-US/_NF/escape-menu/ui/options-menu.ftl
Resources/Locale/en-US/escape-menu/ui/options-menu.ftl
Resources/keybinds.yml

Allows user to set up keybinds for smart-equip to wallet and for open wallet. Keybinds are unbound by default.
QoL
khm
1. Go to Options/Controls and set your key binds for the actions.
2. Grab some money, use your keys.
**Changelog**
:cl:
- add: Adds an option for players to set up keybinds for smart-equip to wallet and for open wallet. Keybinds are unbound by default.

Add Smart-equip to wallet, open wallet

---

Resources/Prototypes/_NF/Catalog/Fills/StorageFillTemplates/stashes.yml
Resources/Prototypes/_NF/Entities/Objects/Misc/treasure.yml

Making sure that max fill volume of random tables for hidden stashes doesn't exceed the duffel volume.
Bug fix
yml
1. Spam spawn stashes.
not needed
**Changelog**
not needed

Fix the issue with overfilling hidden stashes

---

Content.Server/_NF/Roles/Systems/InterviewHologramSystem.cs
Content.Shared/_Goobstation/Vehicles/SharedVehicleSystem.cs
Content.Shared/_NF/Roles/Components/InterviewHologramComponent.cs
Content.Shared/_NF/Roles/Events/DismissInterviewEvent.cs

A touchup to the interview hologram system.
Adds admin logging, fixes mind roles, and creates a spawn complete event (for station records, traits, etc.)
Pork barrels a vehicle action bugfix that I missed.
Note: job acceptance log currently isn't showing up, unsure why (client-side action?).
Traits, mind roles: unintentional, oversight.  Fixes #3326.
Admin logging: admin sanity.
Added a Station field to the InterviewHologramComponent that's set on player spawning (lookup could be buggy if the player moved to space).
I'd like for the code path taken to be reduced, this copies more of GameTicker's spawn logic, but using the action is better than adjusting the station record.
1. Open two clients.
2. On the first client, spawn in, purchase a ship, take your ID out of the computer, and open a …

Interview holograms: admin logging, spawn event

---

Content.Client/Lobby/LobbyUIController.cs

Fixes the fallback in `GetPreferredJob()` to take missing job prototypes into account.
People's character UIs have stopped working after we renamed `PirateCaptain` to `NFPirateCaptain`.
The code still assumes `SharedGameTicker.FallbackOverflowJob` is a valid job prototype ID. If it isn't, we've got way more serious problems elsewhere.
1. Set a high-priority job on one of your character slots. Not Contractor.
2. Close server, rename that job prototype to something else.
3. Start server again. Your character should fall back to Contractor; the UI should not crash.
N/A
Sir, this is a fixing change, not a breaking change.
**Changelog**
:cl:
- fix: The lobby UI should once again load properly for all players.

Add a proper fallback for GetPreferredJob

---

Resources/Maps/_NF/Shuttles/Sr/duchess.yml
Resources/Maps/_NF/Shuttles/ceres.yml
Resources/Maps/_NF/Shuttles/gasbender.yml
Resources/Maps/_NF/Shuttles/kilderkin.yml

Title.
Adds BecomesStation components to the Duchess and Ceres, and fixes capitalization errors in Gasbender and Kilderkin.
Appease the MapRenderer.
6 lines of YML changes. Total.
- Run Content.MapRenderer on any of the four shuttles.
- Realize you forgot to tell Robust to ignore that it isn't technically a map, fix that.
- Try again.
- See it complete.
- Go view your render(s).
**Changelog**
Nah

Fix shuttles missing BecomesStation components

---

Content.Shared/_NF/Species/Components/GoblinComponent.cs
Resources/Prototypes/Entities/Objects/Consumable/Food/Containers/tin.yml
Resources/Prototypes/Entities/Objects/Consumable/Food/frozen.yml
Resources/Prototypes/Entities/Objects/Specific/Janitorial/trashbag.yml

- Added missing component to trash bags.
- Distributed goblin craft related component through more trash items.
Goblins now able to craft bags from trash bags and can utilize more trash items in crafting.
This pull request introduces a new `GoblinPreciousTrash` tag and a corresponding `GoblinPreciousTrashBag` component, updating several entity prototypes to include these additions. These changes enhance the goblin-related mechanics by categorizing specific items as "precious trash" for goblins.
* Added a new `GoblinPreciousTrashBagComponent` in `GoblinComponent.cs` to represent a specialized trash bag for goblins. (`[Content.Shared/_NF/Species/Components/GoblinComponent.csR17-R19](diffhunk://#diff-ab77990984df2f01f32a04d4fcb4b5f4a85f37e0cadb98180fdd852289a96520R17-R19)`)
* Introduced the …

Fix goblin recipes, allow using more trash for crafting

---

Resources/Prototypes/Roles/Jobs/departments.yml

This pull request introduces a small change to the `departments.yml` file. The change hides the `StationTrafficController` job from the editor by adding the `editorHidden: true` property.
It makes the list shorter to see and hide the 3 jobs that show up again anyway.
Open game lobby, look on loadout.
N/A
N/A
**Changelog**
N/A

Hide Command Department

---

Resources/Prototypes/_NF/Damage/modifier_sets.yml
Resources/ServerInfo/_NF/Guidebook/Mobs/Sheleg.xml

Changed 25% to 20% overall protection, added 5% more electric damage.
25% is a bit too much
This pull request updates the damage modifiers and guidebook descriptions for the Sheleg morphotype, ensuring consistency between the gameplay mechanics and documentation. The changes primarily involve adjustments to damage resistance and vulnerability values.
* Updated the Sheleg morphotype's damage resistance values for Blunt, Slash, and Piercing damage from 0.75 to 0.80 in `modifier_sets.yml`.
* Increased the Sheleg morphotype's vulnerability to Shock damage from 1.2 to 1.25 in `modifier_sets.yml`.
* Adjusted the Sheleg morphotype's description in `Guidebook/Mobs/Sheleg.xml` to reflect the updated resistance values, changing "25% less Blunt, Slash and Piercing damage" to "20% less Blunt, Slash …

Sheleg change damage modifiers

---

Content.Server/_DV/Weapons/Ranged/Systems/EnergyGunSystem.cs
Content.Shared/Weapons/Ranged/Systems/BatteryWeaponFireModesSystem.cs
Content.Shared/Wieldable/SharedWieldableSystem.cs

Ensures that wieldable energy guns with fire modes wield first, then toggle fire modes, and not both at the same time.
Annoying to use otherwise.
Uses the Handled field in the UseInHandEvent.
Swaps EnergyGunSystem to use UseInHandEvent for consistency with other gun systems (prevents using the fire mode toggle when not holding it)
1. Spawn energy submachine gun.
2. Pick it up.  Press Z, it should wield and not toggle fire modes.  Press Z, it should toggle fire modes (and break the visuals, this is expected, sadly)
3. Spawn laser carbine.
4. Pick it up.  Press Z, it should wield and not toggle fire modes.  Press Z, it should toggle fire modes.
**Changelog**
not sure the gun refactor has hit the live server, if not, no real point

Fix wield vs. fire mode ordering for energy guns

---

Resources/Prototypes/Entities/Objects/Devices/Circuitboards/Machine/production.yml
Resources/Prototypes/Entities/Objects/Devices/flatpack.yml
Resources/Prototypes/Entities/Structures/Machines/research.yml
Resources/Prototypes/Recipes/Lathes/Packs/science.yml
Resources/Prototypes/Research/experimental.yml
Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/flatpackvend.yml
Resources/Prototypes/_NF/Entities/Markers/Spawners/Random/dungeon_items_engineering.yml
Resources/Prototypes/_NF/Entities/Markers/Spawners/Random/dungeon_items_hydroponics.yml
Resources/Prototypes/_NF/Entities/Markers/Spawners/Random/dungeon_items_kitchen.yml
Resources/Prototypes/_NF/Entities/Markers/Spawners/Random/dungeon_items_medical.yml
Resources/Prototypes/_NF/Entities/Markers/Spawners/Random/dungeon_items_research.yml
Resources/Prototypes/_NF/Entities/Objects/Devices/flatpacks.yml
Resources/Prototypes/_NF/Recipes/Lathes/electronics.yml

- Commented out kitchen, chemical, medical, science, and engineering flatpack kits from expedition loot tables;
- Removed science consoles from flatpack vendomat;
- Removed salvage, engineering and service techfabs;
- Added artifact analyzer pad flatpack to vendomat;
- Added thrusters, gyros, generators, solar, freezer, heater and grounding rods to vendomat;
- Slightly rearranged order of items in flatpack vendomat.
- Added R&D computer board to Basic Xenoarch Research.
The problem with the wide availability of science kits stems from science being a superdepartment (which is a separate issue) that allows a player to obtain every machine and technology upgrade other departments have to offer, and the kit itself allows a player to bypass at least 2 intended game loops: seeking out …

Trim flatpack kits in loot tables and vendomats

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/chefvend.yml

Removes `contrabandInventory` from the ChefVend.
The contraband inventory includes ice cream sandwiches and donk pockets, and we don't want finished foods in the vending machine. It also contains a box of broken eggs, for some reason, which we don't want people wasting spesos on.
This does remove the only source of ice cream sandwiches, but oh well!
YAML, innit.
1. Get yourself a ChefVend
2. Cut the MNGR wire.
3. Behold, no extra stuff.
N/A
**Changelog**
:cl:
- fix: Ice cream sandwiches and donk pockets are no longer available in the ChefVend when hacked.

Remove contraband inventory from ChefVend

---

Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Battery/battery_pistols.yml

The title says it all, right? :)
This appears to have been missed in the mega gun rebalance PR. Upstream's advanced laser pistol recharges at 30 W, slower than the antique laser pistol's 40 W. Our rebalance antique laser pistol recharges at 30 W, so I made the advanced 20 W.
Without this change, it inherits from something else, which defaults it to a paaaaaainful 3 W.
YAML.
1. Spawn an advanced laser pistol
2. pew pew
3. Behold the less painful recharge rate.
N/A
No.
**Changelog**
N/A, it's a fix for something that hasn't even been deployed yet.

Increase auto-recharge rate for advanced laser pistol

---

Resources/Prototypes/Catalog/Fills/Lockers/suit_storage.yml
Resources/Prototypes/_NF/Catalog/pirate_uplink_catalog.yml
Resources/Prototypes/_NF/Recipes/Lathes/Packs/Deprecated/nfsd_techfab.yml
Resources/Prototypes/_NF/Recipes/Lathes/clothing-eva.yml

Swap the Pirate and Prisoners suits to frontier EVA
N/A
N/A
**Changelog**
:cl:
- tweak: Prisoner and pirate EVA suit lockers now contain Frontier EVA suits.

Update EVA Suits Lockers

---

Resources/Prototypes/_NF/Entities/Clothing/OuterClothing/softsuits.yml

Restored 5% speed penalty.
Unintended change
yml
1. Get an EVA suit, examine, note the speed penalty
**Changelog**
:cl:
- fix: Restore EVA softsuit 5% speed penalty.

Restore EVA softsuit 5% speed penalty

---

Resources/Maps/_NF/Shuttles/adder.yml

Replaced captain access-locked airlock with an airlock without an access lock.
Fix unintended hurdle
yml
1. Buy Adder, loose your ID, walk in the cockpit.
**Changelog**
:cl:
- tweak: Replaced captain access-locked airlock with an airlock without an access lock.

Fix Remove access lock on LVHI Adder captain airlock

---

Content.Server/Shuttles/Systems/DockingSystem.Shuttle.cs
Resources/Prototypes/Entities/Effects/shuttle.yml

Fixes two issues introduced in [wizden#35772](https://github.com/space-wizards/space-station-14/pull/35772)
1. CanDock returns a grid-relative angle, but GetDockingConfigs expects a world angle.
2. The FTL visualizer was marked as noRot, and would not be rotated.
@metalgearsloth, take the fixes if you want.
Fixes https://discord.com/channels/1123826877245694004/1376652511943065660
rotato
1. Join the game, aghost, move to Dock 5 really quickly to catch the initial docking.  The bus rotations should reflect where the bus actually arrives.
2. Warp to Medical Dispatch.
3. Mass purchase Stasises (Stases?)
4. No collisions or wonky docking.
**Changelog**
:cl:
- fix: Purchased ships should no longer collide with each other on docking.

Docking angle fix

---

Resources/Prototypes/_NF/Research/experimental.yml

Yeah so apparently RD hardsuits are getting removed from sci ships
Removes the armored hardsuits prerequisite from RD hardsuit research, making it less of a hassle to get
it's not that useful for combat, just for the explosive and heat damage (okay so maybe silicon combat)
Also it just was always a hassle to print more RD suits
Pressed shift 3 on two lines in experimental .yml
Open the guidebook, notice the rd tech no longer needs armored hardsuit
None?
**Changelog**
:cl:
- tweak: Research Director hardsuit research no longer needs armored hardsuit research.

not needing t2 sec for RD hardsuit

---

Resources/Locale/en-US/_EE/chat/chatstack.ftl

Remove the exclamation mark at the end of repeated messages.
At the tiny font size the stack thing is shown at, the exclamation mark is easily confused with the digit "1". It doesn't really add anything but noise.
.ftl
1. Repeat yourself. Repeatedly.
N/A
No.
**Changelog**
N/A, too small to mention

Remove trailing "!" in chatstack counter

---

Content.Shared/Station/SharedStationSpawningSystem.cs

Removes a Frontier code addition that duplicated name identifiers on spawn.
Bug.
IIRC the NameIdentifierSystem changed in the last one or two upstream merges, should've removed this then.  My mistake.
Removes a block of code that adds a name identifier to the entity's name proper.  When this was added, borgs would spawn without a specifier at all.  This has been resolved, so this is no longer needed.
Spawn as a borg with a custom name, check your name, one specifier.
Spawn as a borg with a default name, check your name, one specifier.
Take Pun Pun's ghost role, one specifier.
Expected output from test procedure:
**Changelog**
:cl:
- fix: Borgs now spawn with one numeric identifier, not two.

Fix duped name identifiers on spawn.

---

Resources/Maps/_NF/Dungeon/lava_brig.yml
Resources/Maps/_NF/Dungeon/lava_mercenary.yml

Should not be mapped on basic dungeon tilesets, remove the point of ever using them as NFSD if anyone can find them and just edit records with no effort.
N/A
**Changelog**
No

Replace criminal records computers with camera monitors on dengeon maps

---

Content.Client/Lobby/UI/HumanoidProfileEditor.xaml
Resources/Prototypes/_NF/Species/sheleg.yml

Based on this https://www.worldanvil.com/w/ostara-donnyprocs/a/jotunn-28giants29-article and general Nordic points about Jotunn.
And the idea from here https://github.com/space-wizards/space-station-14/pull/38467
Seems to fit, I was not aware it was that simple to fix the age for the race.
N/A
Open editor as Sheleg, up that age.
N/A
**Changelog**
:cl:
- tweak: Sheleg age changed, 80 and lower is young, 400 and lower is middle age and 800 and lower is old age.

Sheleg: Age parameters change

---

Content.Client/Shuttles/UI/MapScreen.xaml.cs
Content.Client/Shuttles/UI/NavScreen.xaml
Content.Client/Shuttles/UI/NavScreen.xaml.cs
Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml.cs
Content.Client/Shuttles/UI/ShuttleNavControl.xaml.cs
Content.Client/_NF/Shuttles/BUI/ShuttleConsoleBoundUserInterface.cs
Content.Client/_NF/Shuttles/UI/NavScreen.xaml.cs
Content.Client/_NF/Shuttles/UI/ShuttleConsoleWindow.xaml.cs
Content.Client/_NF/Shuttles/UI/ShuttleNavControl.xaml.cs
Content.Server/Shuttles/Components/ShuttleConsoleComponent.cs
Content.Server/Shuttles/Systems/RadarConsoleSystem.cs
Content.Server/Shuttles/Systems/ShuttleConsoleSystem.cs
Content.Server/_NF/Shuttles/Systems/ShuttleSystem.cs
Content.Shared/Shuttles/BUIStates/NavInterfaceState.cs
Content.Shared/Shuttles/Components/RadarConsoleComponent.cs
Content.Shared/_NF/Shuttles/Events/SetTrackedCoordinatesRequest.cs
Resources/Locale/en-US/_NF/shuttles/console.ftl

Adds settable map position controls (X/Y) to the nav screen, and a "track this" button beside each target on the map screen.
Custom positions are displayed as "Target" in the nav map, whereas entity targets show up as their respective name.  The colour of the control is currently a light green (open to suggestions)
The position _does not actively track the target entity_ (god, imagine the cheese), merely the position of it when the tracking was requested.
Quality of life.  Roughly in the "holy shit why isn't this a thing" category.
New events in the ShuttleConsoleBUI, new state in the RadarConsoleComponent (though currently not used by the radar console proper and not admeme-able since the Vector2 is nullable), and a new server-side setter in the RadarConsoleSystem to set these fields (to …

Shuttle Console: Shuttle, station, custom map targets

---

Content.Server/_NF/Cargo/Systems/NFCargoSystem.TradeCrates.cs
Content.Server/_NF/PublicTransit/PublicTransitSystem.cs
Resources/Locale/en-US/_NF/cargo/trade-crate.ftl
Resources/Locale/en-US/_NF/publictransit/bus-schedule-component.ftl
Resources/Prototypes/_NF/Entities/Structures/Specific/TradingCrates/crates.yml

Switches the bus schedules and trade crate deadlines to display using relative time (e.g. this happens 2 minutes from now) vs. (this happens at 03:14:15).
Both printouts are now grouped properly using disposable PushGroups, so they shouldn't be mangled in practice.
Minor quality of life, easier to parse.
Mostly just time checks.  Anything within a second is displayed as "arriving any minute now" or "due now", and trading crates also tell how long ago they were due on failure.  Note that buses do not - due to the FTL scheduling, the bus lingers for a few seconds before the next one is considered next to arrive.
A lot of the TotalSeconds checks are a bit dumb in practice, though it does work.
0. In Resources\Prototypes\_NF\Entities\Structures\Specific\TradingCrates\crates.yml, set …

Bus schedules and trade crates display time remaining, not absolute time

---

Content.Server/Doors/Electronics/Systems/DoorElectronicsSystem.cs
Resources/Prototypes/Entities/Objects/Devices/Electronics/door.yml

Outright removes the door electronics config UI.  If configuration is needed, use the access configurator, that works as normal.
Fixes https://github.com/new-frontiers-14/frontier-station-14/issues/3610.
Why remove it entirely?  Being able to set accesses that you don't have doesn't really make sense - the only other way to change accesses at the moment is with an access configurator, and those are far more restrictive with what and when you can change.  Lean into that, remove the multitool configuration.
Removes the UI entirely, removes the event handler for door electronics messages.
Use a multitool on door electronics.  Nothing happens.
Use an access configurator on door electronics.  Works as usual.
Not this time.
**Changelog**
:cl:
- remove: Door electronics can no longer be …

Remove door electronics config UI

---

Content.Shared/Weapons/Marker/SharedDamageMarkerSystem.cs

Adds a check to the LeechOnMarker flow which only applies the healing if the target is alive
Crushers would let any mob that doesn't delete its corpse on death or gib in a small number of whacks be enough of a source of healing that people can run through VGroids without any need for supplementary healing
Adds a check to the MobStateSystem in the OnMarkerAttacked handler to only heal if the target is alive.
1. Crusher marker hit a living mob, observe you get healed
2. Crusher marker hit a dead mob, observe you do not get healed
https://github.com/user-attachments/assets/4cab363c-6ee9-4db2-a83c-b8d01159e6a9
**Changelog**
:cl:Marlyn
- tweak: Crushers now only leech health from living targets

Crushers now only leech on living targets

---

Resources/Prototypes/Catalog/Cargo/cargo_cargo.yml
Resources/Prototypes/Catalog/Cargo/cargo_materials.yml
Resources/Prototypes/Catalog/Cargo/salvage_rewards.yml

Resolves https://ptb.discord.com/channels/1123826877245694004/1400852919221223526
Upstream items slipped in with the merge. Fixed the additional icons that appeared.
Pressed Control+ slash a couple of times
Load up a server and notice the lack of extra cargo mess
None I can notice, but if something breaks later down the line from this, oops
**Changelog**
:cl:
- fix: The Salvage crates (Crushers, Seismic Charge, Fulton) and Gold/Silver crates no longer appear in cargo order terminals

Extra Cargo Options fix

---

Resources/Prototypes/_NF/GameRules/roundstart.yml

Set `lateJoinAdditional` to `false` for all pirate roles.
The previous value, `true`, causes the game to randomly try and promote latejoin players to pirate. Seems like an innocent oversight. We most certainly don't want random Contractors to be randomly told they're a pirate now. The pirate role should only ever be selected explicitly.
YAML, my beloved.
Er. I don't know. Latejoin with loads of clients, make sure you don't get turned into a pirate? How does one prove a negative?
N/A
None.
**Changelog**
:cl:
- fix: Non-pirate latejoins should no longer randomly be turned into pirates.

Don't promote latejoin players to pirate

---

Content.Client/_NF/Chemistry/UI/ChangeReagentWhitelistWindow.xaml
Content.Client/_NF/Chemistry/UI/ChangeReagentWhitelistWindow.xaml.cs

Changes the filter UI for the service selective dropper to show in-game names for reagents instead of their internal ID.
Reported on Discord: https://discord.com/channels/1123826877245694004/1404533088431640636
Because players generally won't expect they need to filter for "EnergyDrink" when they want to remove Red Bool from a beaker.
Replaces all references to the reagent ID in the ChangeReagentWhitelist UI with `LocalizedName`. The change event emitted from the window passes a full prototype reference, so the rest of the code doesn't need to care what the UI shows.
Also widens the filter window a bit so the apply button doesn't look weird with long names.
- Spawn a service selective dropper. Open filter window. Observe that filter window shows "Red Bool" instead of "EnergyDrink" and …

Use localized reagent name in service selective dropper filter UI

---

Content.Server/Construction/ConstructionSystem.Computer.cs
Content.Server/Construction/ConstructionSystem.Machine.cs
Content.Server/_NF/BindToStation/BindToStationSystem.cs

This PR ensures that machines no longer get their external machine DRM state and internal board DRM state out of sync. This means:
- Flatpacks you unpack on a ship or station won't get their internal board DRM'd to that station
- DRM'd boards can't be flatpacked and then deconstructed to get a board whose DRM has been reset
I changed the pass in machine part population to only bind the board if the machine it was being generated for was already bound to a station. I also added a loop to the BindToStation method which recurses it onto any contained boards.
Bypassing machine station binding is bad, and non-DRM'd boards/machines "becoming" station-locked is a pain in the neck for players.
1. Crowbar a ship machine, observe the internal board retains the boundness of the external machine
2. …

Fixes DRM quirks

---

Resources/Prototypes/_NF/Research/techtree.yml

Removed Advanced mining borg module from Bluespace ore Storage in the research tree
There is already a advanced mining borg module research after bluespace ore bag bags it this seems unintended
Open game, open R&D computer, look at the research tree where bluespace ore bag is located, notice that it no longer unlocks advanced mining borg module
**Changelog**
:cl:
- remove: Removed Advanced Mining Cyborg Module from Bluespace Ore Bag research to not make the next research, Advanced Salvage Cyborg, useless

Removed cyborg module unlock from Bluespace Ore Storage research

---

Content.Client/Medical/CrewMonitoring/CrewMonitoringWindow.xaml.cs
Content.Server/Medical/SuitSensors/SuitSensorSystem.cs
Content.Shared/Medical/SuitSensor/SharedSuitSensor.cs

I added checks for the crew monitoring interface to only add blips to the map if the sensor reading came from the same Map. Buttons for coordinated people on other maps are disabled, but you can identify coordinatedness by the color of the circle next to the health indicator (green = coordinates)
It's very confusing and distracting to see a bunch of blips for people on FO while on an away mission, and likewise confusing to see blips for expeditioners while on FO. This both makes coordination on expeditions easier, as well as streamlines the process of rescuing injured crew.
Added another field to the suit sensor packets which contains a "map hash" - this map hash is compared with the map hash where the crew monitor is used, and will then only display blips on that same map.
Spawn a bunch …

Crew monitors now only show blips for the same Map/Surface

---

Resources/Prototypes/_NF/Roles/Jobs/Civilian/janitor.yml
Resources/Prototypes/_NF/Roles/Jobs/Civilian/valet.yml
Resources/Prototypes/_NF/Roles/Jobs/Frontier/security_guard.yml
Resources/Prototypes/_NF/Roles/Jobs/Frontier/stc.yml
Resources/Prototypes/_NF/Roles/Jobs/Nfsd/brigmedic.yml
Resources/Prototypes/_NF/Roles/Jobs/Nfsd/nfdetective.yml
Resources/Prototypes/_NF/Roles/Jobs/Service/mail_carrier.yml

A few jobs still had radio keys and cartridges in their bags. This fixes that.
QoL. Pairable with #3893.
YML changes.
- Join as job that previously had a key or cartridge in backpack.
- Most Frontier jobs were guilty of this.
- Look inside.
- No key/cartridge.
- Look at headset/PDA.
- Rejoice in saving a whole 10 seconds of your 4-hour shift to pre-installation QoL.
**Changelog**
:cl:
- fix: Jobs that did not auto-install encryption keys or PDA cartridges now do so

Auto-apply job-specific cartridges and channels

---

Resources/Prototypes/Entities/Objects/Devices/payload.yml

Cherrypicks [Wizden 38049](https://github.com/space-wizards/space-station-14/pull/38049) by @KamTheSythe 
Maintainer discussion regarding #3918 
The author removed the explode interaction when taking 25 damage from explosive paylooads.
stuff a toolbox full of exploding payloads and a single exploding grenade
watch how the explosion is around the size of a single grenade
One explosive grenade + 2 payloads was in that box
**Changelog**
:cl:
- tweak: Exploding payloads no longer chain off one another

remove explosions from destroying a explosive payload (#38049)

---

Resources/Prototypes/Entities/Objects/Weapons/Throwable/grenades.yml

Thanks for the assistance @arimah 
Modular grenades no longer trigger their effects on taking enough damage.
Maintainer discussion regarding #3918 and concerns of "Backpack explosives" like upstream has
Removed TriggerBehavior from mod.grenades
put two modular grenades next to each other
detonate one, notice how only one grenade's worth of explosion went off.
I couldn't see any, but sanity check's are always nice
**Changelog**
:cl:
- remove: Modular Grenades no longer activate their effects when taking enough damage.

Modular grenades require a full grenade to explode
