Content.Server/Cloning/CloningSystem.cs, Content.Shared/CCVar/CCVars.cs, Resources/Maps/frontier.yml, Resources/Prototypes/Entities/Structures/Power/apc.yml, Resources/Prototypes/_NF/Catalog/Fills/AstroVend.yml
cloning clones banks again and a few map tweaks, vending machine inventory revamp, 6 hour shift, etc.
=> Cloningmisc

Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactComponent.cs, Content.Server/_NF/GameRule/NfAdventureRuleSystem.cs, Content.Shared/CCVar/CCVars.cs, Resources/Prototypes/Atmospherics/gases.yml, Resources/Prototypes/Entities/Objects/Misc/space_cash.yml, Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml, Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml, Resources/Prototypes/GameRules/events.yml
pretty much the cl
:cl: checkraze
- add: NT Galactic Bank now posts shift earnings to Discord
- tweak: Economy balance for artifacts, gas cans, and fixed accesses
- fix: you cant sell money again
=> launch patch 2

Resources/Prototypes/Entities/Objects/Power/powercells.yml, Resources/Prototypes/Entities/Objects/Specific/Medical/healthanalyzer.yml, Resources/Prototypes/_Nyano/Entities/Mobs/Player/borgs.yml
Adds a new self-recharching power cell and uses it for the health analyzer that cyborgs have.
I'm having running the dev build locally, so I don't know if it works.
**Media**
**Changelog**
:cl: crazybrain
- fix: Medical cyborgs now have self-recharching health analyzers.
=> Medical cyborg health analyzer self-recharching

Content.Server/Shuttles/Components/ShuttleComponent.cs, Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs, Content.Server/Shuttles/Systems/ShuttleSystem.cs, Resources/Maps/cargodepot.yml, Resources/Maps/frontier.yml
Permits per-shuttle anchor values. Adds anchors to Frontier station and cargo depots.
**Media**
=> Add anchors

Content.Client/Players/PlayTimeTracking/JobRequirementsManager.cs, Content.Client/UserInterface/Systems/Ghost/GhostUIController.cs, Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs, Resources/Maps/frontier.yml, Resources/Prototypes/Atmospherics/gases.yml, Resources/Prototypes/Catalog/Cargo/cargo_livestock.yml, Resources/Prototypes/Catalog/Cargo/cargo_materials.yml, Resources/Prototypes/Catalog/VendingMachines/Inventories/medical.yml, Resources/Prototypes/Catalog/VendingMachines/Inventories/salvage.yml, Resources/Prototypes/Maps/frontier.yml, Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml, Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml, Resources/ServerInfo/Rules.txt
=> respawn_fix

Resources/Prototypes/Entities/Mobs/Player/arachnid.yml, Resources/Prototypes/Entities/Mobs/Player/diona.yml, Resources/Prototypes/Entities/Mobs/Player/dwarf.yml, Resources/Prototypes/Entities/Mobs/Player/human.yml, Resources/Prototypes/Entities/Mobs/Player/reptilian.yml, Resources/Prototypes/Entities/Mobs/Player/slime.yml, Resources/Prototypes/Entities/Mobs/Player/vox.yml
fixes mail so everyone can recieve it!
Mail is still barely touched in order to make it work here, so likely if you transfer ships/get added or removed from ship manifests or after a while the mail office might 'lose' your address.  Once a nyano re-base happpens we could probably change the base code to be more robust so it can handle us better.
=> Mail Fixes

Resources/Prototypes/Atmospherics/gases.yml
Balance tritium and frezon price.
**Media**
**Changelog**
:cl:
- tweak: Balanced tritium and frezon price
=> Balance a tritium and frezon price

Resources/Prototypes/_NF/Shipyard/default_shipyard_catalog.yml
they tuk r jerbs
until a proper manifest console can be made, just going to reduce and in some cases remove some job slots from ships for people on a few of the ships.
=> jobs balance

Resources/Maps/Shuttles/courserx.yml, Resources/Maps/Shuttles/dartx.yml, Resources/Maps/Shuttles/sparrow.yml
unlock the dart door, no more sparrow plasma, and uh warp point inthe courser
=> ship adjustments

Content.Server/Shipyard/Systems/ShipyardSystem.Consoles.cs, Content.Server/_NF/Bank/ATMSystem.cs, Content.Server/_NF/Bank/StationATMSystem.cs, Content.Shared.Database/LogType.cs
Adds admin logs for the ATM, shipyard and station bank account. Doesn't log additions to the station bank account, as I'm not sure how to handle those
**Media**
**Changelog**
:cl:
No CL no fun
=> Add admin logs

Content.Shared/Cargo/Components/SharedCargoTelepadComponent.cs
telepad speed boost for faster cargo
=> telepad_speed

Content.Server/VendingMachines/VendingMachineSystem.cs, Content.Server/_NF/GameRule/NfAdventureRuleSystem.cs, Resources/Maps/tinnia.yml, Resources/Prototypes/Entities/Objects/Specific/Service/vending_machine_restock.yml
=> Tinnia's Rest

Resources/Maps/tinnia.yml
adds some more solar to tinnia to make it  much more forgiving. also adds fax machine and a few fun little goodies.
=> tinnia_update

Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs
**Media**
**Changelog**
:cl:
- fix: Fixed possible null reference.
=> Fixed possible null reference

Content.Server/_NF/Bank/StationATMSystem.cs, Content.Server/_NF/GameRule/NfAdventureRuleSystem.cs, Resources/Locale/en-US/_NF/adventure/adventure.ftl
discord relay re-write. not the greatest sort but it will do since we have to trim to top/bottom anyway. need to later exclude incorrect placements during odd midpop rounds etc.
=> Discord Relay Re-Write

Resources/Maps/Shuttles/condor.yml, Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
**Media**
**Changelog**
:cl:
- remove: Removed hand teleporter from condor shuttle
=> Removed hand teleporter from condor shuttle

Resources/Prototypes/Entities/Clothing/Hands/colored.yml
Changed Insulated Gloves prices in a way that makes more sense
Why are normal insulated gloves cheaper than budget ones? ($75 for normal gloves, $150 for budget)
Well, I have no idea, that's why I suggest changing them a bit, and also increase price for regular insulated gloves a bit, as all of those get bought instantly after new shift starts.
**Media**
Old prices:
New prices:
**Changelog**
:cl:
- fix: Rebalanced 'budget insulated gloves' and 'insulated gloves' prices
=> Set insulated gloves prices that make more sense

.vscode/tasks.json, Resources/Prototypes/Entities/Objects/Consumable/Food/Containers/bowl.yml, Resources/Prototypes/Entities/Objects/Consumable/Food/Containers/plate.yml, Resources/Prototypes/Entities/Objects/Consumable/Food/Containers/tin.yml, Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml, Resources/Prototypes/Entities/Objects/Devices/radio.yml, Resources/Prototypes/Entities/Objects/Fun/bike_horn.yml, Resources/Prototypes/Entities/Objects/Misc/books.yml, Resources/Prototypes/Entities/Objects/Misc/broken_bottle.yml, Resources/Prototypes/Entities/Objects/Misc/fluff_lights.yml, Resources/Prototypes/Entities/Objects/Misc/handcuffs.yml, Resources/Prototypes/Entities/Objects/Misc/paper.yml, Resources/Prototypes/Entities/Objects/Shields/shields.yml, Resources/Prototypes/Entities/Objects/Specific/Medical/hypospray.yml, Resources/Prototypes/Entities/Objects/Tools/flare.yml, Resources/Prototypes/Entities/Objects/Tools/gps.yml, Resources/Prototypes/Entities/Objects/Tools/lighters.yml, Resources/Prototypes/Entities/Objects/Tools/matches.yml, Resources/Prototypes/Entities/Structures/Furniture/potted_plants.yml, Resources/Prototypes/Entities/Structures/Machines/Computers/frame.yml, Resources/Prototypes/Entities/Structures/Machines/fax_machine.yml, Resources/Prototypes/Entities/Structures/Piping/Disposal/pipes.yml, Resources/Prototypes/Entities/Structures/Storage/paper_bin.yml, Resources/Prototypes/Entities/Structures/Wallmounts/Signs/posters.yml, Resources/Prototypes/_Nyano/Entities/Objects/Books/hyperlinks.yml
All kinds of trash have a price now, which allows to sell it instead of messing up cargo platform every time
Janitors now have a reason to check pipes exit from time to time, to pick up the junk and come sell it
Most bowls, plates, broken things, matches, lighters, flares, paper (and bin), books, tin cans, medipens, gps, handheld radio, and even fax machine can be sold now!
This should partially prevent cargo becoming a mess and add some reason to pick up random trash during salvage
Trash is also made out of materials, after all!
**Media**
**Changelog**
:cl:
- fix: Most trash can be sold now
=> Trash and some stuff prices implemented

Resources/Maps/lpbravo.yml
adds grav and removes the comms console because we cant have nice things.  the machines are supposed to be perma anchored dont know why they arent goign to investigate that one
=> lpb_touchup

Content.Shared/Salvage/Expeditions/Modifiers/SalvageTimeMod.cs, Resources/Prototypes/Procedural/salvage_mods.yml, Resources/Prototypes/Procedural/salvage_rewards.yml
re-balanced the expeditions from upstream and re-added some goodies. its the frontier live a little.
=> salvage_buff

Resources/Maps/Shuttles/carrier.yml, Resources/Maps/Shuttles/fighter.yml, Resources/Prototypes/Roles/Jobs/Security/brigmedic.yml, Resources/Prototypes/Roles/Jobs/departments.yml, Resources/Prototypes/Roles/play_time_trackers.yml, Resources/Prototypes/_NF/Shipyard/carrier.yml, Resources/Prototypes/_NF/Shipyard/default_shipyard_catalog.yml, Resources/Prototypes/_NF/Shipyard/fighter.yml, Resources/migration.yml
Adds 2 new security vessels, primarily the largest one being the Carrier, large battle cruiser with armory, medbay, a very long range sonar, its very big and difficult to maneuver, that is why it will have the very small ships Fighter attached to its side for arrests boarding and chasing pirates.
**Media**
**Changelog**
:cl:
- add: Securistan has developed 2 new flagship vessels, Carrier and Fighter
=> New security vessels

Content.Server/Parallax/BiomeSystem.cs, Content.Shared/Parallax/Biomes/Layers/BiomeMetaLayer.cs, Content.Shared/Parallax/Biomes/SharedBiomeSystem.cs, Resources/Prototypes/Procedural/biome_templates.yml
guh expeditions such pain hopefully they get in a stable position and I dont have to just disable them
=> salvage_revert_again

Content.Server/Cargo/Systems/CargoSystem.Orders.cs, Content.Server/VendingMachines/VendingMachineSystem.cs
=> buff station income

Resources/Maps/Shuttles/carrier.yml, Resources/Prototypes/_NF/Shipyard/carrier.yml
Update carrier to fix some issues, removed the the blukie suit for the HOS one, added brigmed hardsuit, added sink, changed renault for shiva (sorry arachnophobes), added health analizers and the crew monitor server.
no need for changelog.
=> Couple of changes to the carrier

Content.Server/Cargo/Systems/CargoSystem.Shuttle.cs
**Media**
Alive:
Dead:
**Changelog**
:cl:
- fix: Fixed mob corpses being unsellable
=> Fixed mob corpses being unsellable

Resources/Maps/Shuttles/anchor.yml, Resources/Prototypes/_NF/Shipyard/anchor.yml
Switch to hydroponics instead of the freezer since no Nyano rotting for food right now, removed chaplain clothing area and replaced with a tiny pool/jacuzzi, added a few more drip items, fixed warp point, fixed cryogenic co2 filtering, fixed sink placements, just a lot of QoL stuff based on community feedback - also raised the price because the total for the vessel increased with these changes
:cl:
- tweak: Altered the Anchor based on community feedback.
=> Anchor Update #3

Resources/Maps/Shuttles/sprinter.yml, Resources/Prototypes/_NF/Shipyard/sprinter.yml
This introduces a light freighter often picked by bounty hunters due to its quick acceleration and exceptional cargo space for the measly price of 66,028 spesos. This ship, due to its size and cost, firmly lands itself in the medium class, but size doesn't stop this ship from moving freight at exceptional speeds across the sector.
:cl:
- add: Added the Sprinter, a bounty hunter's delight.
=> sprinter.yml

Resources/Maps/Shuttles/anchor.yml, Resources/Maps/Shuttles/sprinter.yml
Fixes issues with the sprinter and anchor, the anchor just getting a cell recharger and the sprinter getting tiny fans in the correct locations as well as a cell recharger and warp location rename.
:cl:
- tweak: Changed Sprinter and Anchor to both include cell rechargers, and fixed some issues with the Sprinter.
=> kesiath hangar hotfix

Resources/Maps/Shuttles/marauder.yml, Resources/Prototypes/_NF/Shipyard/marauder.yml
Introduces the Marauder, a heavy corvette, which is a dedicated deep space patrol vessel outfitted with stealth armor and heavily fortified against pirate assault.
**Media**
:cl: Kesiath
- add: Added the Marauder, a security Heavy Corvette.
=> Marauder intro

Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Security space suits are still slower then other suits but not super slow anymore.
=> Buffed security suits speed  to not be shit.

Resources/Maps/Shuttles/marauder.yml
Leander Inc updated the camera network of the Kes Co security ship marauder up to industry safety and protocol specifications.
no need for CL
=> Update marauder cameras

Resources/Prototypes/Maps/frontier.yml
updates the stations jobs to reflect the new changes.
=> station_jobs_update

Resources/Maps/Shuttles/esquire.yml
minor fixes
**Media**
**Changelog**
- fix: some stuff
=> esquire fixes

Resources/Prototypes/Catalog/Fills/Crates/botany.yml, Resources/Prototypes/Catalog/Fills/Crates/chemistry.yml, Resources/Prototypes/Catalog/Fills/Crates/circuitboards.yml, Resources/Prototypes/Catalog/Fills/Crates/emergency.yml, Resources/Prototypes/Catalog/Fills/Crates/engineering.yml, Resources/Prototypes/Catalog/Fills/Crates/engines.yml, Resources/Prototypes/Catalog/Fills/Crates/medical.yml, Resources/Prototypes/Catalog/Fills/Crates/science.yml
Changed the locked crates to be unlocked, there is no point in having people beating up crates they got just to get the items.
=> No more locked

Resources/Maps/Shuttles/anchor.yml, Resources/Maps/Shuttles/barge.yml, Resources/Maps/Shuttles/cleric.yml, Resources/Maps/Shuttles/condor.yml, Resources/Maps/Shuttles/construct.yml, Resources/Maps/Shuttles/courserx.yml, Resources/Maps/Shuttles/dartx.yml, Resources/Maps/Shuttles/empress.yml, Resources/Maps/Shuttles/enforcer.yml, Resources/Maps/Shuttles/esquire.yml, Resources/Maps/Shuttles/fighter.yml, Resources/Maps/Shuttles/helix.yml, Resources/Maps/Shuttles/honker.yml, Resources/Maps/Shuttles/interceptor.yml, Resources/Maps/Shuttles/mail.yml, Resources/Maps/Shuttles/marauder.yml, Resources/Maps/Shuttles/prospector.yml, Resources/Maps/Shuttles/prowler.yml, Resources/Maps/Shuttles/pts.yml, Resources/Maps/Shuttles/pulse.yml, Resources/Maps/Shuttles/rogue.yml, Resources/Maps/Shuttles/skipper.yml, Resources/Maps/Shuttles/sparrow.yml, Resources/Maps/Shuttles/sprinter.yml, Resources/Maps/Shuttles/trident.yml
Update all ships with new faxes and warp points (see #149 and #135). 
**Media**
**Changelog**
:cl:
=> Ship faxes and ship warp points

Resources/Prototypes/Entities/Mobs/NPCs/carp.yml, Resources/Prototypes/Entities/Mobs/NPCs/space.yml, Resources/Prototypes/Entities/Mobs/NPCs/spacetick.yml
Removed Brain Cells from salvage mobs
=> Removed Brain Cells from salvage mobs

Resources/Maps/Shuttles/anchor.yml, Resources/Maps/Shuttles/pathfinder.yml, Resources/Maps/Shuttles/sprinter.yml, Resources/Prototypes/_NF/Shipyard/anchor.yml, Resources/Prototypes/_NF/Shipyard/marauder.yml, Resources/Prototypes/_NF/Shipyard/pathfinder.yml, Resources/Prototypes/_NF/Shipyard/prowler.yml, Resources/Prototypes/_NF/Shipyard/sprinter.yml
Introduces the Pathfinder, a small decommissioned military vessel capable of expeditions. Additionally, this PR includes Sprinter fixes and the new crewing system for the Anchor.
**Media**
**Changelog**
:cl: Kesiath
- add: Added the Pathfinder, a small expedition capable vessel.
- tweak: Balanced the Sprinter further based on community feedback.
- tweak: Changed Anchor crew settings and added the new console system for picking crew.
=> Pathfinder & More

Resources/Maps/Shuttles/anchor.yml, Resources/Maps/Shuttles/pathfinder.yml, Resources/Maps/Shuttles/sprinter.yml
forgor some stuff
:cl: Kesiath
- fix: Fixed Pathfinder gravity issues and lack of windows.
=> pathfinder hotfix

Resources/Prototypes/_NF/lobbyscreens.yml, Resources/Prototypes/lobbyscreens.yml, Resources/Textures/_NF/LobbyScreens/attributuions.yml, Resources/Textures/_NF/LobbyScreens/risingred.png.yml
Added risingred Lobby Art for issue #167
**Media**
**Changelog**
:cl:
- add: New Lobby Art - risingred
=> Added risingred Lobby Art for #167

Content.Server/VendingMachines/VendingMachineSystem.cs
Fix the multi charge if you spam the buy options
And also the random vend.
=> Vend fix multi charge

Content.Server/Salvage/SalvageSystem.Expeditions.cs, Resources/Prototypes/Catalog/Fills/Crates/food.yml, Resources/Prototypes/GameRules/cargo_gifts.yml
They are getting fixes upstream that we will get soon plus it doesnt really work in our format without a rework plus its causing some silliness i think so yea, basically just yml disabled for now
=> Temporary disable of cargo gifts

Resources/Prototypes/Catalog/Fills/Crates/vending.yml, Resources/Prototypes/_NF/Catalog/Fills/Crates/vending.yml, Resources/Prototypes/_NF/Entities/Structures/Storage/Crates/crates.yml, Resources/Prototypes/_NF/Recipes/Crafting/Graphs/storage/crateplasticbiodegradable.yml
They are so cheap to make and build, you wont give you more then 1 plastic back when your screwdriver them!
:cl:
- tweak: NT budget cuts, all restock crates only give 1 plastic back .
=> Biodegradable Plastic Crates

Resources/Prototypes/Atmospherics/gases.yml
Miasma was worth too much for stink air, too easy to mass farm without crazy effort for what it is.
=> Updating the gasses prices yet again

Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/heavy_rifle.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/magnum.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Revolvers/revolvers.yml
=> Fix cost for revolvers

Content.Server/StationEvents/Components/BluespaceErrorRuleComponent.cs, Content.Server/StationEvents/Events/BluespaceErrorRule.cs, Resources/Locale/en-US/_NF/bluespace-events/events.ftl, Resources/Maps/Bluespace/vault.yml, Resources/Prototypes/_NF/Events/events.yml
Adds our first mid-round event (including the generic system to add many more similar type events).
The event works like this: All players are alerted to a custom message (our first one is that a 'vault has miscalculated FTL). Then, a custom grid, be it a shuttle, poi, custom salvage wreck, whatever mapped set piece you desire, similar to a salvage wreck (saved as a single grid please and thanks) gets warped in the nearby.  The event has optional paramaters, to start, the Reward Factor for instance is multiplied to the value of the object before it is deleted and removed from the round.
In this fashion, our first event, the Vault. It holds around 400k of valuable goods inside, including some rare goodies, but getting into the vault will not be an easy task.  You will have between 17-23 …
=> Bluespace FTL Error

Resources/Maps/Shuttles/crescent.yml
Adds a door to the bar, fixes a cable issue with one of the thrusters and an APC, adds a multitool to cloning, and removes the counters from the stage area.
=> quick crescent microfix

Resources/Prototypes/Entities/Objects/Weapons/Melee/baseball_bat.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/mining.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/pickaxe.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/spear.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/sword.yml
Allows more Melee weapons to be stored on the back and/or suit storage slot, as frontier has more combat than most servers and quick access to/a backup melee weapon would be much appreciated. I only made this change to "large" weapons that one would be likely to store on a back sling were they do have them in real life.
I made this change due to frustrations trying to keep a fireaxe with me on expeds, as you must sacrifice your vital backpack slot if you would like to free your hands from the axe. 
**Media**
**Changelog**
:cl: terezi4real
- tweak: Tweaked Many Melee Weapons to allow storage in back/suit storage slot.
=> Melee weapons on back/suit storage slot

Resources/Prototypes/Entities/Structures/hydro_tray.yml, Resources/Prototypes/_NF/Entities/Structures/hydro_tray.yml
Hydroponics are now machinelayer so you bump into them.
Added climbable so you can still walk over them.
=> Hydroponics MachineLayer

Resources/Prototypes/Entities/Structures/Shuttles/thrusters.yml, Resources/Prototypes/_NF/Entities/Structures/Shuttles/thrusters.yml
Thruster are now "BulletImpassable"
=> Thruster-BulletImpassable

Content.Shared/CCVar/CCVars.cs
=> Disable Artifact EORG

Resources/Maps/Shuttles/anchor.yml, Resources/Maps/Shuttles/empress.yml, Resources/Maps/Shuttles/marauder.yml, Resources/Maps/Shuttles/skipper.yml, Resources/Maps/tinnia.yml
gives the various shuttles and POI the new thrusters gyros and hydro trays
**Media**
**Changelog**
:cl:
checkraze
- tweak: Changed shuttles and POIs to use the new thrusters gyros and hydro trays
=> shuttle_updates_august

Resources/Prototypes/_NF/Entities/Structures/Power/apc.yml
Added protection to command APC
:cl: dvir01
- add: Command APC protections
=> APC-Change

Resources/Maps/Bluespace/vaultsmall.yml, Resources/Prototypes/_NF/Events/events.yml
Adds a smaller variant of the bluespace vault event.  It can trigger with a fewer amount of players, is easier to get in to, holds less loot, and stays around for only 9-12 minutes.
**Media**
**Changelog**
:cl:
checkraze
- add: added the small variant of the bluespace vault event
=> Small Vault

Resources/Maps/Shuttles/pheonix.yml, Resources/Prototypes/_NF/Shipyard/default_shipyard_catalog.yml, Resources/Prototypes/_NF/Shipyard/pheonix.yml
Introducing the NR Pheonix class deep space research vessel.  This NR series ship breaks the trend and reserves it's engineering and manufacturing capabilities for a salvage yard and cargo dock, making this the premier research vessel for floating xenoarcheological finds.
Also updates the existing sci ship offerings.  The Condor is now expedition-able (though does not have the console yet, pending a rework... you'll have to outfit it to exped yourself.)  The condor will eventually be made into a MK. II model that is more specialized for gas mining, while keeping the side research chamber.
**Media**
**Changelog**
:cl:
- add: Added the NR Pheonix research and salvage shuttle
- tweak: NR Condor may now embark on expeditions
=> NR Pheonix: Research, Salvage, and Robotics Shuttle

Content.Client/Nyanotrasen/Mail/MailSystem.cs
fixes the job icons on mail
:cl:
- fix: Fixed mail job icons
=> Mail Job Icon Fix

Resources/Maps/Shuttles/helix.yml, Resources/Maps/Shuttles/pulse.yml
what it says on the tin
:cl:
- fix: Fixed Helix and Pulse!
=> Fix Helix and Pulse

Content.Server/Procedural/DungeonJob.cs
This should get rid of the demon tiles for now. I did some quick testing, and it seemed to not have any adverse side effects. Should at least get rid of them while a proper fix is found.
**Changelog**
:cl:
- fix: Stop demon tiles from spawning
=> Hotfix demon tiles

Content.Server/StationEvents/Components/BluespaceErrorRuleComponent.cs, Content.Server/StationEvents/Events/BluespaceErrorRule.cs, Resources/Locale/en-US/_NF/bluespace-events/events.ftl, Resources/Maps/Bluespace/cache.yml, Resources/Prototypes/_NF/Events/events.yml
Reworks the bluespace event a bit to allow for multiple of them to happen at once, along with introducing the Syndicate Weapons Cache bluespace event.
**Media**
<details>
<summary>Spoiler warning</summary>
</details>
**Changelog**
:cl:
- add: NT has started using the Bluespace FTL error in your sector to intercept Syndicate vessels.
=> syndie cache

Resources/Prototypes/Catalog/Fills/Lockers/heads.yml, Resources/Prototypes/Catalog/Fills/Lockers/security.yml
=> Lockers update 2

Resources/Prototypes/Entities/Objects/Devices/encryption_keys.yml
i am the dumb - typing words at 3 am increases the issue
=> fix nfsd encryption key

Content.Server/Anomaly/AnomalySystem.Generator.cs, Resources/Prototypes/Entities/Structures/Machines/anomaly_equipment.yml
The anomaly generator will only spawn the anomaly on the same ship its on.
:cl: dvir01
- fix: The anomaly generator will only spawn the anomaly on the same ship its on.
=> Anomaly system

Resources/Maps/Shuttles/anchor.yml, Resources/Prototypes/_NF/Shipyard/anchor.yml
:cl: Kesiath
- fix: Fixes the issue where the Anchor does not spawn.
=> Anchor Fix

Content.Server/Research/Systems/ResearchSystem.Client.cs, Content.Server/Research/Systems/ResearchSystem.cs
Makes RnD servers only available to lathes/machines on the same station/vessel
**Media**
**Changelog**
:cl:
checkraze
- tweak: Changed RnD servers to only connect with machines on the same grid.
=> exclusive_servers

Resources/Prototypes/Catalog/Cargo/cargo_materials.yml
People will just buy 100 of crates to idle print them in Frontier into coats.
:cl: dvir01
- tweak: Textiles crate 1000<2000
=> TextilesBalance

Resources/Prototypes/Entities/Structures/Machines/wireless_surveillance_camera.yml
temporary mute camera mics until I can better limit their ranges
:cl:
- remove: Removed microphones from entertainment cameras temporarily until their range can be properly reduced to prevent spam.
=> Mute Camera Microphones

Resources/Prototypes/Catalog/Cargo/cargo_livestock.yml
=> cargo_livestock.yml

Resources/Prototypes/_NF/Shipyard/esquire.yml
Fix esquire ship price, no need for changelog. thanks to the players that reported it.
=> Fix esquire price

Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/magnum.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/shotgun.yml
Booo hoooo powergamers will not longer be able to double tap and cuff someone completely incapacitating them in 0.5 seconds. :^( 
:cl:
- tweak: bye bye shotgun beanbag double tap
=> nerf beanbags

Content.Server/_NF/Commands/GhostRespawnCommand.cs
small fix to respawn
its still desyncing, mind doesnt always init a time of death so we still have to get creative
**Changelog**
=> Respawn hot fix

Content.Server/Ame/EntitySystems/AmeControllerSystem.cs
AME is now much quieter
BONK
bonk
**Changelog**
:cl:
checkraze
- tweak: AME controllers now have noise-cancelling shielding to help curb space madness
=> AME Muffle

Resources/Prototypes/Entities/World/Debris/asteroids.yml, Resources/Prototypes/World/Biomes/basic.yml
Beefs up asteroid spawning
encourage more asteroid mining
**Changelog**
:cl: checkraze
- tweak: Asteroids are now much larger and richer
=> Boost Asteroids

Resources/Prototypes/Catalog/Cargo/cargo_engines.yml
We honestly dont need easy ways to make singulos all around.
no need for CL
=> remove PA from cargo

Resources/Prototypes/_NF/Catalog/Cargo/cargo_livestock.yml, Resources/Prototypes/_NF/Catalog/Fills/Crates/npc.yml, Resources/Prototypes/_NF/Entities/Markers/Spawners/Random/cargo.yml, Resources/Prototypes/_NF/Entities/Mobs/NPCs/emotionalsupportanimals.yml, Resources/Prototypes/_NF/Entities/Mobs/NPCs/pets.yml, Resources/Prototypes/_NF/Entities/Spawners/mobs.yml
Very Emotional, fix.
The issue was with the "combatToggleAction" rework
=> Emotional Fix

Resources/Prototypes/Entities/Clothing/Back/backpacks.yml, Resources/Prototypes/Entities/Clothing/Belt/belts.yml, Resources/Prototypes/Entities/Clothing/OuterClothing/vests.yml
Names fix
Fix
.yml changes
None
**Changelog**
no need
=> NamesUpdates

Resources/Maps/Bluespace/asteroidbunker.yml
Balances things up to make it not a nightmare:
Removed Kuzu and replaced it with a more easy to handle Meatzu (dies to space), Removed Syndicate IFF Console, Syndicate Shuttle Console and Uplink and 1 TC.
Added sniper briefcase, Centercom disguise/pAI, hypospray in CMO Locker, ect...
Replace all Xenomorph (except the one in armory) with acolyte aliens spawners and Meatzu will take a more slow time to spread.
Kudzu was annoying and loot was pehaps too good.
**Changelog**
=> asteroidbunker.yml hotfixes

Resources/Prototypes/Catalog/Cargo/cargo_service.yml
Reduces price of theatrical crate. 
i spend 1800 a shift on a clown mask.
**Changelog**
:cl:
- tweak: A new NT Artistic Grant has lowered the barrier of entry for Theatrical Performances on the frontier
=> Reduces Price of Theatrical Crate

Content.Server/Nyanotrasen/Mail/MailSystem.cs, Resources/Locale/en-US/_Nyano/mail.ftl, Resources/Prototypes/_Nyano/Entities/Objects/Specific/Mail/base_mail.yml
The mail has the recipient name on it
Same as Delta V, simple to sort
.yml changes to grab the name from .ftl
C# To insert the name there
https://discord.com/channels/1123826877245694004/1157760235709136897/1157829515574247546
None
**Changelog**
:cl: dvir01
- tweak: NT Added bigger name fonts on the mail, now you can see names from far away!
=> Mail Easy Sort

Content.Server/Salvage/SalvageSystem.ExpeditionConsole.cs, Content.Shared/Salvage/Expeditions/SalvageExpeditions.cs
Adding error to the FTL warning
Hard to tell without it.
C#
None
**Changelog**
No need
=> FTL Error Sound

Resources/Prototypes/_NF/Entities/Structures/Machines/vending_machines.yml
Fixes spam the ArcadiaDrobe may generate in a debug run.
https://discord.com/channels/1123826877245694004/1123851369913266256/1158090750395957248 
Discord chat where it was recommended and how to fix it. 
no player facing changes
no cl no fun
=> Fix Arcadia Drobe debug issues

Resources/Prototypes/Entities/Objects/Specific/Hydroponics/tools.yml
PlantBag got the same magnet as OreBag
Why not
.yml changes
https://discord.com/channels/1123826877245694004/1127687656084611214/1158179342841565205
None
**Changelog**
:cl: dvir01
- add: Plant bag equipped on your belt will now auto pickup items from the floor.
=> PlantBag Magnet

Resources/Locale/en-US/_NF/bluespace-events/events.ftl, Resources/Maps/Bluespace/cargoniaship.yml, Resources/Prototypes/_NF/Events/events.yml
FOR CARGONIA!
This even add 2 news things, first a new bluespace event that can last 15min to 20min, this event spawns a failed cargonia ship that has a lot of random cargo loot and not a lot of enemies, a good first for those who want some nice starting loot... or supplies! just scavange the ship for goods and your set!
Its also add a sorta-new category for events (at least language wise) so if we add more events that are not asteroids but unknown ships (broken or fully working ships), we could use the same annoncement lines.
Rip Cargonia... finders keepers on the loot!
Loot is randomly generator but is still worth a look, 20k in it and random cargo loot/materials.
Add a new map file and edit the bluespaceevent file and language file.
**Changelog**
:cl: FoxxoTrystan/MatthewBadger
- add: …
=> CargoniaFailedShip Bluespace Event

Resources/Prototypes/Catalog/Fills/Lockers/heads.yml, Resources/Prototypes/Catalog/VendingMachines/Inventories/cart.yml, Resources/Prototypes/Entities/Objects/Misc/paper.yml, Resources/Prototypes/Entities/Objects/Tools/hand_labeler.yml, Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml, Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
Give SR CentCom Headset to allow RP talking with admins instead of aHelp in the case its needed.
Added the red phone to his locker for the same goal.
Giving the sheriff a command headset since its the first thing they take from the locker anyway, also if they cryo with its is lost to the next sheriff, so best if they spawn with it.
Added few more items to the PTech machine for SR
Make the SR more central command based, give the Sheriff the command headset as spawn item.
The phone and headset allows talking with admins without aHelp for less critical stuff, none rule breaking related.
.yml changes
None
**Changelog**
:cl: dvir01
- tweak: NT improved the SR and Sheriff gear.
- tweak: NT added more goods for the Ptech vend for SR.
=> Heads Changes

Resources/Maps/Shuttles/infiltrator.yml, Resources/Prototypes/_NF/Shipyard/infiltrator.yml
Greetings and the Syndicate is now selling this outated Infiltrator, this ship was used by nukies in the past ya know?
This PR add the "Infiltrator" as a Black Market Ship (Class-3), this is a medium size ship that is specialized as operations for operatives, tho now outated its is now a ship for the Black Market, this ship is equipped with an AME Engine (2 Cores), Working atmos, 2 SMES, 1 Medical, 1 Cell, Blastdoors, ect...
If this ship design is famillar its because its nearly the same ship design as the Nukie ship from SS13 TG Station.
More Black Markets ships, more fun!
Ship Name: Infiltrator
Ship Class: Medium (332 Tiles)
Ship Contraband Class: Class-3
Ship Price: 64000
Ship Purpose: "An outated Syndicate Nuclear Operative infiltration ship, expedition capable."
Ship Equipment: 1 …
=> Infiltrator Ship

Resources/Prototypes/Entities/Structures/Machines/anomaly_equipment.yml
Unlock the A.P.E. to everyone
I FORGOR
.yml change
N/A
**Changelog**
:cl: dvir01
- tweak: The A.P.E. Lock fixed!
=> anomaly_equipment.yml

Resources/Maps/Shuttles/hunter.yml
Add the hunter.yml file the missing BecomesStation component.
Its is missing and so some features is not working due to it.
changes hunter.yml file.
**Changelog**
=> hunter.yml missing BecomesStation component

Resources/Prototypes/Roles/Jobs/Security/security_officer.yml, Resources/Prototypes/Roles/Jobs/Security/senior_officer.yml, Resources/Prototypes/_Nyano/Roles/Jobs/Security/prisonguard.yml
Split from the other Bodycam update, just to add the missing ones
Missing
.yml changes
N/A
**Changelog**
N/A
=> BodyCam Starting Gear

Content.Server/Silicons/Borgs/BorgSystem.cs, Resources/Prototypes/Roles/Jobs/Science/borg.yml
About time.
Borgs dont need AA
C#
N/A
**Changelog**
No need
=> Remove Borgs AA

Resources/Locale/en-US/_NF/adventure/adventure.ftl, Resources/Prototypes/_Nyano/Entities/Objects/Books/hyperlinks.yml
Changes the in-game references to the proper Frontier Space Law page.
spesslaw
just replaces some links
**Changelog**
:cl:
- tweak: In-game references to Space Law now point to the correct page.
=> Update in-game references to Space Law

Resources/Maps/Shuttles/svtide.yml, Resources/Prototypes/_NF/Shipyard/svtide.yml
A new low-cost shuttle, the Salvaged(SV)-Tide, for when the construct gets too bland.
Costs 9150, has no tiny fans or gravity generator 
pre-init appraisegrid:
post-init appraisegrid: 
**Changelog**
=> SV-tide salvage shuttle

Resources/Prototypes/Catalog/VendingMachines/Inventories/salvage.yml, Resources/Prototypes/Entities/Objects/Tools/fulton.yml, Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Removed Fulton till we can re balance it in some way, if at all.
Abused
.yml changes
None
**Changelog**
:cl: dvir01
- tweak: Fultons? whats that?
=> Remove Fultons (For now?)

Resources/Prototypes/Catalog/Cargo/cargo_cargo.yml, Resources/Prototypes/Entities/Objects/Specific/Cargo/cargo_pallet.yml
Cargo pallets cannot be moved or destroyed, cannot be removed from floors.
Stop abuse.
.yml changes
N/A
**Changelog**
N/A
=> Cargo Pallets Fix

Resources/Maps/Shuttles/svorange.yml, Resources/Prototypes/_NF/Shipyard/svorange.yml
adds the SV-Orange, a cheap cargo / salvage shuttle
partly destroyed, no tiny fans on salvage airlocks, 16k cost w/ 14k appraisal
**Changelog**
=> sv orange cargo/salvage shuttle

Resources/Locale/en-US/_NF/prototypes/catalog/fills/crates/vending-crates.ftl, Resources/Prototypes/Catalog/Cargo/cargo_vending.yml, Resources/Prototypes/Catalog/Fills/Crates/vending.yml
=> Restock fix

Resources/Prototypes/Catalog/Cargo/cargo_atmospherics.yml, Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
Some minor bug fixes from the merge
fix
merge artifacts
**Changelog**
:cl:
- remove: Removed liquid co2 canisters from cargo
- fix: Fixed SR accesses
=> Merge Fixes

Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
Coats price adjusted 80<30 
Update the coats price to stop printing spam abuse.
.yml changes
N/A
**Changelog**
N/A
=> Coats Price Fix

Resources/Maps/Shuttles/prowler.yml, Resources/Prototypes/_NF/Shipyard/prowler.yml
Completely overhauled the Prowler to fit its mission-set to a greater degree, and fixing the horrific shuttle console issue where the center was far below the ship.
I felt the Prowler is not good enough with its current layout, and it was among my least favorite designs. The armory is consistent with the Marauder, although a bit less extensive, and all armor is patrol suits instead of full armored suits.
**Changelog**
:cl:
- tweak: Remastered the Prowler.
=> Prowler Remaster

Resources/Prototypes/Entities/Objects/Specific/Research/anomaly.yml
Upstream added a long range version, so im fixing the change we made.
Fix
.yml changes
N/A
**Changelog**
:cl: dvir01
- tweak: Anomaly locator range is back to 20, new anomaly locator wide version is up to 2000.
=> Anomaly locator

Resources/Maps/Shuttles/svnugget.yml, Resources/Prototypes/_NF/Shipyard/svnugget.yml, Resources/Prototypes/_NF/Shipyard/svorange.yml
Adds the SV-Nugget, a cheap kitchen shuttle. Also the final shuttle in the line of the SV-Class.
Also fixes a naming issue with the SV-Orange
costs 12250 with a 9k appraisal, no gravity generator.
**Changelog**
=> SV-Nugget kitchen shuttle

Resources/Prototypes/Catalog/VendingMachines/Inventories/cart.yml
MORE
MORE MORE MORE
MORE CLIPBOARDS
N/A
**Changelog**
N/A
=> MORE CLIPBOARDS

Resources/Prototypes/_Nyano/Entities/Mobs/NPCs/dogs.yml
DONT HIT THE PITBULL
OH GOD YOU ARE GOING TO DIE
RUN
Every single bone in your body, if you survive.
**Changelog**
Nope
=> Pitbull Angry

Content.Server/_NF/GameRule/NfAdventureRuleSystem.cs
Shuffles the POI to spread them out a tad and make room for the new POIs
More POI More Gooder, need more spess in spess etc.
none
**Changelog**
=> POI Shuffle

Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml, Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml, Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/satchel.yml, Resources/Prototypes/Catalog/Fills/Lockers/heads.yml, Resources/Prototypes/Entities/Clothing/Belt/base_clothingbelt.yml, Resources/Prototypes/Roles/Jobs/Command/captain.yml, Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml, Resources/Prototypes/_NF/Entities/Clothing/Belt/belts.yml
Fixed SR AA again.
Moved SR and Sheriff items to bags from lockers to allow multi SR and Sheriff to use some basic gear (And not loss it to someone cryo)
Removed stuff from the old cap role to not have it used by mistake.
Fixed all belts type that were 40 to 45 to match with the toolbelt.
Basic logic.
.yml changes
N/A
**Changelog**
:cl: dvir01
- tweak: Most belts adjusted storage 40<45 
- tweak: Basic SR and Sheriff locker items moved to backpacks.
=> Balance changes.

Resources/Maps/courthouse.yml
...i forgor
**Changelog**
:cl:
- fix: Fixed missing courthouse tiny fans.
=> Courthouse Hotfix

Content.Client/Shuttles/UI/RadarControl.cs
IFF signatures outside the UI will now rotate about the center, rather than pile on the sides and corners.
Better directional indication.
Lines 274 - 285.
Added code that finds the radar UI center, offsets the radar UI center to (0,0) for calculation, calculates the IFF UI distance from said center, then finds where the IFF UI would end up. The new IFF UI coordinates are then compared to the original to determine whether the IFF UI is outside the radar's UI, which it then applies if so, offsetting the IFF UI back to the correct location, centered around the visual center.
None
**Changelog**
:cl: McBosserson
- tweak: Central sent out a UI update to all radars in the sector.
https://github.com/new-frontiers-14/frontier-station-14/assets/148172569/dda4d015-4454-49fd-82b8-905d29aa68dd
=> IFF signatures no longer pile up in the corners.

Content.Server/GameTicking/GameTicker.Player.cs
quick in and out adventure
its not great  but it works :TM:
**Changelog**
=> Whitelist Hotfix

Content.Server/GameTicking/GameTicker.Player.cs
Not me putting the whitelist thing in the wrong place. You saw nothing >.>
=> Fix whitelist data check

Content.Server/_NF/GameRule/NfAdventureRuleSystem.cs
shuffled around the POI spawning again after feedback
brought the more functional POI a bit closer, pushed the fluff POI and depots out a bit further instead
some more overlap in the mid-range right now, needs some more fine-tuning still
**Changelog**
:cl:
- tweak: Changed spawning layout of the points of interest.
=> Another POI Shuffle

Content.Server/Botany/Systems/MutationSystem.cs, Content.Server/Shipyard/Systems/ShipyardSystem.Consoles.cs, Resources/Prototypes/GameRules/events.yml
Helps sell ships
SSD Alive players will block the sale still, along with SSD players of objects.
**Changelog**
:cl:
- fix: Shipyards are less strict about who it considers viable crew members
=> Make Organics Check Stricter

Resources/Maps/Bluespace/asteroidbunker.yml
Fix AsteroidBunker because peaches broke it... thanks upstream.
Fixes it.
Edit asteroidbunker.yml
**Changelog**
:cl: FoxxoTrystan
- fix: Fix AsteroidBunker breaking due to peaches.
=> Fix asteroidbunker.yml

Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers.yml
Small fix to make it invincible
=> ShipyardExpedition

Resources/Maps/Shuttles/empress.yml, Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
shortens range on the OP shuttle console
**Changelog**
:cl:
- tweak: Changed the Empress's console to not be so huge, in order to combat server lag
=> Shorten world loader range

Content.Server/Shipyard/Systems/ShipyardSystem.Consoles.cs
Fixes ship station records not updating properly if funny things :tm: happened with your ID card or existing station records.
RP and such
Station Records is a complete mess. Its implemented to be tied to an entity (id cards) and to have a component on an ID card act as a 'key' that corresponds to a specific station's record DB.  While well documented, its very clear that the system was not built to be robust in the slightest, and the downfalls of the system may never be realized upstream. And then a good number of systems are built upon this flimsy house of cards. This is still just a patch over fix.  Future attempts to change records should probably start with a re-working of the existing records system, which is no small feat.
**Changelog**
:cl:
- fix: Fixed Record Consoles sometimes …
=> Station Records fix

Resources/Textures/Structures/Machines/techfab.rsi/meta.json, Resources/Textures/_NF/Structures/Machines/shredder.rsi/meta.json
=> Fix Missing RSI

Resources/Maps/Shuttles/bulker.yml, Resources/Prototypes/_NF/Shipyard/bulker.yml
This is the fixed version of my KL Bulker ship. 
- SMES wasn't connected to the main powergrid, therefore I had to change It.
- The price of the ship is now correct (+15% after the mapinit appraise)
—
—
**Changelog**
:cl:
- add: Kosmologistika note was added on the shuttle console. 
- tweak: Price was changed
- fix: Powergrid was changed for the better.
=> Adds NC Bulker vessel (FIXED)

Resources/Maps/Shuttles/liquidator.yml, Resources/Prototypes/_NF/Shipyard/liquidator.yml
A small ship (175 tiles) equipped with everything one might need to make even the dirtiest ship squeaky clean (ducky slippers included). Notable features:
- Wide array of janitorial supplies, a drain, a sink, and material/biomass recyclers;
- Small chemlab for cases when janitor needs to clean potassium spills;
- Small scale atmo setup for cleaning and replacing atmosphere in a ship if needed;
- Hull shape resembles Light Replacer tool (yet not entirely devoid of function);
- Galoshes!
According to my unsystematic observations that I absolutely can not back with statistics, by the mid-shift ships tend to become rather untidy (especially science oriented vessels) and sometimes it goes so far that air in them becomes barely breathable. Given that as of right now there are no dedicated …
=> New Ship Design: NT Liquidator - Dedicated Janitorial Vessel

Content.Shared/Singularity/Components/ContainmentFieldGeneratorComponent.cs
-Up from 8f up to 16f.
My ship needs it to work correctly, so, I decided to go ahead and change it, since I don't think there's anything else anywhere right now explicitly using these, and it might prove useful later.
This is primarily for my ship that I'm PRing but I think this change is good for frontier shipbuilding anyways.
Simple integer change.
**Changelog**
:cl:
- tweak: Containment Field Generators now search up to 16 tiles away, compared to 8 from before.
=> Improves containment field generator distance

Resources/Prototypes/Entities/Objects/Vehicles/buckleable.yml, Resources/Prototypes/Recipes/Lathes/devices.yml
too easy to spam create some things
**Changelog**
:cl:
- tweak: C.H.I.M.P. handcannons now require Bananium to craft.
- tweak: Wheelchairs market has crashed! They are now worth far less.
=> Market Balance Tweaks

Content.Server/Labels/Label/HandLabelerSystem.cs, Content.Server/Labels/Label/LabelSystem.cs, Content.Server/Nyanotrasen/Item/PseudoItem/PseudoItemSystem.cs, Resources/Locale/en-US/_Nyano/pseudoitem-component.ftl, Resources/Prototypes/DeltaV/tags.yml
Makes felinids (and other psuedo-items) unable to be labeled through strange means
Not intended and allows players to bypass naming rules. Also all I saw was cringe when people did it.
**Changelog**
:cl:
- fix: Fixed psuedo-items being able to have labels applied.
=> Felinid Labeler Fix

Resources/Maps/Shuttles/bazaar.yml, Resources/Prototypes/_NF/Shipyard/bazaar.yml
Added the SLI Bazaar, a personal service vessel designed to provide a platform for merchants to sell their goods, it features two locking cargo docks, a spacious cargo hold, and a mercenary post for shop security.
Missing a dedicated merchant vessel
:cl:
- add: Added SLI Bazaar
=> Adds the SLI Bazaar, a personal shop ship designed for mercantilism 

Resources/Maps/Shuttles/legman.yml, Resources/Prototypes/_NF/Shipyard/legman.yml
Compact, fast, and reliable (most likely) micro shuttle (63 tiles) with low operational costs for reporters who want to be first on a scene. Ideal for journalists with a tight budget - the shuttle price is only 12499 spesos.
- It's hard to make money working as a reporter, so a low price tag with the low operational cost of this shuttle can make the reporter role more attractive.
- Micro shuttle. The more the merrier. Maybe?
**Changelog**
:cl:
- add: NT Legman - a maneuverable microshuttle with low operational costs for reporters who want to be first on a scene.
=> NT Legman: A Microshuttle for Reporters

Resources/Maps/Shuttles/loader.yml, Resources/Prototypes/_NF/Shipyard/loader.yml
=> Fix Loader

Resources/Prototypes/Catalog/Cargo/cargo_service.yml
Remove this crate from cargo, it only exists to be abused.
ID in microwave go MMMMMMMMMMMMM
Access to doors goes up. 
.yml
N/A
**Changelog**
N/A
=> Remove CrateServicePersonnel

Resources/Prototypes/Entities/Objects/Specific/Medical/handheld_crew_monitor.yml
Removed the range test from the Handheld Crew Monitor to fix it
Bug, now its working fine
.yml
N/A
**Changelog**
N/A
=> HandheldCrewMonitor-Fix

Resources/Maps/Shuttles/liquidator.yml
Small changes to the atmos setup on the ship, preflight checklist.
- The previous atmos setup wasn't suitable for its secondary purpose as I envisioned it (secondary purpose - refill air canisters), so I altered the setup slightly in this update.
- The ship has a somewhat high power demand that can be fulfilled by overloading the standard P.A.C.K.M.A.N. unit. The concern here is that newer players might not be aware of how to properly set generator parameters to meet the ship's power demand. To address this issue I added a document, "preflight checklist", that hopefully will guide new ship owners through flight prep.
**Changelog**
- add: NT Liquidator: preflight checklist paper.
- tweak: NT Liquidator: reworked atmospherics setup.
=> NT Liquidator: Minor Update 2

Resources/Prototypes/Catalog/Fills/Lockers/heads.yml, Resources/Prototypes/Catalog/Fills/Lockers/security.yml, Resources/Prototypes/Catalog/VendingMachines/Inventories/sec.yml, Resources/Prototypes/Catalog/VendingMachines/Inventories/secdrobe.yml, Resources/Prototypes/Roles/Jobs/Security/detective.yml, Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml, Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml, Resources/Prototypes/Roles/Jobs/Security/security_officer.yml, Resources/Prototypes/Roles/Jobs/Security/senior_officer.yml, Resources/Prototypes/Roles/Jobs/Security/warden.yml, Resources/Prototypes/_NF/Catalog/Fills/Lockers/security.yml, Resources/Prototypes/_Nyano/Roles/Jobs/Security/prisonguard.yml
Updated lockers, vends and starting gear for security to remove bloat.
Less lockers entity, more items in lockers.
.yml
N/A
**Changelog**
N/A
=> Security Lockers Trim

Resources/Prototypes/_NF/Recipes/Crafting/Cooking/moth_recipes.yml
Oopsies Cotton Pizza uses cloth instead of cotton and the other has unobtainable food to make.
Fixes it.
Changed .yml files.
**Changelog**
=> Fixes moth_recipes.yml

Resources/Prototypes/Entities/Objects/Tools/spray_painter.yml, Resources/Prototypes/Entities/Objects/Tools/tools.yml, Resources/Prototypes/Entities/Objects/Tools/welders.yml
Re-balance the tools prices to avoid printing abuse
Worth less to mass print.
.yml
N/A
**Changelog**
N/A
=> Tools Price Fixing

Resources/Prototypes/_Nyano/Entities/Mobs/Species/felinid.yml
PseudoItem in the Felinds .yml file was commented, this is now fixed.
They can now go back in bags.
During the specie update this system was broken and during multiple tests i have turn it on and off, but then Divir fixed it and i forgot about it.
.yml changes.
**Changelog**
🆑 FoxxoTrystan
- fix: Felinds can now fit back in bags! (normal size ones!)
=> Uncomment PseudoItem for Felinds.

Resources/Prototypes/Research/arsenal.yml
By many request and my opinion also i agree we should remove the taser in research, a one hit stun gun with a lot of charges is EXTREMLY OP when you can build a lot of them, its should be limited only to rewards like Asteroids events, ect...
That why in a lot of servers taser got replaced by disablers.
Read above.
.yml changes.
**Changelog**
:cl: FoxxoTrystan
- remove: Tasers are no longer able to be researched.
=> Remove Taser From Research

Resources/Prototypes/Maps/frontier.yml
Give SR the option to open psychologists jobs.
SR Mental care
.yml
N/A
N/A
**Changelog**
:cl: dvir01
- tweak: Psychologists jobs added to frontier outpost.
=> Psychologist Job For Frontier

Resources/Prototypes/Catalog/Fills/Crates/armory.yml
Replaced the Enforcer for the Krammer on the Expedition reward shotgun crates.
Krammer < Enforcer
Krammer should be able to be gotten by Expedition instead of the Enforcer, where the Enforcer should be mostly kept by Security by default. (same kinda at the WT550)
.yml changes.
**Changelog**
:cl: FoxxoTrystan
- tweak: We just found out that Shotgun Crates has Krammers instead of Enforcers.
=> Shotgun Crate Krammer

Resources/Prototypes/Catalog/VendingMachines/Inventories/ammo.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
Added 1 viper to the Liberation Station when you emag it
Cost 10k
MK58 but faster and syndicate.
.yml
N/A
**Changelog**
N/A
=> Liberation Station Emag

Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml, Resources/Prototypes/_NF/Entities/Structures/atms.yml
Fixing up Sheriff AA level
Going to use the extra SR card anyway, might as well skip it.
.yml
N/A
Need to just remove ``HeadOfPersonnel`` access later.
**Changelog**
N/A
=> Sheriff Perms

Resources/Maps/Shuttles/decadedove.yml, Resources/Prototypes/_NF/Shipyard/decadedove.yml
Changed the layout of the Dove a bit:
- decreased the size of the engine room
- removed stairs
- replaced rear ramp with docking airlocks
- added 2 airlocks to the front of the ship
- added buttons to bolt airlocks selectively
- changed layout of the rear rooms
- added the CargoDrobe and EngiDrobe
- replaced all decals
- replaced regular windows with shuttle windows, added more windows
To accommodate for the changes, the Dove now costs 75000 (up from 70000).
In the current iteration of the Dove, getting from one side of the ship to the other is a bit of a hassle, mostly due to the massive engine room at its core. This becomes more apparent when dragging something, because there are quite a lot of corners to get past. This rework aims to make using the ship more convenient than before.
The …
=> Minor Dove rework

Resources/Prototypes/_Nyano/Entities/Objects/Consumable/Food/ration.yml
Eat snack, empty wrapper bigger then snack.
How?
.yml
N/A
N/A
**Changelog**
N/A
=> PSB Wrapper fix

Resources/Locale/en-US/prototypes/catalog/fills/crates/vending-crates.ftl, Resources/Prototypes/Catalog/Cargo/cargo_vending.yml, Resources/Prototypes/Catalog/Fills/Crates/vending.yml
Fixed all the restocks FTL numbers errors
Updated the clothes restock to actually be 8 boxes. 
QOL
.yml
N/A
N/A
**Changelog**
N/A
=> Restocks FTL

Content.Server/_NF/Smuggling/DeadDropSystem.cs
Security was too powergamy with the hints so they get less info in their hint now.  Also adds an admin log now that we know more about how everything runs.
hints too strong, had to nerf
i also added some comments in the code in case anyone wanted to read
**Changelog**
:cl:
- tweak: Security eavesdropping has been curtailed, smuggler drops will reveal less info to security.
=> Smuggling Changes

Resources/Maps/Shuttles/wasp.yml, Resources/Prototypes/_NF/Shipyard/wasp.yml
Adding the wasp expedition shuttle, capable of going planetside and keep up to 4 prisoners in extended confinement, can be used as a prison ship or you can FLT with it to a planet to make the prisoners earn some money while arrested if they are willing to.
NFSD needed an expedition ship, this is the large version
Perma is designed very lackluster as a way for prisoners to entertain themselves building it however they please that's why also the hydroponics there are the unwrenchable version, it requires constant monitoring of the officers over the prisoners to go and do expeditions and to make sure they dont have unwanted objects on their cells, plus it requires of the officers to supply the prisoners with the gear and open the doors to the expedition
Price will be 145,700
:cl: Leander
- …
=> Wasp expedition shuttle

Resources/Maps/Shuttles/dragonfly.yml
changes the dragonfly's warp point
=> Dragonfly Warp Point

Content.Server/Worldgen/Components/Debris/DebrisFeaturePlacerControllerComponent.cs, Resources/Prototypes/Entities/World/Debris/asteroids.yml, Resources/Prototypes/World/Biomes/basic.yml
lowered asteroid and wreck density and made some changes to the proc gen to try to combat entity spam and lag
=> Wolrd Gen Tweaks

Resources/Maps/Shuttles/garden.yml, Resources/Prototypes/_NF/Shipyard/garden.yml
I added the Garden, a small-sized botany ship with sequestered grow bays and a full horticulture setup. Designed for the green thumbs amongst us.
**Changelog**
:cl:
- add: Added the Garden, a small botany vessel.
=> The Garden - A small botany ship

Resources/Prototypes/Catalog/VendingMachines/Inventories/condiments.yml, Resources/Prototypes/Entities/Objects/Consumable/Food/Containers/condiments.yml
Added more condiments to the condiments stand
More sauce
.yml
N/A
N/A
**Changelog**
:cl: dvir01
- tweak: Added more condiments to the condiments stand
=> More Sauce Please

Resources/Maps/Shuttles/opportunity.yml, Resources/Prototypes/_NF/Shipyard/opportunity.yml
Introducing the "Opportunity" prison expedition ship. A medium ship for the New Frontier Sheriff's Department. 
It holds up to 4 prisoners and can accommodate a warden and several prison guards (probably 3-4 would suffice). 
Ship costs 70000 spesos and is only available at a security shipyard console.
The ship runs off of one uranium generator which should be set to 50 at all times.
The ship comes equipped with:
- Exterior blast door access for guards to release prisoners to the planet surface from their cells.
- Prisoner EVA suits for hostile planetary environments.
- Warden and 3 secoff suit lockers
- Warden locker
- Gun locker with a Kammerer and ammo, and body bags
- A non-lethal crate
- A uranium crate
- 4 ore crates for prisoner ore storage
- 4 pickaxes and 4 orebags
- Prison guard …
=> Adds the "Opportunity" prison expedition ship.

Resources/Maps/frontier.yml
Changelist for Sheriff/Bailiff box (primary role-play value: NFSD administration and command):
- Removed 1 mass scanner (1 -> 0)
- Removed 1 criminal records console (1 -> 0)
- Added 1 ID card computer (0 -> 1)
- Added 1 station administration console (0 -> 1)
Changelist for general NFSD brig area (primary role-play value: brig management):
- Removed 1 security shipyard console (1 -> 0)
- Added 1 criminal records console (0 -> 1)
- Added 1 wallmount ATM on the southeast wall of the box, primarily for payroll deposits, but could also be used for roleplaying paying off bail amounts (0 -> 1)
Changelist for NFSD reception (primary role-play value: talking to people needing services from NFSD, this does not entirely hit the mark, I know):
- Removed 1 station administration console (1 -> 0)
- …
=> Frontier NFSD QoL

Content.Server/DeltaV/Nutrition/Events.cs, Content.Server/Nutrition/EntitySystems/SliceableFoodSystem.cs, Content.Server/Nyanotrasen/Kitchen/EntitySystems/DeepFryerSystem.cs
This update is to match DeltaV code base
Fixing small issues on it from 3 pr's
N/A
N/A
Tested in game, didnt find issues.
``private EntityUid Slice(EntityUid uid, EntityUid user, SliceableFoodComponent? comp = null, TransformComponent? transform = null)``
Need to be set to public when we code merge later
``//using Robust.Shared.Audio.Systems;`` need to be used ones we use new sound system.
**Changelog**
N/A
=> 2023 12 22 deep fryer fixes

Resources/Maps/frontier.yml
- Add shipyard console in maints, below the disposals chute, pending addition of special "trash" shipyard ( @dvir001 )
- Materials reclaimer on top of the disposals chute
- Drain below disposals
- NFSD has a PTech now, pending removal of SR access from Sheriff's ID cards ( @dvir001 )
- Add disposal units to cargo and mail area
- Connect a couple of other disposal units
- Add atmos devices (vents/scrubbers) to the area between ATM's and engineering
- Fix mapping war crimes in the area between ATM's and engineering (wire under walls, pipes under walls, ...)
- Fix biomass at frontier outpost (now 300, was 103)
- Remove crematorium in light of new cryosleeping system
- Probably something else I forgot... I was doing all these changes in a call with @dvir001 and the ball just kept rolling. …
=> Frontier Outpost more things

Resources/Prototypes/_Nyano/Entities/Structures/Machines/deep_fryer.yml
Added cash and id to deepfry blacklist
Keep them safe.
.yml
N/A
N/A
**Changelog**
N/A
=> Deep Fryer blacklist update

Resources/Maps/Shuttles/opportunity.yml, Resources/Maps/Shuttles/wasp.yml, Resources/Prototypes/Roles/Jobs/departments.yml, Resources/Prototypes/_NF/Shipyard/opportunity.yml, Resources/Prototypes/_NF/Shipyard/wasp.yml, Resources/Prototypes/_Nyano/Roles/Jobs/Wildcards/prisoner.yml
Now that sec has exped capable ships, we should allow trusted white-listed players to play as prisoners and do expeditions.
Things to keep security occupied if its a slower round and would like a prisoner to take on expeds.
was mostly implemented already, just needed to be enabled. Moved the late join spot on the 2 ships its added to, so that prisoners dont spawn anywhere silly.
**Changelog**
:cl:
- add: Added the prisoner role to a select few security ships. Whitelisted only.
=> Enable Prisoner role for white-list

Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml, Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml, Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/satchel.yml, Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
Removing the multiphase gun from captain locker, it was added by mistake with the DeltaV pr.
Cleaning the Sheriff locker to help with new POI
Needed.
.yml
N/A
N/A
**Changelog**
N/A
=> Lockers Fix - 2023/12/26

Resources/Prototypes/Entities/Structures/Doors/Airlocks/external.yml, Resources/Prototypes/Entities/Structures/Doors/Airlocks/shuttle.yml
Cherry-Pick this PR early: https://github.com/space-wizards/space-station-14/pull/22706
Quality of life, very good.
**Changelog**
- tweak: You can now walk into external and shuttle airlocks to open them, like all other airlocks.
=> Makes external & shuttle airlocks bump-openable (#22706)

Resources/Maps/Shuttles/lantern.yml, Resources/Prototypes/_NF/Shipyard/lantern.yml
A new vessel to help frontier chaplains carry the light of faith to the distant corners of known space. Key features:
- Spacious chapel for big sermons.
- Сhurch organ.
- Coffin-chute for space burial.
- Morgue with incinerator.
I feel like Chaplains would benefit from having more ships to choose from. Also: "spess lantern".
New .ymls
_"The Lantern is a medium-sized chapel-vessel equipped with everything chaplain might need in their never ending battle for salvation of NT personnel souls.",_ - The Shipyard.
**Ship Size:** Medium
**Recommended Crew:** 2-3+
**Cost:** $33500
**Power Gen Type:** Plasma, Solar
**Expeditions:** No
**IFF Console:** No
**Available Roles:** Chaplain
**Changelog**
- add: Added NC Lantern - a medium-sized ship for Frontier Chaplains.
=> NC Lantern - a medium-sized ship for Chaplains

Content.Server/_NF/Smuggling/Components/DeadDropComponent.cs, Resources/Prototypes/_NF/Markers/Spawners/crates.yml
Adjusts some numbers for spawn rate details on smuggling drops.
had the timer short initially to help test. Also, slightly lowered the chance of getting a contraband crate (down from 50% on any given crate to aroudn 42.86%). Also, halved the chance of surplus crates, but only until we have more dangerous rare options (trap crates or similar dangers).
**Changelog**
:cl:
- tweak: Smuggling crate chance lowered from 50% to ~42%
- tweak: Dead drop timer raised from 10-40 minutes to 15-45 minutes.
=> Smuggling Tweaks

Resources/Maps/Shuttles/bocadillo.yml
Updated Bocadillo:
- Added waste loop, mapped emergency lights, firelocks.
- Removed cables from under the walls.
- Mapped drain.
To curb CO2 build up.
.yml changes
**Changelog**
- tweak: Tweaked Bocadillo - added atmos and drain.
=> Bocadillo Update

Resources/Prototypes/_Nyano/Entities/Objects/Specific/Mail/base_mail.yml
Upstream changes going to make mail and disposals very bad.
=> remove throw damage from mail (DeltaV)

Resources/Maps/Shuttles/pulse.yml
Updated Barge:
- Replaced Shuttle APUs with P.A.C.M.A.N.
- Added firelocks.
APU is dead, long live the new king.
.yml changes
**Changelog**
- tweak: Tweaked Pulse - replaced APUs with P.A.C.M.A.N.
=> Pulse Update

Resources/Maps/Shuttles/pioneer.yml, Resources/Prototypes/_NF/Shipyard/pioneer.yml
Tweaks:
- Removed ore processor.
- Added 2 ore boxes.
- Split salvage [filled, hardsuit] locker in two: salvage [filled] and suit storage [salvage].
- Updated preflight checklist.
- Price gone up slightly: whatever was -> 15950.
Downgraded slightly to make Prospector and Chisel more appealing.
**Changelog**
- tweak: Tweaked Pioneer - replaced ore processor with ore boxes. Note that raw plasma ore can be used as a fuel for generator.
=> Pioneer Rework

.github/labeler.yml
Adding more labelers for code.
=> Extra Labelers

Resources/Prototypes/_NF/Voice/speech_emote_sounds.yml, Resources/Prototypes/_Nyano/Voice/speech_emotes.yml
Fixing
Fixing
.yml
N/A
**Changelog**
:cl: dvir01
- tweak: Felinds can now Sneezes. Cough, Cry and Whistle.
=> Fix felinid

Content.Client/Preferences/UI/HumanoidProfileEditor.Random.cs, Content.Shared/Preferences/HumanoidCharacterProfile.cs
don't reset balance on Randomize Everything
it is unexpected and bad behavior that allows you to wipe several shifts of work in single click.
preserves the credit balance.
**Changelog**
=> don't reset balance on Randomize Everything

Resources/Prototypes/_NF/Entities/Structures/Doors/Airlocks/access.yml
Added captain perms to doors, was missing by mistake.
=> Mercenary Doors

Resources/Maps/Shuttles/loader.yml, Resources/Prototypes/_NF/Shipyard/loader.yml
Reloaded loader
General changes, atmost working in all rooms
Baseline
Mapping
N/A
**Changelog**
N/A
=> Loader - Changes

Resources/Prototypes/Entities/Structures/Windows/plastitanium.yml, Resources/Prototypes/_NF/Entities/Structures/Windows/plastitanium.yml, Resources/Prototypes/_NF/Recipes/Construction/Graphs/structures/plastitanium.yml
Added the new PlastitaniumWindowIndestructible, based the normal wall on it.
For POI / events use only.
.yml
N/A
**Changelog**
N/A
=> Plastitanium Windows

Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers_tabletop.yml
Swapped some parents around so the consoles would keep the correct names
bug fixes
.yml edit
=> Tabletop Computers: Fixing Naming issues

Resources/Prototypes/_NF/Markers/Spawners/untimedAISpawners.yml
Added 4 new spawners for Xenos
There was only one and it was pretty much just full random.
Easy is burrower and drone with a 10% chance of praetorian, runner, and spitter.
Medium is burrower, praetorian, drone, runner, and spitter with a 10% chance of ravager and rouny.
Hard is praetorian, runner, spitter, and ravager with a 10% chance of queen, rouny, drone, and burrower.
Queen is 'oops all queens'.
**Changelog**
:cl:
- add: Added four new xeno spawners for mapping!
=> Adds new xeno AI spawners of various difficulty

Content.Server/_NF/GameRule/NfAdventureRuleSystem.cs
Remove the NorthPole from the POI OnStartup (Commented mostly)
THE GRINCH HE STOLE IT! BUT ALSO ITS 2024! Christmas... is gone... over... until December 2024.
**Changelog**
- remove: The grinch has stolen the northpole away!
=> The Crinch Stole The NorthPole

Resources/manifest.yml
Changed the defaultWindowTitle from "Space Station 14" to "Frontier Station"
Why not?
Delta did it, so why not us!
**Changelog**
=> WindowTitle Fronter Station

Resources/Prototypes/_NF/Shipyard/bocadillo.yml
Up it to 20k
Price issue, too low was same as sell.
.yml
N/A
N/A
**Changelog**
N/A
=> Update Bocadillo Price

Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml, Resources/Prototypes/Entities/Structures/cargo_telepad.yml
Fixed cargo computers to stay floor bound
Abuse.
.yml
N/A
N/A
**Changelog**
N/A
=> Cargo not anchorable anymore

Resources/Prototypes/Catalog/Fills/Crates/salvage.yml
Sosa asked me to remove the pins after I move them to the pride o mat
Low worth clutter to a point they get yeeted into space.
.yml
N/A
**Changelog**
N/A
=> Salvage Pins

Content.Server/_NF/PublicTransit/PublicTransitSystem.cs, Resources/Locale/en-US/_NF/adventure/adventure.ftl
Race conditions present on the server but not my machine, caused 2 shuttles to spawn in on the same tick. This update changes the system startup to happen only once, and only after the RoundStarted event fires. As a result, the system as a whole is a bit less dynamic, and non-standard setups where you are implementing a bus route on a round that doesnt already call for it, means you will have to toggle the cvar to activate the system, but in our use cases we should never come across this.
Also implements an advertising system that will inform riders of the next planned destination and wait time, both upon arrival and departure.
fixes/upgrades
In order to get chat to work properly, I manually set all the chat parameters. I dont know which one exactly allowed it to work, but I suspect the …
=> Public Transit Patch

Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers_tabletop.yml
=> Fix ComputerTabletopSensorMonitoring

Resources/Maps/_NF/Shuttles/bazaar.yml
Adds latejoin spawnpoint to bazaar
**Changelog**
No CL.
=> Bazaar hotfix

Resources/Maps/_NF/Shuttles/bazaar.yml, Resources/Prototypes/_NF/Maps/Outpost/frontier.yml, Resources/Prototypes/_NF/Maps/POI/nfsd.yml
Removes:
- Reporter jobslots on frontier
- ~~Chaplain jobslots on frontier~~ (Not changed, Chaplain is still necessary due to how a bible works)
- Musician jobslots on frontier
- Lawyer jobslots on frontier
Adds:
- Bailiff jobslots on frontier
We have ships for reporters, chaplains and musicians. ( @dvir001 )
We also have lawyers on NFSD station now.
We did not have bailiff yet on NFSD station. Now we do.
**Changelog**
No CL.
=> Jobslots patches

Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers_tabletop.yml
Fix to the problem with tabletop consoles that prevented them from being interactable.
Bugfix
.yml changes
**Changelog**
- fix: Fixed the problem with tabletop consoles.
=> Tabletop Consoles Fix

Resources/Maps/_NF/Outpost/frontier.yml, Resources/Maps/_NF/POI/nfsd.yml
NFSD outpost:
- Add disposal tubes. (Can not be used to access NFSD outpost interior.)
- Add drain to below the sink in the break room.
- Add an extra dock on the back that only allows access to the jani closet. There's not even a door to go inside from there.
- Add atmos checklist. Rename atmos devices to match this checklist.
Frontier outpost:
- Allow clippy the right of breathing. (Adds vent and scrubber to the mail carrier room.)
- Add atmos checklist. Rename atmos devices to match this checklist. Remove useless atmos devices.
NFSD outpost (this room does have a light now):
Frontier outpost:
**Changelog**
No CL.
=> NFSD Outpost split Day 1 patches

Resources/Prototypes/_NF/Shipyard/investigator.yml, Resources/Prototypes/_NF/Shipyard/rosebudmki.yml, Resources/Prototypes/_NF/Shipyard/rosebudmkii.yml
Bump prices for Investigator and both Rosebud ships.
They were underpriced.
**Changelog**
No CL.
=> Adjust prices for Investigator and Rosebuds

Resources/Maps/_NF/Shuttles/inquisitor.yml, Resources/Prototypes/_NF/Shipyard/inquisitor.yml
- Redo all piping
- Remove customfilled closets from cells
- Remove booze dispenser (not a bar ship)
- Remove tactical maid skirt
**Changelog**
No CL.
=> Inquisitor (Update)

Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers_tabletop.yml
=> Tabletop Computers Fix

Resources/Prototypes/Catalog/VendingMachines/Inventories/theater.yml
Added clown & mime gear to AutoDrob.
Missing 
.yml
N/A
**Changelog**
:cl: dvir01
- add: Added clown & mime gear to AutoDrob.
=> Clown&Mime

Content.Client/Fax/UI/FaxBoundUi.cs, Content.Client/Fax/UI/FaxWindow.xaml
Fixes the fax machines
**Changelog**
:cl:
- fix: Fixed fax machines
=> Fax machine fix

Content.Server/StationEvents/Events/BluespaceErrorRule.cs
Fixes bluespace events deleting people
**Changelog**
:cl:
- fix: Fixed bluespace events deleting people
=> Bluespace Events Fix

Resources/Maps/_NF/Shuttles/rosebudmkii.yml, Resources/Prototypes/_NF/Shipyard/marauder.yml, Resources/Prototypes/_NF/Shipyard/opportunity.yml
=> Fixing spawn and errors

Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Projectiles/toy_projectiles.yml
Make the bb bullets despawn
Less spam
.yml 30 sec
N/A
N/A
**Changelog**
N/A
=> BB Despawn

Content.Server/Research/Systems/ResearchSystem.Console.cs
Make the R&D computer silent again.
Spam.
C# omit one line
N/A
N/A
**Changelog**
N/A
=> Silent R&D

Resources/Prototypes/Catalog/Cargo/cargo_engineering.yml
WARP Points spam
Spam
.yml
N/A
N/A
**Changelog**
N/A
=> Remove BeaconBundle

Resources/Prototypes/Nyanotrasen/Entities/Objects/Specific/Mail/tools.yml
Mail bags now accept items of size up to normal.
Mails are now normal-sized items, so mail bags should accept at least normal-sized items (was previously small-sized items).
Yml quick-fix.
**Changelog**
- fix: Mail bags are now able to recieve mails again.
=> Fix mail bag max item size being too small to recieve mails

Content.Client/Shipyard/UI/ShipyardConsoleMenu.xaml, Resources/Locale/en-US/_NF/cargo/cargo-console-component.ftl
The `ShipyardConsoleMenu` labels for "Bank spesos" and "Shuttle estimated value" were changed to match the formatting used by `BankATMMenu`, `CargoConsoleMenu`, `CargoPalletMenu`, and `VendingMachineMenu`. "Bank spesos" was changed to "Account Balance" and "Shuttle estimated value" was capitalized to "Shuttle Estimated Value". Some changes to localization were made.
This changes all variants of the shipyard menu.
A future refactor PR is being prepared to amend this and the localization files to improve internal naming consistency, and to consolidate and move related localization to a better directory (`_NF`). These refactor commits are separated in accordance with the pull request guidelines.
This change improves visual consistency.
N/A
Localization file …
=> feat(ui): Improve Shipyard Menu visual consistency

Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml, Resources/Prototypes/_NF/Entities/Clothing/OuterClothing/hardsuits.yml
Security patrol to almost match security but have less armor and more speed.
Merc suit buff since it was honestly very bad.
Weak suit stats.
.yml
N/A
N/A
**Changelog**
N/A
=> Buff Security patrol suit and merc

Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml, Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml
SR Office machines movable again as per requested to allow changes to office layout
Requested.
.yml
N/A
N/A
**Changelog**
N/A
=> SR Office machines movable

Resources/Maps/_NF/Shuttles/mayflower.yml
The Og Pr ( https://github.com/new-frontiers-14/frontier-station-14/pull/932 )  was broken.  So I wipe everything to attempt to fix it
Mostly Changes to the Webs, Change the nest location, added the crates back 
**Changelog**
tweak: Mayflower
=> Mayflower (Update)

Resources/Prototypes/Entities/Mobs/Species/arachnid.yml
**Changelog**
:cl:
- fix: Fixed Arachnid blood to copper blood.
=> Fix Arachnid's Blood

Content.Server/Research/Systems/ResearchSystem.Client.cs, Content.Server/Research/Systems/ResearchSystem.Server.cs
I fixed the issue with RD servers not appearing in the list for new ships
Because it didnt work for MONTHS
Calling register/unregister AFTER the entire map has been initialized makes it work.
While the solution in this PR may not be great, we can all enjoy working RD servers until the base code gets a makeover party.
none
**Changelog**
fix: RD servers not showing on new ships
=> Fix RD server(s) for new ships/stations

Resources/Locale/en-US/connection-messages.ftl
Changes the panic bunker deny new account text to a more intuitive message of "Your account is new to this server. Your first connection was less than {$minutes} minutes ago"
This PR is open to suggestions for better / more fitting / more concise messages. I have considered and decided against a number of other messages:
- "Your Frontier Station account is too new. It must be older than {$minutes} minutes"
- "Your profile on the server is too new. It must be older than {$minutes} minutes"
- "It has been less than {$minutes} minutes since your first connection to the server"
- "Your first connection is too new. It must be older than {$minutes} minutes"
- "Your first connection to the server was less than {$minutes} minutes in the past"
- "Your first appearance on the server was less than …
=> loc(bunker): Clarify account age deny reason

Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
This PR increases analyzer computer <> pad  linking range by 3 blocks.
Frontier being a ship based fork should allow for more flexibility even though these two machines are a inseperable combo, it has some really big downsides when designing ships, look at gourd's old design where the computer was crammed in the gap between the room and the ship, or the investigator, which never worked. 
After this change is merged, mappers can actually make better designs, it being 1 or 2 blocks further away from the analyzer pad simply allows designs for which it was meant to have.
I've actually went and asked the code author of this linker range mechanic, EmoGarbage, why it was a max range of '5'. and he answered 
Hence, this PR
none
**Changelog**
tweak: increase analyzer computer <> pad  linking range …
=> Increase default analyzer linking range

Content.Server/Cargo/Systems/CargoSystem.Orders.cs, Content.Server/VendingMachines/VendingMachineSystem.cs
Makes it so income is mirrored and sent to NFSD outpost, to allow sheriffs to manage their own finances and pay their own crew
A real station administration console needs to be mapped onto NFSD now
**Changelog**
:cl:
- tweak: NFSD now has their own bank account for payroll
=> Split station bank accounts

Content.Server/Power/Pow3r/BatteryRampPegSolver.cs, Resources/Prototypes/Procedural/Magnet/asteroid.yml
This PR mutes a assert error in the BatteryRampPegSolver class while i'm looking into why this is failing.
Seems to trigger when big power surge happens, balances out later though, so we can just mute it.
Check this change out; I can see the YML's existing in our repo, but none of the CS changes, and reason why i commented out the YML's for now is because every map is loaded but uses generator type `NoiseDunGen` which we didn't merge from this 
https://github.com/space-wizards/space-station-14/commit/bf79acd127483d64f96dc23f2e64c74ceb84303d
none
**Changelog**
Development changes only, won't affect production
remove: debug assertions that are annoying for development
remove: maps that use NoiseDunGen
=> Mute Debug assertions that crash debug

Content.Server/Database/ServerBanDef.cs, Resources/Locale/en-US/connection-messages.ftl
Just some clarifications on the ban message when a banned player try to connect to the server
single line of "code" added
**Changelog**
no need for CL this will be only observable by banned players
=> Tweaks to ban message

Content.Client/Shuttles/UI/RadarControl.cs
=> Fix RadarControl errors

Resources/Maps/_NF/Shuttles/placebo.yml
Hotfix for the Placebo
Forgot HV Cabels and a Cable terminal.
**Changelog**
- fix: The Placebo now has HV cabels!
=> Hotfix for the Placebo

Resources/Maps/_NF/Shuttles/stratos.yml, Resources/Prototypes/_NF/Shipyard/stratos.yml
Fix some initial issues with the Stratos ship
These are the issues that were changed and why:
- Practically no side thrust, since top has 6, left has 2, right has 2, so increased  them from 2 to 3 per side.
- Atmos distro line was missing a pipe causing no air to go to ship
- Atmos distro pump enabled by default now otherwise no air to ship
- No toolbelt on the entire ship, so added a locker in engine room
- Fix side docking ports give no space to dock since the ship's 'butt' was wider
- Added a gyro since it is normal for medium size ships to have 2, not 1.
- Fixed fire alarm not getting power because it was 1 tile too far to receive it.
-
All the exact changes in this ship are listed above, it does not need a screenshot.
**Changelog**
add: toolbelt
add: 2 side thrusters
add: gyroscope …
=> Ship (update) - Stratos

Content.Server/Info/ShowRulesCommand.cs
Just a little admin QOL for a command very often used.
**Changelog**
No need for CL since this will be only used by admins.
=> Add autocompletion to showrules

Content.Shared/CCVar/CCVars.cs
Disables tile ripping on spacing. Really really not ideal since its the only visual indicator of a spaced room, but upstream broke it very very badly recently with tile prying changes and they likely wont fix it so we will just disable for now sadly.
**Changelog**
=> disable tile ripping

Resources/migration.yml
Fixed migration file
Bug
.yml
N/A
N/A
**Changelog**
N/A
=> Fix migration.yml so debug build work again

Resources/Maps/Shuttles/cleric.yml, Resources/Maps/_NF/Shuttles/searchlight.yml
ClothingBeltParamedicFilled to ClothingBeltMedicalEMTFilled
=> Fix broken ships

Resources/Prototypes/Entities/Objects/Devices/pda.yml, Resources/Prototypes/_NF/Entities/Objects/Devices/pda.yml
Add music to admin PDA
Using the super synthesizer type
Jester
Jester might be forced to use his hands for admin work now.
N/A
**Changelog**
N/A
=> Jester Music PDA

Content.Server/Nyanotrasen/Kitchen/EntitySystems/DeepFryerSystem.cs
This pr once again makes deep fryer play sound when starting to add oil
it didnt work
couple lines code change
**Changelog**
fix: bubbly sound
=> Fix ambient when adding oil to fryer

Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml, Resources/Prototypes/Entities/Structures/Shuttles/cannons.yml, Resources/Prototypes/Procedural/salvage_rewards.yml, Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/circuitvend.yml
Tweaks shuttle gun values
we want to use them but the damage values from upstream were kind of insane
the pka gun is a great mining tool but is quite pitiful in any other respect. this is so people arent stacking a ton of them and griefing other players, since upstream values basically made it into a ship destroyer  weapon for free.
**Changelog**
<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
..>
:cl:
- tweak: Re-balanced ship weapons and added the basic mining laser to the circuit vend.
=> Shuttle Gun Rebalance

Resources/Prototypes/GameRules/roundstart.yml
removes the wall replacement of rusty walls
bad sprites, also bad system of replacement as it replaces wrong types
**Changelog**
:cl:
- fix: Fixed rusty wall replacement
=> Remove rusty wall variations

Content.Client/StationRecords/GeneralStationRecordConsoleWindow.xaml.cs, Content.Server/StationRecords/Systems/GeneralStationRecordConsoleSystem.cs
fixes the records console
bug fix
spent all morning messing with my own UI to figure out why its dissapearing, turns out it was a server side system issue
This doesnt fix the dissappearing records issue, thats a seperate issue that I have yet to track down. Instead this just forces the job select portion of the window to always display regardless of the existance of records while we solve that issue.
**Changelog**
:cl:
- fix: Fixed job selector not showing up in empty records consoles
=> Records console fix

Content.Server/Research/Systems/ResearchSystem.Client.cs, Content.Server/Research/Systems/ResearchSystem.cs
Makes a more permanent fix from #1026
More sound solution compared to the previous band aid fixes.
Uses `EntityLookupSystem.ComponentQueries#GetChildEntities()` to select only research servers attached to the same grid. 
**Changelog**
=> refactor(research): Improve initial research client registration

Resources/ServerInfo/Rules.txt
Server rules have been updated to reflect and clarify how players should behave inside the station safezone, also added a clause to the metacomunications rule and as a plus the server rules has been beautified a little and its more readable.
It has always been discussed on how the safezone affects the server gameplay for both experienced and new players, this changes are done to reflect the way the admin team best thinks how players should behave inside the safezone. so now the safezone will have its own dedicated rule with new causes added to it. 
no code changed, space law will have 2 new crimes added to reflect this changes to the station rules.
Ideally this will also come bundled with the NFSD resprites and changes too 
New rule.
More readable rules.
**Changelog**
:cl: Leander
- …
=> Update server rules

Resources/Prototypes/_NF/Shipyard/Security/opportunity.yml
A glaring security risk has come to my attention that I will need some time to fix.  In the meantime the ship should not be available to unwitting NFSD members.
**Changelog**
:cl:
- remove: Opportunity temporarily removed.
=> Remove Opportunity from shipyard

Resources/ServerInfo/Rules.txt
Just the final touch ups to the server rules that wanted to do, removed mentions of HOS and HOP for Sheriff and Station Rep, added bullet points, clarification on character names and piracy/smuggling rule we have been doing for a while.
:cl: Leander
- tweak: smugglers and pirates are no longer in the same team.
=> Rules formatting 

Resources/Prototypes/_NF/Shipyard/Security/opportunity.yml
=> Opportunity (Disable)

Resources/Prototypes/Roles/Antags/Thief.yml, Resources/Prototypes/Roles/Antags/nukeops.yml, Resources/Prototypes/Roles/Antags/revolutionary.yml, Resources/Prototypes/Roles/Antags/traitor.yml, Resources/Prototypes/Roles/Antags/zombie.yml
Dvir asked me to do this
**Changelog**
=> Disable antag roles in the lobby

Resources/Maps/_NF/Shuttles/point.yml, Resources/Prototypes/_NF/Shipyard/point.yml
Fixed some issues I noticed in the point
Fixes wiring
Fixes atmos pipes being in walls
Removes 2 apcs
Decreased price
Original Maker of shuttle: Spessman
The point Had issues and I just fixed them
If you're unsure whether your PR will require media, ask a maintainer.
Check the box below to confirm that you have in fact seen this (put an X in the brackets, like [X]):
-->[X]
=> SV Point (Update)

Resources/Maps/_NF/POI/grifty.yml
- Expanded Grifty's to add a small bathroom, enlogating the station is the proccess.
- Fixed SMES wiring so that the it actually provides power to the powernet.
- Fixed disposals missing piping under walls.
- Added an air alarm and adjusted atmos.
Would love @DustScoundrel to review this since this POI is their creation
Grity's is a gas station, all gas stations should have a filthy bathroom to vomit into after a long trip.
n/a
**Changelog**
:cl:
- tweak: Grifty's Gas and Grub has recieved a small expansion
=> Expanded Grifty's 

Resources/Maps/_NF/Shuttles/cleithro.yml, Resources/Prototypes/_NF/Shipyard/cleithro.yml
A normal psychologist ship, with a waiting room, reception area and a cozy office.
A simple build, nothing weird, very simple.
Mapping.
<details> 
<summary>Secret</summary>
https://cdn.discordapp.com/attachments/1217953335026651176/1217979526328483931/image.png?ex=6605fed4&is=65f389d4&hm=1a2cb9ffe9aaaff196222c81d88ae9483d63336b002fe49afd47bd92cc51000d&
</details>
N/A
**Changelog**
:cl: dvir01
- add: Added the Cleithro psychologist shuttle, just a normal ship.
=> Cleithro (New) - Normal Psychologist Shuttle

Resources/Prototypes/Nyanotrasen/Entities/Structures/Machines/lathe.yml
Added base recipes to the engi techfab, including most engi equipment printable at autolathes with the addition of shuttle tech and shuttle power generation boards
A massive issue with running an engi crew to repair broken ships is the fact that many components once lost, such as the shuttle console, can't be easily repaired or replaced. While many shuttle parts can be bought at cargo, some critical pieces to ship repair cannot. If in the future ship armaments are going to be a bigger part in frontier, engi crews need a method of getting replacement parts without just sticking a science kit down and researching the tech themselves.
https://discord.com/channels/1123826877245694004/1220642006687289424
**Changelog**
:cl:
- tweak: The engi techfab has been upgraded to include everything …
=> Add Shuttle and power gen technology to Engi-Fab

Resources/Maps/_NF/Shuttles/pathfinder.yml
- Replaced outer hull diagonal steel walls with diagonal reinforced steel walls for visual consistency.
- Atmos mixer now starts with proper gas mix proportions.
QoL kind of.
**Changelog**
- tweak: Pathfinder tweaks: replaced outer hull diagonal steel walls with diagonal reinforced steel walls.
=> Pathfinder Minor Tweak

Resources/Prototypes/StatusEffects/job.yml, Resources/Prototypes/_NF/Catalog/security_uplink_catalog.yml
Fixes the NFSD icons and Uplink entries for the new hardsuits
:cl: Leander
- tweak: Fix NFSD job icons
=> Fix NFSD job icons and uplink

Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
Adds the sheriff access back to the SR so they can fully edit their own doors or help pay the NFSD if there is no Sheriff available.
**Changelog**
:cl: Leander
- tweak: Station Representative has full access now.
=> Update SR access to be AA

.github/PULL_REQUEST_TEMPLATE.md
This PR swaps the "Technical details" in the new PR template with "How to test"
We have more PR's that dont really require technical details unless the coder really needs to explain it in detail.
Because of this, I propose to replace the "Technical details" with "How to test" which helps new contributors do testing and reviewing more efficiently and discover faster how things work.
- Open a new PR in github
- Check if "Technical details" was replaced with "How to test"
(this doesn't actually work until this PR is merged in this case, but it is a great way to demonstrate how to test it!)
**Changelog**
remove: Removed technical details heading in new PR template.
add: Added How to test section that can help contributors to test.
=> Change template to include test section

Resources/Maps/_NF/Outpost/frontier.yml
Just fixing all the station's directional signs.  Can you believe the bar sign was still pointing toward the old captain's bar!?
**Changelog**
No CL
=> Frontier Sign Fix [Update]

Content.Server/Cargo/Components/CargoPalletConsoleComponent.cs, Content.Server/Cargo/Systems/CargoSystem.Shuttle.cs, Resources/Maps/_NF/POI/cargodepot.yml
This is the first installment of changes to cargo..
Cargo selling areas can now be mapped in more than one area 
The cargo console component can be opened while mapping (in vv) and now has a new range variable to check for cargo pallets
Default is 8 around the computer, so currently mapped ones will still work everywhere.
Also, Cargo Depot now has 4 computers!
Put down a NFHigh cargo selling computer and put some pallet tiles in a long line.
Default radius is 8, so once you go past there, you can put 10 items on each pallet on the line and it will only see 8
**Changelog**
add: cargo selling computers now have a configurable range
=> Allow multiple cargo computers on one grid

Resources/Maps/_NF/POI/grifty.yml
Fast grifty fix for this error:
Also run fix atmost and added markers for spaced rooms
N/A
**Changelog**
N/A
=> Grifty (Update)

Resources/Maps/_NF/Shuttles/skipper.yml, Resources/Prototypes/_NF/Shipyard/skipper.yml
Fixed the price,
Fixed the freezer room to be a real freezer, don't die while flying, use the coat.
Generators are auto startup.
Needed.
N/A
**Changelog**
N/A
=> Skipper (Update)

Content.Shared/Bed/Sleep/SharedSleepingSystem.cs, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/shotgun.yml
Tranq shell takes 4 shots now to stun someone
2 tapping people is cringe
changed 2 numbers
:cl: Leander
- tweak: Tranquilizer shells now come with with less amount of CH.
=> Nerf tranquilizer shells

Resources/Prototypes/_NF/Entities/Structures/Storage/Crates/crates.yml, Resources/Prototypes/_NF/Markers/Spawners/posters.yml
lowers the value and frequency of smuggling
people were gaming it too much, it should be more rp focused and less profit focused
**Changelog**
:cl:
- tweak: Slightly lowered the value of smuggled crates
- fix: Fixed dead drop spawn rate
=> April 2024 Smuggling Tweaks

Content.Server/Botany/Systems/PlantHolderSystem.cs
Botany systems basically got nerfed into irrelevancy by upstream in order to stop powergaming death nettles, but we dont really have that issue and the nerfs make the actual system unplayable for botanists. There are a couple different proposed solutions upstream, and I'm waiting for one of them to be chosen, but in the mean time we are just going to un-obtrusively lessen the blow for clipping plants until the proper fix is implemented.
**Changelog**
:cl:
- tweak: Temporarily changed plants to lose less health when clipped
=> April 2024 Botany Tweaks

Content.Server/_NF/Smuggling/DeadDropSystem.cs, Resources/Prototypes/Entities/Objects/Misc/subdermal_implants.yml, Resources/Prototypes/_NF/radio_channels.yml
Fix the deaddrop not announcing to the new NFSD radio and also the tracking implants.
Also changing the color to be more readable and visible.
=> Fix NFSD announcements

Content.Shared/Shipyard/Components/SharedShipyardConsoleComponent.cs
=> Updated NFSD shipyard radio

Resources/Prototypes/Entities/Markers/Spawners/Random/paintings.yml
Adds The Greatest Work of Art to the random painting spawner.
Witness
**Changelog**
- tweak: "Night Of The Post Goblin" (painting) has come.
=> "Night Of The Post Goblin" to the random painting spawner

Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/HMGs/hmgs.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/LMGs/lmgs.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Revolvers/revolvers.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Rifles/rifles.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml, Resources/Prototypes/Entities/Objects/Weapons/security.yml, Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Guns/revolvers.yml, Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Launchers/launchers.yml
This PR goes through and gives more context to all the guns in game for players, new or old, to be able to quickly see if it should be contraband or not.
Tired of hearing the bickering back and forth on whether a gun is contraband or not, people don't actually read space law so hopefully they WILL read the descriptions of the item.
**Changelog**
:cl:
- tweak: Changed descriptions of guns to be clearly contraband or not.
=> Gun Descriptions including context for Contraband status

Resources/Maps/_NF/Shuttles/Security/whiskey.yml, Resources/Prototypes/_NF/Shipyard/Security/whiskey.yml
Updated the NSF Whiskey to use the new NFSD sprites and reapplied the floor decals.
As per #1230 the Whiskey needed an update.
While reworking the floor decals, I found a lot of them did not mesh well with the tiles used, so I replaced the decals to be less high contrast and visually intrusive. 
Removed the books and replaced with book spawners. 
Checkout branch, loadgrid.
None!
**Changelog**
:cl:
- tweak: Added new NSFD sprites to the NSF Whiskey and tweaked decals.
=> NSF Whiskey: Sprite update and decal redecorate

Content.Server/_NF/Smuggling/DeadDropSystem.cs
Fixes the dead drops to spawn correctly and give the proper paper
=> Smuggling Fixes

Resources/Maps/_NF/POI/nfsd.yml, Resources/Prototypes/Entities/Markers/Spawners/jobs.yml, Resources/Prototypes/_NF/Entities/Structures/Doors/Airlocks/access.yml, Resources/Prototypes/_NF/Markers/Spawners/jobs.yml
NFSD Update to be NFSD
N/A Color and machine swap
N/A
**Changelog**
:cl: dvir01
- tweak: NFSD Fixed the colors and machines on the NFSD base
=> NFSD (Update)

Resources/Maps/_NF/POI/cove.yml, Resources/Maps/_NF/Shuttles/BlackMarket/barnacle.yml, Resources/Maps/_NF/Shuttles/BlackMarket/menace.yml, Resources/Maps/_NF/Shuttles/BlackMarket/schooner.yml, Resources/Prototypes/Entities/Markers/Spawners/Conditional/pirates.yml, Resources/Prototypes/_NF/Shipyard/BlackMarket/barnacle.yml
Pirates need more betterer options to start pirating, this is a 'stealth' vessel of an old familiar one designed to blend in over radar.
Small, cheap piracy ship that offers very little for protection
**Changelog**
:cl:
- add: Adds the Barnacle black market ship
=> NC Barnacle (New BlackMarket Ship)

.github/mapchecker/config.py, Resources/Maps/_NF/Shuttles/BlackMarket/bocakillo.yml, Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml, Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers.yml, Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers_tabletop.yml, Resources/Prototypes/_NF/Shipyard/BlackMarket/bocakillo.yml
It looks like a Bocadillo on radar to blend in with more innocent ships...
It's tight, it's uncomfortable, it's got almost no cargo room, but it will make NFSD think twice about getting in your personal space.
A tiny plastitanium vessel suited to a crew of 2 to 3 pirates. Has two broadside cannons and a rear-facing disposals launcher. Runs on plasma.
The disposals launcher will eject anything you put in it, at speed, toward whoever is following you...I suggest explosives or a particularly foolhardy boarding party.
Might break the meta.
**Changelog**
:cl:
- add: Adds the Bocakillo, pirate ship.
=> Bocakillo (New Blackmarket pirate ship)

Resources/Prototypes/Catalog/Cargo/cargo_shuttle.yml, Resources/Prototypes/_NF/Catalog/Cargo/cargo_shuttle.yml, Resources/Prototypes/_NF/Catalog/Fills/Crates/engines.yml, Resources/Prototypes/_NF/Entities/Objects/Devices/flatpacks.yml, Resources/Prototypes/_NF/Entities/Objects/Devices/production.yml, Resources/Prototypes/_NF/Entities/Structures/Shuttles/thrusters.yml, Resources/Prototypes/_NF/Entities/Structures/Shuttles/thrusters_nfsd.yml, Resources/Prototypes/_NF/Entities/Structures/Shuttles/thrusters_security.yml
=> Thrusters Fix. again.

Resources/Prototypes/Guidebook/species.yml, Resources/ServerInfo/Guidebook/Mobs/Goblin.xml
Adds a short entry to Guidebook about goblins and their mechanical peculiarities.
This info should be available to players without diving into game files.
Open guidebook, navigate to species, look for goblins
none afaik
**Changelog**
- add: Added  a short entry to guidebook concerning goblins.
=> Goblin species guidebook entry [v1, before Goblin Diet merge]

Resources/Maps/_NF/Shuttles/Security/empress.yml, Resources/Prototypes/_NF/Shipyard/Security/empress.yml
Removed the filled armory from the Empress. 
Awaiting an update to add Gun Cases, to create an Armory Restock for lethal and non-lethal weaponry which will be purchasable via the uplink.
**Changelog**
=> 04/29/2024 - Armory Removal (Empress)

Resources/Prototypes/_NF/Entities/Objects/Devices/pda.yml
NFSD Brigmedic PDA inherits from BaseMedicalPDA, which has a medical scanner
It really feels like that Brigmedics should have medical scanners on their PDAs
Take brigmedic PDA (Make sure it's the one with description: "Whosoever bears this PDA heals the law." as that is the NFSD Brigmedic PDA)
Apply PDA to self
Recieve a medical scan.
https://github.com/new-frontiers-14/frontier-station-14/assets/89804215/255042b5-20e4-427d-9dae-49263cbef733
(Fairly sure the shudder and first failure was due to my computer having performance issues and should not happen on the actual server)
**Changelog**
:cl:
- add: Brigmedic PDAs can now perform medical scans
=> NFSD Brigmedic PDA now has a medical scanner

Content.Server/StationEvents/Events/IonStormRule.cs
Makes ion storm events randomly change laws to **all cyborgs in the sector** (including in space), rather than only when on **one randomly selected shuttle**.
Rule as-is on `master` meant ion storms rarely affected cyborgs.  This makes law changes much more frequent, and should be more suitable for a setting like Frontier Station with many shuttles.
Build and run local server.
With the sandbox commands, spawn a cyborg on Frontier Outpost.
Switch control to cyborg - stay on station.
Enter `/addgamerule IonStorm` into chat until your laws change.
Should be quick on branch to be merged, should never happen on master.
**Changelog**
tweak: Increased system-wide electromagnetic interference.
=> Make ion storms system-wide instead of shuttle-local

Resources/Maps/_NF/Outpost/frontier.yml
Fixes a few dirt decals to be cleanable:
- at the shipyard/ATMs
- at the medical cloning computer
- at the medical docks
Bugfix? It seemed unintentional that these random decals were not cleanable.
Apply space cleaner.
**Changelog**
=> fix(map): Fix uncleanable dirt decals on Frontier Outpost

Resources/Maps/_NF/Shuttles/BlackMarket/falcon.yml, Resources/Prototypes/_NF/Shipyard/BlackMarket/falcon.yml
Adds the Falcon pirate ship, a medium sized ship with a hangar bay to store loot, vehicles and the riches. its meant to be used alongside hoverbikes so the pirate gang gets deployed to its victim while the ship pilot docks to the ship. 
Meant to look like the kestrel.
More ships for the pirates, yes.
**Changelog**
:cl: Leander
- add: New falcon blackmarket ship.
=> Falcon (New Blackmarket pirate ship) 

Resources/Prototypes/_NF/StatusEffects/job.yml
Fixed the job.yml file that contains the asset paths for NF-specific job icons.
**Changelog**
:cl: blueDev2
- fix: Fixed Frontier Outpost Job Icons
=> Fixed sechuds for security guard

Content.Client/Shuttles/UI/ShuttleNavControl.xaml.cs
Fixes a UI scaling issue with the IFF labels on mass scanner, etc.
Fixes #1337
Bugfix. Deja vu.
Observe mass scanner with different UI scales. They should appear identical to 100% scale.
**Changelog**
=> fix(ui): Fix shuttle nav control IFF text UI scaling

.github/workflows/build-map-renderer.yml, .github/workflows/build-test-debug.yml, .github/workflows/publish.yml, .github/workflows/test-packaging.yml, .github/workflows/yaml-linter.yml
Replicates https://github.com/DeltaV-Station/Delta-v/pull/1199 but pins to a slightly newer version for kicks
https://github.com/dotnet/core/issues/9309
update your branches and push and let the comfort of the green check marks wash back over you
**Changelog**
=> pin dotnet to 8.0.204

.github/workflows/build-docfx.yml, .github/workflows/build-map-renderer.yml, .github/workflows/build-test-debug.yml, .github/workflows/publish.yml, .github/workflows/test-packaging.yml, .github/workflows/yaml-linter.yml
=> 2024 05 17 Engine Patch

.github/mapchecker/config.py
Update to mapchecker to allow ButtonFrameCautionSecurity decal
=> Mapchecker (Update)

Content.Client/UserInterface/Systems/Storage/Controls/StorageContainer.cs, Content.Client/UserInterface/Systems/Storage/StorageUIController.cs
Bug fix
https://github.com/space-wizards/space-station-14/pull/27960
=> fix orphaned storage grid pieces getting stuck to the cursor (#27960)

Resources/Prototypes/_NF/Entities/World/Debris/asteroids.yml
Better brown for AsteroidRock type asteroids.
Bad suggestion.  Too dark.  Sorry.
1. /aghost
2. Fly into space.
3. /spawn AsteroidRockDebrisNFMedium
4. Move a little.
5. /spawn AsteroidDebrisNFMedium
6. Move off the asteroid.
7. Check your mass scanner (4).  Compare the colours vs. Frontier (or a POI) and the asteroids.
Recommended fix
vs. Current head of master (0a1c109) - AsteroidRock circled in green.
**Changelog**
=> Fix nearly-invisible asteroids

Resources/Prototypes/_NF/Entities/Mobs/NPCs/pets.yml
Fixes Clippy's Build in radio to recive messages
Forgotten line that is needed some small fixes, PR requested by Dvir01
Run it and try to talk with clippy in radio
**Changelog**
🆑 
- fix: Fixed Clippy not hearing Service Radio
=> Fixes Clippy to recive Radio Messages

Resources/Maps/_NF/Shuttles/crown.yml, Resources/Prototypes/_NF/Shipyard/crown.yml
No breaking the game this time?
I hope.
=> Crown (Update)

Content.IntegrationTests/Tests/Fluids/FluidSpillTest.cs, Content.Shared/Fluids/SharedPuddleSystem.Evaporation.cs
Add more liquids to evaporate system to combat lags
FluorosulfuricAcid
Vomit
InsectBlood
AmmoniaBlood
ZombieBlood
Blood
Slime
CopperBlood
Sap
JuiceTomato
After 6 hours its starting to hurt.
Spawn blood, watch it dry.
N/A
Less work for janitors overall but worth the lag save.
**Changelog**
N/A
=> Make more liquids evaporate

Resources/Locale/en-US/_NF/paper/paper-misc.ftl, Resources/Maps/_NF/POI/cove.yml, Resources/Prototypes/_NF/Catalog/Fills/Crates/fun.yml, Resources/Prototypes/_NF/Catalog/Fills/Paper/misc.yml
General QOL and buffs
Removed all vending machine (LessLethalVendingMachine & VendingMachineTankDispenserEVA)
Replaced the vending machines with gear (Added pictures)
Added a pirate hover bike crate
Added an EMP Emitter
Added liquid canisters to air distro,
Need some general improvement before we get around to adding an uplink
Open the game build
Warp to Pirate Cove
N/A
**Changelog**
:cl: dvir01
- tweak: Pirate Cove got new equipment shipment.
=> PirateCove (Update)

Resources/Prototypes/_NF/Entities/Effects/portal.yml, Resources/Prototypes/_NF/Objects/Devices/admin_hand_teleporter.yml
This adds in a admin version of the handheld teleporter, which works across maps and dosent make a random teleport when only one portal 
It has been requested by admins, so here it is
- Load Frontier
- Spawn in the admeme hand teleporter
- Create Portals across maps
- Get teleported
**Changelog**
:cl:
- add: Added Admeme Hand teleporter
=> Adds Admin teleporter

Resources/Prototypes/_NF/Entities/Effects/portal.yml
Fixes typo
misspell in code
- Run game
- Spawn Hand teleporter [admeme]
- Do portals
- Use Portals
**Changelog**
:cl:
- fix: Admeme Teleporter hotfix
=> hotfix: Admin teleporter

Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
Non-lethal Mosin inherits the magazine size, whitelist from its lethal parent.
Mismatch of magazine sizes.
Build and run locally.
1. Spawn a lethal Mosin and a non-lethal Mosin.
2. Both should have five bullet magazines.
3. Lethal Mosin should fire lethal rounds, non-lethal Mosin should fire non-lethal rounds.
4. Spawn a .45 box of ammo, try to load both Mosins, they should fail.
None.
**Changelog**
=> Mosin hotfix: non-lethal version inherits mag size

Resources/Maps/_NF/POI/trade.yml
Title, Anchors the trade post POI into place.
Too many troubles and lame issues.
get ship, try to push POI, if it moves then something went wrong.
**Changelog**
No need for CL
=> Anchor trade station into place

Resources/Prototypes/Entities/Mobs/NPCs/elemental.yml, Resources/Prototypes/_NF/Entities/Mobs/NPCs/elemental.yml
balance pass on mining creatures after player feedback
consensus was that the new mining creatures were "too difficult" to "just right", and along with that ore yields from asteroids suffered as a result as well.
**Changelog**
:cl:
- tweak: Lowered the movement speed and damage of ore crabs and golems
- tweak: Increased the ore yield from ore crabs and golems
=> mining crab and golem rebalance

Content.Server/Devour/DevourSystem.cs
* Update DevourSystem.cs
* Update DevourSystem.cs
* Update Content.Server/Devour/DevourSystem.cs
---------
Fixes **devour**,  cherry picked from upstream.
fixed dragons **devouring** people and deleting them.
take dragon, **devour** someone and butcher dragon.
**Changelog**
:cl: Leander
- tweak: Dragons can devour people again without deleting them.
=> Fix devour

Resources/Prototypes/_NF/Entities/Clothing/Eyes/hud.yml
This adds wanted status and a job icon to the brigmedic HUD by reparenting the brigmedic under both medical and NFSD HUDs.
Going by the description of the object and the medsechud construction prototype in the entity definition, it seems like this was intended behaviour.
The brigmedic is a security officer, shouldn't they have a security HUD?
This is liable to some power gaming, but if access to these is controlled (no references to entity prototype ID apart from brigmedic loadout and definition), that shouldn't be much of an issue.
1. Spawn brigmedic HUD, put it on.
2. You should see your health status.
3. Give yourself a wanted status.
4. The wanted status should show up along with your medical status.
**Changelog**
:cl:
- tweak: The Brigmedic HUD now has job icon, wanted status, and …
=> Add wanted status, job icon, health icon to Brigmedic HUD

Resources/Prototypes/_NF/Entities/Mobs/NPCs/artifact_construct.yml
Fix artifact fragment spawn rate for grimforged golems
it dropped too many
butcher a artifact golem and check drops
**Changelog**
:cl:
- fix: Fix grimforged golems dropping too many fragments
=> Fix artifact fragment spawn rate

Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Updated the hardsuit to have just a bit better armor value. More in line with NFSD suits.
**Changelog**
Better armor less ting ting on skin
-->
=> Updated Pirate Captain Hardsuit

Resources/Prototypes/Entities/Objects/Weapons/Guns/turrets.yml
=> Turrets Fix

Resources/Prototypes/_NF/Entities/Mobs/NPCs/baby_dragon.yml
baby dragon can emote now as it was intended.
Muh roleplay
**Changelog**
No need for CL
=> Fix baby dragon emote

Content.Server/Tabletop/TabletopSystem.cs, Content.Shared/CCVar/CCVars.cs
"This feature should never have been merged, it can be trivially abused to break the entire server.
It's behind a CVar because honestly that's the easiest way to 1984 the feature."
Causes issues.
Spawn a battle map, try to put stuff on it, won't work.
**Changelog**
Nope.
=> Cherry-pick: Remove placing items on tabletop boards. (#29513)

Content.Shared/Storage/EntitySystems/MagnetPickupSystem.cs
Adjusted how magnetic objects (e.g. ore bags, plant bags, construction bags) calculate the next time to check for nearby pickups.
In the case where a particular bag is almost full, equipped on your belt, and has its magnet enabled, and when you're surrounded by objects it could normally pick up, but cannot (e.g. offset inventory space), if for whatever reason, NextScan was reset or very much behind the current game time, the scan will run each frame.
On the head of master, and on this branch, try the following:
1. Spawn a construction bag of holding.
2. Spawn many steel stacks, enough to fill the bag with a good number underneath you.
3. Pick up the construction bag.
4. Turn off the magnet.
5. Adjust the inventory so it resembles the picture below (two spaces open on either side of steel …
=> Fix Magnetic Client-side Lag

Content.Server/Construction/Conditions/MachineFrameComplete.cs, Content.Server/Construction/ConstructionSystem.Machine.cs, Content.Server/Construction/MachineFrameSystem.cs, Resources/Locale/en-US/machine/machine.ftl, Resources/Prototypes/Entities/Objects/Power/powercells.yml
Fixes a few issues with upgradeable machine parts.  Small power cells and antique power cells get a power cell rating.
Component insertion during machine construction should work as expected (insert a stack, amount adjusts reflecting the entire stack, or what was taken off).  Machines have their parts refreshed on construction.
Fixing regression vs. pre-upstream merge, bug fixes.
1. Spawn a few ready machine frames in, and a SMES board for each.
2. Spawn some power cells, one of each type.
3. Insert power cells into machine frames, examine that count is accurate.
4. Spawn and insert other materials, confirm that _Completed_ message only shows up when all components are added.
5. Double check upgrade rating on completion, should be accurate to the components used.
6. Spawn another machine …
=> Machine Part Bugfixes

Resources/Prototypes/_NF/Catalog/Fills/Crates/nfsdarmory.yml, Resources/Prototypes/_NF/Catalog/security_uplink_catalog.yml
Just a small PR to restore the uplink listing since we forgot about it
=> Restore NFSD Nonlethal Armory

Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/head.yml, Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/outer.yml, Resources/Prototypes/_NF/Loadouts/Jobs/Janitor/head.yml, Resources/Prototypes/_NF/Loadouts/Jobs/Janitor/outer.yml, Resources/Prototypes/_NF/Loadouts/contractor_loadout_groups.yml, Resources/Prototypes/_NF/Loadouts/janitor_loadout_groups.yml, Resources/Prototypes/_NF/Loadouts/mercenary_loadout_groups.yml, Resources/Prototypes/_NF/Loadouts/pilot_loadout_groups.yml, Resources/Prototypes/_NF/Mail/mail.yml
Added warning cone, plunger and wet floor sign to loadouts. Janitors can have those for free.
Style
Skim through head and outer clothing loadout menus
"M" in "MRP"
**Changelog**
- add: Added warning cone, plunger and wet floor sign to loadouts. Janitors can have those for free.
=> Stylish loadout items

Content.Server/_NF/Construction/Components/PartExchangerSystem.cs, Content.Server/_NF/Construction/ConstructionSystem.Machine.Upgrades.cs
Minor change to RPED replacement algo.  Removal of items from lists is now done by index instead of by value comparison.
Items have their status updated - elements that started in the RPED will not be reinserted into the RPED.  Elements that were removed from the machine _will_ be inserted into the RPED, if there's space.  They will be dropped on the ground if they do not fit.
Stack removal was buggy.  Occasionally, insertion would consume _all of the stacks of a type in your inventory_.  Easy way of replicating: spawn an RPED, a thruster upgrade kit, insert caps into RPED, upgrade a thruster.  Poof, no more super caps.
1. Spawn RPED, thruster upgrade kit, thruster.
2. Load RPED with thruster upgrade kit.
3. Upgrade thruster.  RPED should have 8 capacitors left in it (note: currently in …
=> RPED Fixes, Minor Cleanup

Resources/Locale/en-US/speech/speech-chatsan.ftl
Chat-san was replacing ATM (automated teller machines) with "at the moment".  Since we have ATMs, this is odd.  Replaced it with another acronym, so if the list gets extended, we don't need to renumber things.  Worst case, we fix a dupe.
bank at the moment
withdrawal-only at the moment
101.3 kPa = 1 at the moment
1. Build and run.
2. Say "ATM".
3. Say "lfg".
4. Say "LFG".
5. LFG.
**Changelog**
=> Chatsan: ATM restored

Resources/Prototypes/_NF/Entities/Effects/portal.yml, Resources/Prototypes/_NF/Objects/Devices/admin_hand_teleporter.yml
Yet another Admeme teleporter fix, blame it on upstream
Added small requested changes from Whatstone
*I do not have the ability to test this, as my local builds are just bonked*
it was broken and now it is repaired
Clone
Run
Spawn admeme teleporter
Place portal on frontier
go to tinnias
Place portal
see it works
**Changelog**
=> Another admeme teleporter fix

Content.Server/Shipyard/Systems/ShipyardSystem.Consoles.cs
In ShipyardSystem, if no listing is provided to GetAvailableShuttles, the function will get the list from the current entity given to the function.  Also, removes the listing being passed in from RefreshUnit (consistency with other current use).
Regression, I broke this in my suggested changes for #1459.
1. Spawn any mothership console.
2. Buy a ship.
3. The purchase should go through.
**Changelog**
No changelog, not yet pulled in serverside.
=> Mothership Console Hotfix

Content.Server/Forensics/Components/FiberComponent.cs, Content.Server/Forensics/Systems/ForensicsSystem.cs, Resources/Locale/en-US/_NF/forensics/fibers.ftl, Resources/Prototypes/Entities/Clothing/Hands/base_clothinghands.yml, Resources/Prototypes/Entities/Clothing/Hands/colored.yml, Resources/Prototypes/Entities/Clothing/Hands/gloves.yml, Resources/Prototypes/_NF/Entities/Clothing/Hands/gloves.yml
DeltaV https://github.com/DeltaV-Station/Delta-v/pull/1455
This also revert
https://github.com/new-frontiers-14/frontier-station-14/pull/1439
And fix missing fiber colors for frontier gloves
=> Unique glove fibers (#1455)

Content.Client/Lathe/UI/LatheMenu.xaml.cs, Content.Server/Lathe/LatheSystem.cs, Content.Shared/Lathe/LatheComponent.cs, Resources/Prototypes/Entities/Objects/Devices/Circuitboards/Machine/production.yml
Apply microwave upgrade logic to lathes - prototype specifies a base coefficient, then multiply this by the upgrade part strength.
Fixed requirements in circuit imprinter, should be buildable again.
Note: hyper-convection lathes _do not_ upgrade their speed (they don't have the parts to upgrade it), this stays at 3x the usual rate.
Lathes weren't upgrading properly, and the circuit imprinter wasn't buildable.
1. Construct a circuit imprinter.
2. Upgrade the circuit imprinter with tier 3 parts.
3. Your stats should match the picture below (300% speed increase, material decreased by 27.75%).
4. Spawn materials, print something.  Amounts shown on UI should be consistent with consumed resources, and should reflect the upgrade to the machine.
**Changelog**
:cl:
- fix: Circuit imprinters are …
=> Lathe Fix: components upgrade time and material cost, circuit imprinter fix

Resources/Maps/_NF/POI/cove.yml, Resources/Prototypes/_NF/Maps/POI/cove.yml, Resources/Prototypes/_NF/Shipyard/base.yml
Added a station records computer to the pirate cove, along with a StationRecords component.
Pirates couldn't recruit more pirates.  A tragedy.
1. Spawn as pirate.
2. Open job slots for more pirates on your new station records console.
3. Join as a pirate.
4. Buy a ship.
5. Use the station records computer on the ship.  It should have listed jobs.
The location of the station records computer, scenically placed between the kitchen door and washroom.
The station records computer on the station.  So many pirate roles.
**Changelog**
I'll leave this one blank.  Change if needed.
=> Pirate Cove: add station records computer, inherit BaseStationRecords

Content.Server/NPC/Systems/NPCCombatSystem.Ranged.cs, Content.Server/StationEvents/Events/BluespaceErrorRule.cs, Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
Fixed Bluespace events having issues with mobs not getting nuked.
Fixed an issue related to players on the floor and bad aim of mobs based on EE code fix
Fixup
Bluespace de spawn mobs, you can spawn a new blue event and wait the timer or edit one on event files to be 120 sec and see them get nuked with the event while players dont.
For the other issue, go on a bed and spawn an AI hostile turret, it should hit you normally without issues.
N/A
N/A
**Changelog**
N/A
=> Small Mobs Fixing

Resources/Maps/_NF/Shuttles/ceres.yml, Resources/Prototypes/_NF/Catalog/Fills/Paper/Shipyard/manuals.yml, Resources/ServerInfo/_NF/Guidebook/Shipyard/Ceres.xml
Update the Ceres to work better with vox, and change its power source to a SUPERPACMAN.
* Remove air canister, change to a mixer with oxy and nitro.
* Move grav gen to engineering section to make room.
* Replace double PACMAN with single SUPERPACMAN.
* Add Ceres user manual item and place it in the engineering section.
* Replace coloured lateral lights with correct type. Somehow I managed to sneak in AlwaysPowered lights, which is clearly illegal.
* Remove air sensors. Pointless.
* Update guidebook.
Vox! 🐔
The change to a SUPERPACMAN was based on observations and experience with using the ship. My reasoning is thus:
* Two PACMANs at 12 kW can run for 56 minutes on a full stack each. That's 56 minutes for *two* stacks of plasma.
* A single SUPERPACMAN at 24 kW can run for 54 minutes on a …
=> Ceres (Update): Vox + tiny tweaks

Resources/Prototypes/_NF/Mail/Items/misc.yml
Fixes cognizine, opporozidone syringe mail items.
Non-functional.
1. Spawn cognizine, opporozidone syringes.
2. Spawn beaker.
3. Inject solutions into beaker, draw them from beaker.
**Changelog**
:cl:
- fix: Cognizine and oppozidone syringe mail items now work properly.
=> Cognizine, opporozidone syringe fixes

Resources/Maps/_NF/Shuttles/mailpod.yml, Resources/Prototypes/_NF/Shipyard/mailpod.yml, Resources/Prototypes/_NF/Shipyard/parcel.yml
=> MailPod (Update)

Resources/Maps/_NF/POI/cove.yml, Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers_tabletop.yml, Resources/migration.yml
Moves ComputerTabletopComputerIFFPOI to ComputerTabletopIFFPOI
Redundant.
1. Spawn.
2. Go to the cove.
3. IFF Computer exists.
**Changelog**
None needed, no visible in-game changes.
=> Migrate ComputerTabletopComputerIFFPOI to ComputerTabletopIFFPOI

Resources/Prototypes/_NF/Entities/Structures/Storage/Closets/wall_lockers.yml
Removes fixtures from wall lockers.  For whatever reason, the fixture inherited from the base closet prevented the wallmount from aligning its opening arc.
Caused a bug where filled chemistry lockers could only be opened from the south, regardless of the rotation of the locker.
1. Spawn a wall.
2. Put a filled chemistry locker in the wall facing north (lit panel to the left).
3. Stand to the north of the wall.  You should be able to open the locker.
4. Stand to the south of the wall.  You should not be able to open the locker.
5. Spawn a medical wall locker, view the PhysicsComponent, confirm there are zero fixtures defined for the object.
6. Spawn a filled chemistry locker, do the same.
**Changelog**
:cl:
- fix: Chemistry lockers should now be openable from the correct direction.
=> Chemistry wall locker: rotation fix for opening

Resources/Maps/_NF/Shuttles/camper.yml
Fixes stacked beds on the camper
**Changelog**
=> Camper Stacked Bed Fix

Resources/Maps/_NF/Shuttles/prospector.yml, Resources/Prototypes/_NF/Shipyard/prospector.yml
- Two canisters for atmos.
- Fixed exterior light.
- Added button outlines.
- Redesigned docking port.
- Replaced generator with running one.
Vox, fixes.
Buy prospector.
**Changelog**
- tweak: Updated Prospector. Exterior light now works.
=> Prospector (Update)

Content.Server/Shipyard/Systems/ShipyardSystem.Consoles.cs
Restores shipyard ping/buzzes on purchases, sales, and errors.  Issues with volume should've been resolved.
I would recommend restoring this to PlayPvs if there aren't other errors - all the other sounds related to the computer (keyboard tapping, ID ejection/insertion) can be heard by other players nearby.
The SoundSpecifier was used instead of the string - this way, the component can specify if the volume or other audio parameters for the playback should be altered.
Quality of life.  It's surprising how much a little ping after a good shift helps you feel.
1. Start a server.
2. Join on two clients.
3. Move both clients to a shipyard console.
4. Purchase a ship on one client, should only be heard on that client.
5. Sell a ship on that client, should only be heard on that client.
6. Eject …
=> Shipyard: restore ping

Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
Saves the old bank balance on randomized characters.
Bug, clears bank balance on character slots.
1. Open Character Select window
2. Select a character with a non-default bank balance.
3. Hit the "Randomize everything" button.
4. Hit Save
5. Your bank balance should be the same.
**Changelog**
:cl:
- fix: The randomize everything button now respects a character slot's bank balance.
=> Save old bank balance on randomized characters

Resources/Prototypes/Recipes/Lathes/tools.yml, Resources/Prototypes/_NF/Entities/Objects/Tools/welders.yml, Resources/Prototypes/_NF/Recipes/Lathes/tools.yml
For https://github.com/new-frontiers-14/frontier-station-14/pull/1720
Why are we getting free weld.
Print from autolate a welder, comes empty.
N/A
N/A
**Changelog**
:cl: dvir01
- tweak: Printed welders now comes empty.
=> Empty Welders

Content.Shared/_NF/Preferences/Loadouts/Effects/RoleBlacklistLoadoutEffect.cs, Content.Shared/_NF/Preferences/Loadouts/Effects/SexLoadoutEffect.cs, Resources/Locale/en-US/_NF/preferences/loadout-effects.ftl, Resources/Prototypes/_NF/Entities/Clothing/Neck/scarfs.yml, Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/jumpsuit.yml, Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/shoes.yml, Resources/Prototypes/_NF/Loadouts/loadout_effects.yml
Two disparate minor features.
Adds titles to the NFSD badges.
Hides topless boxer shorts and the gladiator jumpsuit for female characters.
NFSD: quality of life, PTech now explicitly shows which badges are which.
Loadouts: decency.
1. Open the Character Setup screen
2. Create a female character.
3. Open the Contractor loadout setup, open the jumpsuit tab.
4. Scroll down.  You should not see an entry for boxer shorts or the gladiator jumpsuit.
5. Create a male character.
3. Open the Contractor loadout setup, open the jumpsuit tab.
4. Scroll down.  Select the boxer shorts.
5. Change your sex to Female.
6. Egads.  Save your loadout.  Grey jumpsuit.
7. Start the round.
8. Warp to the NFSD Outpost.  Check the PTech, all of the badges should be properly labelled.
**Changelog**
Minor fix, no …
=> NFSD Badges, Loadout Decency

Resources/Prototypes/_NF/Mail/Items/misc.yml, Resources/Prototypes/_NF/Mail/mail.yml, Resources/Prototypes/_NF/Mail/mailDeliveries.yml
Adds a vulp cannon.  Currently only obtainable as a rare mail drop.
Loadable with little critters.
Fun.
Balance: can cause _mild_ grief if carrying isn't blockable, and I think hitting people with other, high speed people can do damage.
1. Spawn vulp cannon.
2. Spawn goblin.
3. Carry goblin.
4. Right click vulp cannon, "insert Urist McGoblin".
5. Launch goblin.
I will add this later, got lazy.
**Changelog**
:cl:
- add: The lil vulp cannon, capable of launching small humanoids, is now obtainable through mail.
=> Vulp Cannon

Content.Shared/Preferences/Loadouts/RoleLoadout.cs
RoleLoadout checks loadoutGroup subgroups during validation, this was missing before.  Now loadout groups that have subgroups (e.g. Pilot, Mercenary) can select items from those subgroups (i.e. Contractor and/or Pilot items).
Bug in #1717.
1. Open Character Setup for a character.
2. Edit the loadout for the Mercenary job.
3. Equip an EVA Helmet.
4. Save your loadout.
5. The helmet should still be on your character.
6. Start the round.
7. Your character should have an EVA helmet equipped.
**Changelog**
Minor bugfix, feature not yet live, nothing to report.
=> Loadout Hotfix: RoleLoadout checks subgroups in EnsureValid

Resources/Prototypes/_NF/Shipyard/BlackMarket/barnacle.yml, Resources/Prototypes/_NF/Shipyard/BlackMarket/bocakillo.yml, Resources/Prototypes/_NF/Shipyard/BlackMarket/falcon.yml, Resources/Prototypes/_NF/Shipyard/BlackMarket/menace.yml, Resources/Prototypes/_NF/Shipyard/BlackMarket/schooner.yml
Fix prototype used for pirate ships
Doesn't exist
1. Spawn as pirate.
2. Purchase ship.
3. Shuttle console works, station records computer works.
**Changelog**
=> Pirate Hotfix: fix vessel prototype

Resources/Prototypes/_NF/Loadouts/Jobs/Prisoner/face.yml, Resources/Prototypes/_NF/Loadouts/Jobs/Prisoner/survival.yml, Resources/Prototypes/_NF/Loadouts/brigmedic_loadout_groups.yml, Resources/Prototypes/_NF/Loadouts/contractor_loadout_groups.yml, Resources/Prototypes/_NF/Loadouts/mercenary_loadout_groups.yml, Resources/Prototypes/_NF/Loadouts/nfsd_loadout_groups.yml, Resources/Prototypes/_NF/Loadouts/pilot_loadout_groups.yml, Resources/Prototypes/_NF/Loadouts/prisoner_loadout_groups.yml, Resources/Prototypes/_NF/Loadouts/role_loadouts.yml, Resources/Prototypes/_NF/Loadouts/security_guard_groups.yml, Resources/Prototypes/_NF/Loadouts/sheriff_loadout_groups.yml
Mask options are now mandatory.  They came in a survival box before, so you should have one now.  Prisoners also now receive a complimentary breath mask and emergency gas tank.
Survivability, prisoner care (have a heart)
Vox preparedness (mass vox prisoner casualties on the Wasp, sheriff resigns in shame).
1. Buy a wasp, open a prisoner slot, `respawn`
2. Spawn in as an oxygen-breathing prisoner.
3. Your pockets should contain a gas mask and oxygen tank (a small one).
4. Run `respawn`.
5. Spawn in as a nitrogen-breathing prisoner.
6. Your pockets should contain a gas mask and nitrogen tank (a small one).
7. Run `respawn`.
8. Check the Sheriff loadout.  No mask should be visible.
9. Spawn as Sheriff, you should have a mask in your kit.
10. Run `respawn`.
11. Repeat 8-10 for Sergeant and …
=> Loadouts: make masks mandatory

Resources/Audio/_NF/Ambience/attributions.yml
Adds attributions for used sounds with artifact construct
N/A
N/A
:cl:
- add: attributions added for artifact construct
**Changelog**
=> Construct attributions

Content.Client/Shuttles/UI/NavScreen.xaml.cs
In the NavScreen, added a length check before attempting to search for a "-" character.
Some ships' MetaData component do not have a defined name. This causes a crash when accessing their shuttle console during the mapping workflow.
Start local server + client.
Use 'mapping' command to create new map and grid with Praeda
Mapinit the Praeda map
Click the shuttle console
**Changelog**
:cl:
- fix: Fixed a client crash when accessing shuttle console during mapping work.
=> Fix client crash when accessing some shuttle consoles

Resources/Maps/_NF/Test/dev_map.yml
Fixed mail
Fixed powerline
Deep fry
=> dev_map (Update)

Resources/Maps/_NF/Outpost/frontier.yml, Resources/Prototypes/_NF/Shipyard/Sr/bottleneck.yml
Reverts new-frontiers-14/frontier-station-14#1725
=> Revert "Adds SR Shipyard Console to Frontier Outpost"

Content.Shared/Vehicle/SharedVehicleSystem.cs
Fixes vehicles so the honk action does not play twice for the rider.
Mildly annoying, simple fix.  Honk honk.
1. Spawn ATV.
2. Honk, should only play once (no echo).
3. Join on another client.
4. Honk, both clients should hear only one honk (one overall echo).
**Changelog**
:cl:
- fix: Vehicle horns no longer play duplicated sounds for the rider.
=> Undupe client-side honk

Resources/Maps/_NF/Shuttles/hauler.yml, Resources/Prototypes/Catalog/Cargo/cargo_fun.yml, Resources/Prototypes/Nyanotrasen/Entities/Markers/Spawners/Random/boxes.yml
Few stuff I missed.
Random space food.
People buying 6 party crates just for cakes...
A vend machine I missed.
N/A
N/A
N/A
**Changelog**
N/A
=> Removed Missed Food

Resources/Maps/_NF/POI/trade.yml
Adds components to the grid (can/will be moved to the station pending #1737)
I goofed.
1. Spawn, warp to Trade Outpost.
2. Spawn some iron ore on the pallets.
3. Sell the iron ore.
4. Purchase back the iron ore from the cargo market console.
5. It should work.
**Changelog**
:cl:
- fix: Trade Outpost cargo market console now works correctly.
=> Trade depot: add cargo market data component

Resources/Prototypes/Entities/Objects/Tools/tools.yml, Resources/Prototypes/_NF/Entities/Objects/Tools/shipyard_rcd.yml
Changes shipyard RCD (and regular RCD) to share values, increases vend prices to 5000 spesos.
Currently abusable through shipyard market.
1. Warp to cargo depot.
2. Spawn RCD, Shipyard RCD.
3. Sell both, ~1.5k total sale.
4. Purchase both from middle console, ~$10k total.
5. Warp to trade outpost.
6. Spawn RCD, Shipyard RCD.
7. Sell both, ~1k total sale.
8. Purchase both from market access terminal, ~$5k total.
**Changelog**
No changelog, might deserve one though.
=> RCD: add vend prices

Resources/Prototypes/Entities/Clothing/Shoes/magboots.yml
Reduced advanced magboots' price to 200.
Requested.
1. Spawn advance magboots, sell it.
**Changelog**
No CL.
=> 2024 08 05 advanced magboots

Content.Shared/Salvage/SharedSalvageSystem.cs, Resources/Prototypes/Catalog/Fills/Crates/food.yml, Resources/Prototypes/Nyanotrasen/Reagents/Consumable/Food/condiments.yml, Resources/Prototypes/Procedural/salvage_rewards.yml, Resources/Prototypes/Reagents/Consumable/Food/ingredients.yml, Resources/Prototypes/Reagents/biological.yml, Resources/Prototypes/_NF/Catalog/Fills/Items/briefcases.yml, Resources/Prototypes/_NF/Entities/Markers/Spawners/Random/cargo.yml, Resources/Prototypes/_NF/Procedural/salvage_rewards.yml
=> More Food Fixups

Resources/Prototypes/Catalog/Fills/Books/bookshelf.yml, Resources/Prototypes/Catalog/Fills/Crates/service.yml, Resources/Prototypes/Catalog/Fills/Lockers/heads.yml, Resources/Prototypes/Catalog/Fills/Lockers/security.yml, Resources/Prototypes/Catalog/VendingMachines/Inventories/lawdrobe.yml, Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml
Changes remaining references to BookSpaceLaw (introduced upstream) to HyperlinkBookSpaceLaw, which is our space law book.
I goofed in the upstream merge.
1. Spawn as lawyer, start with a usual space law book in your backpack.
2. Spawn lawdrobe, purchase space law book, should be the same.
3. Spawn security lockers, check contents, should include our space law books, not wizden ones.
**Changelog**
No changelog, not in-game yet.
=> Fix BookSpaceLaw references to Hyperlink versions

Content.Server/_NF/Market/Systems/MarketSystem.MarketConsole.cs
Items with StackComponent get incorrect price per unit in their market data.
Also, now uses dynamic price
Spawn a captains space suit
make sure price is not 100$
**Changelog**
=> Market console price fix

Content.Client/_NF/Market/UI/MarketMenu.xaml.cs, Content.Server/_NF/Market/Systems/MarketSystem.MarketConsole.cs, Resources/Maps/_NF/POI/cargodepot.yml, Resources/Maps/_NF/POI/trade.yml, Resources/Prototypes/Catalog/Cargo/cargo_materials.yml, Resources/Prototypes/Catalog/Cargo/cargo_vending.yml, Resources/Prototypes/DeltaV/Catalog/Cargo/cargo_vending.yml, Resources/Prototypes/DeltaV/Entities/Objects/Specific/Service/vending_machine_restock.yml, Resources/Prototypes/Entities/Objects/Specific/Service/vending_machine_restock.yml, Resources/Prototypes/_NF/Catalog/Cargo/cargo_materials.yml, Resources/Prototypes/_NF/Catalog/Cargo/cargo_vending.yml, Resources/Prototypes/_NF/Entities/Objects/Specific/Service/vending_machine_restock.yml
Cleanup the market
Holy moly
Look at new filters
Sell at cargo
N/A
N/A
**Changelog**
N/A
=> Fix Cargo Trade

Content.Server/_NF/PublicTransit/PublicTransitSystem.cs, Resources/Maps/_NF/Shuttles/Bus/publicts.yml, Resources/Maps/_NF/Test/dev_map.yml, Resources/Prototypes/_NF/Maps/debug.yml
Fix metadata
:cl: whatston3
- fix: Public transit should now properly prioritize bus docks.
=> DevNF (Update)

Resources/Maps/_NF/Dungeon/experiment.yml, Resources/Maps/_NF/Dungeon/lava_mercenary.yml, Resources/Maps/_NF/Dungeon/salvage_outpost.yml, Resources/Maps/_NF/Dungeon/snowy_labs.yml, Resources/Maps/_NF/Dungeon/virology_lab.yml
Title
Upd
Dunno
Eh?
**Changelog**
not needed
=> Resaved dungeon templates under recent master

Content.Client/_NF/Latejoin/VesselListControl.xaml.cs
Removes jobless stations from the latejoin UI.
**Note:** ships without jobs like the Menace, Hunter, Infiltrator, and the Bottleneck, will also not be shown.
No real reason to show them if they can't be joined.
1. Start the game, remain in the lobby.
2. Bring up the latejoin UI.
3. No Trade Outpost, Anomalous Lab listed.
Before PR
After PR
**Changelog**
No CL, minor UI feature, no gameplay impact.
=> LateJoin menu: remove jobless stations

Content.Shared/Atmos/Atmospherics.cs
Revert upstream space damage.
Space damage good, makes tiny shuttles dangerous.
Very carefully.
**Changelog**
Nope.
=> Revert upstream space damage

Resources/Maps/_NF/Test/dev_map.yml, Resources/Prototypes/_NF/Maps/debug.yml
=> DebugNF (Update)

Resources/Prototypes/Entities/Structures/Wallmounts/intercom.yml
Remove tool use from prebuilt intercoms, make NFSD/Security/Command/All variants indestructible.
Constructed intercoms are still destructible and fully accessible.
Changes upstream put encryption keys inside intercoms.  Oversight on my part.  Free command key, anyone?
1. Spawn a Throngler.
2. Spawn a base intercom (id `Intercom`), and an NFSD, Security, Command, and All intercom.
3. Try to destroy the intercoms.  The base should be destructible, the others should not.
4. Try to unscrew the intercoms.  It should not work.
5. Build an intercom from scratch.
6. Unscrew the constructed intercom.
7. Insert a key.
8. Spawn another intercom of that type.
9. Check that comms work.
TBD
- [] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an …
=> Intercom: disable tool use, make sensitive versions indestructible.

Resources/Prototypes/Roles/Antags/traitor.yml
Removes selectable preferences for sleeper agents.
We don't have sleeper agents, missed this in the upstream merge.
Open the character setup window, click the Antags tab, no sleeper agent option.
**Changelog**
:cl:
- fix: The option to set character antag preferences for the sleeper agent has been removed, sleeper agents cannot spawn.
=> Remove character preferences for sleeper agent.

Resources/Prototypes/Procedural/dungeon_configs.yml
Adds rock walls to the Mineshaft config.
Looks very odd having expedition maps without enclosing walls.
**Note: this requires #1858 to run properly, otherwise the dungeon job fails to generate properly - pull #1858 in when testing, or use [whatston3:2024-08-14-mineshaft-rockwall-testbench](https://github.com/whatston3/frontier-station-14/tree/2024-08-14-mineshaft-rockwall-testbench)**
1. Run `dungen 1 Mineshaft 300 300` (change the X/Y params if rerunning)
2. Run `tp 300 300` (ditto)
3. Disable lights, look at the dungeon, it's surrounded by rock, like a mineshaft.
4. Go on expedition to a cave biome.  If you have straight hallways with dirt floors, you're on Mineshaft.  Haunted has curved hallways, and steel hallways are other map configs.
A randomly generated Mineshaft dungeon.  Note …
=> Ensure Mineshaft dungeons (expeditions, space dungeons) have actual walls

Resources/Maps/_NF/POI/mchobo.yml
Prevents the Derelict McCargo from being moved.
Consistency with other POIs.
1. Spawn or puchase a ship.
2. Ram the Derelict McCargo.
3. It shouldn't move.
It didn't move.
**Changelog**
:cl:
- fix: The Derelict McCargo is now properly space anchored.
=> Anchor the Derelict McCargo

Resources/Prototypes/Nyanotrasen/Entities/Objects/Consumable/Food/ration.yml
The PSB is no longer edible with the wrapper on, and I made a small set of rewrites to the descriptions.
You don't eat the peel?
1. Spawn PSB (or take the one out of your bag), right click it, no "Eat" option.
**Changelog**
Very small, no changelog.
=> PSB: inedible peel, grammar/style pass

Content.Server/_NF/GameRule/NfAdventureRuleSystem.cs, Content.Shared/_NF/GameRule/PointOfInterestPrototype.cs
Adds a "CanMove" field to POI definitions - defaults to false.  When POIs are initialized, their linear and angular damping is set according to its value, either to 999999 or 0.05 (currently hardcoded).
Adding a POI and forgetting to set the damping strengths is annoying.  Also, makes a clearer distinction between shuttle-like and station-like POIs should we want to support them.
1. Open Resources\Prototypes\_NF\PointsOfInterest\nfsd.yml, set CanMove to true.
2. Spawn in-game, buy a Harbormaster.
3. Bully the NFSD, their station should move.
4. Go bully another POI, shouldn't budge.
**Changelog**
Feature useful for development, shouldn't have visible changes in-game, no changelog.
=> Add CanMove field to POI prototype

Resources/Maps/_NF/Shuttles/stasis.yml
Addresses missing pipe segment under the engineering door.
Adds missing distro pipe with coloring.
Air is good?
Spawn Stasis. Ensure airflow.
**Changelog**
:cl:
- fix: A missing pipe was added to the Stasis.
=> Stasis Pipe Patch

Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Boxes/rifle.yml
Fixes the cartridge type for the rubber bullet box.
Bug.
Spawn rubber bullet box, cycle, rubber bullets.
**Changelog**
:cl:
- fix: Large rubber bullet boxes now contain rubber bullets, not practice bullets.
=> Fix big box of rubber bullets

Resources/Prototypes/Catalog/Fills/Crates/salvage.yml, Resources/Prototypes/Recipes/Reactions/fun.yml
Reverts new-frontiers-14/frontier-station-14#1923
=> Revert "Make plastic more findable and buff recipe"

Content.Client/Shuttles/UI/ShuttleDockControl.xaml.cs
"Undock" buttons can be pressed in the shuttle console's Dock tab when your current dock is undocked.
Better quality of life, slight annoyance.
1. Buy a ship.
2. Undock all docks starting from your currently selected dock (the lighter magenta square).  It should work.
3. Redock all possible docks.
4. Undock all docks with your currently selected dock being the last.  It should work.
The first, second, and fourth docking sequences here cannot currently be done without reselecting the current dock.  The third can.
https://github.com/user-attachments/assets/d0d8d4f5-a528-4ecc-8ec4-62c6a356b233
**Changelog**
🆑
- tweak: The docking tab now allows undocking other docks when the currently selected one is not connected.
=> Shuttle Console: allow undocking other docks when current dock is not connected.

Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/_NF/Recipes/Lathes/chemistry.yml
Adds a vial and small energy cell recipes to the medical techfab.
There is no way to craft a vial at the moment that I am aware of. So this adds a simple recipe to have it accessible along with other pieces of lab equipment.
The medical techfab is also capable of producing a number of tools that require power to operate, but has no way of providing power for those tools. So this adds a base level power cell recipe to allow players to use the things that they create.
Plop down a medical techfab, add materials. Print a vial. Print a small energy cell. 
**Changelog**
Add: Recipe for medical techfab to print vials and small energy cells.
=> Medical techfab vial and small energy cell

Resources/Prototypes/Recipes/Construction/Graphs/structures/girder.yml, Resources/Prototypes/Recipes/Construction/Graphs/structures/girder_clockwork.yml, Resources/Prototypes/Recipes/Construction/Graphs/structures/grille_diagonal.yml
Removes rotation from girders and grilles.  Allows for correct construction of rotated diagonal walls.  Regular walls still snap their rotation and should work fine.
Bug announced on Discord: https://discord.com/channels/1123826877245694004/1269972225096683622
1. Build a diagonal shuttle wall in all four directions, follow instructions, should be built correctly each time.
2. Build a diagonal grille and diagonal clockwork grille in all four directions, follow instructions, should be built correctly each time.
https://github.com/user-attachments/assets/47cc5540-c09b-4306-a864-fb41016ffdcb
**Changelog**
:cl:
- fix: Diagonal shuttle walls are now built in their correct orientation.
=> Remove rotation from girders, diagonal grilles

.github/labeler.yml
Labels PRs with changes to SWSL files as "Shaders", instead of whatever is going on now.
So many "Changes: Shaders".  I messed up a little bit.
Nope.
**Changelog**
Nope.
=> Labeler: better label changes to shaders.

Content.Client/Shipyard/UI/ShipyardConsoleMenu.xaml.cs, Resources/Locale/en-US/_NF/shipyard/shipyard-console-component.ftl
Localizes the shipyard category/class strings.
We appreciate our downstream friends.
Open the shipyard console in the NFSD Outpost and Frontier Outpost.  Check the Size and Class dropdowns, both should display results in plain English, no hyphenated jibberish.
The image below shows the class dropdown in the NFSD shipyard console.
**Changelog**
A little bit pointless, but I'll include it just in case.
:cl:
- add: Shipyard size/class strings have been localized.
=> Localization strings for shipyard categories/class

Resources/Prototypes/Entities/Structures/Machines/fax_machine.yml
Reverts #807.
No longer needed, paper sits nicely on the fax machine when received.
Fixes https://discord.com/channels/1123826877245694004/1282666423256223815
1. Send fax to the bridge.
2. Move to the bridge.
3. Fax sits on the machine without issue.
4. Spawn a long range fax machine.  Spawn an armed mousetrap.  Drag the fax machine over the mousetrap, nothing happens.
Behold the fax machine.  It works just fine, as-is, no issue.
**Changelog**
=> Revert Change fax layer (#807)

Resources/Audio/DeltaV/Voice/Vulpkanin/attributions.yml, Resources/Prototypes/DeltaV/Voice/speech_emotes.yml, Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/packs.yml, Resources/Prototypes/Nyanotrasen/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/Nyanotrasen/Voice/speech_emotes.yml, Resources/Prototypes/_NF/Entities/Objects/base_contraband.yml, Resources/Prototypes/_NF/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/_NF/Voice/speech_emotes.yml
Rounding up a bunch of small bugs and exploits.
Post-update time.
1. Bark. (Use custom emotes for all non-wizden races, e.g. belches, sings...)
2. Bark.
3. Bark.
4. Repeat.
**Changelog**
:cl:
- fix: Harpy and vulpkanin emotes should now work properly from chat.
- tweak: Interdyne herbals packets are no longer worth FUCs.
- fix: Techfabs no longer display an ERROR when running.
=> Bug round up: emote fixes, no value for interdyne cigs

Content.Server/Engineering/EntitySystems/SpawnAfterInteractSystem.cs
Fixes an issue where turrets would be deployed infinitely.
Fixes #1982.
RobustToolbox bug:
Entity is added to queuedDeletionsSet, then QueueDeleteEntity is called:
Entity is added to queuedDeletionsSet again (it was already there), so this fails:
1. Deploy turret, should pop out of hands.
2. You can try using carpets or inflatable walls, though these hit a different code path.  Should still work, though.
**Changelog**
:cl:
- fix: Turrets are properly consumed on deploying.
=> Fix infinite turret deployment: TryQueueDelete->QueueDelete

Content.Server/Instruments/SwappableInstrumentComponent.cs, Content.Server/Instruments/SwappableInstrumentSystem.cs, Resources/Prototypes/DeltaV/Entities/Mobs/Species/harpy.yml
Harpies' instrument sound can now only be swapped by themselves.
Note: this only removes the menu item, but does not restrict the actual change in the instrument itself.
Mild shittery, doesn't make much sense. ~~Just punch them anyways.~~
1. Spawn as a harpy.
2. Right click yourself, set your instrument style.
3. Spawn another harpy.
4. Right click them, can't set their instrument style.
Selecting another harpy - no _Instrument Style_ option.
Selecting yourself, _Instrument Style_ option.
**Changelog**
:cl:
- tweak: Harpies' instrument sound can only be changed by themselves.
=> Harpies' instrument sound can only be changed by themselves

Resources/Prototypes/DeltaV/SoundCollections/harpy.yml, Resources/Prototypes/DeltaV/Voice/speech_emote_sounds.yml, Resources/Prototypes/DeltaV/Voice/speech_emotes.yml, Resources/Prototypes/Voice/speech_emotes.yml
Revises harpy emote sound collections: decreases volume for some louder sounds, removes grating, loud, or long sounds.  Adds \*clicks and \*squishes (would've added our splat.ogg, but it's a bit loud).
Literally #1984.  Less grating on the ears.
Be a harpy, make noises.
If there are noises that are sorely missing, consider selecting snippets to be played, creating new audio clips, and reducing the volume for emote use.
**Changelog**
:cl:
- remove: Loud, grating, long, and irrelevant harpy emote sounds were removed from collections.
- add: The \@clicks and \@squishes are now available for harpies.
=> Revise harpy emote sets & noises.

Content.Client/Power/PowerMonitoringWindow.xaml.cs
Retrieves the TransformSystem in the power monitor through the EntityManager rather than through the IoC manager.
Throws exceptions.
1. Spawn on Frontier.
2. Enter the bridge.
3. Use the power monitor console.
4. It should pop up.
**Changelog**
:cl:
- fix: The power monitoring console should work correctly.
=> Fix power monitoring console dependencies

Resources/Prototypes/_NF/Entities/Objects/Tools/tools.yml
Fixed material compositions for shipyard rcd
it is currently possible to reclaim shipyard rcd for 50 iron sheets and 10 sheets of plastic
the cost to make though, is 10 times less than that. 
fabricate a shipyard rcd and check cost.
reclaim a shipyard rcd in the reclaimer and check output.
none
**Changelog**
:cl:
- fix: shipyard rcd reclaiming for much more than it is to make one.
=> Inherit shipyard rcd material composition

Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/outer.yml
Fixes the biker coat and commented out R&D science coat loadouts.
Bug from the upstream merge, no items in the actual loadout.  These two were the only ones with remaining startingGear artifacts.  My mistake.
1. Select contractor/pilot/merc loadouts, go to the "outer clothing" tab, select the biker jacket.
2. Spawn.  You should be equipped with a biker jacket if you can afford it.
**Changelog**
:cl:
- fix: The biker jacket is purchasable again from Contractor, Pilot, and Merc loadouts.
=> Fix biker coat loadout

Resources/Prototypes/_NF/Entities/Mobs/Species/goblin.yml, Resources/Prototypes/_NF/Mail/Items/misc.yml
Resizes the lil vulp cannon's inventory space.
Nobody fits!
Spawn a felinid, cram them in there.
Spawn a goblin, cram them in there.
**Changelog**
Not in-game, not needed.
=> Fix lil vulp cannon size

Resources/Prototypes/EstacaoPirata/Entities/Objects/Misc/cards.yml, Resources/Prototypes/_NF/Entities/Structures/Machines/fax_machine.yml
Removes noSpawn instances added by recent PRs.
No noSpawn no-nos.
Build.
Lint.
No problems.
**Changelog**
Not relevant to gameplay.
=> More noSpawn to categories.

Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_base.yml
Adds respirator component to humanoid mobs.
The respirator parameters mean that the mob shouldn't actually ever breathe, shouldn't suffocate if they ever _do_ update, and if they did suffocate, they wouldn't take damage from it.
Exceptions from LP Bravo enemies.  Syndicate enemies had internals but not respirators, which caused issues.
1. Generate a few worlds.
2. Any with LP Bravo shouldn't have exceptions from naval deckhands.
3. Warp to LP Bravo.
4. NPCs shouldn't be gasping.
**Changelog**
Not really touching gameplay, just fixing some exceptions.
=> Fix missing respirator exceptions on syndicate naval operative mobs.

Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml, Resources/Prototypes/_NF/Catalog/Fills/Backpacks/duffelbag.yml, Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Boxes/nfsd.yml, Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/explosives.yml, Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Launchers/launchers.yml, Resources/Prototypes/_NF/Entities/Objects/Weapons/Throwable/grenades.yml
Remove duplicated assets "Emp" to "EMP"
Fixed Nfsd boxes
Bugs.
N/A
N/A
N/A
**Changelog**
:cl:
- fix: NFSD EMP Grenades box now has EMP Grenades
=> Emp Fixups

Resources/Maps/_NF/Shuttles/lyrae.yml, Resources/Prototypes/_NF/Shipyard/lyrae.yml
Updated the SBB Lyrae.
Added directional fans.
Streamlined wiring in some places and removed an APC.
Internals and AME fuel lockers.
Reworked lighting.
Changed some tiles and decorations.
Scientist EVA.
New things were added to the game and the ship has been updated accordingly.
Price adjusted to $48000 as it now appraises at $40000 so I applied a 20% markup. This is an overall reduction of $3000.
Checkout the branch, buy the ship.
Uninit. Showing all the stuff.
Initialised.
Nil.
**Changelog**
:cl:
- tweak: Updated the SBB Lyrae
=> SBB Lyrae 1.2

Resources/Maps/_NF/Shuttles/prospector.yml
Replaced tiny fans under airlocks and blast doors.
Removed loose plasma and added plasma fuel locker.
The drop down looks odd but the fan under the plastic flaps is orientated properly.
Compliance.
Check fans.
BREATH.
**Changelog**
🆑 
-tweak: Prospector updated with directional fans.
=> Prospector tiny fan update

Resources/Maps/_NF/Shuttles/loader.yml
Tiny fans replaced with directional fans.
Loose plasma removed, added plasma fuel locker.
Fuel locker set in the place of a maintenance closet. Awarded them a complimentary toolbox as an apology.
compliance
check fuel locker
check fan orientation
**Changelog**
🆑 
-tweaked: replaced loader tiny fans with directional fans
=> Loader directional fan update

Resources/Maps/_NF/Shuttles/garden.yml
Tiny fans replaced with directional fans.
Generator replaced with ship type.
Added plasma fuel wall locker.
Updated atmos tanks for compliance. 
Threw in a complimentary beaker.
Compliance.
Check mixer.
Check power.
Check tiny fans.
**Changelog**
🆑 
- tweak: Garden updated with directional fans and o2/n2 system.
=> Garden Directional Fan Update

Resources/Maps/_NF/Shuttles/chisel.yml
Updates tiny fans with directional fans.
Brings atmos to compliance.
Adds plasma fuel locker.
Remove loose plasma fuel.
Compliance.
Check power.
Check atmos.
Check fans.
**Changelog**
🆑 
- tweak: Chisel updated with directional fans.
=> Chisel directional fan update.

Resources/Maps/_NF/Shuttles/bulker.yml
Updated the Bulker with directional fans.
Replaced internal plastic flaps with the non airtight version.
Removed loose fuel and added a uranium fuel locker.
COMPLIANCE.
Check directional fans.
**Changelog**
🆑 
- tweak: Updated Bulker directional fans, fuel locker and atmos mixer.
=> Bulker Directional Fan Update

Resources/Maps/_NF/Shuttles/bocadillo.yml
Updated Bocadillo with new directional fans.
Added fuel locker. Removed loose fuel.
Updated gas mixer with appropriate values.
Compliance
Test atmos.
Check fans.
IUO one picture.
**Changelog**
🆑 
- tweak: Updated Bocadillo with directional fans.
=> Bocadillo Directional Fan Update

Resources/Maps/_NF/Shuttles/spirit.yml, Resources/Prototypes/_NF/Shipyard/spirit.yml
Updated tiny fans with directional fans.
Small update to the superstructure to accommodate o2/n2 compliance.
Alterations to pipe layout to better fit the new canisters, pictures included.
Small shift to item locations.
Alterations to the guidebook/naming convention following discussion with @Actualcatmoment to take over maintaining the shuttle while they're on hiatus.
COMPLIANCE.
Test atmos. Test power. Check fans. Do the thing.
**Changelog**
🆑 
- tweak: Updated Spirit with directional fans
=> Spirit Directional Fan Update

Content.Server/_NF/Smuggling/Components/StationDeadDropHintExemptComponent.cs, Resources/Prototypes/_NF/Entities/Stations/base.yml, Resources/Prototypes/_NF/Entities/Stations/nanotrasen.yml
Removes dead drop hint generation on vessels - these weren't being populated with actual hints, but they were still being generated on vessel tables, which is odd.
Cleans up some station prototype parenting.
Oversight from #1667.  My mistake.
1. Buy a few Crescents.
2. aghost, fly around on each, look for outstanding papers on tables.
3. There should be none.
**Changelog**
Not currently in game, no changelog needed.
=> Make shuttles dead drop hint exempt

Resources/Maps/_NF/Shuttles/bazaar.yml
Updated tiny fans to be directional fans.
Updated gas mixture for vox compliance.
Removed loose fuel and replaced with fuel locker.
Compliance.
Test fuel locker.
Test atmos.
Check all blast doors and docking ports for directional fans. Note the ship has some weird blast doors above some thrusters.
**Changelog**
🆑 
- tweak: updated Bazaar with directional fans, fuel locker and atmos update.
=> Bazaar Directional Fan Update

Resources/Maps/_NF/Shuttles/Expedition/gourd.yml
AME locker in. Loose fuel out. 
Tiny fans out. Directional fans in.
Why are we here.
**Changelog**
🆑 
- tweak: Replaces Gourd tiny fans with directional fans.
=> Replaces Gourd tiny fans with directional fans.

Resources/Maps/_NF/Shuttles/investigator.yml
Replaces tiny fans with directional fans.
Didn't add a fuel locker. Space wasn't available and the juice didn't seem worth the squeeze in this case. Likely worth taking another look in the future at the engineering area layout.
Compliance.
Check doors. Check blast doors. Check flaps.
**Changelog**
🆑 
- tweak: Replaces Investigator tiny fans with directional fans
=> Replaces Investigator tiny fans with directional fans

Resources/Maps/_NF/Shuttles/placebo.yml
Replaced tiny fans with directional fans.
Rebuilt engineering room to hold o2/n2 tanks.
Removed loose fuel. Added fuel locker.
NO HOPE NO ESCAPE NO HOPE NO ESCAPE NO HOPE NO ESCAPE
Check the fans.
Check atmos.
**Changelog**
🆑 
- tweak: Updates Placebo tiny fans with directional fans.
=> Placebo directional fan update.yml

Resources/Maps/_NF/Shuttles/phoenix.yml
Replaced fans.
Atmos compliance change.
Added fuel locker, removed loose fuel.
Compliance.
Check doors.
Check atmo.
Check fuel.
**Changelog**
🆑 
- tweak: Replaces Phoenix tiny fans with directional fans.
=> Replaces Phoenix tiny fans with directional fans.

Resources/Maps/_NF/Shuttles/Scrap/disciple.yml
Replaced tiny fan with directional fan.
Ensured atmos remained out of compliance.
Compliance.
Check tiny fans replaced with directional fans.
**Changelog**
🆑 
-tweak: Disciple tiny fans replaced with directional fans.
=> Replace Disciple tiny fans with directional fans

Resources/Maps/_NF/Shuttles/Scrap/nugget.yml
Tiny fans replaced with directional fans.
Aggressively ignored all other possible items.
Compliance.
Check the airlock directional fan.
**Changelog**
🆑 
- tweak: Changed Nugget tiny fan to directional fan.
=> Replace Nugget tiny fans with directional fans.

Resources/Maps/_NF/Shuttles/Scrap/orange.yml
Replaced tiny fans with directional fans.
Added one additional directional fan in the airlock in the "conning tower". Seemed broken and bad to have nothing there.
Compliance.
Check tiny fans gone. Check directional fans be where they oughta be.
**Changelog**
:cl: 
- tweak: Replaced Orange tiny fans with directional fans.
=> Replace Orange tiny fans with directional fans.

Resources/Maps/_NF/Shuttles/Scrap/point.yml
Replaced Point tiny fans with directional fans.
Compliance.
Check airlocks. All should be directional fan'd.
**Changelog**
🆑 
- tweak: Update Point tiny fans with directional fans.
=> Update Point tiny fans with directional fans.

Resources/Maps/_NF/Shuttles/Scrap/canister.yml
Replaced tiny fan with directional fan.
Compliance.
Check fans. If you're sweating it's not there.
**Changelog**
🆑 
-tweak: Update Canister tiny fans with directional fans.
=> Update Canister tiny fans with directional fans.

Resources/Maps/_NF/Shuttles/Expedition/decadedove.yml
Replaces tiny fans on the Dove with directional fans.
Remove loose AME fuel. Replace with fuel locker.
Compliance.
Check airlocks for tiny fans.
**Changelog**
🆑 
-tweak: Update Dove tiny fans with directional fans.
=> Update Dove tiny fans with directional fans.

Resources/Maps/_NF/Shuttles/Expedition/dragonfly.yml
Replaced tiny fans with directional fans.
Compliance.
Check fans. Should be directional. But not tiny.
**Changelog**
:cl:
- tweak: Replaces Dragonfly tiny fans with directional fans.
=> Replaces Dragonfly tiny fans with directional fans.

Content.Server/Nyanotrasen/Mail/MailSystem.cs, Content.Shared/RCD/Systems/RCDSystem.cs
Restore opening mail with ID cards.  ID card events are not considered handled by the RCDSystem when the system does nothing.
Small MailSystem using TryComp rather than HasComp
Bug.
1. Spawn mail.
2. Open with ID card.
3. Spawn mail.
4. Open with PDA (with ID inside)
5. Swipe shipyard RCD with card.  Should work.
6. Spawn RCD, use ID card on non-shipyard RCD.  Nothing happens.
**Changelog**
:cl:
- fix: Using your ID card to open mail should work again.
=> Fix: ID card can open mail, minor MailSystem cleanup.

Resources/Locale/en-US/_NF/implant/implant.ftl, Resources/Prototypes/Catalog/VendingMachines/Inventories/medical.yml, Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/civimed.yml, Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/contravend.yml, Resources/Prototypes/_NF/Entities/Objects/Misc/implanters.yml
Adds a label to implanters available in vendors.  Purchasers have no idea what item type it is otherwise.  For the syndicate storage implant, this isn't ideal, but it's better than a new player buying an unknown syndie item for 25k.
This only affects vendor implanters - other implanters are either loose in the world and examinable at will, or exist in loadouts where we can name them appropriately.
Reorders the medical tracker to the top of the list (less scrolling to the most used implanter).
Quality of life.  Bug report: https://discord.com/channels/1123826877245694004/1289945078109831239
1. Visit a CiviMed, look at the inventory, all the implanters should be properly labeled in the stock.
2. Visit a ContraVend, look at the inventory, the implanter should be properly labeled in the …
=> Add a label to implanters available in vendors

Resources/Maps/_NF/Outpost/frontier.yml
Unrotates the Nanotrasen sign on Frontier.
It's sideways.
1. Load the game, look at the sign.
2. It's not sideways.
Before.  Sideways.
After.  Not sideways.
**Changelog**
No.
=> Remove the rotation from the Frontier Nanotrasen sign

Resources/Prototypes/Nyanotrasen/Entities/Structures/Machines/deep_fryer.yml
Cherry-picks Delta-V#1940 (thank you, Radezolid), blacklists PDAs from deep fryer's crispy list.
Currently, damaged deep fryers aren't repairable, and deep frying PDAs changes the name of the ID inside.
1. Try to deep fry a PDA (it shouldn't work).
2. Throngle the deep fryer (it should turn into a machine frame, you should get your components back).
Following the above test regimen:
https://github.com/user-attachments/assets/d380bb35-6504-4443-9b06-113c4852989b
**Changelog**
:cl: Radezolid and whatston3
- fix: Deep fryers are now repairable, PDAs cannot be deep fried.
=> Repairable deep fryer (Delta-V#1940), no crispy PDAs

Resources/Maps/_NF/Shuttles/stasis.yml
Some weird issue where there is no plating under the rear most tiles in the hydroponic bay. Extremely odd. Replaced the tiles and it seems to be working now. I have less than 0 idea how this is even possible. Wont show up unless you attempt to rip the room apart.
This PR also flips one cabinet and fixes some issues with SMES wiring. Everything is functional but this will make it a bit cleaner.
Some atmos scrubbers were moved in the engineering room when addressing wiring. Re-plumbed and re-configured to the air sensor.
The plates couldn't be crowbar'd but could be jacked to reveal only space beneath. This addresses this issue.
The SMES thing is simply a quick wiring optimization. I'm bad.
Attempt to crowbar the tiles in the hydroponic bay. They should come loose. Plating should be …
=> Hotfix for bugged Stasis floor tiles.

Content.Server/_NF/GameRule/NfAdventureRuleSystem.cs, Content.Shared/_NF/GameRule/PointOfInterestPrototype.cs, Resources/Maps/_NF/POI/lodge.yml, Resources/Maps/_NF/POI/tinnia.yml, Resources/Maps/_NF/POI/trade.yml, Resources/Prototypes/_NF/PointsOfInterest/bahamamamas.yml, Resources/Prototypes/_NF/PointsOfInterest/lodge.yml, Resources/Prototypes/_NF/PointsOfInterest/tinniasrest.yml, Resources/Prototypes/_NF/PointsOfInterest/trade.yml
Adds a BusStop field to the POI prototype.
Removes the StationTransitComponent from Tinnia's, the Expeditionary Lodge and the Trade Outpost, sets BusStop in their respective POI prototypes to true.  Sets BusStop to true in Bahama Mama's.
Gets the bus to stop at Bahama Mama's.
Seems easier to forget one component in a 20k line file than comparing a 20 line prototype definition.
1. Ride the bus.
2. VV on the Public Transport Shuttle's grid, look at the TransitShuttleComponent.
3. Set the time to zero, the bus should start FTL.
4. Arrive at your next stop.
5. Let the bus spool down for a bit.
6. Go to step 3 until you arrive back at Frontier Station.
Since none of the POIs now have an inherent StationTransitComponent, they're all being populated through the gamemode.
**Changelog**
:cl:
- …
=> Add BusStop field to POI Prototype

Content.Server/GameTicking/GameTicker.Spawning.cs
Reverts new-frontiers-14/frontier-station-14#1966
Bing may keep legs as a treat.
=> Revert "Remove Bing Guss Legs"

Resources/Prototypes/Entities/Objects/Misc/books.yml, Resources/Prototypes/Entities/Structures/Machines/bombs.yml, Resources/Prototypes/Guidebook/rules.yml, Resources/Prototypes/Guidebook/security.yml, Resources/Prototypes/Guidebook/species.yml, Resources/Prototypes/_NF/Entities/Clothing/Hands/gloves_mob_hostile_npcs.yml, Resources/ServerInfo/Guidebook/Mobs/Species.xml
A few minor fixes in the guidebook and for a minor missing RSI field
Bugs.
1. Open the guidebook, scroll to the bottom, no "Space Law" entry.
2. Open the species page, should load, no error on loading.
3. Check the server log, no error about duplicate Goblin entries.
4. Run `spawn MobMercenarySpecialistAssault`, the merc should have a visible Gestio rifle.
**Changelog**
Minor fixes, not worth a changelog entry.
=> Minor miscellaneous cleanup (Guidebook, missing RSI)

Content.Server/Ghost/GhostSystem.cs
Inverted a condition.
Dumb.
1. readmin
2. warp to Pirate's Cove, should work.
3. warp back to Frontier Outpost.
4. open the ghost warp tab
5. deadmin
6. click on the Pirate's Cove button in the warp tab
7. shouldn't work
8. readmin
9. check admin logs
10. Should have entries for player trying to use an admin-only warp point.
**Changelog**
No changelog, not yet in-game.
=> Admin-only ghost warp fix

Resources/Maps/_NF/Bluespace/vault.yml, Resources/Maps/_NF/Bluespace/vaultsmall.yml
Fixes #2147 
by deleting the BookSecretDocuments entity from the maps. 
Bugfix
Run the addgamerule command for both vaults, see that they once again spawn properly.
Probably none.
=> Fix vault FTL by deleting the missing prototype

Resources/Prototypes/_NF/Shipyard/phoenix.yml
=> Update Phoenix Price

Resources/Prototypes/Recipes/Reactions/biological.yml, Resources/Prototypes/Recipes/Reactions/food.yml
Fixes https://github.com/new-frontiers-14/frontier-station-14/issues/2182
Yummy blood should be less yummy.
N/A
N/A
N/A
**Changelog**
N/A
=> Unblood Your Blood

Content.Shared/Singularity/Components/SharedEmitterComponent.cs, Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml, Resources/Prototypes/Entities/Structures/Power/Generation/Singularity/emitter.yml
Fixes https://github.com/new-frontiers-14/frontier-station-14/issues/2183
Made the emitter no longer work like the mining PTK-800.
Upped power use to 1500
Its not a PTK-800.
N/A
N/A
N/A
**Changelog**
:cl:
- tweak: Removed the lock from emitters, fixed the emitters to no longer work like the PTK-800 for mining.
=> Emitters Changup

Resources/Prototypes/Entities/Objects/Materials/crystal_shard.yml
Crystal shards can be created with 15 water, sugar and ethanol. This allows crystals to be reclaimed for the sugar and ethanol.
There is no current source for ethanol. This seems like a reasonable one. Given that it can be created through the combination of these elements it stands to reason that those elements could be recaptured.
Grind crystals.
**Changelog**
🆑 
- tweak: Crystals produce sugar and ethanol when ground down.
=> Extractable crystal shard

Resources/Prototypes/Recipes/Construction/Graphs/furniture/shelfs.yml
If a shelf is constructed it always faces south. This should address that.
While south is objectively the superior cardinal direction server rules dictate that we show no preferences nor bias against filthy other directioners.
Build shelf in non south directions. Place things upon.
None
**Changelog**
🆑 
- fix: Fix constructed shelves always facing south.
=> Fixes shelf construction rotation

Content.Shared/Maps/ContentTileDefinition.cs, Resources/Prototypes/Entities/Objects/Tools/tools.yml, Resources/Prototypes/Tiles/floors.yml, Resources/Prototypes/Tiles/planet.yml
Fixes the Shovel to act basically identically to a Crowbar, but slower and only for dirt and grass. Why it was using custom components to begin with is beyond me. Might send this fix upstream too later.
1. Bug fix for #2167 
2. Parity with other tools
3. The alternative was un-shoveling the shovel
- Spawn any of the 6 diggable tile types.
- Spawn a shovel.
- Get digging.
- Trip on your shoelaces and stop digging.
- Be sad that you have lost your telekinetic dirt abilities.
N/A
**Changelog**
:cl:
- fix: Fixed Shovel instantly digging on cancel
=> Shovel fixes

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Adds carpets to the tile cutter.
They're currently on the uniform printer. Which is out of circulation pending review of some damn thing or another. Probably abuse. Who knows. This gives the people their bread and circuses to keep the rabble complacent.
Grab the tile cutter from the flat pack vendor. Set it up. Print carpets. Place carpets. Luxuriate. Spill wine on the carpet. Know it's never coming out.
None. 
**Changelog**
🆑 
- add: Adds carpets to the tile cutter.
=> Adds carpets to the tile cutter.

Resources/Prototypes/Entities/Objects/Consumable/Food/meat.yml
Make meatballs cookable again.
Accidentally nuked in the latest upstream merge.
1. Cook a meatball.
N/A
No.
**Changelog**
N/A
=> Make meatballs cookable again

Tools/publish_multi_request.py
=> Publishing workflow changes

Resources/Prototypes/Entities/Objects/Misc/fluff_lights.yml, Resources/Prototypes/Entities/Structures/Furniture/chairs.yml, Resources/Prototypes/Entities/Structures/Walls/girders.yml, Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/base_turret.yml
Fixes following errors flagged in https://github.com/new-frontiers-14/frontier-station-14/pull/2209:
Failed NoMaterialArbitrage [12 s]
Error Message:
Multiple failures or warnings in test:
1)   WeaponTurretContrabandDenyingDeployed increases in price after being destroyed
Entities spawned on destruction: [SheetSteel1, 5]
Assert.That(spawnedPrice, Is.LessThanOrEqualTo(price))
Expected: less than or equal to 0.049999997019767761d
But was:  29.499999999999996d
2)   ClockworkGirder increases in price after being destroyed
Entities spawned on destruction: [SheetBrass1, 2],[PartRodMetal1, 2]
Assert.That(spawnedPrice, Is.LessThanOrEqualTo(price))
Expected: less than or equal to 25.0d
But was:  30.0d
3)   WoodenBench increases in price after being destroyed
Entities spawned on destruction: …
=> Material Arbitrage Fixes

Resources/Maps/_NF/Dungeon/lava_brig.yml
Title, related to https://github.com/new-frontiers-14/frontier-station-14/pull/2209
Fixes
**Changelog**
=> Resaved LavaBrig template

Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/implanter.yml
Adds names to loadouts in implanters.
Bug.
1. Open the loadout selectors.
2. Go to the implanters tab.
3. Wow, names.
Currently not localized.
**Changelog**
:cl:
-fix: Implanters in loadout selection are now properly labeled.
=> Label implanters

Resources/Maps/_NF/Shuttles/skipper.yml
Adds:
- Electric range
- Food assembler
- Kitchen shelf.
- N2/O2 emergency locker in stairwell.
Changes:
- Position of shutter and black door buttons. Both are next to the freezer/bridge.
- Waste atmos pump is now a MAX atmos pump.
- Some food items shifted position.
- Generators are both pushing 10000W to keep up with new power demands.
Removes: 
- One table
- Old grill
Kitchen ship gonna kitchen.
Load ship. Test.
None.
**Changelog**
🆑 
- add: Skipper kitchen equipment.
=> Skipper kitchen equipment hotfix.

Resources/Maps/_NF/Shuttles/Nfsd/wendigo.yml
Fix!
Fix. Skibidi network configurator.
1. Test succeeds.
N/A
No.
**Changelog**
N/A
=> Fix Wendigo network configurator error

Resources/Prototypes/Entities/Objects/Tools/fulton.yml
Remove static price https://github.com/new-frontiers-14/frontier-station-14/pull/2209
its not being sold anywhere
its not used
=> Remove static price

Resources/Prototypes/_NF/Catalog/Fills/Items/weapon_cases_expedition.yml, Resources/Prototypes/_NF/Entities/Objects/Storage/weapon_cases.yml
Changed inventory size to allow storage of weapons with 5x4 footprint, changed container footprint, so one couldn't place long weapon case inside long weapon case.
**Changelog**
=> Long weapon cases fix

Resources/Prototypes/_NF/Shipyard/Nfsd/broadhead.yml, Resources/Prototypes/_NF/Shipyard/Nfsd/inquisitor.yml, Resources/Prototypes/_NF/Shipyard/Scrap/orange.yml, Resources/Prototypes/_NF/Shipyard/Sr/chauffeur.yml, Resources/Prototypes/_NF/Shipyard/bookworm.yml, Resources/Prototypes/_NF/Shipyard/caduceus.yml, Resources/Prototypes/_NF/Shipyard/ceres.yml, Resources/Prototypes/_NF/Shipyard/garden.yml, Resources/Prototypes/_NF/Shipyard/kilderkin.yml, Resources/Prototypes/_NF/Shipyard/lantern.yml, Resources/Prototypes/_NF/Shipyard/mccargo.yml, Resources/Prototypes/_NF/Shipyard/pts.yml, Resources/Prototypes/_NF/Shipyard/spirit.yml
=> Price Fixup Ships

Resources/Maps/_NF/Dungeon/cave_factory.yml, Resources/Maps/_NF/Dungeon/haunted.yml, Resources/Maps/_NF/Dungeon/lava_brig.yml, Resources/Maps/_NF/Dungeon/lava_mercenary.yml, Resources/Maps/_NF/Dungeon/salvage_outpost.yml, Resources/Maps/_NF/Dungeon/snowy_labs.yml, Resources/Maps/_NF/Dungeon/virology_lab.yml
For https://github.com/new-frontiers-14/frontier-station-14/pull/2209
=> Dungeons Maps Fix

Resources/Prototypes/_NF/Shipyard/Expedition/gasbender.yml, Resources/Prototypes/_NF/Shipyard/harbormaster.yml, Resources/Prototypes/_NF/Shipyard/hauler.yml, Resources/Prototypes/_NF/Shipyard/lyrae.yml, Resources/Prototypes/_NF/Shipyard/phoenix.yml, Resources/Prototypes/_NF/Shipyard/piecrust.yml
Fix missing price issues on ships
=> Ships Price Fixup

Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/Entities/Structures/Wallmounts/intercom.yml, Resources/Prototypes/EstacaoPirata/Entities/Objects/Misc/cards.yml, Resources/Prototypes/Nyanotrasen/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/_NF/Catalog/Fills/Lockers/wardrobe_job.yml, Resources/Prototypes/_NF/Entities/Clothing/OuterClothing/goblin_outerclothing.yml, Resources/Prototypes/_NF/Entities/Objects/Consumable/Drinks/drinks_keg.yml, Resources/Prototypes/_NF/Entities/Objects/Consumable/Food/ingredients.yml, Resources/Prototypes/_NF/Entities/Objects/Misc/mortuary_urn.yml, Resources/Prototypes/_NF/Entities/Objects/Tools/welders.yml, Resources/Prototypes/_NF/Entities/Structures/Machines/crate_machine.yml, Resources/Prototypes/_NF/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/_NF/Entities/Structures/Machines/microwave_recipe_assemblers.yml, Resources/Prototypes/_NF/Entities/Structures/Shuttles/thrusters_security.yml, Resources/Prototypes/_NF/Entities/Structures/Storage/Closets/wall_lockers.yml, Resources/Prototypes/_NF/Entities/Structures/atm.yml
Adds components to entity YAML definitions that get added on spawn/init.
Ammo techfab can now accept blueprints.
(see #2263) Test failures (init, save, should match uninit state) - this will reduce the amount of map cruft (weird ContainerContainer definitions, etc.)
Ammo techfab: why not?
Use ATMs, they should work.
Use intercoms, they should work.
Use cards, they should work.
**Changelog**
:cl:
- add: Ammo techfab can now receive blueprints.
=> Entity YAML Cleanup

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Removes the salvage magnet circuitboard from the circuit imprinter.
Currently does nothing, has no value to print, no let down for players expecting it will.
Open circuit imprinter, no salvage magnet board option.
**Changelog**
:cl:
- remove: The salvage magnet is no longer printable from the circuit imprinter.
=> Remove salvage magnet board recipes

Resources/Prototypes/_NF/Entities/Clothing/Back/base_clothing_backpack.yml
Readds slowdown to duffelbags.
Seems to have been an oversight with #2213.
Right now duffelbags are a straight upgrade to other bags.
1. Spawn duffelbags variant
2. Walk around with it equipped/ in hand
3. Examine its values to see slowdown
n/a
n/a
**Changelog**
:cl:
- fix: Duffelbags once again slow their wearer's sprint speed by 10%.
=> readd duffelbag slowdown

Content.Client/Nyanotrasen/Kitchen/Components/DeepFriedComponent.cs, Content.Client/Nyanotrasen/Kitchen/Visualizers/DeepFriedVisualizer.cs, Content.Server/Nyanotrasen/Kitchen/Components/DeepFriedComponent.cs, Content.Server/Nyanotrasen/Kitchen/Components/DeepFryerComponent.cs, Content.Server/Nyanotrasen/Kitchen/EntitySystems/DeepFryerSystem.Results.cs, Content.Server/Nyanotrasen/Kitchen/EntitySystems/DeepFryerSystem.cs, Content.Server/Traits/Assorted/FriedTraitComponent.cs, Content.Server/Traits/Assorted/FriedTraitSystem.cs, Content.Shared/Gravity/SharedGravityGeneratorComponent.cs, Content.Shared/Nyanotrasen/Kitchen/Components/SharedDeepFriedComponent.cs, Content.Shared/Nyanotrasen/Kitchen/Prototypes/CrispinessLevelSetPrototype.cs, Resources/Locale/en-US/nyanotrasen/kitchen/deep-fryer-component.ftl, Resources/Prototypes/Nyanotrasen/Entities/Structures/Machines/deep_fryer.yml, Resources/Prototypes/Nyanotrasen/crispiness_levels.yml, Resources/Prototypes/_NF/Entities/Objects/Consumable/Food/meals.yml, Resources/Prototypes/_NF/shaders.yml, Resources/Textures/_NF/Shaders/spectral.swsl
* Adds a CrispinessLevelSet prototype for deep fried items.  These contain a set of crispiness levels, their entity names, and the shader to apply to them.
* Adds a CrispinessLevelSet for the existing deep fryer, this restores the "deep-fried" state.
* Adds a CrispinessLevelSet for the cauldron that inverts and darkens the colour of the item - this has three states, "spooky", "spectral", and "burned".
Fun.
1. Spawn deep fryer.
2. Deep fry stuff.
3. Should come out and look crispy and golden brown.
4. Spawn cauldron.
5. Deep fry stuff.
6. Should come out and look spectral, ghostly and blue.
**Changelog**
:cl:
- add: Items fried in the cauldron now look ghostly.
=> Spooky cauldron item shader, the return of "deep-fried"

Resources/Maps/_NF/Outpost/frontier.yml, Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Removes Service access from the mass media console (no more JaniTales).
Replaces the medical records console with a mass media console in Frontier Outpost's bridge.
(Happy to swap it back if/when it actually does something, could also replace the surveillance camera computer that's just a TV)
NEWS.
1. Publish a story as a contractor.  It works.
2. Publish a story from Frontier Outpost's bridge.  It works.
**Changelog**
:cl:
- fix: News consoles have had their access removed, anyone can publish news stories.
- tweak: Frontier Outpost's bridge now has a mass media console.
=> Fix Mass Media Console access, add one to Frontier bridge

Content.Server/_NF/GameRule/NfAdventureRuleSystem.cs, Resources/Locale/en-US/_NF/adventure/adventure.ftl
Fixes Discord webhook use - "NT Galactic Bank" had color tags around it, which Discord apparently didn't like.
I goofed.
**Changelog**
=> End of Round Printout Fix

Resources/Maps/_NF/Shuttles/phoenix.yml
Sure love getting a trit canister with my ship based on RNG.
=> Phoenix (Hotfix)

Resources/Prototypes/_NF/Catalog/Fills/Lockers/medical.yml
The filled paramedic voidsuit locker did not container a paramedic voidsuit. Now it does.
Locker should contain what it advertises containing.
Place locker. Open locker. Peer inside. 
**Changelog**
- fix: Restore paramedic voidsuit to filled paramedic voidsuit locker.
=> Filled paramedic voidsuit locker fix.

Resources/Prototypes/_NF/Shipyard/caduceus.yml
Cad price adjusted from 109000 to 115000.
Test demanded minimum price of 110000. This gives us some wiggle room.
Run test.
**Changelog**
- tweak: Adjusted CAD price for arbitrage compliance.
=> Cad price fix

Content.Server/EntityEffects/Effects/PlantMutateGases.cs
Removed by mistake on upstream update
https://github.com/new-frontiers-14/frontier-station-14/pull/667
N/A
**Changelog**
N/A
=> Restore #667

Resources/Prototypes/_NF/Entities/Clothing/Neck/cloaks.yml
Addressed sloppy code, removing an unnecessary node reference.
We live in a society.
Kill a Rosy the Maple Mothroach. The blood is on my hands.
Craft the cloak. Should craft. Without a stream of errors.
**Changelog**
:cl:
- fix: Fixed rosy mothroach cloak recipe error.
=> Test fail correction for Rosy Mothroach Cloak

Resources/Maps/_NF/POI/trademall.yml, Resources/Prototypes/_NF/PointsOfInterest/trademall.yml
This PR coincides with #2365
Tweaks the following things:
- Atmos/Engi:
- Enabled atmos mixer
- Recolored pipes
- Adds atmos vacuum markers
- Adds a dedicated air alarm for the lower shop, moved the vent also
- Added dedicated air alarm and APC to the boarded up space below bridge
- Did not alter the wiring and piping (or lack thereof)
- Removed some old disconnected wiring
- Wired power to the kitchen airlocks
- Added a solar tracker so the solar array actually generates power
- Some extra HV cable has been laid in Engi beneath the generators
- Solars aren't always going to be producing power, so the mall definitely might need a hand sometimes
- Safety:
- Removed HV-electrified grilles along solars
- Other:
- Changed the decal patterns around the docks
- Added windows and light posts to …
=> Trade Mall tweaks

Content.Server/Botany/Systems/BotanySystem.Seed.cs, Content.Server/Botany/Systems/PlantHolderSystem.cs, Content.Server/Storage/EntitySystems/SpawnItemsOnUseSystem.cs
Explicitly drops items next to the user when harvesting plants or getting their seeds.
Gets stuck on vehicles (ATV, wheelchair, etc.).
Because your character is parented to the vehicle, anything spawned at its location will inherit the parent of the vehicle, thus you drag it around.
Fixes #1910.
1. Spawn hydro trays, wheat seeds and a wheelchair.  Get in the wheelchair.
2. Grow wheat.
3. Clip wheat, seeds should fall on the floor.
4. Harvest wheat, wheat should fall on the floor.
5. Take hydro tray with grown wheat outside into space.
6. Clip wheat, harvest wheat, both should be floating in space.
7. Spawn ClothingBackpackPunkLootA, open on wheelchair, contents should fall on the ground (or in space).
**Changelog**
:cl:
- fix: Harvesting while riding vehicles or wheelchairs no longer …
=> Botany: drop items when harvesting or clipping seeds

Resources/Prototypes/_NF/Recipes/Lathes/security.yml
Forgot to add material requirements for empty mags in lathe recipes.
Bug fix
**Changelog**
- fix: Fixed material requirements for empty mags.
=> Empty mag lathe fix

Resources/Prototypes/Entities/Objects/Specific/Hydroponics/tools.yml
Fixed plant bag item size
it was small
Try putting plant bag into toolbelt
:cl:
- fix: Fixed plant bags able to fit inside toolbelt
=> Fix botany bags fit in toolbelt

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
A quick one-line fix to add ingots as valid materials for the cutter machine.
Gold and silver floors are uncraftable through the machine otherwise.
1. Spawn in a cutter machine.
2. Spawn in gold and silver ingots.
3. Insert the ingots into the cutter.
4. Print a gold floor and a silver floor.
5. You now have gold floors and silver floors, yippee!
(I know it's not necessary but I just want to demonstrate that it works on my localhost)
https://github.com/user-attachments/assets/399b37d2-64c8-494e-9f2f-0ef4daddb5d6
**Changelog**
:cl:
- fix: The cutter machine now accepts gold and silver ingots.
=> Add ingot to the list of valid materials to insert in the cutter machine

Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
Removes biomass from recycling pills.
Oversight.  Pills can contain arbitrary contents, and can be created with practically anything.
1. Spawn pill.
2. Recycle pill.
3. No materials.
**Changelog**
:cl:
- remove: Pills no longer give biomass on recycling.
=> No biomass when recycling pills.

Resources/Maps/_NF/Shuttles/Scrap/bison.yml
Replaced the locked airlock and engineering airlocks in front of the power room with their unlocked variants.
Added a plasma fuel locker to the power room. 
Made a quick stab at coloring the pipeline before abandoning that nightmare.
Uh, I was going to work on the generators but... Scrap ship. 
These doors being locked in this fashion doesn't seem well aligned with the general expectations of player experience, scrapship or not.
I'm just a humble spaceship janitor what do I know.
Buy the ship. Feel regret. Test doors. Feel satisfaction.
**Changelog**
🆑 
- tweak: Replaced locked airlocks in Bison with unlocked variants.
=> Replace locked airlocks on Bison

Content.Server/Atmos/EntitySystems/FlammableSystem.cs, Content.Server/Explosion/EntitySystems/TriggerSystem.cs, Content.Server/_NF/Atmos/Components/IgniteOnProjectileHitComponent.cs, Content.Server/_NF/Explosion/Components/TriggerOnProjectileHitComponent.cs, Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Projectiles/crossbow_bolts.yml
Cleans up how crossbow bolts work, particularly those with triggered behaviours.
Adds a few new components for triggering on ProjectileHitEvent (collide is insufficient and causes false positives, like crafting in your hand without any free hands), and for ignition on ProjectileHit (similar to melee hit - if you can do this nicely using Flammable, IgnitionSource and IgniteOnTrigger, do let me know).
Other bolts (syringe, sponge tip) now are destroyed on collision - seems reasonable to me, can change if needed.
Shrapnel effect seems to be sporadic when occurring in walls.  Triggering on ProjectileHit also means that bouncing projectiles either will not trigger (landing eventually without triggering) or will trigger after a bounce - I think this is desirable behaviour, gives crossbows some …
=> Crossbow bolt cleanup, trigger fixes

Content.Shared/Vehicle/SharedVehicleSystem.cs, Resources/Locale/en-US/vehicle/vehicle.ftl
Prevents characters from riding vehicles while pulling something.
https://discord.com/channels/1123826877245694004/1306370018820227215
1. Be a non-lizard.  Drag something around (note the virtual item in your hand).
2. Try to mount an ATV.  Shouldn't work, should get a printout saying you need to stop pulling stuff.
3. Hop into a bed, should work.
4. Be a lizard.  Drag something around (note the lack of a virtual item in your hand).
5. Try to mount an ATV.  Shouldn't work, should get a printout saying you need to stop pulling stuff.
6. Stop pulling stuff.
7. Hop on the ATV.
8. Try to pull something else, shouldn't work.
**Changelog**
:cl:
- fix: Characters can no longer pull objects while riding vehicles that require hands.
=> Vehicles: no riding while pulling

Resources/Maps/_NF/Shuttles/bulker.yml
The Bulker appeared to be missing a cable terminal in its powersetup resulting in no charge for the SMES. This adds one.
While doing my casual look around I also noted a pair of disposal trunks seemingly leading to nowhere in the equipment room. I took care of those.
Not sure if the air alarms being MIA (or at least I didn't see them during a casual look around) is a cause for concern. You'll have to ask someone who gets paid more than I do about that.
Bulker? I hardly know 'er.
Buy ship. Observe power. Ensure SMES gains charge when producing an excess of juice.
**Changelog**
🆑 
- fix: Corrected Bulker missing cable terminal.
=> Adds missing Bulker cable terminal.

Content.Server/Station/Systems/StationRenameWarpsSystems.cs, Content.Server/_NF/GameRule/NfAdventureRuleSystem.cs, Content.Server/_NF/Smuggling/DeadDropSystem.cs, Content.Server/_NF/StationEvents/Events/BluespaceErrorRule.cs
Fixes dead drop warp point visibility.
I goofed.
1. Spawn in, purchase a ship (we need the shipyard map).
2. Find a dead drop (dead drop pinpointer, warp around)
3. VV on the dead drop, set the time to zero, summon the dead drop.
4. Open the warp list menu as an admin, should look something like Picture 1 in Media.
5. Deadmin.
6. Open the warp list menu, should look something like Picture 2 in media.
Picture 1, admin warp list
Picture 2, player warp list
**Changelog**
:cl:
- fix: Syndicate supply drop pod warp points are no longer visible for players.
=> Hotfix: Dead drop warp point visibility

Resources/Prototypes/_NF/Procedural/basalt_vgroid.yml, Resources/Prototypes/_NF/Procedural/cave_vgroid.yml, Resources/Prototypes/_NF/Procedural/chromite_vgroid.yml, Resources/Prototypes/_NF/Procedural/snow_vgroid.yml
They looked cool but they lag the server when they get hit
Lags
N/A
N/A
N/A
**Changelog**
N/A
=> VGroid remove mini grids

Resources/Maps/_NF/Shuttles/crescent.yml
Remove custom fill bluespace beaker from the Crescent's cryotube.
Kudos to Beej and Kyokona for insisting they weren't crazy in seeing a 300u bluespace beaker floating around Frontier.
Custom fill bad.
Buy Crescent, check cryotube. Beaker is bye.
**Changelog**
🆑 
- fix: remove custom fill from Crescent cryotube.
=> Fix - Crescent. Custom fill cryotube.

.github/workflows/build-test-debug.yml, Content.IntegrationTests/Tests/EntityTest.cs, Content.IntegrationTests/Tests/Storage/StorageInteractionTest.cs, Content.IntegrationTests/Tests/UserInterface/UiControlTest.cs
Small part of https://github.com/new-frontiers-14/frontier-station-14/pull/2423 just to restore most working tests.
=> Restore some integration tests

Resources/Prototypes/Atmospherics/gases.yml
Pr to go with https://github.com/new-frontiers-14/frontier-station-14/pull/2412
Canisters base worth up to 1000 to make sure you are not losing money on salvage.
Just pumping plasma into canisters for millions isn't actually atmos work, try to make trit / frezon for ones.
N/A
N/A
**Changelog**
:cl:
- tweak: Atmos gases price ajusted.
=> Update gases price

Resources/Maps/_NF/Shuttles/camper.yml
@AF-Buyrcsp2 Yo, jumped on this one. Give a shout if you have an opinion otherwise. Tagged on Discord as well.
Connects the Camper's scrubber, vent and sensor to the air alarm.
Also cleaned up some invalid network configs in the yml.
Bug report. Needs doing. Vox gonna Vox.
Fire up the Camper. Check the air alarm / connected systems.
**Changelog**
🆑 
- fix: Fix Camper air system networking.
=> Fix - Camper Shuttle disconnected air alarm

Content.Shared/CCVar/CCVars.cs, Content.Shared/_NF/CCVar/NFCCVars.cs
Revert expedition time cooldown
Linked pr: https://github.com/new-frontiers-14/frontier-station-14/pull/2385
Balancing 
since rewards are going to be removed
Only change  is a cvar, it should be as it used to be 
Can test, do an expedition
succeed and fail one
**Changelog**
:cl:
- tweak: Revert expedition cooldown time
=> Revert expedition time cooldown

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
The medicaltechfab was missing an EVA suit, this restores Erhard's departmental suit to that machine.
Looks like an accidental oversight. Restores the department EVA suit to the department lathe.
Print a suit from the medical techfab.
**Changelog**
🆑 
-tweak: Restore medical specialist EVA suit to the medical techfab.
=> Updates Med Lathe w/ service EVA.

Resources/Maps/_NF/Shuttles/Sr/broom.yml
Replased ATM with withdrawal only variant
I goofed
Buy Broon, try to deposit, fail.
**Changelog**
=> Broom ATM fix

Resources/Prototypes/_NF/XenoArch/Effects/utility_effects.yml
Fixes FTL references to new artifact effects.
https://discord.com/channels/1123826877245694004/1310572694286368789
I goofed.
Science!  Double check that the effect hint FTL entries (which are all "artifact-effect-hint-") match with the YAML references.
**Changelog**
:cl:
- fix: Fixed missing artifact localization strings.
=> Fix mop, petting effect hints

Resources/Prototypes/_NF/Shipyard/Sr/broom.yml, Resources/Prototypes/_NF/Shipyard/bocadillo.yml, Resources/Prototypes/_NF/Shipyard/kilderkin.yml, Resources/Prototypes/_NF/Shipyard/spirit.yml
Adjusts the prices of several ships to pass integration tests.
- **LVHI Broom**: 12750 -> ~~12800~~ 13500
- **NC Bocadillo**: 24500 -> ~~24550~~ 25000
- **LVHI Kilderkin**: 48750 -> ~~48900~~ 49500
- **FSB Spirit**: 18000 -> ~~18100~~ 18500
Oh no, woe is me, the prices have fallen pennies short of 5% mark-up, billions of PR integration tests must fall.
This PR's actions should pass. Probably.
**Changelog**
:cl:
- tweak: Slightly increased the prices of the Broom, Bocadillo, Kilderkin, and Spirit.
=> Fix integration tests

.github/workflows/publish.yml
Restore auto-publish.
Restore auto-publish.
**Changelog**
=> Restore auto-publish

Content.Shared/Whitelist/EntityWhitelistSystem.cs
Reverts new-frontiers-14/frontier-station-14#2442
Were fine.
=> Revert "add debug logging to entitywhitelist - DeltaV #2263"

Resources/Prototypes/Entities/Structures/Machines/recycler.yml, Resources/Prototypes/_NF/Entities/Structures/Machines/material_reclaimer.yml
I hate this so much
God forbid I yeet a candy and the machine, might piss it off.
Dont
No
Yes
**Changelog**
N/A
=> I blame Milon for this one

Resources/Maps/_NF/Shuttles/Scrap/orange.yml, Resources/Maps/_NF/Shuttles/Scrap/point.yml, Resources/Maps/_NF/Shuttles/Scrap/scrap-hauler.yml
General reported issues
Xeno queen and plasma that delete your soul
=> Fix scrap ships

Content.Client/Shuttles/UI/ShuttleMapControl.xaml.cs
Adds a check to ensure an entity exists in the map screen before getting its transform.
Map screen list updates occur on scan, when old items are referenced, they lock the console in a state where it generates nonstop exceptions.
https://discord.com/channels/1123826877245694004/1311908827372847145
1. Open two clients.
2. On client 1, purchase two ships.
3. On client 2, board a ship, open the shuttle console UI.
4. On client 2, swap to the MAP tab, scan for objects.
5. On client 1, sell the other shuttle.
6. On client 2, the map should remain usable, but the button for the old ship (that no longer exists) does nothing when pressed.
**Changelog**
:cl:
- fix: The map screen will remain usable when a listed ship is sold.
=> Shuttle console map fix: check entity exists before getting its transform.

Resources/Prototypes/Reagents/medicine.yml
Removes blood restoration from Cryoxadone.
1. Infinite source of cryoxadone when applied on, for example, dead bears.  They just sit and bleed.
2. Not terribly meaningful on dead bodies who can't take extra bloodloss damage, and there are better sources of blood restoration (e.g. saline) on live ones.
1. Buy a Stasis, set up the cryo loop, spawn a bear.
2. Kill it with knives.
3. Chuck the bear in a cryo pod.
4. Apply cryoxadone.
https://www.gettyimages.com/detail/news-photo/pablo-lopez-of-the-miami-marlins-dumps-gatorade-on-brian-news-photo/1408747824
**Changelog**
:cl:
- remove: Cryoxadone no longer restores blood.
=> Remove blood restoration from cryoxadone

Resources/Prototypes/_NF/Entities/Objects/Consumable/Food/meat.yml
Makes breaded chicken cut into breaded cutlets instead of raw ones.
Conservation of breading.
Cut breaded chicken, receive breaded cutlets.
🍗
**Changelog**
Trivial, no changelog.
=> Breaded chicken cuts into breaded cutlets

Resources/Prototypes/Catalog/VendingMachines/Inventories/medical.yml, Resources/Prototypes/Catalog/VendingMachines/Inventories/wallmed.yml, Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/civimed.yml
Adds medtek cartridges to the civi and nanomeds.
I also made the medical folders for the mini infinite because, well, why not? I mean legitimately why not.
Was overlooked when distributing cartridges.
Look in the vends. Observe.
**Changelog**
- add: Adds medtek cartridges to the medical vending machines.
=> Adds medtek cartridges to Nano/Civimed

Resources/Prototypes/_NF/Entities/Structures/atm.yml
Changed the station admin console so it can no longer be broken via crowbar. After crowbarring, it became impossible to reassemble the console due to screwing already being disabled. Prying is now also disabled.
Idiot proofing the station admin console (I am the idiot)
Spawn in a station admin console, see that you can no longer pry off the screen.
Shouldn't be any.
**Changelog**
=> Bugfix: Station admin console can no longer be deconstructed by prying.

Resources/Prototypes/Recipes/Construction/Graphs/furniture/curtains.yml, Resources/Prototypes/Recipes/Construction/Graphs/furniture/seats.yml, Resources/Prototypes/Recipes/Construction/Graphs/furniture/tables.yml
Swaps recipes tagged with CarpetX to use the FloorCarpetX material instead.
Likely upstreaming the table/curtain definitions.
Stacks.  https://discord.com/channels/1123826877245694004/1313953948691857518
Build some carpeted chairs with stacks of carpet, note that one carpet was removed.
**Changelog**
:cl:
- fix: Fancy tables, chairs and curtains now respect carpet stacks.
=> Carpet construction recipes/graphs respect stacks

Content.Client/UserInterface/Systems/Guidebook/GuidebookUIController.cs
Reduces guidebook open depth (the level of expansion from the root) from 2 to 1.
Hides the shipyard manuals, and I think the base categories and the things underneath are _honestly_ easier to pick out at a glance.
Open the guidebook, should look like the picture in Media.
So clean.
**Changelog**
No changelog, trivial change.
=> Reduce guidebook open depth to 1

Content.Server/DeltaV/Mail/EntitySystems/MailSystem.cs, Content.Server/DeltaV/Mail/MailCommands.cs, Resources/Locale/en-US/nyanotrasen/mail.ftl, Resources/Prototypes/_NF/Mail/mail.yml
Fixes the gold wristwatch mail, now contains a wristwatch.
Swaps the MailtoCommand to use the LocalizedCommands class, which allows for completions.  Adds completions to mailto.
Makes mailto easier to use.  Individual entities can be sent through the mail without needing a container, and the target does not need to be within the same station as the teleporter receiving the mail.
Removes unused `bulkmailtest` fluent entries.
Wristwatch: https://discord.com/channels/1123826877245694004/1313077319740424214
mailto: input from quigley, myzumi
Send yourself some mail.  Observe the handy completions.
**Changelog**
:cl:
- fix: Fixed a bug with wristwatch mail packages.
=> Fix wristwatch mail, better mailto command

Content.Server/Emp/EmpOnTriggerComponent.cs, Content.Server/Emp/EmpSystem.cs, Content.Server/_NF/Emp/EmpDescriptionComponent.cs, Content.Server/_NF/M_Emp/M_EmpSystem.cs, Resources/Locale/en-US/_NF/emp/emp.ftl, Resources/Prototypes/Entities/Objects/Misc/subdermal_implants.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/explosives.yml, Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/pistol.yml, Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/explosives.yml, Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml, Resources/Prototypes/_NF/Entities/Structures/Machines/m_emp.yml
Separated from #2350 - adds EMP descriptions to items with EMP effects.
Note: the subdermal implant only puts the values for the EMP effect into the description of the implant, can't do much more there.
Quality of life.  You cannot tell how strong an EMP effect is, or how long it lasts just from looking at it.  This addresses that.
1. Examine objects with EMP effects.
Acrylic paint on canvas.
**Changelog**
:cl:
- add: Items with EMP effects can now be examined to get their effect's duration and strength.
=> EMP: examine UI on items with EMP effects

Resources/Maps/_NF/Outpost/frontier.yml
Fixed an issue with the Frontier Outpost disposals where items flying out of the chute would impact the nearby window and over time destroy the grill underneath. I've solved this issue by shifting the window over.
While a cosmetic issue, this could possibly lead to a larger problem in the future.
- Load the Frontier Outpost
- Look at disposals
**Changelog**
=> Frontier Outpost - Fixed disposals issue

Resources/Prototypes/_NF/Entities/Objects/Fun/toys.yml, Resources/Prototypes/_NF/Entities/Objects/Specific/rehydrateable.yml
Adds a dehydratable sharkminnow.  Looks like a sharkminnow plush (thank you, @Ghost-Prince), behaves like a dehydrated space carp.  Currently unmapped.
!!FUN!!  Bigger, meaner space pets.
Spawn a dehydratable sharkminnow, carry it around, it should act like a sharkminnow plush.
Spray it with water, it should turn into a sharkminnow.
Tingus, Greg and Greg II pose for the camera.
**Changelog**
Not yet in-game, no changelog.  Should be changed if mapped in this PR.
=> Dehydratable Sharkminnow

Resources/Prototypes/Entities/Objects/Misc/treasure.yml, Resources/Prototypes/_NF/Stacks/coins.yml
Makes coins stackable.
Seems natural, good value compression.  People are more likely to pick up coins off of wrecks/salvage if they don't need to trade a bunch of slots for individual ones.
Stack coins, split stacks.
Truly, the world's hardest metal.
**Changelog**
:cl:
- tweak: Coins are now stackable.
=> Stackable coins

.github/workflows/publish.yml
Fixes indentation in publish github job.
Publish job isn't working.
Cargo cult testing: https://github.com/DeltaV-Station/Delta-v/blob/master/.github/workflows/publish.yml
Format matches here: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions - schedule within the on object, cron underneath that, all using 2-space indentation.
Should be good, this time for real.
**Changelog**
:^)
=> Fix publish indentation

Resources/Maps/_NF/Shuttles/Nfsd/empress.yml
Fixes Empress Double Thruster
No moar free sidethrust!
- Spawn Empress
- Go to Right Thruster Wing
- See no Double Thrusters
Before
After
**Changelog**
🆑 
- Removed Empress Double Mapped Thrusters
=> Fix Empress Double Thruster

Resources/Maps/_NF/Dungeon/cave_factory.yml, Resources/Maps/_NF/Dungeon/haunted.yml, Resources/Maps/_NF/Dungeon/snowy_labs.yml, Resources/Prototypes/Procedural/Themes/experiment.yml, Resources/Prototypes/Procedural/Themes/haunted.yml, Resources/Prototypes/Procedural/Themes/lava_brig.yml, Resources/Prototypes/Procedural/Themes/mineshaft.yml, Resources/Prototypes/Procedural/Themes/snowylabs.yml, Resources/Prototypes/Procedural/dungeon_configs.yml, Resources/Prototypes/Procedural/salvage_mods.yml, Resources/Prototypes/_NF/Entities/World/Debris/wrecks.yml, Resources/Prototypes/_NF/Procedural/Themes/cave_factory.yml, Resources/Prototypes/_NF/Procedural/Themes/experiment.yml, Resources/Prototypes/_NF/Procedural/Themes/haunted.yml, Resources/Prototypes/_NF/Procedural/Themes/lava_brig.yml, Resources/Prototypes/_NF/Procedural/Themes/lava_mercenary.yml, Resources/Prototypes/_NF/Procedural/Themes/mineshaft.yml, Resources/Prototypes/_NF/Procedural/Themes/salvage_outpost.yml, Resources/Prototypes/_NF/Procedural/Themes/snowylabs.yml, Resources/Prototypes/_NF/Procedural/Themes/virology_lab.yml, Resources/Prototypes/_NF/Procedural/Themes/wreck.yml, Resources/Prototypes/_NF/Procedural/basalt_vgroid.yml, Resources/Prototypes/_NF/Procedural/cave_vgroid.yml, Resources/Prototypes/_NF/Procedural/chromite_vgroid.yml, Resources/Prototypes/_NF/Procedural/dungeon_configs.yml, Resources/Prototypes/_NF/Procedural/salvage_mods.yml, Resources/Prototypes/_NF/Procedural/scrap_vgroid.yml, Resources/Prototypes/_NF/Procedural/snow_vgroid.yml, Resources/Prototypes/_NF/tags.yml
Fix some broken tiles sets
:cl:
- fix: Fixed a few issues with exped/vgroid configs & maps.
=> Dungeons hotfix

Resources/Maps/_NF/POI/nfsd.yml
What it says on the tin.  Cargo pallet's been deprecated in favour of explicit buy/sell pallet.
Fixes #2555.
Spawn at NFSD outpost.
Sell things using the pallet.
**Changelog**
:cl:
- fix: The cargo pallet in the NFSD Outpost now works properly.
=> Replace NFSD cargo pallet with sell pallet

Resources/Prototypes/Recipes/Lathes/medical.yml
Changed medical techfab plastic cost for jugs from 4 to 1
Y'all want us to use jugs unlimited. We should probably be able to print more than 2 with the default plastic on most medical ships.
Balance woes: 2 jugs recycle to 1 plastic. So no eternal plastic production.
Check recipe on medical techfab.
**Changelog**
🆑 
-tweak: Adjust base plastic cost for jugs in the medical techfab from 4 to 2 sheets.
=> Adjust jug plastic cost in medical techfab.

Content.Server/Nutrition/EntitySystems/FoodSequenceSystem.cs, Resources/Prototypes/Nyanotrasen/Entities/Objects/Specific/Species/felinid.yml
Restore hairball kebabs.
Feature critical.
1. Be human, try to eat hairball, fail miserably.
2. Be moth, try to eat hairball, fail miserably.
3. Be cow, try to eat hairball, fail miserably.
4. Make hairball kebab, burger and taco, find success.
Lawyer on standby for _alleged_ breaches of food safety
Mm, protein.  The protein here is coming from the hairballs in the meal, so the solution transfer is working as expected.
**Changelog**
no
=> Restore hairball burgers/tacos/kebabs

Resources/Locale/en-US/_NF/job/department.ftl, Resources/Locale/en-US/job/department.ftl, Resources/Prototypes/Roles/Jobs/departments.yml, Resources/Prototypes/_NF/Roles/Jobs/departments.yml
Changes department name fields to use department-[ID] values.
Pain.  There's a bunch of uses of department-[ID] that undermine the whole point of the name field in the prototype.
Pick a job, confirm no missing ID strings.
Character Setup Menu
Crew Monitoring Console
**Changelog**
:cl:
- fix: Fixed issues with missing department localization strings.
=> Department Name fields match department-[ID]

Resources/Maps/_NF/POI/trade.yml
In the Trade Outpost, the two pads under the cargo teleporters in cargo bay 1 were sell pads vs. catwalks, this fixes that.
Consistency.
Either load up the trade outpost or visit in-game, go to cargo bay 1, the pads under the teleporter should be catwalk, not sell pads.
Cargo bay 1, note the yellow catwalk under the telepads, and how it isn't green.
**Changelog**
Nah, trivial change.
=> Trade Outpost: Replace sell pallets under the telepads in CB1 with catwalk

Resources/Prototypes/_NF/PointsOfInterest/depots.yml
Adds spawn presets to the alt cargo depot.
Goofed.
Start game, cargo depot should be around.
**Changelog**
:cl:
- fix: Cargo Depots should be spawning normally now.
=> Add alt depot presets

Resources/Maps/_NF/Shuttles/BlackMarket/menace.yml
Sets the IFF to HideLabel for the Menace.
https://discord.com/channels/1123826877245694004/1321874524161052784
Buy Menace.
No IFF label.
Rejoice.
There it is.
**Changelog**
:cl:
- fix: The Menace now spawns with its IFF label hidden.
=> Menace: spawn with IFF hidden

Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/light_rifle.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/magnum.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/pistol.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/rifle.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/SpeedLoaders/magnum.yml, Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/SpeedLoaders/heavy_rifle.yml
Adds mag states for empty mags.
Upstream issues require... hm.
Prettier, regardless, makes more sense.
Spawn any magazine with "any)" in the name, fill it, watch it as it fills.
Each affected magazine (the Novalite extendo assault clippazine never had this issue, kudos to the creator) in a filled state.
**Changelog**
:cl:
- fix: Printed empty magazines now have fill states.
=> Add fill states for "any" mags

Resources/Prototypes/_NF/Entities/Clothing/Head/hats.yml, Resources/Prototypes/_NF/Loadouts/Jobs/Mercenary/head.yml, Resources/Prototypes/_NF/Loadouts/mercenary_loadout_groups.yml
Reintroducing the HoS beret under a new name for mercenary drip (only in mercenary loadout)
For John Moth
Drip
500 speso for very balanced drip
Check the mercenary hats in the loadouts
**Changelog**
=> Commander's Beret (HoS beret for mercs)

Resources/Prototypes/Entities/Structures/Shuttles/station_anchor.yml
Station Anchors sell price brought in line with other Fabs and Flatpack
Station Anchor sell price was 10 times higher than any other fab and is a stock board
Load local host
go to cargo
spawn, depower and unanchor the anchor
no longer get 15381 per anchor
N/A
**Changelog**
=> Update station anchor sell price

Resources/Prototypes/Entities/Structures/Machines/flatpacker.yml
Adds a magnet to the Flatpacker 1001
QoL Upgrade
Load up enviorment
Go to the flatpacker/spawn a flatpacker
See it has a magnet
turn it on
put a pile of mats on it
watch it absorb them
rejoice
[](https://www.dropbox.com/scl/fi/cl5pf51o1tw58nn4zd6d0/Content.Client_2025-01-08_10-25-09.mp4?rlkey=omt3r1ic432g8ns7lltlq497v&st=lym46gev&dl=0)
None
**Changelog**
=> Flatpacker Magnet

Resources/Prototypes/_NF/Entities/Structures/Dispensers/condiments.yml
Copy / pastes the bit of code from the condiment vending machine to allow the condiment dispenser to enjoy hiding behind shutters.
Reagent dispensers can't natively hide behind shutters. This provides it with some useful functionality. Decided to hold off on touching the booze/soda dispenser for now as they're upstream and I know it's merge season.
Place under shutter. Close shutter. Shutter closes now.
Code might have extra stuff. Maybe some things can be removed. I don't know!?
**Changelog**
🆑 
- tweak: Condiment dispenser can now be shuttered.
=> Condiment dispenser can now be shuttered. 

Resources/Prototypes/_NF/Entities/Structures/Lighting/ground_lighting.yml, Resources/_NF/migration.yml
Fixes issues from #2636.
All black lights in LP Bravo start as light tubes with nothing on the walls.
Visit LP Bravo, spawn a red post light.
**Changelog**
Trivial, no changelog.
=> Fix red light fill, powered black light migration

Content.Client/Shuttles/UI/ShuttleNavControl.xaml.cs, Content.Client/_NF/Shuttles/UI/ShuttleNavControl.xaml.cs, Content.Server/_NF/StationEvents/Events/BluespaceErrorRule.cs, Resources/Prototypes/_NF/PointsOfInterest/edison.yml, Resources/Prototypes/_NF/PointsOfInterest/lodge.yml
Fixed radar math, localized names in BluespaceErrorRule, brighter blue for exped lodge/edison.
AAH.
**Changelog**
=> Radar Hotfixes

Resources/Maps/_NF/POI/nfsd.yml
There was an unanchored pipe under the door leading into the interrogation chamber. Oddly it was just vibing but was waiting to be picked up. Presumably for interrogation reasons.
- Replaced unanchored pipe with anchored pipe
- Adds vent system to interrogation room. Finally breathing room.
- Adds firelock to airlock.
- All plugged into the air alarm.
I was accused of leaving random pipes laying around. Disgraceful. 
Visit the interrogation room at the NFSD HQ. Check that no lingering pipes are laying about. Lament that your tools for persuading suspects have been reduced.
Look at this little bastard.
All better.
**Changelog**
🆑 
- fix: Replaced faulty atmos pipe in NFSD interrogation room.
=> NFSD atmos adjustment

Resources/Maps/_NF/POI/nfsd.yml
The last PR examining the unanchored pipe in the NFSD HQ revealed that, honestly, things are kind of in a shambles.
- Small adjustment to the buy pad thing.
- Addition of additional scrubbers and vents to any space where people may be. Such as the front desk thing.
- Addition of vents to the prison cells. What the heck.
- Additional scrubbers in the hallway outside of the detective's office. No more c02 gasping.
- The sheriff's front desk is no longer a death box.
Breath.
Biggest change.
**Changelog**
🆑 
- tweak: Adjusted NFSD vents/scrubbers to create more of a breathable space.
=> NFSD HQ Atmos adjustment

Resources/Changelog/Frontier.yml
Added a changelog entry for the gaslocks, Edison POI, and the changes to the Gasbender/Ambition.
haha oops
**Changelog**
no
=> Gaslock changelog entry

Content.Client/Shuttles/UI/ShuttleNavControl.xaml.cs
In the ShuttleNavControl's Draw call, the IFF labels are placed respecting UI scaling
https://discord.com/channels/1123826877245694004/1330275368434663498
1. Open radar, things should look fine.
2. Engage grandma vision - set UI scaling to something higher.
3. Open radar again, things should still look fine.
4. Reminisce about the good old days.
Need my glasses for this one.
**Changelog**
:cl:
- fix: Radar screens should respect UI scaling.
=> Radar UI scaling fix

Content.Client/Fax/AdminUI/AdminFaxEui.cs, Content.Client/Fax/AdminUI/AdminFaxWindow.xaml, Content.Client/Fax/AdminUI/AdminFaxWindow.xaml.cs, Content.Server/Fax/AdminUI/AdminFaxEui.cs, Content.Server/Fax/FaxConstants.cs, Content.Server/Fax/FaxSystem.cs, Content.Server/Nuke/NukeCodePaperSystem.cs, Content.Server/_NF/StationEvents/Components/RandomFaxRuleComponent.cs, Content.Server/_NF/StationEvents/Events/RandomFaxRule.cs, Content.Shared/Fax/AdminFaxEui.cs, Content.Shared/Fax/Components/FaxMachineComponent.cs, Resources/Locale/en-US/fax/fax-admin.ftl
Faxed papers that are stamp protected are now received as stamp protected.
Not sure if it's necessary to change _every_ instance of the fax messages, but this PR does that.
I goofed.
1. Take a piece of paper, fax it to yourself.
2. Write on it with a Cybersun pen.
3. Stamp it with a sheriff's stamp.
4. Fax the stamped piece of paper.
5. Try to write on the piece of paper with the Cybersun pen, it should sign it.
**Changelog**
Could, I dunno.
=> Fax stamp protection

Content.Server/Light/EntitySystems/EmergencyLightSystem.cs
EmergencyLightSystem: UpdateState gets the current alert from the sector's component, not the current station's.
Emergency lights were stuck on when turning into green state.
1. Spawn comms console, ensure you have all access.
2. Set the alert to Red state.
3. Emergency lights should turn on.
4. Set the alert to Green state.
5. Emergency lights should turn back off.
**Changelog**
:cl:
- fix: Emergency lights should properly turn off when resetting to green state.
=> Emergency Light Fix

Resources/Prototypes/_NF/Entities/Structures/Piping/Atmospherics/binary.yml
Sets the layer of external gaslocks to WallLayer - they should be impassible by small creatures.
Note that portable gaslocks are still AirlockLayer, so mice and mothroaches can hide under them.  Best of luck little buddy.
https://discord.com/channels/1123826877245694004/1330586176628981840
Spawn a gaslock, spawn a mothroach, become mothroach, try to scurry under a gaslock, you should run into it.
Not this time.
**Changelog**
Small change, no changelog.
=> Fix external gaslocks being passable by small creatures.

Resources/Prototypes/Entities/Clothing/OuterClothing/vests.yml
The merc web vest now explicitly parents off of the syndicate web vest's own parents.
The parenting here isn't great - either we can keep the base web vest as-is and define a new NF variant, replacing use in loot tables (not done here) or fix the merc vest itself (as done here).
ContrabandClothing inheritance causes unwanted faction associations.
Fixes #2742.
See #2742.
Minding their own business.
**Changelog**
:cl:
- fix: Mercenary web vests no longer trigger the CDET.
=> Fix merc web vest parenting

Resources/Maps/_NF/POI/nfsd.yml, Resources/Prototypes/_NF/Access/security.yml, Resources/Prototypes/_NF/Roles/Jobs/Nfsd/brigmedic.yml
Updated NFSD's brig layout to include:
- An area for prisoners to withdraw cash for bail, deposit cash for end of shift, and for sale of docked ships. 
- A morgue/crematorium.
- A chemistry locked door to protect the sanctity of the chemlab for the brigmedic
- A security locked shutter button.
- No disposals access for prisoners.
- Replaced the old nasty civilian medbay sign with a brigmed sign.
Updated the brigmedic access to give them medical and chemistry access.
Added a criminal records computer and detective sign to the detective office.
No morgue and no crematorium make officers try to cremate executed prisoners with energy swords. 
Allowing just any officer to enter and use the chemistry area cheapens the brigmedic role.
Without a place within the brig for prisoners to …
=> NFSD Outpost update (morgue/crematorium/prisoner ATM/prisoner sell shipyard) and Brigmed access update

Resources/Prototypes/_NF/Entities/Structures/Machines/lathe.yml
Fix for #2677 regarding missing recipes
Whoops, accident
Check the mercfab after researching xray or laser cannons
Print one
?
Profit
**Changelog**
:cl:
- fix: Fixed missing Mercfab recipes
=> Fix for #2677

Resources/Prototypes/_NF/Entities/Objects/Fun/spaceblade.yml
What it says on the tin.
With this, space blades will now collide with machines, tables and plastic flaps instead of hovering over everything.
Note that mobs walking over spaceblades will now affect them when spinning, and they will collide with loose stuff on the floor.  If we changed this to LowImpassible from MidImpassible, they'd go under tables (and small mobs like mice would affect them when walking over them).
Making a scuffed implementation slightly less scuffed.
Let it rip, throw space blades at things.
**Changelog**
:cl:
- fix: Space blades no longer fly on top of machines.
=> Improve space blade collisions

Resources/Locale/en-US/_NF/devices/pda.ftl, Resources/Prototypes/Entities/Objects/Devices/pda.yml
I've debated about whether or not this should be an upstream PR instead of a Frontier PR but I've decided that the length of rounds on Frontier (6 hours, 12 hours at this time of writing) are enough that players may wish to purge a sentient PDA's player if they are being disruptive. If suggested, I'll just go and peddle this upstream but I'll do it here first.
For one thing, it'll enable players who have a sentient PDA to be able to bring the PDA into line. It also just gives more player agency and a way out if they do not wish to keep a ghost player with them.
It'll also give players the option to remove flashlight spammers.
1. Open up two clients (or get a second tester)
2. Using the admin tools, set the PDA to be a ghost role or force a sentient machine event.
3. The second …
=> Allow players to purge PDA ghost players

Resources/Changelog/Frontier.yml
Just altered the changelog entry for https://github.com/new-frontiers-14/frontier-station-14/pull/2780 to be more in line with the Pull Request guidelines.
I feel like I should've written the changelog for it better if I'm being honest, so I'm rectifying that mistake.
1. Open lobby
2. Open changelog
3. Wow, it's text!
=> Alter changelog entry (#5689) for #2780

Content.Server/Holopad/HolopadSystem.cs, Content.Server/Labels/Label/LabelSystem.cs, Content.Server/_NF/Station/Systems/StationRenameHolopadsSystem.cs, Resources/Prototypes/Entities/Structures/Machines/holopad.yml, Resources/Prototypes/_NF/Entities/Structures/Machines/holopad.yml
=> 2025 01 21 telepad formatting suggestions

.github/workflows/nf-shipyard-tests.yml
Hotfix for shipyard test workflow.
I goofed in the upstream merge.
Believe.
But really, compare the shipyard test workflow with the integration test.
**Changelog**
nope
=> Shipyard test hotfix: build using .NET 9

Content.Client/Materials/UI/MaterialDisplay.xaml.cs
Changes in lathes and ore processors the available eject amounts.
QoL. Makes it much easier to eject larger amounts, instead of having to do per few amounts, can do full stacks.
Spawn lathe/ore processor
Make sure its powered
Insert any material/stacks (example steel)
Open it
Check the UI if all elements align
Try to eject material with each button
**Changelog**
:cl:
- tweak: Lathes can now eject materials in stacks of 30.
=> Change lathe material eject counts to previous amounts

Resources/Maps/_NF/Shuttles/Nfsd/hypnos.yml, Resources/Prototypes/_NF/Shipyard/Nfsd/hypnos.yml
Renames Wendigo to Hypnos.
Hypnos was a primordial deity in Greek mythology, the personification of sleep.  When you think about it, this ship puts other ships to sleep.
It was discussed here:
https://discord.com/channels/1123826877245694004/1334930355618058322
Look, with your special eyes.
None.
None
**Changelog**
:cl:
- tweak: Renamed Wendigo to Hypnos.
=> Rename Wendigo to Hypnos

Resources/Prototypes/_NF/Catalog/Fills/Paper/forms_medical.yml, Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/civimed.yml
Hi.
I added the medical folder found on the nanomed to the civimed, along with a price fix so it's not 3000 spesos. 
General player requests. Seems fine. Just forms.
Try to buy them from a civimed. If you aren't chicken.
**Changelog**
🆑 
- add: Medical forms can now be purchased from the CiviMed.
=> Adds medical paperwork to civimed.

Resources/Maps/_NF/Shuttles/Sr/bottleneck.yml, Resources/Maps/_NF/Shuttles/Sr/broom.yml, Resources/Maps/_NF/Shuttles/Sr/chauffeur.yml, Resources/Maps/_NF/Shuttles/Sr/mailpod.yml, Resources/Maps/_NF/Shuttles/Sr/parcel.yml, Resources/Maps/_NF/Shuttles/Sr/watchdog.yml
This adds the ship variant holopad to the:
- Bottleneck
- Broom
- Chauffeur
- Mailpod
- Parcel
- Watchdog
Due to space issues I was forced to do a little tinkering in the cockpit of the Chauffeur. I have a PR up, #2832, that will allow us to circle back and free up some space in the cockpit to put everything back where it was more or less in the future. In the meantime I placed the pilot webbing and scarf on the cockpit.
Compliance.
Spawn shuttles. Or check yaml, to ensure everything looks good to go.
**Changelog**
🆑 
- add: Holopads to the SR/Frontier support craft.
=> Holopad additions to SR / Frontier Support craft.

.github/mapchecker/config.py, .github/mapchecker/mapchecker.py, .github/mapchecker/util.py, .github/mapchecker/whitelist.yml, .github/workflows/nf-mapchecker.yml, Resources/Prototypes/_NF/Shipyard/Nfsd/paladin.yml, Resources/Prototypes/_NF/Shipyard/Sr/watchdog.yml
Update to the mapchecker to map to a few changed directories.
DeltaV moved to _DV, this wasn't using it.
_Nyano has been removed, this was still using it.
POI directory changed.
Added a set of legal overrides that should match for entity IDs or names that are fine (these should be more specific than the illegal matches in practice).
Fixed the mapchecker running on POIs, they should check without issue.
Removed the expeditionary lodge and the trade outpost from the whitelist.  Frontier should be there, it's a special case, but the NFSD outpost, the cove and LPBravo could be fair game.
Bugs.
Run the mapchecker (should run in this PR), there shouldn't be any "this directory doesn't exist" messages.
**Changelog**
No in-game effect.
=> Mapchecker: legal overrides, POI logic, other fixes

Resources/Prototypes/_NF/Recipes/Cooking/medical_recipes.yml
Corrects crafting recipe to match contained reagent.
Polypen seems to cost 20 reagent to craft, contains 15 reagent. Small correction.
Damn it Dusty.
Check yaml to ensure the pen contains 15 reagent, costs 15 reagent and injects 15 reagent.
**Changelog**
🆑 
- fix: Poly medipen recipe corrected.
=> Polypen recipe correction

Content.Shared/DeviceLinking/Components/TwoWayLeverComponent.cs, Resources/Maps/_NF/POI/nfsd.yml, Resources/Maps/_NF/Shuttles/Expedition/charon.yml, Resources/Maps/_NF/Shuttles/Scrap/scrap-hauler.yml, Resources/Maps/_NF/Shuttles/bazaar.yml, Resources/Maps/_NF/Shuttles/bodkin.yml, Resources/Maps/_NF/Shuttles/hauler.yml, Resources/Maps/_NF/Shuttles/vagabond.yml, Resources/Prototypes/Entities/Structures/conveyor.yml
**LEFT FORWARD
RIGHT BACK
LEFT FORWARD
RIGHT BACK**
left/right forward is fine too
TwoWayLever has a default direction of "to the right" when mapped in the middle (its default state).  This is, by default, mapped to "backwards".  This is dumb.  If you click a lever for the first time, it should go forwards.  Adds the sync sprite to conveyors so the conveyors all appear at the same state.
Changes a bunch of mapped conveyor belts to be left forward, right back.  The NFSD's target loop is set to forward/forward.
No instances of levers were found to be changed to push to the left or right explicitly.
The distinction between in/out is _ignored_ here, merely forward/reversed.  
**NOTE: The Hauler's wacky rotated outside belt was not fixed at the time of writing.**
Driving me nuts.
Check the …
=> Consistent Conveyors

Content.Server/Chemistry/EntitySystems/InjectorSystem.cs
Reapplies the selective service dropper fixes added by @arimah in #1771.  Not sure when they were removed, presumably after https://github.com/space-wizards/space-station-14/commit/c8f2ddc72985172992570fd5f1d60300948b33ed.
I used LINQ to get the string array parameter compared to the original, which changed the reagent whitelist component.
The changes work.  Addresses the issues reported with the service selective dropper.
1. Spawn milk, spawn black pepper, and two large beakers.
2. Pour 20 u milk, 10 u pepper into one of the beakers.
3. Set the reagent filter to Blackpepper.
4. Spam click the beakers for a good long while.
5. Check the total volume of the beakers, it should add to 30, and at no time should the beakers appear empty when they aren't.
**Changelog**
:cl: arimah
- fix: The …
=> Reapply selective service dropper fixes

Resources/Prototypes/_NF/Entities/Objects/Specific/Medical/hypospray.yml
The hypospray could previously hold 5u of reagent in its container. This pr will increase that value by an additional 5, resulting in an ultimate value of 10. This effectively doubles the reagent capacity of the hypospray. 
It was nerfed into the ground because of some person from a long time ago. I believe that the current state of Frontier no longer requires it to exist as such. We can increase it to 10 for now to see if the server can bear the burden.
Fill with reagent. If it maxes out at 5 I screwed up, it should go to ten. Keep filling. 
If it fill to 10 but doesn't fill any more that's good. That's the target. Don't try to fill it with more reagent unless you want to undermine my good name.
If it fills past 10 I screwed up. It should have stopped there. However you failed the trust …
=> Ups Hypospray reserve from 5u to 10u

Content.Server/_NF/Medical/MedicalBountyPriceGunSystem.cs, Content.Server/_NF/Security/Components/ContrabandPriceGunComponent.cs, Content.Server/_NF/Security/ContrabandPriceGunSystem.cs, Content.Shared/_NF/Medical/MedicalPriceGunComponent.cs
The medical and contraband price guns now beep, consistent with the base appraisal tool.
The API of both was swapped out from EntityUid, Component to Entity<Component>.
Consistency.
1. Scan yourself with the contraband tool.  Beep.  Message should be accurate.
2. Spawn and scan a blood red hardsuit with the contraband tool.  Beep.  Message should be accurate.
3. Scan yourself with the medical bounty scanner.  Beep.  Message should be accurate.
4. Spawn an emergency medical pod, scan the occupant.  Beep.  Message should be accurate.
**Changelog**
:cl:
- tweak: Contraband and medical bounty scanners should now beep when used.
=> Contraband and medical price scanners beep

Resources/Prototypes/_NF/Catalog/Fills/Crates/materials.yml, Resources/Prototypes/_NF/Entities/Materials/materials.yml, Resources/Prototypes/_NF/Entities/Structures/Machines/lathe.yml
This adds a new entity entry of 50 units of biomass, a chest to store it and a suffix for the upstream biomass chest to create distinction.
Small entry for mapping on future shuttles that employ the biogenerator. 
Spawn chest. Observe biomass. Could this have been you?
**Changelog**
🆑 
- add: 50 unit biomass chest. Amazing. Amazing. Truly. Just phenomenal.
=> Great job biomass chest w/ 50 units

Resources/Prototypes/Catalog/Cargo/cargo_engines.yml
Switches the crate containing radiation collectors to abstract. Removing them from public sale and bringing us one step closer to finally removing all cargo options from cargo once and for all.
Radiation collectors are broken in their current state and do not currently have a practical place within the energy economy of Frontier. Not to say that they don't have utility on places such as Edison, but at present their purchase and use are generally more exploitative of systems that do not function as intended.
Check cargo listing. Make sure I got the right crate. Mighta goofed up.
**Changelog**
🆑 
- tweak: Remove radiation collectors from cargo.
=> Removes radiation collectors from cargo

Resources/Maps/_NF/POI/trade.yml
This PR should have replaced the withdraw only ATMs with deposit types on the trade station.
A possibly contentious PR. At the moment the Trade Mall allows one to deposit spesos. The Trade Station does not. 
I think I'd like to at least examine the logic there to establish a rule or desired player behavior.
Double check that I didn't muck up or miss an ATM.
**Changelog**
🆑 
- tweak: Changes withdraw only ATMs on the trade station to deposit types.
=> Replaces withdraw only ATMs with deposit ATMs on trade station

Resources/Locale/en-US/lathe/lathe-categories.ftl, Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/Recipes/Lathes/categories.yml, Resources/Prototypes/_NF/Recipes/Lathes/biogen.yml
- Raw ingredient items present in the chef vend now have an equivalent in the Biogenerator (BG). This excludes cheese/butter.
- All standard and medicinal seeds present in the seed-o-whatever it's called can now be created in the BG.
- New seed category for the BG.
- Added a pig biocube option because, well, why not.
An effort to move away from vends where possible strikes me as ideal. Merging the seed inventory to the biogenerator seems logical. With seeds producing 1 biomass when reclaimed allowing a seed to be exchanged for a seed seems reasonable. While this slightly games a system of recycling trending towards loss I believe this is ideal for preventing accidental exhaustion of resources.
Per discussion with maintainers I believe that it would be ideal to address the value of …
=> Bio Generator inventory embiggining

Resources/Maps/_NF/POI/tinnia.yml
A small PR that adds a single ship sale console to Tinnia's to bring it in line with the Bahama Mommy's.
Consistency is key.
Go see. Go sell.
**Changelog**
🆑 
- add: Ship sale console added to Tinnia's
=> Adds a ship sale console to Tinnia's

Resources/Prototypes/Entities/Clothing/Shoes/boots.yml, Resources/Prototypes/_NF/Loadouts/Jobs/Mercenary/shoes.yml
Jackboots: free for mercs, remove the one-off clothing slowdown modifier.  An alternative to #2558.
Why have bizarre one-off stuff?  If general combat slowdown mitigation is needed beyond adrenaline through drugs to be fitting for Frontier gameplay, why not change the mechanics at their root?  This is left for now (it's a separate question), but the jackboots' one-off status is removed.
Apologies to @Radezolid for the lengthy delay on the original feature.
1. Edit your merc loadout - jackboots should be free.
2. Take some damage, you slow down (check your editor).
**Changelog**
:cl:
- remove: Jackboots no longer provide slowdown resistance, but are free in merc loadouts.
=> Jackboots: free for mercs, no slowdown modifier.

Resources/Maps/_NF/Shuttles/bulker.yml
The Bulker was missing an air alarm. Now it isn't.
I also shifted the position of the holopad in the cockpit, which was behind a locker and over a vent.
- I dunno. Compliance maybe? Why AM I doing this?
Buy Bulker. Ensure air is alarmed. Ensure holopad is holopadded. 
**Changelog**
🆑 
- tweak: Add air alarm system to the Bulker
=> Add bulker air alarm

Resources/ServerInfo/_NF/Guidebook/Shipyard/Brigand.xml, Resources/ServerInfo/_NF/Guidebook/Shipyard/Chisel.xml, Resources/ServerInfo/_NF/Guidebook/Shipyard/Comet.xml, Resources/ServerInfo/_NF/Guidebook/Shipyard/Gasbender.xml, Resources/ServerInfo/_NF/Guidebook/Shipyard/Harbormaster.xml, Resources/ServerInfo/_NF/Guidebook/Shipyard/Kestrel.xml, Resources/ServerInfo/_NF/Guidebook/Shipyard/Kilderkin.xml, Resources/ServerInfo/_NF/Guidebook/Shipyard/Lantern.xml, Resources/ServerInfo/_NF/Guidebook/Shipyard/Legman.xml, Resources/ServerInfo/_NF/Guidebook/Shipyard/Pathfinder.xml, Resources/ServerInfo/_NF/Guidebook/Shipyard/Vagabond.xml
Replace the word: 
Unmodifued
With
Unmodified
Correct word
Test1: https://www.merriam-webster.com/dictionary/unmoudified
Test2: https://www.merriam-webster.com/dictionary/unmodified
N/A
- [X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X ] I have added media to this PR or it does not require an ingame showcase.
=> Fixed typo in guidebook - ship manuals

Content.Client/Physics/Controllers/MoverController.cs, Content.Server/Physics/Controllers/MoverController.cs, Content.Shared/Movement/Systems/SharedMoverController.cs
Cherry-picks [space-wizards:space-station-14#34016](https://github.com/space-wizards/space-station-14/pull/34016/).
This fixes issues with rotation on vehicles and in mechs.
Edit: Many thanks to @Tayrtahn for this fix.
Drastically improves hoverbike use.  Makes wheelchairs more tolerable.
1. Hop in a Ripley, move around, rotate your camera, up/down/left/right movement should be relative to the screen's orientation, which should always be at a 90 degree angle to the grid you're on.
2. Hop on a hoverbike, repeat the steps for 1, same outcome.
3. Repeat steps 1 and 2 but rotating in space.  The rotations should be 90 degrees from each other, as you'd expect.
4. Repeat steps 1 and 2 where you move off of one station/ship onto another.  Rotations should be tied to the grid you're on. …
=> Cherry-pick Tayrtahn's space-station-14#34016

Content.Shared/CCVar/CCVars.NPC.cs
Increases the maximum number of simultaneous AI to 256 from 128.
Too many of 'em, they just stop working sometimes.
With absolutely nothing running in-game, this works fine on my potato.  Spawning in 10 Crescents, still fine.
1. Download an autoclicker (optional).
2. Create 210 monkey cubes, trash bins can help you count them.
3. Rehydrate them all.
4. Watch them run around.  None of them should be stuck.
Seconds before disaster.  Don't run this live.
Yup.
**Changelog**
Eh.  In-game effects should be marginal.  "NPCs should react" - yes, they should normally do that.
=> Increase max NPC count to 256

README.md, Resources/Locale/en-US/_NF/adventure/adventure.ftl, Resources/Prototypes/Nyanotrasen/Entities/Objects/Books/hyperlinks.yml
Replace instances of "www.frontierstation14.com" with "frontierstation.wiki.gg" where appropriate.
so that the links don't [404](https://frontierstation14.com/index.php/Space_Law)
Use the space law book. Get sent to the new wiki.
N/A
**Changelog**
:cl:
- fix: Links have been updated to point to the new wiki.
=> update links to point to the new wiki

Resources/Prototypes/Entities/Mobs/NPCs/miscellaneous.yml
Restore upstream damage per sec, avoid entity spam.
=> Update Killer Tomatos

Resources/Maps/_NF/Shuttles/Scrap/scrap-crescent.yml, Resources/Maps/_NF/Shuttles/crescent.yml
Swapped out the locked door in the crescent science lab for a regular science door.
Also swapped on the scrap variant
fixes https://discord.com/channels/1123826877245694004/1340808139372757052
- Spawn the ship
- Open the door
N/A
**Changelog**
No changelog, too minor
=> removed the access locked door from the crescent sci lab

Resources/Maps/_NF/Shuttles/comet.yml
Added a LV cable beneath the cargo hold material reclaimer.
Missing cable causing power issues. Shameful.
Buy ship. Check thruster and light is on.
**Changelog**
🆑 
- fix: Fix missing LV cable on the Comet
=> Comet LV cable fix

Resources/Prototypes/_NF/Entities/Clothing/Ears/headsets.yml
ClothingHeadsetCommon inherits from BaseClearContraband.  Civilian loadout options shouldn't be contraband.
**Changelog**
:cl:
- fix: The civilian headset selection should no longer be labeled as contraband.
=> Clear contraband status from common-only loadout headsets

Resources/Maps/_NF/Shuttles/comet.yml
#2931 made a few changes to suggestions made in the older Comet PR.
* card deck is card box
* uncleanable dirt is gone
* beer growler is a small bottle
Cleans up a bunch of no-rotation entities.
Unrotated entities:
* AirlockEngineering
* FirelockGlass
* Grille
* GasPipeStraight (180 only, equivalent to no rotation)
* TableCounterMetal
* TableReinforced
* WallReinforced
* WallSolid
* WeaponCapacitorRecharger
1. Purchase a comet.
2. Turn subfloor on, check the pipes are all connected.
3. Look around.  Is anything oddly rotated?  It shouldn't be.
Fore view.
Aft view.
**Changelog**
Unneeded.
=> Comet Hotfix: Fix reversions from #2931

Resources/Maps/_NF/Shuttles/caduceus.yml
Adds a holopad to the bridge of the CAD.
Apparently one wasn't added because there's a general sense that the Caladrius will be merged one day. That seems a bit silly as who knows how long that'll take.
Squint at the yml.
**Changelog**
🆑 
- add: CAD gets a holopad.
=> Cad Holopad

Resources/Maps/_NF/POI/edison.yml
Converted the withdraw-only ATMs on Edison to regular ATMs.
Edison is almost entirely set up to be a place to end your shift with a sell shipyard console and cryo facility, but there is nowhere to deposit your money. Before this could be shortcutted by tossing cash on your ship before you sell, but the new lowered sell value makes this no longer viable (and this doesn't work if you aren't playing solo and need to split money). Edison spawns far enough out that the presence of a deposit ATM doesn't seem like it would affect normal play/balance.
Deposit money in the ATM. Go down the hall and cryo with your money secure in your bank account.
None.
**Changelog**
:cl:
- tweak: Edison withdraw-only ATMs changed to regular ones.
=> Swap Edison's withdraw-only ATMs for regular ones.

Resources/Prototypes/Entities/Structures/Walls/walls.yml, Resources/Prototypes/Entities/Structures/Windows/plastitanium.yml
soft fixes by adding a tint to the Plastitanium walls that are not able to be destroyed by any means as well as asking a reference to Skub that hints to the fact that they are not able to be destroyed.
https://github.com/new-frontiers-14/frontier-station-14/issues/2753
People have tried to destroy walls that have no indication that they can in-fact not be destroyed 
load up PR 
Spawn indestructible plast wall 
examine
see attatched media 
- [x ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ x] I have added media to this PR or it does not require an ingame showcase.
**Changelog**
Tweak: made indestructible walls & Windows able to be examined to see that they …
=> adds a color& description hint to indestructible walls used in Multiple UIV's

Content.Server/_EE/Nutrition/EntitySystems/FoodGuideDataSystem.cs, Content.Server/_NF/Medical/EntitySystems/MedicalRecipeDataSystem.cs, Content.Shared/Kitchen/MicrowaveMealRecipePrototype.cs, Resources/Prototypes/_NF/Recipes/Cooking/medical_recipes.yml
Minor MedicalRecipeDataSystem refactor.  Not much to see, should be cleaner.
Clean.
Open the medical recipe guidebook, should work fine.
**Changelog**
No real in-game effect.
=> Minor MedicalRecipeDataSystem refactor

Resources/Maps/_NF/Shuttles/crescent.yml
- Remove AI core.
- Replace room setup in general to be a borg tinkering/charging station. It's a quick room edit but I think it's probably fine.
The Crescent AI core was added due to brain rot in a discord call rampage. It was going to have the appropriate functionality added "soon". Alas, soon has come and gone. People keep trying to make it work. Let's put it to bed for now.
We can add it back when it works and it's not a source of bug reports and confusion.
Buy a Crescent. Go to room. Nod.
**Changelog**
🆑 
- tweak: Crescent AI core removed and room placed with borg recharge/tinker room.
=> IHF crescent ai core removal

Content.Client/Materials/MaterialReclaimerSystem.cs, Content.Server/Materials/MaterialReclaimerSystem.cs, Content.Shared/Materials/SharedMaterialReclaimerSystem.cs
A few proposals to fix some audio issues with the material reclaimer:
1. The reclaimer, under _some set of circumstances_ can start a looping stream that never stops.
2. When directly inserting something into a reclaimer, you do not get audio, but others around you do.
The fix for 1 might work, I wasn't really able to reproduce the issue locally but the new lifecycle seems to make sense and doesn't break the reclaimer under test.
so many bug reports and complaints
Fixes https://github.com/new-frontiers-14/frontier-station-14/issues/2944
Probably https://discord.com/channels/1123826877245694004/1299075187131547668
Insert an item into the reclaimer by hand, should make sound.
Recycle a bunch of stuff, run around on another client while it's processing, the sound shouldn't loop forever. …
=> MaterialReclaimer audio bugfixes

Resources/Prototypes/_NF/Entities/Structures/Storage/Crates/crates.yml
Increase contraband crate timeout from 40 mins to 1 hour
Because smuggling should be slow and sneaky, not a speedrun to get arrested.
- spawn in a contraband crate
- check the delivery due time
n/a
**Changelog**
no changelog, smuggling is sneaky beaky like
=> bump contra crate timeout to 1 hour

Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml
This is a very small PR that removes the enzyme from corn in favor of additional corn oil.
As culinary shuttles are poorly equipped to extract the desired reagent it seems puzzling to me that two task differentiated products would be sourced from a single produce. Corn oil is good for fying and other uses. It would be ideal if chefs could get the thing from the thing.
A consideration here is if bungo should remain an exotic seed or be brought into the more conventional plant inventory so as to provide an accessible gateway to enzyme.
Juice your corn.
**Changelog**
🆑 
- tweak: Enzyme removed from corn. Corn now contains more corn oil.
=> Remove enzyme from corn, add additional corn oil.

Content.Shared/_NF/CCVar/NFCCVars.cs, Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers_shipyard.yml
Increase ship resale
- ~~75% -> 85% for normal shipyards~~
- 50% -> 70% for illegal shipyards
because 50% is extremely low
Check the resale rate ingame.
N/A
**Changelog**
:cl:
- tweak: The shipyard console on the pirate cove's sale tax decreased from 50% to 30%.
=> Increase pirate ship resale rate to 70%

Resources/Maps/_NF/Shuttles/bazaar.yml
Adds disposal piping to the existing network connecting to one disposal that was missing it.
The disposal unit was missing piping that goes to the material reclaimer , this PR fixes it
Spawn bazaar observe that the disposal unit now works
This piping  was missing from the current Bazaar shuttle
**Changelog**
:cl:
- fix: Fixed disposal system on the Bazaar so all disposal units work now.
=> adds disposal piping for a disposal unit that is missing it to the Bazaar

Resources/Prototypes/_NF/Catalog/Fills/Crates/npc.yml, Resources/Prototypes/_NF/Datasets/Names/dog.yml, Resources/Prototypes/_NF/Entities/Mobs/NPCs/emotionalsupportanimals.yml
Adds a less sec-branded McGriff to the emotional support pet list, along with a set of dog names that might better fit a pug.
Gives the base cat and dog a RandomMetadata for the base cat and dog into the base.
pug funny
1. Spawn pug, examine pug, pet pug, dress up the pug.
2. Spawn pet crates until you get a pug.
Finally, pug.
**Changelog**
:cl:
- tweak: Pugs are now available in the emotional support pet spawner.
=> Add a pug to the list of emotional support pets.

Resources/Prototypes/Catalog/VendingMachines/Inventories/seeds.yml, Resources/Prototypes/_NF/Recipes/Lathes/Packs/biogen.yml, Resources/Prototypes/_NF/Recipes/Lathes/biogen.yml
I added bungo to the biogen and seedvend loadout.
With corn losing out on enzyme it seemed reasonable to add the main source to the common circulation. While bungo is technically an exotic I believe it is mostly so due to the nature of the pit. Which is not desirable as a dietary item.
Look at your screen.
Say: "bungo"
Repeat as needed.
Also check the seed vend and the biogenerator.
**Changelog**
🆑 
- add: bungo fruit added to seed vend and biogen list.
=> bungo bungo bungo

Resources/Maps/_NF/POI/medical.yml, Resources/Prototypes/_NF/Entities/Structures/Machines/vending_machines.yml
This PR addresses some missing anchoring parenting from some POI suffixed vending machines. Which can currently be walked off with.
It also replaces some of these vends on the dispatch poi with their POI counterparts in order to prevent people with sticky fingers from accidentally making a sad choice.
It also adds a few new vends to the POI list to batten down the hatches on the POI due to a rash of recent thefts.
I also added one light in the dark hallway outside of the security office. Don't tell.
POI flagged vending machines should have the anchoring parenting in place. Discussed with Whatstone. Seems fine.
Check yaml. Check the vends in the POI.
If this all seems reasonable we can do a tour.
**Changelog**
🆑 
- fix: POI vends missing anchoring component.
- add: Some additional POI …
=> Great Job Updated POI Vend parenting

Resources/Prototypes/_NF/Entities/Structures/Specific/TradingCrates/base.yml
Switched base crates from BaseStructure to BaseStructureDynamic to allow crates to be anchorable/unanchorable
being unable to unwrench your contra crates is... a little broken.
spawn in contraband crate
see that it can be unwrenched and pulled
N/A
**Changelog**
:cl:
- fix: Trade crates can now be anchored and unanchored again.
=> hotfix crates being unwrenchable

Resources/Prototypes/_NF/Maps/debug.yml
Adds an overflow borg slot to the dev map.
Requested.
Swap to NFDev, spawn as borg.
**Changelog**
no effect for players
=> Add borg slot to dev map

Content.Client/Silicons/Borgs/BorgMenu.xaml.cs, Content.Client/VendingMachines/VendingMachineBoundUserInterface.cs, Content.Server/Station/Systems/StationSpawningSystem.cs, Content.Shared/IdentityManagement/Identity.cs, Content.Shared/Station/SharedStationSpawningSystem.cs, Resources/Locale/en-US/_NF/vending-machines/vending-machine-component.ftl
A varied set of changes to avoid BUI exceptions.
Should fix https://discord.com/channels/1123826877245694004/1346718459983302666.
Fixes https://discord.com/channels/1123826877245694004/1347163871604899860.
Avoids https://github.com/space-wizards/space-station-14/issues/35494 and https://github.com/space-wizards/space-station-14/issues/35528.
1. Spawn as a borg with a pseudonym, note your identifier is present (e.g. (Si-1234)).
2. aghost, unlock borg, unscrew borg, open the borg's interface, no exception.
3. Spawn as a borg without a pseudonym, note your identifier is still present.
4. aghost, unlock borg, unscrew borg, open the borg's interface, no exception.
**Changelog**
:cl:
- fix: Vending machine and borg UI errors on open shouldn't result in the game being unplayable.
=> Avoid exceptions in vending machine, borg, and strippable BUI creation

Content.Client/_NF/Atmos/UI/GasSaleMenu.cs, Content.Server/_NF/Atmos/Systems/GasDepositSystem.cs, Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers.yml
A few minor bugfixes for gas sale points and consoles.
Adds suffixes to gas sales consoles, fixes oxygen and nitrogen labels, prices each nearby sales point independently instead of grouping the mixture together and pricing the combination.
Bugs.
1. Spawn connector ports and gas points, connect two together.
2. Spawn a gas sale console nearby, check the modifier, the colour of the rate text should be red if low, green if high.
3. Add a canister of ammonia and oxygen to each point.
4. The canisters should empty fairly quickly.
5. Check the gas sale console, the mixture should be listed correctly as oxygen and ammonia.
6. Examine the sale price, it should be the sum of the mixtures (e.g. pure ammonia and oxygen), rather than the price of a mixture of both contents (50/50 ammonia/oxygen). …
=> Gas sale point bugfixes

Resources/Prototypes/_NF/Loadouts/Jobs/Pirates/trinkets.yml, Resources/Prototypes/_NF/Loadouts/Jobs/SeniorOfficer/trinkets.yml, Resources/Prototypes/_NF/Loadouts/Jobs/StationRep/trinkets.yml
Pouches vent in wrong container
Fixes https://discord.com/channels/1123826877245694004/1348822788885971094/1348822788885971094
**Changelog**
- fix: Fixed incorrect placement of pouches in loadouts.
=> Hotfix: Pouches loadout

Resources/Prototypes/_NF/Catalog/pirate_uplink_catalog.yml
Fixes the freelance radio implant currency, adds a uplink store condition, and removes the (unused) discount category.
I goofed.
Spawn as a civilian.
Purchase freelance radio.
Inject it, `:f aharr`
Enjoy the radio message.
**Changelog**
:cl:
- fix: The freelance radio implant can now actually be purchased by pirates.
=> Fix freelance radio implant

README.md
Fix the bottom readme table.
Bottom text
Write a thing about testing your code.
Technically didn't do anything wrong since markdown isn't code.
Check the rich diff, see that it's a table.
**Changelog**
no
=> Fix the bottom readme table

Content.Server/Administration/ServerApi.cs
Adds AdminOnly as a possible Body Value inside the ServerAPI, making it possible to use Admin Only Messages via Remote.
Does not break existing things.
Was Locally tested, works
We Shall also add Comments via Discord!
- Run
- Send Request
- See a success if admined
**Changelog**
=> Add Support for AdminOnly Messages Via ServerAPI

Resources/Prototypes/_NF/Entities/Clothing/Wallet/base_wallet.yml
Prevents wallets from going into a pocket when opened in-hand.  Similar to backpacks.
Bug.
YAML edit
Activate wallet in-hand, should open.
I had a picture but forgot.
**Changelog**
not yet in-game, no changelog
=> Wallet hotfix: set quickEquip to false

README.md
Removes trailing slashes from all repo URLs in the README
Consistency.
big up the mark down
Read.  Rich diff should look fine.
**Changelog**
no
=> Remove trailing slashes from all repo URLs in the readme

Resources/Maps/_NF/Shuttles/ambition.yml, Resources/Maps/_NF/Shuttles/gasbender.yml, Resources/Prototypes/_NF/Shipyard/ambition.yml, Resources/Prototypes/_NF/Shipyard/gasbender.yml
Moves the Gasbender and Ambition to the standard shipyard console, increases their value to 20% margins on current value.
Gasbender prices increased to $88k based on appraisals of $73.2k, Ambition prices increased to $160k based on appraisals of $133.3k.
Expedition gas harvesting bad.  Value of ship go up, price go up.
Values based on the conservative end of gridappraisals of ~7 ships for both.  Observed deviation was under $1k for both.
1. Check the Frontier shipyard, buy the Gasbender and Ambition.  Both shouldn't error.
2. Appraise the grid, should be close to the numbers mentioned in the PR.
3. Use the Atmospheric category, both should show up.
4. Look for the Expedition category, shouldn't be there.
5. Check for the expedition console, should be an empty computer frame on both. …
=> Move the atmospheric exped ships to the standard shipyard console, revalue to 20% margins.

Resources/Maps/_NF/Shuttles/comet.yml
Fixes Comet fax machine, swaps the prototype over to FaxMachineShip.
Wrong prototype used, doesn't have a power button.
Fixes https://discord.com/channels/1123826877245694004/1351241880884740120
YAML swap.
Buy comet, press power button on the fax machine, it turns off.
no
**Changelog**
no
=> Fix Comet fax machine.

Resources/Prototypes/Entities/Structures/Piping/Atmospherics/binary.yml
Because the dual-port vent is a mapping noob trap
At the request of maptainers
Adds HideSpawnMenu category to the dual-port vent yml
- open the spawn menu
- search vent
- fail to find any dual port ones
**Changelog**
No changelog, only affects mappers (and I guess admins who want to map the dual-port vent inround?)
=> hide dual-port vent from spawn menu

Content.Server/NPC/HTN/HTNSystem.cs
Reverts new-frontiers-14/frontier-station-14#2907
This make it so mobs will attack you after you already died till you get gibbed
=> Revert "Stop NPC's from trying to plan when they wont be able to plan anyways in space"

Resources/Prototypes/Entities/Clothing/Ears/headsets.yml
Add ContrabandClothing parent to freelance headset.
Wasn't associating the wearer with the contraband faction.
One line YAML change.
Wear the non-over-ear freelance headset, get blasted by a CDET turret.
**Changelog**
:cl:
- fix: The freelance headset is now counted as contraband clothing.
=> Add ContrabandClothing parent to freelance headset

Resources/Prototypes/Entities/Objects/Specific/Janitorial/trashbag.yml
The trashbag magnet is no longer set to on by default.
Nothing funnier than not being able to figure out where stuff is going because it's being hoovered into a trashbag that's in a box in a locker. Nothing. This is the peak of comedy.
MagnetEnabled? False!
Grab a trashbag. Hold it next to your opinions on anime. Nothing should happen.
Then turn on the magnet. Observe.
**Changelog**
🆑 
- tweak: Trashbag magnet no longer defaulted to on.
=> Trashbag magnet defaulted to off

Resources/Changelog/Frontier.yml, Resources/Prototypes/Species/species_weights.yml, Resources/Prototypes/_DV/Species/chitinid.yml
Removes Chitinids from being a roundstart species.
Also removes Rodentia from the weighted random species list.
Upon request.
Spawn a bunch of centcomm officers, no ants, no rats.
Spawn a bunch of medical corpses, no ants, no rats.
It never happened.  It's fiction.
https://www.youtube.com/watch?v=GM-e46xdcUo
**Changelog**
changelogs removed
=> Remove Chitinids from roundstart

Resources/Prototypes/_NF/Reagents/toxins.yml
Reduces the strength of antiseptic fluid's effects.
An infinitely respawning source of barf is maybe not so good.
Reducing reagent effect strength.
A full large beaker's worth should add ~40 thirst (you should get thirstier, but mildly so) and deal a whopping 10 poison damage.
1. Chug
2. Chug
3. Chug
4. Chug
5. Notice that, while not dead, you don't feel great.
**Changelog**
no
=> Reduce strength of antiseptic effects

Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml, Resources/Prototypes/Entities/Structures/Power/chargers.yml, Resources/Prototypes/Entities/Structures/Wallmounts/monitors_televisions.yml, Resources/Prototypes/_NF/Entities/Structures/Wallmounts/notice_board.yml
Removes a fixture from the wallmount wall charger.  Without the fixture, its arc behaves as expected regardless of how the ship/station it is on is rotated.
Fixe boog.
Wallmount collision checks use special checks to find the angle and arc for interactions, they use this to selectively ignore the anchored entities on the same tile (i.e. the wall).  If this doesn't happen, the angle that gets passed in is zero, and since the rotation is calculated in worldspace, it's inconsistent with the rotation of the ship.
1. Purchase a ship.
2. On the ship, spawn a wallmount recharger on a wall.
3. Rotate the ship you're on.
4. Hover over the recharger, the interaction highlight should remain green or red regardless of the ship's rotation.
A video (0:21) of the above test procedure run on a Garden …
=> Remove fixture from wallmount cell charger

Content.Server/_NF/Mech/Equipment/EntitySystems.cs/MechForkSystem.cs, Content.Shared/_NF/Cargo/Components/CrateStorageRackComponent.cs, Content.Shared/_NF/Whitelist/Components/NFCrateComponent.cs, Resources/Prototypes/Entities/Structures/Storage/Crates/base_structurecrates.yml, Resources/Prototypes/_NF/Entities/Objects/Specific/Mech/mecha_equipment.yml, Resources/Prototypes/_NF/Entities/Structures/Machines/crate_storage_rack.yml, Resources/Prototypes/_NF/Recipes/Construction/structures.yml
Fixes the power fork whitelist, adds a better description to the crate storage rack and its construction entry.
Cleans up a bit of cruft in the MechForkSystem.
Unintended bug; testing is good.  Description is needed, nothing actually says how many crates the rack can hold.
Adds a new whitelist component for generic crates (needed, there isn't anything that denotes a crate as specifically a crate).
Ideally there's probably a ForkInsertableComponent eventually and this whitelist can be removed, and ideally we can store the size of the item in slots for larger items (e.g. shipping containers).
1. Spawn an Emu with a battery.
2. Try to pick up trash on the ground.  Fail miserably, lose no battery power.
3. Try to pick up a crate.  Pick it up successfully.
4. Try to pick up a trading crate. …
=> Fix power fork whitelist, better crate storage rack description.

Content.Server/Weapons/Ranged/Systems/GunSystem.cs
Forcibly reparents any fired bullets to the same entity that's used for spawning everything else in the GunSystem.
Disabler bolts are parented to your parent, which might be a vehicle.  This is dumb.
SetParent runs matrix multiplication if the parent isn't correct.  This sucks, but if it's not correct, it's not correct.
1. Fly around on a hoverbike, shoot a disabler SMG, should look fine, like the test video below.
2. Shoot an Atreides, should look fine.
3. Shoot a pneumatic cannon, should look fine.
Firing a disabler SMG from a hoverbike.
https://github.com/user-attachments/assets/5f575380-694c-42be-9299-a0980af51fee
**Changelog**
:cl:
- fix: Firing any gun from a vehicle should parent the bullets to the map/grid you're on.
=> GunSystem: Reparent bullets to grid/map

Resources/Prototypes/_NF/Catalog/Fills/Lockers/locker_wallmount.yml, Resources/Prototypes/_NF/Catalog/Fills/StorageFillTemplates/materials.yml
A simple PR that adds a 2x fill wall locker for double bananium generators.
For shuttles packing two DK reactors for whatever reason they may be. Looking at you Gasbender.
Adds a 2x fill wall locker.
Spawn locker. Open locker. Count fuel. Should be 2.
**Changelog**
🆑 
- add: double bananium fuel wall locker
=> Double Banana Fuel

Content.Server/Administration/Systems/BwoinkSystem.cs
Simply switches the Position of the Admin Only/Silent tag with the DC Tag
Makes it prettier
Before;
After;
**Changelog**
=> Switched Position of AdminOnly/Silent and Discord Tag

Resources/Prototypes/_NF/Entities/Structures/Specific/roguesilicons.yml
Changes weird phrasing (bad grammar? whatever, it's wrong) for the rogue AI node structure
1. Spawn in a "rogue AI node"
2. Examine it. The description will not be unusually phrased
Trust me.
=> Changes weird phrasing for the rogue AI node structure

Resources/Prototypes/_NF/Reagents/Consumables/Drink/drinks.yml
reduced ethanol amount in metabolism
so you dont need to fill the glass with 50% dylo
Reduced metabolism ethanol by about 50%
load, drink, dont die
**Changelog**
:cl:
tweak: Frontier drinks now process into less ethanol.
=> Reduces Processed Ethanol amount so it does not kill you after one glass

Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml
Noticed what seemed like an oversight regarding produce not generating biomass when reclaimed. An investigation revealed that a change in parenting somewhere along the line may have caused this feature to be disabled. Possibly in an upstream merge.
Grind up apple. Get biomass. 
The issue of reagent generation + biomass generation is intended to be addressed in another PR. For now the matter seems largely trivial vs. the benefits of simply depositing the produce directly into a biogenerator.
Directed the foodproducebase to the recyclableitemorganictiny entity. Resolving the issue of produce no longer providing biomass.
Throw produce into the reclaimer. Should provide biomass. Slices and food products should not.
**Changelog**
🆑 
- fix: Produce once again provides biomass when reclaimed.
=> Great Job Produce Biomass

Resources/ServerInfo/_NF/Guidebook/Shipyard/Kestrel.xml
A trivial change that removes the Ripley chassis from the Kestrel guidebook.
No Ripley is present. Not even an arguable frame. Buyer remorse abounds. Don't ask about the Pathfinder.
Community raised issue. Easy fix. Full shuttle guidebook audit probably in order someday.
There never was a Ripley.
**Changelog**
🆑 
- tweak: Remove Ripley from Kestrel guidebook.
=> Update Kestrel Guidebook 4/10/25

Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_rogue_ai.yml
Typo with some scrap bot names. They were malfunctionnig, now they are malfunctioning. The keepers of the language will smile upon us this day.
We stan unctions in this house.
Quick text edit
Check yml
**Changelog**
🆑 
- fix: malfunctioinggigng robots are now malfunctioning.
=> malfunctioning scrap unit name typo fix

Content.Shared/Anomaly/SharedAnomalySystem.cs
Anomalous infections should not have their physics changed when being thrown or landing.
Fixes https://discord.com/channels/1123826877245694004/1353447482755125348.
Fixes https://discord.com/channels/1123826877245694004/1349363869449060352.
HasComp to check for anomalous infection.
1. Comment out all artifact effects except Throw.
2. Spawn an anomaly trap.
3. Step into it.
4. Activate the anomaly, get thrown by it.  You should get thrown, land, and be able to walk.
5. Connect with another client.
6. On client 2, spawn a GORILLA gauntlet and an anomaly core.
7. Insert the core into the gauntlet, punch the character from client 1.  They should be thrown, land, and still be able to walk.
8. On client 2, pick up the character from client 2 and throw them.  They should be thrown, land, and …
=> AnomalySystem: do not reset infectious physics

Content.Shared/Foldable/FoldableSystem.cs
Changes the conditions for storage and buckling interactions of foldable objects.  The description in the component (which is reasonable) says that unfolded items should be uninserted, but these conditions are reversed.  Also, I assume that if you can unfold yourself in a container (e.g. a hat), you're probably fine to ignore that and be inserted into a container.
There's another insertion event that's handled with these conditions, I don't know why they don't all use the same condition.
Fixes https://discord.com/channels/1123826877245694004/1359763277541802054
Cancellable actions had their cancel conditions changed.
1. Jam a folded body bag in a locker, be astounded that it works.
2. Spawn two caps, fold one, put them both in a locker.
3. Spawn a folded wheelchair and a deployable …
=> FoldableSystem: fix blocking conditions.

Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs
Resets the FTL coordinate range so we avoid precision issues from large coordinate values.
Fixes https://discord.com/channels/1123826877245694004/1360373441521516544.
Sets the effective FTL coordinate range to (-20000, 20000].
1. Open Resources\Prototypes\_NF\public_transit_routes.yml.
2. Add `travelTime: 5` and `waitTime: 5` to all routes.
3. Start a round.
4. Ride the bus (this will take maybe two minutes).
5. Check the coordinates of the bus on the shuttle console.
6. When in FTL, your X coordinates should always be between -20k and 20k.
7. Each jump should increase by ~2.5k (5x the 500 offset between shuttles).
8. Jump 8 times, you should loop over from +20k to -20k.
Bus coordinates in FTL.  They can be negative now.
**Changelog**
:cl:
- fix: Travelling into FTL should no longer cause …
=> Rollover FTL coordinates

Resources/Prototypes/_NF/Roles/Jobs/Nfsd/senior_officer.yml
Fixes senior officer playtime - deputy and security dept. were reversed.
Typo?  I blame Salv.
Getting this useful, uncontroversial bit out of #3241.
All YAML.
Load up game as new player, check senior officer time reqs in the character select screen.
**Changelog**
:cl: MagosAmphrose
- fix: Corrected senior officer playtime requirements.
=> Fix senior officer playtimes

Content.Server/_NF/Shipyard/Systems/ShipyardSystem.Consoles.cs, Content.Shared/_NF/Shipyard/Components/SharedShipyardConsoleComponent.cs, Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers_shipyard.yml
Localizes the captain string you get when purchasing a ship.
Upon request.
Left it as a LocId vs. a JobPrototype for arbitrary strings.
1. Purchase a ship.
2. You are the captain now.
3. Respawn as a Deputy.
4. Purchase an NFSD ship.
5. You are not the captain now.
not really
**Changelog**
none, little in-game effect locally
=> Localize captain string

Resources/Prototypes/_NF/Shipyard/vitalis.yml
Fixes the Vitalis' vessel definition.
Makes the description 20% less german.
Bad parenting.
yammels
Buy ship, get IFF.
**Changelog**
no
=> Shuttle (Hotfix): Vitalis

Resources/Prototypes/Entities/Structures/Piping/Atmospherics/trinary.yml
What started as an earnest fix turned into a cherry-pick (https://github.com/space-wizards/space-station-14/pull/36428)
Bug.
yammels
1. Spawn on Frontier Outpost, put a tile down over a gas mixer, it shows up under the mixer.
no
**Changelog**
:cl: DinnerCalzone
- fix: Fixed gas mixers and pneumatic valves being hidden by floor tiles.
=> Fix mixer/pneumatic valve visibility (cherry-pick wizden#36428)

Tools/_NF/dump_admin_logs.py
Adds a tool to dump admin logs.
Upon request.
Tool written in python using psycopg2 to process and dump admin logs in monthly chunks up to a given date.
The user that the script connects as now requires TEMPORARY access to make a temporary table.  All joins are explicit, there are no fetchall commands, everything is per row, and we run forward using a cursor in batches of 500.
1. Set up your game to use Postgres.
Your server_config.toml file should include lines similar to the following.  If you're not running at localhost:5432 or connecting to a database called "ss14" through the "postgres" user, you will need to set other parameters.
```
[database]
engine = "postgres"
pg_password = "my_postgres_password"
```
2. Install python 3 and psycopg2 if needed.
3. Run the tool.  Using the above …
=> Admin log dump tool

Resources/Prototypes/_NF/Shipyard/Sr/duchess.yml
Bumped the shuttle price to ~~25550~~ 25000.
Ship-test not happy.
yml
1. PR something that touches existing shuttle, see no errors.
2. (Also buy NT Dutchess, note the new price)
none
**Changelog**
don't think it's needed
=> NT Duchess price fix

Content.Server/Lathe/LatheSystem.cs, Content.Shared/Lathe/SharedLatheSystem.cs
Limits lathe system request size.
**Changelog**
eh
=> LatheSystem: limit lathe request size

Resources/Prototypes/_NF/Shipyard/ceres.yml
We flew a little too close to the sun. Adding 500 spesos value so we can pass some tests for today. Can be remedied later.
Increases the price of the Ceres MK II by 500 spesos to avoid tripping arbitrage. I anticipate this will receive a deeper change with the shakedown cruise of the shuttle, but for now this will allow us to not fail tests.
Trivial change. 
Negligible impact.
**Changelog**
=> Value correction for Ceres MK II

Resources/Maps/_NF/POI/medical.yml
Rotates the medical dispatch mirror.
Fixes https://discord.com/channels/1123826877245694004/1366459516123742339
yammels
use the mirror
I forgor, but it works in testing.
**Changelog**
no
=> Rotate the Medical Dispatch mirror

Content.Server/Physics/Controllers/MoverController.cs
A hotfix for botched velocity calculation.
I goofed.
If you're going very quickly in one direction, then turn, any component inline with the velocity should be removed.  You might get briefly slightly faster lateral movement, but I don't think it should compound.
1. Take the Harbourmaster, upgrade all of the thrusters with T4 capacitors.
2. Try to accelerate past 50 m/s while turning.
**Changelog**
:cl:
- fix: Ships now better respect maximum velocity.
=> MoverController: return the velocity limiting

Resources/Prototypes/_NF/Shipyard/baroness.yml, Resources/Prototypes/_NF/Shipyard/vitalis.yml
Ensuring all ships use interview slots.
Interview good.
yammels
Purchase both, respawn, check latejoin menu, whoops, all Applicants.
**Changelog**
no
=> Baroness/Vitalis: use interview slots

Content.Server/Administration/Systems/BwoinkSystem.cs
Fixes _webhookData not being used,
This fixes the Hyperlinking inside Ahelp Messages and some other Problems.
The PR also changes some wording in the Log messages as the webhook can be a generic one and not from discord (Wording changed from "Discord" to "Webhook")
Added a small text for Forks that senderId can be a SystemUserId when oriented from an Webhook (I wonder why i added this :P (joke))
This somehow has been removed when the Original PR was made way back then.
Upstream also has it this way (expect our api changes, [for refernce](https://github.com/space-wizards/space-station-14/blob/973ad71f5cd8799824850da35d9d009d26706272/Content.Server/Administration/Systems/BwoinkSystem.cs#L367))
(This issue has also plagued me for months as i thought it would be an issue Bot sided.)
- Start a …
=> BwoinkSystem WebhookData Fixes & Changed Log Messages

Resources/Locale/en-US/_DV/datasets/names/oni.ftl, Resources/Locale/en-US/_NF/interaction/interaction-popup-component.ftl, Resources/Locale/en-US/nyanotrasen/interaction/interaction-popup-component.ftl
Cleans up FTL warnings.
Poor comment format.
fittle
CI tests are sufficient.
**Changelog**
no
=> Cleanup FTL warnings

Content.Shared/_Goobstation/Vehicles/SharedVehicleComponent.cs, Content.Shared/_Goobstation/Vehicles/SharedVehicleSystem.cs
Fixes issues with vehicle actions.
Should fix https://discord.com/channels/1123826877245694004/1367312115110510702
Uses PoweredFlashlightSystem as a basis for how actions are added/removed.  Actions are now created on mapinit (vs. creating and destroying new actions with each new rider) and are granted/revoked from the riders.
1. Open two clients.
2. On client 1, spawn two NFSD hoverbikes near the valet's desk.  Get on one, turn on the siren and lights.
3. On client 2, walk over to the hoverbikes.  No issues on client 2's console, the vehicles should be in their expected state (one rider on, siren on, lights on)
**Changelog**
:cl:
- fix: Fixed client-side issues with vehicle actions.
=> Fix vehicle actions

Resources/Prototypes/Recipes/Crafting/crates.yml
Restored the secure crate crafting
They look cool
I did not add "_#Frontier_" because this is actually how it is upstream
Recklessly 🤘
Sorry, no picture today
**Changelog**
:cl:
- tweak: Secure crate are craftable once again!
=> Restore the secure crate craft

Resources/Prototypes/_NF/Shipyard/nook.yml
From now on we're adding a minimum of 500 spesos over that minimum.
Missed arbi by 30 spesos on random hell fill.
**Changelog**
=> Shuttle (Update) Nook Arbi Final

Content.Server/_NF/GameTicking/Rules/NFPirateRuleSystem.cs, Content.Server/_NF/Pirate/Components/AutoPirateCaptainComponent.cs, Content.Server/_NF/Pirate/Components/AutoPirateComponent.cs, Resources/Locale/en-US/_NF/ghost/roles/ghost-role-component.ftl, Resources/Maps/_NF/POI/cove.yml, Resources/Prototypes/_NF/Entities/Mobs/NPCs/pets.yml, Resources/Prototypes/_NF/Roles/MindRoles/mind_roles.yml
Adds a new field to the AutoPirate/AutoPirateCaptain that does not adjust their faction on spawn.
Made Clarpy's ghost role a Pirate instead of just a Team Antagonist.
Added another pill bottle to the cove.
Clarpy dementia moment, wasn't handled as a special case in the pirate antag stuff.
All in About the PR.
Spawn on the Cove.  Check Clarpy's faction, should be Cat.
Take Clarpy's ghost role, check the faction, should still be Cat.
**Changelog**
:cl:
- fix: Clarpy is no longer aggressive when its ghost role is abandoned.
=> Fix Clarpy's faction

Resources/Locale/en-US/_NF/guidebook/guides.ftl, Resources/Prototypes/_NF/Guidebook/shipyard.yml
Corrects alphabetical listing of Nook shuttle and adds missing Crossroads reference. 
ABCs are important.
Check yamal. Check guidebook.
- [X ] I have read [CONTRIBUTING.md](https://github.com/new-frontiers-14/frontier-station-14/blob/master/CONTRIBUTING.md) and and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
**Changelog**
🆑 
- fix: Correct new shuttle guidebook ordering.
=> Guidebook Corrections

Content.Client/Lobby/UI/CharacterPickerButton.xaml.cs
Part two of client lobby UI JobPrototype safety.
Partially fixes https://discord.com/channels/1123826877245694004/1369241801617313913
Use TryIndex instead of Index, won't throw exceptions.
1. Nuke DB
2. Run server & client, create a character, set their preference for Contractor to high.
3. Close server & client.
4. Open DB (I recommend DB browser for SQLite)
5. Edit the role_id in the job table entry to "blorbus".
6. Shouldn't have issues with the character selection button.
**Changelog**
none, should be lumped in with the changelog from #3358.
=> job check in CharacterPickerButton.xaml.cs

Content.Server/Medical/SuitSensors/SuitSensorSystem.cs
What it says on the tin.
Bug.
Adds a check for the EmpDisabledComponent (which exists on items already disabled by EMPs)
1. Turn your suit sensor to something that isn't Off.
2. Spawn EMP emitter.
3. Blast yourself.
4. Spawn handheld crew monitor.
5. You shouldn't show up.
6. Spawn another EMP emitter.
7. Blast yourself.
8. Spawn another handheld crew monitor.
9. You still shouldn't show up.
10. VV to the EmpDisabledComponent, set the disabled timeout to 0 (or wait until it elapses)
11. View the crew monitor, you should show up.
12. Check your jumpsuit, your sensor should be in the same setting as in step 1.
13. Change your suit sensor, the crew monitor should adjust.
**Changelog**
:cl:
- fix: Multiple EMPs no longer remove a suit's sensors permanently.
=> Fix suit sensors being permanently disabled on multiple EMPs

Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/computers_shuttle_records.yml
Removes the "BaseStructureDisableToolUse" From the Shuttle Records Computer in order to make it wrenchable, Allows SR/Sheriff to move the Console inside the Office.
Requested by Kam
Allows the Office to be redesigned more.
The Console is also already Gridlocked to Frontier Station either way, so you cannot really Steal it.
- Go to Console
- Unwrench
- Profit
**Changelog**
=> Makes the Shuttle Records Computer Wrenchable

Content.Server/_NF/GameRule/NfAdventureRuleSystem.cs
Sorts the player list alphabetically on the roundend screen
QoL. So it's easier to find yourself to figure out how much you gained/lost.
In NFAdventureRuleSystem.cs _AppendRoundEndText_, converts the dict of players into a list, sorts it by player name and then enumerates over the list.
- Join a bunch of clients with different names to the same server
- Start the round
- End the round
- See that the list is sorted.
None identified
**Changelog**
:cl:
- tweak: round end galactic bank list is now sorted alphabetically.
=> Sort roundend player list

Resources/Prototypes/_NF/Entities/Structures/Storage/Closets/Lockers/lockers.yml, Resources/Prototypes/_NF/Entities/Structures/Storage/Closets/closets.yml
Fixed parenting and moved the location of the FSB standing suit locker to a more appropriate? Location.
Visual/lock bug.
Yaml
Spawn locker. Observe lock. No one is locked out. Maybe children.
**Changelog**
- fix: FSB locker lock locks the locker.
=> Fixes FSB locker parenting, moves to new location

Resources/Maps/_NF/Shuttles/BlackMarket/falcon.yml
The Falcon had a stowaway extra thruster. This PR removes it.
Walk the plank.
yaml
Spawn schooner. Check thruster count. No double thrusters.
**Changelog**
:cl:
- fix: Remove redundant aft thruster on Falcon shuttle.
=> Shuttle (Update) Falcon Redundant Thruster Fix

Resources/Locale/en-US/_NF/reagents/meta/biological.ftl, Resources/Prototypes/_NF/Entities/Objects/Consumable/Food/produce.yml, Resources/Prototypes/_NF/Reagents/biological.yml
Renamed and Tweaked the Reagent
Cause it didnt work
No new files, only renamed and added nutri
Spawn fruit, eat, grind, drink
non as i know of
**Changelog**
:cl:
- fix: Monkanana Reagent now works
- tweak: Added Nutriment and Vitamin to the fruit
=> Fix for the monkey juice

Resources/Locale/en-US/_NF/metabolism/metabolism-groups.ftl, Resources/Prototypes/Reagents/medicine.yml, Resources/Prototypes/_NF/Body/Organs/sheleg.yml, Resources/Prototypes/_NF/Chemistry/metabolism_groups.yml
Allow Sheleg to use Oculine so they can fix eye damage.
Also made the sheleg chems metabolizer a bit slower (.25<.20)
This pull request introduces a new metabolism group called "Sheleg" and integrates it into the system by updating relevant files. The changes include defining the new group, adjusting its properties, and ensuring compatibility with existing systems.
* [`Resources/Locale/en-US/_NF/metabolism/metabolism-groups.ftl`](diffhunk://#diff-ca31fc4b717e69855704fc0187819a27ba63d8443404fed8d9f11c0c9a1d36e4R2): Added a new localization entry for the "Sheleg" metabolism group.
* [`Resources/Prototypes/_NF/Chemistry/metabolism_groups.yml`](diffhunk://#diff-5673c0d645828f1c6a575d3bca049e5efb1fcd6628002ec94735a3fd820d9279R5-R9): Defined the "Sheleg" metabolism group with its unique ID and …
=> Sheleg Oculine Fix

Content.Server/_NF/GameRule/NfAdventureRuleSystem.cs, Resources/Maps/_NF/Outpost/frontier.yml, Resources/Maps/_NF/Shuttles/Scrap/scrap-barge.yml, Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_expeditions_carp.yml
Bugfix bonanza.
Fixes a few issues:
https://discord.com/channels/1123826877245694004/1372564396009717800
https://discord.com/channels/1123826877245694004/1372563385908203672
https://discord.com/channels/1123826877245694004/1372449517382930583
https://discord.com/channels/1123826877245694004/1372828803080130570
mapping changes, wyvern fixture: yammels
hologram changes: add comp checks for borgs/holograms on spawn - these are the only jobs (currently) that don't have a way to meaningfully interact with a bank account.
1. Spawn the barge, interact with the plasma, all good.
2. Right-click on the blue route bus schedule on Frontier Outpost near dock 5, should only be one.
3. Use two clients.  Spawn in as a character, buy a ship, open a job, respawn as another character in the interview …
=> Fix barge plasma/bus schedule mapping bugs, end of round hologram bank entries

Resources/Prototypes/_NF/Entities/Markers/Spawners/mechs.yml
This PR adds a new vehicle spawner for the EMU. Allowing us to mark cargo shuttles with the brand of SIN. 
Bad news is you take an unrecoverable 10k hit by buying the shuttle with the spawner on it. 
Nice to be able to put one in at spawn to inform players that it exists. They'll probably buy one anyways. But maybe they don't know it exists. 
Yaml
Place spawner. Examine spawnee.
**Changelog**
🆑 
- add: EMU spawner for mapping.
=> Spawn emu.

Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/engivend.yml, Resources/Prototypes/_NF/Catalog/VendingMachines/Inventories/youtool.yml
Added bags to POI variants of listed vendomats
Seems reasonable
yml
Spawn at FO, schlep to EngiVend or YouTool, ogle
**Changelog**
:cl:
- add: Construction bags are now available from YouTool and EngiVend at POIs.
=> Add construction bag to YouTool and EngiVend

Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Battery/battery_pistols.yml
Adds ProjectileBatteryAmmoProviderComponent to the Frontier upgraded CHIMP
I goofed - inheritance is fine but the base upgraded chimp's ammoprovider doesn't have a valid prototype.
yammels
Spawn an upgraded CHIMP, it should shoot.
**Changelog**
no
=> Fix the upgraded chimp

Resources/Maps/_NF/Shuttles/searchlight.yml
Trivial change. Adds missing late join and warp points.
Needed for things.
Yaml
Load grid check presence.
**Changelog**
trivial change
=> Shuttle (Update) Searchlight LJ and WP addition

Resources/Prototypes/_NF/Hydroponics/seeds.yml
Fixes the reagent definitions inside the monkanana seed.  Increased the base potency of the plant (why not) and tweaked the numbers so they should generate a fruit with the same stats as a reference monkanana.
Nonexistent reagent.
yammels
Spawn monkanana, monkanana seeds, and a hydro tray
Grow a monkanana
Compare the two in two juicers, they should have the same stats (though the reference monkanana will be slightly smaller)
trust me bro
**Changelog**
:cl:
- fix: Grown monkananas now contain primatine, nutriment, and vitamin.
=> Fix monkanana seed definition

Resources/Prototypes/_NF/Entities/Clothing/OuterClothing/hardsuits.yml
Add ContrabandClothing parent to elite pirate hardsuit
blue pew pew
yammels
spawn elite pirate hardsuit
put it on
spawn CDET
pew pew pew
**Changelog**
eh
=> Add ContrabandClothing parent to elite pirate hardsuit

Content.Shared/_DV/Abilities/ItemCougherSystem.cs, Resources/Prototypes/_DV/Actions/types.yml
Mirror https://github.com/DeltaV-Station/Delta-v/pull/3705
N/A
**Changelog**
N/A
=>  fix hairballs being infinite (DeltaV #3705)

Resources/Prototypes/_NF/Shipyard/nightlight.yml
=> Fix Nightlight Shuttle Price

Resources/Prototypes/Catalog/VendingMachines/Inventories/cargodrobe.yml
Adds Quartermaster Hats, Suits, Winter Wear, and Capes to CargoDrobe Vendomat.
Only QM Stamp and Headset were available, despite other department uniform vendomats containing full set of command attire.
There were few times where I wanted to dress up as QM on cargo/salvage ship, yet I couldn't as it was missing from vendomat. 
1. Spawn CargoDrobe with Entity Spawner.
1. Buy things.
**Changelog**
:cl:
- add: Added missing QM items to CargoDrobe.
=> Added missing QM items to CargoDrobe Vendomat

Content.Shared/Storage/EntitySystems/MagnetPickupSystem.cs
Improves counting objects on magnet pickup.
Only objects that could be considered for pickup actually increment the count.
Fixes https://discord.com/channels/1123826877245694004/1380160299146936350
order of operations & logic
1. Spawn construction bag, 40 bananas around it.
2. Spawn a bunch of steel sheets.
3. Turn the construction bag on, it should pick up many steel sheets at a time.
**Changelog**
ehh
=> Better Magnet Count

.editorconfig
Sets the severity of the namespace matching in .editorconfig to None.
Our namespace is _NF, this is _fine_.
.editorconfig
Open any _NF namespaced file, no yellow warning under the namesapce.
Amazing.
**Changelog**
not player-facing
=> .editorconfig: Ignore underscore-prefixed namespaces

Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/antimateriel.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
Removes contraband value from the base musket and anti-materiel rifle.
Oversight.
yammels, all reparenting
Spawn musket, no value.
Spawn anti-materiel rounds, no value.
**Changelog**
:cl:
- tweak: Anti-materiel rounds now have no FUC value.
=> Musket, .60 anti-materiel rounds: no contraband value

Content.Server/_NF/CryoSleep/CryoSleepSystem.cs
Adds an argument to the DoAfterArgs so a user doesn't need to be able to actually interact to enter into cryo.
Sleeping users have an action blocker that prevents them interacting with things, this avoids that.
one-liner argument addition
1. Spawn Urist McFluff.
2. Open VV [on Urist], edit the SSDIndicatorComponent, set the sleep time to zero.  Moth go sleep.
3. Shove him into a cryo sleep pod.
4. Open VV [on the pod], open the CryoSleepComponent, the DoAfter should not be null.
5. After 30 seconds or so, moth will be teleported to nullspace.
**Changelog**
:cl:
- fix: SSD characters can be dragged into cryosleep without issue.
=> Fix issue with SSD preventing cryo doafter.

Resources/Prototypes/_Goobstation/Entities/Objects/Vehicles/vehicles.yml
Changes vehicles' physics body type to kinematic controller.
Fixes https://discord.com/channels/1123826877245694004/1380057802478981200.
If it moves via direct player input, it should be a kinematic controller.
yammels
Spawn a fast vehicle (ATV/hoverbike/skeleton motorcycle).
Pull vehicle.
Hop on vehicle.
Doesn't drive like molasses.
**Changelog**
:cl:
- fix: Vehicles now move at reasonable speeds when pulled.
=> Change vehicles' physics body type to KinematicController

Resources/Maps/_NF/Shuttles/phoenix.yml
Fix missing locker
Fixed wrong RD suit locker to SuitStorageEVAScientist
N/A
**Changelog**
:cl:
- fix: Added missing scientist locker on Phoenix shuttle
=> Shuttle (Hotfix): Phoenix

Resources/Maps/_NF/Shuttles/Scrap/scrap-investigator.yml
Swap SuitStorageRD to SuitStorageEVAScientist
N/A yml
N/A
**Changelog**
N/A
=> Shuttle (Hotfix): Scrap Investigator

Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/bags.yml, Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/encryption_keys.yml
Does what it says on the tin.
Unintended.  These aren't supposed to be visible, they're either: higher up on the list (as default equipment), or automatically equipped in your headset.
effects->hideEffects
Open the DOC loadout.
Look at the encryption key list, everything should be selectable, four options total.
Look at the backpack list, everything should be selectable, untold numbers of options.
Backpack section, no unselectable medical backpack:
Encryption key section, no unselectable medical encryption key:
**Changelog**
trivial, no
=> Loadout: Hide DOC medical backpack, medical encryption key

Content.Server/Power/Nodes/CableNode.cs
Fixes an issue with adjacent cable terminals breaking connections they shouldn't.
Cherry-picks https://github.com/space-wizards/space-station-14/pull/38377.
Fixes https://github.com/space-wizards/space-station-14/issues/36339#issuecomment-2781189884 (as far as I can tell - _only_ the comment, not the larger issue)
Giant pain when mapping considering our maps are comparatively tiny and having multiple SMESes with cable terminals to the north is a common setup.
C# one-liner.  Having a cable terminal across from you does not mean you have no more nodes to connect to.
This setup is impossible to create without this PR - the bottom row of cables would be split in two between the SMESes.
**Changelog**
No CL, really only of use for mappers.
=> Fix cable terminals breaking HV cables (cherry-pick wizden#38377)

Resources/Prototypes/_NF/Entities/Structures/Machines/Computers/frame_tabletop.yml
I added a bland, functionless tabletop computer child for the tabletop computer parent. It's for mapping purposes. I presume if someone wanted to create the illusion of hard work without actual purpose but couldn't find 🫵. 
Yuki asked me to. Didn't ask too many questions.
yaml
Place it. Admire it. Maybe it has games on it.
**Changelog**
🆑 
- add: A bland functionless tabletop computer has been added to Frontier for mapping purposes. Neat.
=> A tabletop computer for tabletop computing on tabletops.

Resources/Prototypes/_NF/Catalog/Cargo/cargo_cargo.yml, Resources/Prototypes/_NF/Entities/Markers/Spawners/mechs.yml
Decreases EMU market and spawn price from 10k to 5k.
The EMU has purpose within a specific gameplay loop. Outside of that loop it doesn't really have relevance. It has 0 sell value. At the moment the cargo loop has a 10k barrier point to entry. It's basically a 10k ticket to get in line for the cargo box ride.
Maybe that's reasonable. I don't know.
But what I -do- know is that if you want to have a friend move boxes with you, which I think we want to encourage, you now have a 20k barrier to entry. For moving boxes. You're losing that money.
I think we can agree that seems pretty robust.
So -technically- what I'm doing is adjusting the price point so that there's a 10k barrier to entry for you and a friend to move boxes together. Which I think we want. Maybe even three friends for 15k. …
=> EMU price adjustment

Resources/Locale/en-US/_DV/construction/construction-categories.ftl
Port of https://github.com/DeltaV-Station/Delta-v/pull/3797
Bugfix
One (1) locale entry
**Changelog**
=> Fix missing locale entry for the Flags construction category (DeltaV #3797)

Content.Server/Station/Systems/StationSpawningSystem.cs, Resources/Prototypes/_NF/Loadouts/Jobs/Pirates/ears.yml
Fixes a few minor bugs with pirate role loadouts.
I goofed.
Pseudonyms: changes made to the EquipRoleLoadout function that weren't applied to the SpawnPlayerMob override. [Regression from the last upstream merge]
Loadouts: `head` to `ears` [Regression from #3560]
Set your pseudonym to something funny.
Spawn as a pirate.
Your headset should be on your head and not on the floor.
Your name should also be the funny pseudonym.
**Changelog**
meh
=> Fix pirate pseudonyms, headset loadouts

Resources/Prototypes/Entities/Clothing/Back/specific.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/watergun.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml, Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/projectiles.yml
Fixes the water blaster, super water blaster, and backpack spray tank.
Marks the projectile file with an ignored region.
Fixes https://discord.com/channels/1123826877245694004/1383144861728768120
YAML edits.
Spawn water blaster, super water blaster, backpack spray tank, spray nozzle, and something to fill them with (I recommend corn oil).
Fill and shoot all of them, they should all work.
**Changelog**
:cl:
- fix: Water blasters and the spray nozzle should work properly again.
=> Fix water blasters and spray nozzle/tank

Resources/Prototypes/_NF/Catalog/Fills/Lockers/suit_storage.yml
This locker has stuff AND an EVA suit. To compliment the version that has stuff AND a hard suit.
Seems nice. I want to use it. My problems are now your problems.
lmay
Spawn locker. Observe contents. Nod.
**Changelog**
🆑 
- add: new salvage locker type with fill and eva suit. Huzzah.
=> Filled softsuit salvage locker.

Resources/Prototypes/_NF/Decals/markings.yml
Evil decals
evil decals
evil decals
evil decals
evil decals
**Changelog**
no :)
=> Evil decals

Resources/Prototypes/Entities/Structures/Shuttles/cannons.yml, Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/explosives.yml
Fixes the Friendship's ammo tags
this issue 
https://github.com/new-frontiers-14/frontier-station-14/issues/3644
Bug Fix
Grenade Tag was missing for the friendships ammo
Buy rogue fire gun load gun happyness 
**Changelog**
:cl:
- fix: The Friendship can now fire grenades again.
=> Hot fixes Rogue's Gun being broken

Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_base.yml, Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_expeditions_carp.yml
Title
Space adders once again have control over their lives and they can (and will) chose to kill you.
Missing parent
1. Spawn in. spawn `NFMobSmallRainbowSnake`, observe the NPC behaving as hostile NPCs usually behave.
**Changelog**
:cl:
- fix: Space snakes should behave normally now.
=> Space snakes hotfix

Tools/publish_multi_request.py
seeding the new cdn with a build. Revert once fully transitioned.
=> cdn seeding

Tools/publish_multi_request.py
=> CDN-changes

Tools/publish_multi_request.py
restoring the cdn after seeding
=> CDN restore

Resources/Prototypes/Entities/Mobs/NPCs/miscellaneous.yml, Resources/Prototypes/Entities/Objects/Consumable/Food/meat.yml
Reverts new-frontiers-14/frontier-station-14#3634
by popular demand (1 person demanded it)
=> Revert "remove value from killer tomato and killer tomato related products"

Resources/Prototypes/_DV/Entities/Structures/Machines/smartfridge.yml
This PR adds the hypo type to the smartfridge whitelist.
The smartfridge can currently hold all of the tools and materials utilized in this space thanks to our friends from Delta. However we differ in our use of smartpens so this is adding our Frontier tool to the inventory that we inherited from them. 
Basically QoL and consistency.
Yaml
Place a medical pen in the smart fridge. Huzzah.
Not this does technically allow you to store a hypo in there as well. Which is not something I see as a problem.
**Changelog**
🆑 
- tweak: Smart fridge can now store medical pens (and hypo sprays) alongside other lab tools.
=> Update (Smartfridge) Whitelist adjustment.

Content.Server/_NF/Research/Systems/RandomBlueprintSystem.cs
Bug logic error
N/A
N/A
Gambling
All have 1-3 techs
N/A
**Changelog**
N/A
=> No schematics from tech scrap bug (Hotfix)

Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
Access fixup for borgs
N/A
**Changelog**
N/A
=> Borg Access (Hotfix)

Content.Server/_NF/Shipyard/Components/PreventShipyardTitleOverwriteComponent.cs, Content.Server/_NF/Shipyard/Systems/ShipyardSystem.Consoles.cs, Resources/Prototypes/_NF/Roles/Jobs/Engineering/plant_manager.yml, Resources/Prototypes/_NF/Roles/Jobs/Frontier/sr.yml, Resources/Prototypes/_NF/Roles/Jobs/Medical/doc.yml, Resources/Prototypes/_NF/Roles/Jobs/Nfsd/sheriff.yml
Before this change, Command roles lose their title if they buy a ship directly from a shipyard, without using a voucher.
After this change, Command roles do not get their title overwritten when they buy a ship from the shipyard.
It's a little confusing to see sector announcements be given by Directors of Care that are labeled as simply "captain", and it's probably also annoying to the other command positions, too
New `PreventShipyardTitleOverwrite` component that prevents a shipyard console from overwriting your job's title
1. Be a contractor, buy ship from common shipyard. Observe your title is now captain.
2. Be a station representative, buy ship from common shipyard. Observe your title is still SR.
3. Be a sheriff, buy ship from common shipyard. Observe your title is still sheriff.
4. …
=> Command retains ID title on shipyard purchase

Content.Client/Clothing/ClientClothingSystem.cs, Content.Shared/_NF/DisplacementMap/Components/DisableDisplacementsComponent.cs, Content.Shared/_NF/DisplacementMap/Components/FluffyWhitelistComponent.cs, Resources/Locale/en-US/_NF/preferences/ui/humanoid-profile-editor.ftl, Resources/Locale/en-US/_NF/traits/traits.ftl, Resources/Prototypes/Entities/Mobs/Species/moth.yml, Resources/Prototypes/_NF/Traits/height.yml
Added a new selectable "Fluffy" trait for moths that disables displacement maps.
Many people have expressed their love for how moths look with displacement maps, however some people like me aren't big fans. I made this as a compromise, it lets the people that want the displacement maps still have them, and lets people like me have the look we want.
yamlmaxxing
1: Load game
2: Make a moth character with the "fluffy" trait
3: Load into the round with such character, see that their legs look different
4: Respawn, disable the "fluffy" trait on the moth character
5: Load in, see that they look skinnier
**Changelog**
:cl: 
- add: Added new "Fluffy" trait for moths that disables displacement maps.
=> Displacement toggle trait for moths

Resources/Prototypes/_NF/Catalog/Fills/Lockers/service.yml
This PR adds a simple chef freezer to replace the redundant freezer/closet combo mapped everywhere and the generally bad chef closet fill.
The chef closet fill isn't great for us and it's kind of silly that we map both the freezer and the closet everywhere. This provides an alternative for mapping.
yml
spawn, observe
**Changelog**
🆑 
- add: A new chef freezer with cooking fill for mapping.
=> New Chef Freezer to replace the closet

Resources/Prototypes/_NF/Entities/Structures/Doors/Windoors/windoor.yml
Adds pirate locked secure windoors for mapping purposes.
Requested when lack of windoors was noticed during pirate fleet revamp.
YAML
Spawn new windoor.
Open it as pirate.
Don't open it as not pirate.
None.
**Changelog**
:cl:
- add: Added pirate locked secure windoors.
=> Pirate locked secure windoors

Resources/Prototypes/_NF/Catalog/Fills/Crates/service.yml
Is it a spacespresso? A spacepresso? Who knows.
But now they're all named the same thing.
Consistency is good. Even when wrong.
yaml
Extensively.
**Changelog**
Trivial change,
=> Presso crate correction.

Resources/Prototypes/_NF/Mail/mailDeliveries.yml
There was a prototype for special SR mail which attempted to spawn a nonexistent prototype, which on my testing server hung it. I'm not sure if this would happen on the release servers, but it's good to patch this before it can crash a round
only you can stop bad prototype references
changes the referenced prototype to one that exists
Is there a protocol to force a specific letter to spawn? I don't know of one.
N/A
**Changelog**
N/A
=> Fixes a nonexistent prototype for mail to the SR

Resources/Prototypes/_NF/Entities/Structures/Machines/microwave_recipe_assemblers.yml
The electric range gave you a guidebook page only explaining the high-level role of the chef without providing recipes. It now includes a recipe list so you don't need to examine a kitchen assembler for the recipe list instead anymore
Clarity for new cooks!
YML change, added the foodrecipes guidebook tag
Examine range, see the recipes list now present
https://github.com/user-attachments/assets/0dbe9724-dac8-4822-bdbd-1f80338155e6
N/A
**Changelog**
:cl: Marlyn
- fix: Electric range now comes with a recipe list in the guidebook link
=> Electric range now includes the recipe list too

Resources/ServerInfo/_NF/Guidebook/Shipyard/Surveyor.xml
Tweak to our horrible guidebook system to change the outstanding issue of the guidebook pointing to the wrong kind of generator fuel.
The rest of it remains consistently out of date along with all of the others. So this is good.
People scroll past words to find pictures.
words
read
**Changelog**
Trivial change.
=> guidebook is clown

Resources/Prototypes/Entities/Structures/Machines/Medical/cryo_pod.yml
I got annoyed by having to right click cryo pods to view patient stats so I identified the culprit and removed it.
I want to look at the patient not do a useless inapplicable action
The `ItemToggle` component of the cryo pod was removed, which fires a `ItemToggleActivateAttemptEvent`, `ItemToggleDeactivateAttemptEvent`, and `ItemToggledEvent`. Of these, only the ItemToggledEvent has a relevant signal listener, the health analyzer, and for the health analyzer this simply disables continuous patient updates. This is probably much less useful than actually seeing the patient health information and so I deem it must go.
Put patient in cryo pod. Click or press E while hovering the mouse over it and see the health output. Clicking or pressing E on an empty pod causes a momentary client …
=> Cryopods let you health analyze on click/hover-E again

Resources/Prototypes/_NF/Entities/Objects/Consumable/Food/ingredients.yml
Changed the parent for them rice noodles to prevent them from being sliceable into themselves. Whoops.
We observe the laws of natural reality in this house.
yamamal
More than we tested the last one apparently.
**Changelog**
🆑 
- fix: Noodles can no longer be sliced into noodles that can be sliced into noodles that can be sliced into noodles that can be sliced into noo
=> Update (noodles) 

Resources/Prototypes/_NF/Shipyard/nook.yml, Resources/Prototypes/_NF/Shipyard/skipper.yml
More of these damn arbitration things because I guess this is the kind of thing that someone else should do. Increased shuttle prices by 500.
Stop error
yamamamamlml
Sure sure.
**Changelog**
🆑 
- fix: Nook and Skipper price increased by 500.
=> Nook/Skipper Arbitrage fix.

Resources/Prototypes/Entities/Structures/Walls/walls.yml
Fixes the sprite color for the Diagonal Plastitanium walls. Currently the normal and indestructible colors are switched.
My sanity when looking at nfsd ships.
yaml
Spawn Plastitanium Diagonal walls. Check color/description. Attempt make boom.
**Changelog**
Not needed
=> Fix plastitanium diagonal wall color

Resources/Prototypes/_NF/Entities/Objects/base_contraband.yml
Pirates can no longer "sell" pirate contraband for 0 dubloon
Currently, the Plunder Exchange Computer accepts pirate contraband, effectively deleting it from existence. This PR fixes that
The poor pirates are getting scammed 😔
Removed a single (1) line of yml
Place pirate contraband on plunder exchange pallet
Use the plunder exchange computer to confirm that you can't "sell" them
❌📷
**Changelog**
=> Stop pirates from giving away contraband on the black market

Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/pda.yml, Resources/Prototypes/_NF/Loadouts/contractor_loadout_groups.yml
Adds the contractor PDA into the contractor loadout as the default option. (The clear PDA is still available)
It has always bothered me that the contractor PDA wasn't an option in the loadouts, seemingly only available in the SR PTech vending machine for some reason!
Lots of spaces removed apparently
Check the civilian loadouts
**Changelog**
:cl: Bonaout
- add: The Contractor PDA is now available in loadouts!
=> Add the Contractor PDA in loadouts

Resources/Prototypes/Entities/Objects/Materials/materials.yml
Changed the sprites of bones used in the cargo market terminal being bones
Bones are Bones, you cant say they are a Cotton
Get a working cargo setup (go to Trade Mall for example), spawn some bones, spawn a material silo, place bones in the material silo, unachor the silo and sell it on the platform, check the cargo market terminal, bones are no longer cotton.
PS.: you cant sell bones directly on the cargo terminal for some reason, most likely another bug
**Changelog**
=> Fixed the sprites of bones being cotton sprite in the cargo market terminal

Resources/Prototypes/Recipes/Construction/structures.yml
Made so the construction ghost for catwalks are now be able to be constructed on top of basalt, snow and dirt tiles, the ones you find on expeditions or vgroids. This allows to pass thru lava, plasma and water rivers/lakes.
This allows to pass thru lava and plasma rivers/lakes without doing strange tactics like splashing yourself with water or using moon boots, just make a small bridge instead. 
Also catwalks for water for some events and such.
Create basalt, snow (not astro-snow) and undiggable dirt tiles, create a catwalk construction ghost, construct cat walk (additionally you can add lava or liquid plasma or water entities on top of it)
**Changelog**
:cl:
- tweak: Catwalks can now be placed on top of lava, liquid plasma and water on expeditions and vgroids. Expeditioners rejoice!
=> Allow to construct catwalks on top of lava, liquid plasma and water on vgroids and expeditons

Resources/Prototypes/Entities/Markers/Spawners/Random/Salvage/tables_loot.yml
Removes the upstream chem barrels from the salvage loot table.
Upstream added their own chem barrels to the loot tables, making the overall proportion of barrel based spawns higher and messing with the rates of specific chemicals.
Plus the barrels look tiny and different.
YML
Fly around and look at wrecks, don't see tiny barrels.
None. 
**Changelog**
:cl:
- remove: Removed upstream chem barrels from loot tables.
=> Remove duplicate upstream chem barrels.

Resources/Prototypes/_NF/Entities/Clothing/Wallet/base_wallet.yml
Adds quick insert and area insert capabilities to the wallet.
Opening syndicate loot bundles and the like drop a lot of cash on the ground, which is annoying to pick up one at a time. This adds area insert to the wallet, allowing you to click on the ground next to the pile in order to grab the whole lot. Normal magnet capabilities not added to avoid accidentally thieving incidents.
YAML
- Put a pile of cash on the ground, click next to it with the wallet to pick it all up.
- Click on a single speso stack on the ground with the wallet, also pick it up.
None.
**Changelog**
:cl:
- tweak: The wallet can now pick up cash and other wallet contents from the ground.
=> Add area insert to wallet.

Resources/Prototypes/_NF/Entities/Structures/Dispensers/condiments.yml
Adjusted some parenting pieces on the condiment dispenser to correct the issues with the upstream change for inventory UI.
Why not.
I swapped the one with the other then shifted the whatsit over to be where it needed to be and then did the 'ol hattrick.
Check condiment dispenser. Maybe try building one too. I dunno if I did that. Should be fine.
**Changelog**
🆑 
- fix: Condiment dispenser UI should work as intended. As -I- intended. Behold! BEHOLD!
=> Dispense with the condiments

Content.Shared/Atmos/Piping/Unary/Components/SharedVentScrubberComponent.cs, Resources/Prototypes/_NF/Atmospherics/gases.yml
I added helium to the list of default gasses pulled by the scrubbers. Somewhere along the way this seems to have been borked.
Thank Mace for pointing this one out.
Seemed like it would be a gas.
C# but pretty simple C#. Even YOU can check this one. Yes, you.
Check to see that scrubbers list helium.
Check that it's enabled by default. No work needed. Your ideal scenario.
Plop down a helium tank, open 'er up. Observe as the helium is whisked away by a scrubber.
As you can see all of the gas has moved from one side to the other side. Remember that helium cannot be seen by people who hate mothroaches.
**Changelog**
🆑 
- fix: Helium now scrubbed by default.
=> Air scrubbers pull helium by default

Resources/Prototypes/_NF/Catalog/Fills/Lockers/locker_wallmount.yml
Filled the fill with the right fill and not the wrong fill. Now it's filled with the proper fill. This PR also adds an unfilled version.
It claims to be filled, but it not filled. It is unfulfilled. Now it is fulfilled.
Also adds an unfulfilled version to be used where appropriate.
ymalaml
Examine.
Shoulda named this branch Dr. Fill
**Changelog**
🆑 
- fix: Filled medicine locker now filled.
=> Addresses the empty filled medicine wall locker
